// Code generated by mwsapigen, DO NOT EDIT.

package mock_client

import (
	"context"
	"reflect"

	"go.uber.org/mock/gomock"

	"go.mws.cloud/go-sdk/service/mk8s/client"
)

// MockMk8sReleaseChannel is a mock of Mk8sReleaseChannel interface.
type MockMk8sReleaseChannel struct {
	ctrl     *gomock.Controller
	recorder *MockMk8sReleaseChannelMockRecorder
}

// MockMk8sReleaseChannelMockRecorder is the mock recorder for MockMk8sReleaseChannel.
type MockMk8sReleaseChannelMockRecorder struct {
	mock *MockMk8sReleaseChannel
}

// NewMockMk8sReleaseChannel creates a new mock instance.
func NewMockMk8sReleaseChannel(ctrl *gomock.Controller) *MockMk8sReleaseChannel {
	mock := &MockMk8sReleaseChannel{ctrl: ctrl}
	mock.recorder = &MockMk8sReleaseChannelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMk8sReleaseChannel) EXPECT() *MockMk8sReleaseChannelMockRecorder {
	return m.recorder
}

// ListMk8sReleaseChannels mocks base method.
func (m *MockMk8sReleaseChannel) ListMk8sReleaseChannels(arg0 context.Context, arg1 client.ListMk8sReleaseChannelsRequest) (*client.ListMk8sReleaseChannelsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMk8sReleaseChannels", arg0, arg1)
	ret0, _ := ret[0].(*client.ListMk8sReleaseChannelsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMk8sReleaseChannels indicates an expected call of ListMk8sReleaseChannels.
func (mr *MockMk8sReleaseChannelMockRecorder) ListMk8sReleaseChannels(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMk8sReleaseChannels", reflect.TypeOf((*MockMk8sReleaseChannel)(nil).ListMk8sReleaseChannels), arg0, arg1)
}
