// Code generated by mwsapigen, DO NOT EDIT.

package vpc

import (
	"context"

	"github.com/go-faster/jx"

	"go.mws.cloud/go-sdk/internal/conv"
	"go.mws.cloud/go-sdk/internal/decode"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	resparsers "go.mws.cloud/go-sdk/internal/resources/parsers"
	valuesctx "go.mws.cloud/go-sdk/pkg/context/values"
	resifaces "go.mws.cloud/go-sdk/pkg/resources/interfaces"
	resmodels "go.mws.cloud/go-sdk/pkg/resources/models"
)

var (
	OneToOneNatRefTemplate = resparsers.Template{
		{
			Value:       "oneToOneNat",
			IsConstant:  false,
			SearchAfter: false,
		},
		{
			Value:       "oneToOneNats",
			IsConstant:  true,
			SearchAfter: false,
		},
		{
			Value:       "network",
			IsConstant:  false,
			SearchAfter: true,
		},
		{
			Value:       "networks",
			IsConstant:  true,
			SearchAfter: false,
		},
		{
			Value:       "project",
			IsConstant:  false,
			SearchAfter: true,
		},
		{
			Value:       "projects",
			IsConstant:  true,
			SearchAfter: false,
		},
		{
			Value:       "vpc",
			IsConstant:  true,
			SearchAfter: false,
		},
	}
)

func NewOneToOneNatID(project, network, oneToOneNat string) OneToOneNatID {
	m := OneToOneNatID{
		oneToOneNat: oneToOneNat,
		network:     network,
		project:     project,
	}
	m.path = m.ID()
	return m
}

func ParseOneToOneNatID(path string) (OneToOneNatID, error) {
	m := OneToOneNatID{
		path: path,
	}
	if err := m.Parse(context.Background()); err != nil {
		return OneToOneNatID{}, err
	}
	return m, nil
}

func NewOneToOneNatIDFromAnyID(resource resmodels.AnyResourceID) (OneToOneNatID, error) {
	return ParseOneToOneNatID(resource.ID())
}

type OneToOneNatID struct {
	oneToOneNat string
	network     string
	project     string
	path        string
}

func (m *OneToOneNatID) ResourceName() resifaces.ResourceName {
	if m == nil {
		return ""
	}
	return resifaces.ResourceName(m.oneToOneNat)
}

func (m *OneToOneNatID) GetOneToOneNat() string {
	if m == nil {
		return ""
	}
	return m.oneToOneNat
}

func (m *OneToOneNatID) GetNetwork() string {
	if m == nil {
		return ""
	}
	return m.network
}

func (m *OneToOneNatID) GetProject() string {
	if m == nil {
		return ""
	}
	return m.project
}

func (m *OneToOneNatID) ServiceSlug() string {
	return "vpc"
}

func (m *OneToOneNatID) ID() string {
	if m == nil || m.oneToOneNat == "" || m.network == "" || m.project == "" {
		return ""
	}

	return m.ServiceSlug() + "/projects/" + m.project + "/networks/" + m.network + "/oneToOneNats/" + m.oneToOneNat
}

func (m *OneToOneNatID) Parse(ctx context.Context) error {
	if m == nil {
		return nil
	}

	result, err := resparsers.Reference(ctx, m.path, OneToOneNatRefTemplate.AsID())
	if err != nil {
		return reserrors.NewParseIDError(m.path, err)
	}

	m.oneToOneNat = result["oneToOneNat"]
	m.network = result["network"]
	m.project = result["project"]

	return nil
}

func (m *OneToOneNatID) Clone() *OneToOneNatID {
	if m == nil {
		return nil
	}
	clone := *m
	return &clone
}

func (m OneToOneNatID) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *OneToOneNatID) Encode(e *jx.Encoder) {
	if m == nil {
		e.Null()
		return
	}
	result := m.ID()
	if result == "" {
		result = m.path
	}
	e.Str(result)
}

func (m *OneToOneNatID) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *OneToOneNatID) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("OneToOneNatRef")
	}

	v, err := decode.Str(d)
	if err != nil {
		return err
	}

	m.path = v
	return nil
}

func NewOneToOneNatRef(project, network, oneToOneNat string) OneToOneNatRef {
	m := OneToOneNatRef{
		id: OneToOneNatID{
			oneToOneNat: oneToOneNat,
			network:     network,
			project:     project,
		},
	}
	m.id.path = m.absolutePath()
	return m
}

func ParseOneToOneNatRef(ctx context.Context, path string) (OneToOneNatRef, error) {
	m := OneToOneNatRef{
		id: OneToOneNatID{
			path: path,
		},
	}
	if err := m.Parse(ctx); err != nil {
		return OneToOneNatRef{}, err
	}
	return m, nil
}

func NewOneToOneNatRefFromAnyRef(ref resmodels.AnyResourceRef) (OneToOneNatRef, error) {
	ctx := valuesctx.WithValuesStore(context.Background(), ref.GetPathValues())
	return ParseOneToOneNatRef(ctx, ref.Path())
}

type OneToOneNatRef struct {
	id OneToOneNatID
}

func (m *OneToOneNatRef) ResourceName() resifaces.ResourceName {
	if m == nil {
		return ""
	}
	return m.id.ResourceName()
}

func (m *OneToOneNatRef) GetOneToOneNat() string {
	if m == nil {
		return ""
	}
	return m.id.GetOneToOneNat()
}

func (m *OneToOneNatRef) GetNetwork() string {
	if m == nil {
		return ""
	}
	return m.id.GetNetwork()
}

func (m *OneToOneNatRef) GetProject() string {
	if m == nil {
		return ""
	}
	return m.id.GetProject()
}

func (m *OneToOneNatRef) ServiceSlug() string {
	return "vpc"
}

func (m *OneToOneNatRef) IDPath() string {
	if m == nil {
		return ""
	}
	return m.id.ID()
}

func (m *OneToOneNatRef) Path() string {
	if m == nil {
		return ""
	}
	if m.id.path == "" {
		return m.absolutePath()
	}
	return m.id.path
}

func (m *OneToOneNatRef) Parse(ctx context.Context) error {
	if m == nil {
		return nil
	}

	result, err := resparsers.Reference(ctx, m.id.path, OneToOneNatRefTemplate)
	if err != nil {
		return reserrors.NewParseReferenceError(m.id.path, err)
	}

	m.id.oneToOneNat = result["oneToOneNat"]
	m.id.network = result["network"]
	m.id.project = result["project"]

	return nil
}

func (m *OneToOneNatRef) Clone() *OneToOneNatRef {
	if m == nil {
		return nil
	}
	clone := *m
	return &clone
}

func (m OneToOneNatRef) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *OneToOneNatRef) Encode(e *jx.Encoder) {
	if m == nil {
		e.Null()
		return
	}
	e.Str(m.Path())
}

func (m *OneToOneNatRef) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *OneToOneNatRef) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("OneToOneNatRef")
	}

	v, err := decode.Str(d)
	if err != nil {
		return err
	}

	m.id.path = v
	return nil
}

func (m *OneToOneNatRef) absolutePath() string {
	if m == nil || m.id.oneToOneNat == "" || m.id.network == "" || m.id.project == "" {
		return ""
	}

	return "projects/" + m.id.project + "/networks/" + m.id.network + "/oneToOneNats/" + m.id.oneToOneNat
}
