// Code generated by mwsapigen, DO NOT EDIT.

package rm

import (
	"context"

	"github.com/go-faster/jx"

	"go.mws.cloud/go-sdk/internal/conv"
	"go.mws.cloud/go-sdk/internal/decode"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	resparsers "go.mws.cloud/go-sdk/internal/resources/parsers"
	valuesctx "go.mws.cloud/go-sdk/pkg/context/values"
	resifaces "go.mws.cloud/go-sdk/pkg/resources/interfaces"
	resmodels "go.mws.cloud/go-sdk/pkg/resources/models"
)

var (
	EnabledServiceRefTemplate = resparsers.Template{
		{
			Value:       "service",
			IsConstant:  false,
			SearchAfter: false,
		},
		{
			Value:       "enabledServices",
			IsConstant:  true,
			SearchAfter: false,
		},
		{
			Value:       "project",
			IsConstant:  false,
			SearchAfter: true,
		},
		{
			Value:       "projects",
			IsConstant:  true,
			SearchAfter: false,
		},
		{
			Value:       "rm",
			IsConstant:  true,
			SearchAfter: false,
		},
	}
)

func NewEnabledServiceID(project, service string) EnabledServiceID {
	m := EnabledServiceID{
		service: service,
		project: project,
	}
	m.path = m.ID()
	return m
}

func ParseEnabledServiceID(path string) (EnabledServiceID, error) {
	m := EnabledServiceID{
		path: path,
	}
	if err := m.Parse(context.Background()); err != nil {
		return EnabledServiceID{}, err
	}
	return m, nil
}

func NewEnabledServiceIDFromAnyID(resource resmodels.AnyResourceID) (EnabledServiceID, error) {
	return ParseEnabledServiceID(resource.ID())
}

type EnabledServiceID struct {
	service string
	project string
	path    string
}

func (m *EnabledServiceID) ResourceName() resifaces.ResourceName {
	if m == nil {
		return ""
	}
	return resifaces.ResourceName(m.service)
}

func (m *EnabledServiceID) GetService() string {
	if m == nil {
		return ""
	}
	return m.service
}

func (m *EnabledServiceID) GetProject() string {
	if m == nil {
		return ""
	}
	return m.project
}

func (m *EnabledServiceID) ServiceSlug() string {
	return "rm"
}

func (m *EnabledServiceID) ID() string {
	if m == nil || m.service == "" || m.project == "" {
		return ""
	}

	return m.ServiceSlug() + "/projects/" + m.project + "/enabledServices/" + m.service
}

func (m *EnabledServiceID) String() string {
	return m.ID()
}

func (m *EnabledServiceID) Parse(ctx context.Context) error {
	if m == nil {
		return nil
	}

	result, err := resparsers.Reference(ctx, m.path, EnabledServiceRefTemplate.AsID())
	if err != nil {
		return reserrors.NewParseIDError(m.path, err)
	}

	m.service = result["service"]
	m.project = result["project"]

	return nil
}

func (m *EnabledServiceID) Clone() *EnabledServiceID {
	if m == nil {
		return nil
	}
	clone := *m
	return &clone
}

func (m EnabledServiceID) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	if err := m.Encode(&e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (m *EnabledServiceID) Encode(e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	result := m.ID()
	if result == "" {
		result = m.path
	}
	e.Str(result)
	return nil
}

func (m *EnabledServiceID) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *EnabledServiceID) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("EnabledServiceRef")
	}

	v, err := decode.Str(d)
	if err != nil {
		return err
	}

	m.path = v
	return nil
}

func NewEnabledServiceRef(project, service string) EnabledServiceRef {
	m := EnabledServiceRef{
		id: EnabledServiceID{
			service: service,
			project: project,
		},
	}
	m.id.path = m.absolutePath()
	return m
}

func ParseEnabledServiceRef(ctx context.Context, path string) (EnabledServiceRef, error) {
	m := EnabledServiceRef{
		id: EnabledServiceID{
			path: path,
		},
	}
	if err := m.Parse(ctx); err != nil {
		return EnabledServiceRef{}, err
	}
	return m, nil
}

func NewEnabledServiceRefFromAnyRef(ref resmodels.AnyResourceRef) (EnabledServiceRef, error) {
	ctx := valuesctx.WithValuesStore(context.Background(), ref.GetPathValues())
	return ParseEnabledServiceRef(ctx, ref.Path())
}

type EnabledServiceRef struct {
	id EnabledServiceID
}

func (m *EnabledServiceRef) ResourceName() resifaces.ResourceName {
	if m == nil {
		return ""
	}
	return m.id.ResourceName()
}

func (m *EnabledServiceRef) GetService() string {
	if m == nil {
		return ""
	}
	return m.id.GetService()
}

func (m *EnabledServiceRef) GetProject() string {
	if m == nil {
		return ""
	}
	return m.id.GetProject()
}

func (m *EnabledServiceRef) ServiceSlug() string {
	return "rm"
}

func (m *EnabledServiceRef) IDPath() string {
	if m == nil {
		return ""
	}
	return m.id.ID()
}

func (m *EnabledServiceRef) Path() string {
	if m == nil {
		return ""
	}
	if m.id.path == "" {
		return m.absolutePath()
	}
	return m.id.path
}

func (m *EnabledServiceRef) String() string {
	return m.IDPath()
}

func (m *EnabledServiceRef) Parse(ctx context.Context) error {
	if m == nil {
		return nil
	}

	result, err := resparsers.Reference(ctx, m.id.path, EnabledServiceRefTemplate)
	if err != nil {
		return reserrors.NewParseReferenceError(m.id.path, err)
	}

	m.id.service = result["service"]
	m.id.project = result["project"]

	return nil
}

func (m *EnabledServiceRef) Clone() *EnabledServiceRef {
	if m == nil {
		return nil
	}
	clone := *m
	return &clone
}

func (m EnabledServiceRef) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	if err := m.Encode(&e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (m *EnabledServiceRef) Encode(e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.Str(m.Path())
	return nil
}

func (m *EnabledServiceRef) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *EnabledServiceRef) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("EnabledServiceRef")
	}

	v, err := decode.Str(d)
	if err != nil {
		return err
	}

	m.id.path = v
	return nil
}

func (m *EnabledServiceRef) absolutePath() string {
	if m == nil || m.id.service == "" || m.id.project == "" {
		return ""
	}

	return "projects/" + m.id.project + "/enabledServices/" + m.id.service
}
