// Code generated by mwsapigen, DO NOT EDIT.

package rm

import (
	"context"
	"fmt"

	"github.com/go-faster/jx"

	"go.mws.cloud/go-sdk/internal/conv"
	"go.mws.cloud/go-sdk/internal/decode"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	resparsers "go.mws.cloud/go-sdk/internal/resources/parsers"
	valuesctx "go.mws.cloud/go-sdk/pkg/context/values"
	resifaces "go.mws.cloud/go-sdk/pkg/resources/interfaces"
	resmodels "go.mws.cloud/go-sdk/pkg/resources/models"
)

var (
	ProjectPolicyRefTemplate = resparsers.Template{
		{
			Value:       "policy",
			IsConstant:  false,
			SearchAfter: false,
		},
		{
			Value:       "policies",
			IsConstant:  true,
			SearchAfter: false,
		},
		{
			Value:       "project",
			IsConstant:  false,
			SearchAfter: true,
		},
		{
			Value:       "projects",
			IsConstant:  true,
			SearchAfter: false,
		},
		{
			Value:       "rm",
			IsConstant:  true,
			SearchAfter: false,
		},
	}
)

func NewProjectPolicyID(project, policy string) (ProjectPolicyID, error) {
	if policy == "" {
		return ProjectPolicyID{}, reserrors.NewFieldIsEmptyError("policy")
	}
	if project == "" {
		return ProjectPolicyID{}, reserrors.NewFieldIsEmptyError("project")
	}
	m := ProjectPolicyID{
		policy:  policy,
		project: project,
	}
	m.path = m.ID()
	return m, nil
}

func NewMustProjectPolicyID(project, policy string) ProjectPolicyID {
	m, err := NewProjectPolicyID(project, policy)
	if err != nil {
		panic(err)
	}
	return m
}

func ParseProjectPolicyID(path string) (ProjectPolicyID, error) {
	m := ProjectPolicyID{
		path: path,
	}
	if err := m.parse(); err != nil {
		return ProjectPolicyID{}, err
	}
	return m, nil
}

func NewProjectPolicyIDFromAnyID(resource resmodels.AnyResourceID) (ProjectPolicyID, error) {
	return ParseProjectPolicyID(resource.ID())
}

type ProjectPolicyID struct {
	policy  string
	project string
	path    string
}

func (m *ProjectPolicyID) ResourceName() resifaces.ResourceName {
	if m == nil {
		return ""
	}
	return resifaces.ResourceName(m.policy)
}

func (m *ProjectPolicyID) GetPolicy() string {
	if m == nil {
		return ""
	}
	return m.policy
}

func (m *ProjectPolicyID) GetProject() string {
	if m == nil {
		return ""
	}
	return m.project
}

func (m *ProjectPolicyID) ServiceSlug() string {
	return "rm"
}

func (m *ProjectPolicyID) ID() string {
	if m == nil || m.policy == "" || m.project == "" {
		return ""
	}

	return m.ServiceSlug() + "/projects/" + m.project + "/policies/" + m.policy
}

func (m *ProjectPolicyID) String() string {
	return m.ID()
}

func (m *ProjectPolicyID) Clone() *ProjectPolicyID {
	if m == nil {
		return nil
	}
	clone := *m
	return &clone
}

func (m *ProjectPolicyID) AsRef() *ProjectPolicyRef {
	if m == nil {
		return nil
	}
	return &ProjectPolicyRef{
		id: *m,
	}
}

func (m *ProjectPolicyID) Equal(other *ProjectPolicyID) bool {
	if m == other {
		return true
	}
	if m == nil || other == nil {
		return false
	}
	return m.policy == other.policy && m.project == other.project
}

func (m ProjectPolicyID) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	if err := m.Encode(&e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (m *ProjectPolicyID) Encode(e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	result := m.ID()
	if result == "" {
		return fmt.Errorf("encode id: %w", reserrors.ErrIDIsEmpty)
	}
	e.Str(result)
	return nil
}

func (m *ProjectPolicyID) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *ProjectPolicyID) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("ProjectPolicyID")
	}

	v, err := decode.Str(d)
	if err != nil {
		return err
	}

	m.path = v
	return m.parse()
}

// Deprecated: Parse method is no longer required.
// Internal fields are populated automatically during decoding.
// This method will be removed in the next SDK release.
func (m *ProjectPolicyID) Parse(ctx context.Context) error {
	return nil
}

func (m *ProjectPolicyID) parse() error {
	if m == nil {
		return nil
	}

	if m.path == "" {
		return reserrors.NewParseIDError("", reserrors.ErrPathIsEmpty)
	}

	result, err := resparsers.Reference(context.Background(), m.path, ProjectPolicyRefTemplate.AsID())
	if err != nil {
		return reserrors.NewParseIDError(m.path, err)
	}

	m.policy = result["policy"]
	m.project = result["project"]

	return nil
}

func NewProjectPolicyRef(project, policy string) (ProjectPolicyRef, error) {
	if policy == "" {
		return ProjectPolicyRef{}, reserrors.NewFieldIsEmptyError("policy")
	}
	if project == "" {
		return ProjectPolicyRef{}, reserrors.NewFieldIsEmptyError("project")
	}
	m := ProjectPolicyRef{
		id: ProjectPolicyID{
			policy:  policy,
			project: project,
		},
	}
	m.id.path = m.absolutePath()
	return m, nil
}

func NewMustProjectPolicyRef(project, policy string) ProjectPolicyRef {
	m, err := NewProjectPolicyRef(project, policy)
	if err != nil {
		panic(err)
	}
	return m
}

func ParseProjectPolicyRef(ctx context.Context, path string) (ProjectPolicyRef, error) {
	m := ProjectPolicyRef{
		id: ProjectPolicyID{
			path: path,
		},
	}
	if err := m.Parse(ctx); err != nil {
		return ProjectPolicyRef{}, err
	}
	return m, nil
}

func NewProjectPolicyRefFromAnyRef(ref resmodels.AnyResourceRef) (ProjectPolicyRef, error) {
	ctx := valuesctx.WithValuesStore(context.Background(), ref.GetPathValues())
	return ParseProjectPolicyRef(ctx, ref.Path())
}

type ProjectPolicyRef struct {
	id ProjectPolicyID
}

func (m *ProjectPolicyRef) ResourceName() resifaces.ResourceName {
	if m == nil {
		return ""
	}
	return m.id.ResourceName()
}

func (m *ProjectPolicyRef) GetPolicy() string {
	if m == nil {
		return ""
	}
	return m.id.GetPolicy()
}

func (m *ProjectPolicyRef) GetProject() string {
	if m == nil {
		return ""
	}
	return m.id.GetProject()
}

func (m *ProjectPolicyRef) ServiceSlug() string {
	return "rm"
}

func (m *ProjectPolicyRef) IDPath() string {
	if m == nil {
		return ""
	}
	return m.id.ID()
}

func (m *ProjectPolicyRef) Path() string {
	if m == nil {
		return ""
	}
	if m.id.path == "" {
		return m.absolutePath()
	}
	return m.id.path
}

func (m *ProjectPolicyRef) String() string {
	return m.IDPath()
}

func (m *ProjectPolicyRef) Parse(ctx context.Context) error {
	return m.parse(ctx, false)
}

func (m *ProjectPolicyRef) Clone() *ProjectPolicyRef {
	if m == nil {
		return nil
	}
	clone := *m
	return &clone
}

func (m *ProjectPolicyRef) Equal(other *ProjectPolicyRef) bool {
	if m == other {
		return true
	}
	if m == nil || other == nil {
		return false
	}
	return m.id.policy == other.id.policy && m.id.project == other.id.project
}

func (m ProjectPolicyRef) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	if err := m.Encode(&e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (m *ProjectPolicyRef) Encode(e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	result := m.Path()
	if result == "" {
		return fmt.Errorf("encode reference: %w", reserrors.ErrPathIsEmpty)
	}
	e.Str(result)
	return nil
}

func (m *ProjectPolicyRef) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *ProjectPolicyRef) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("ProjectPolicyRef")
	}

	v, err := decode.Str(d)
	if err != nil {
		return err
	}

	m.id.path = v
	return m.parse(context.Background(), true)
}

func (m *ProjectPolicyRef) parse(ctx context.Context, allowPartial bool) error {
	if m == nil || m.isParsed() {
		return nil
	}

	if m.id.path == "" {
		return reserrors.NewParseReferenceError("", reserrors.ErrPathIsEmpty)
	}

	var options []resparsers.Option
	if allowPartial {
		options = append(options, resparsers.AllowPartial())
	}

	result, err := resparsers.Reference(ctx, m.id.path, ProjectPolicyRefTemplate, options...)
	if err != nil {
		return reserrors.NewParseReferenceError(m.id.path, err)
	}

	m.id.policy = result["policy"]
	m.id.project = result["project"]

	return nil
}

func (m *ProjectPolicyRef) isParsed() bool {
	return m != nil && m.id.policy != "" && m.id.project != ""
}

func (m *ProjectPolicyRef) absolutePath() string {
	if m == nil || m.id.policy == "" || m.id.project == "" {
		return ""
	}

	return "projects/" + m.id.project + "/policies/" + m.id.policy
}
