// Code generated by mwsapigen, DO NOT EDIT.

package model

// Real OAPI model name: ModelSpec
type ModelSpecResponse struct {
	// Размер контекстного окна модели в токенах.
	ContextWindowSize *uint                    `json:"contextWindowSize,omitempty" yaml:"contextWindowSize,omitempty"`
	InputModalities   InputModalitiesResponse  `json:"inputModalities" yaml:"inputModalities"`
	OutputModalities  OutputModalitiesResponse `json:"outputModalities" yaml:"outputModalities"`
	Modalities        ModalitiesResponse       `json:"modalities" yaml:"modalities"`
	Capabilities      CapabilitiesResponse     `json:"capabilities" yaml:"capabilities"`
	Deprecation       DeprecationResponse      `json:"deprecation" yaml:"deprecation"`
	// Размер модели в миллиардах параметров.
	Size *float32 `json:"size,omitempty" yaml:"size,omitempty"`
	// Разработчик модели.
	Developer *string `json:"developer,omitempty" yaml:"developer,omitempty"`
}

func (m *ModelSpecResponse) GetContextWindowSize() *uint {
	if m != nil {
		return m.ContextWindowSize
	}
	return nil
}

func (m *ModelSpecResponse) SetContextWindowSize(val *uint) {
	m.ContextWindowSize = val
}

func (m *ModelSpecResponse) GetContextWindowSizeOr(val uint) uint {
	if m != nil && m.ContextWindowSize != nil {
		return *m.ContextWindowSize
	}
	return val
}

func (m *ModelSpecResponse) GetInputModalities() InputModalitiesResponse {
	if m != nil {
		return m.InputModalities
	}
	return InputModalitiesResponse{}
}

func (m *ModelSpecResponse) SetInputModalities(val InputModalitiesResponse) {
	m.InputModalities = val
}

func (m *ModelSpecResponse) GetOutputModalities() OutputModalitiesResponse {
	if m != nil {
		return m.OutputModalities
	}
	return OutputModalitiesResponse{}
}

func (m *ModelSpecResponse) SetOutputModalities(val OutputModalitiesResponse) {
	m.OutputModalities = val
}

func (m *ModelSpecResponse) GetModalities() ModalitiesResponse {
	if m != nil {
		return m.Modalities
	}
	return ModalitiesResponse{}
}

func (m *ModelSpecResponse) SetModalities(val ModalitiesResponse) {
	m.Modalities = val
}

func (m *ModelSpecResponse) GetCapabilities() CapabilitiesResponse {
	if m != nil {
		return m.Capabilities
	}
	return CapabilitiesResponse{}
}

func (m *ModelSpecResponse) SetCapabilities(val CapabilitiesResponse) {
	m.Capabilities = val
}

func (m *ModelSpecResponse) GetDeprecation() DeprecationResponse {
	if m != nil {
		return m.Deprecation
	}
	return DeprecationResponse{}
}

func (m *ModelSpecResponse) SetDeprecation(val DeprecationResponse) {
	m.Deprecation = val
}

func (m *ModelSpecResponse) GetSize() *float32 {
	if m != nil {
		return m.Size
	}
	return nil
}

func (m *ModelSpecResponse) SetSize(val *float32) {
	m.Size = val
}

func (m *ModelSpecResponse) GetSizeOr(val float32) float32 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return val
}

func (m *ModelSpecResponse) GetDeveloper() *string {
	if m != nil {
		return m.Developer
	}
	return nil
}

func (m *ModelSpecResponse) SetDeveloper(val *string) {
	m.Developer = val
}

func (m *ModelSpecResponse) GetDeveloperOr(val string) string {
	if m != nil && m.Developer != nil {
		return *m.Developer
	}
	return val
}

func (m *ModelSpecResponse) Clone() *ModelSpecResponse {
	if m == nil {
		return nil
	}

	clone := *m
	if m.ContextWindowSize != nil {
		cloneContextWindowSize := *m.ContextWindowSize
		clone.ContextWindowSize = &cloneContextWindowSize
	}
	clone.InputModalities = *m.InputModalities.Clone()
	clone.OutputModalities = *m.OutputModalities.Clone()
	clone.Modalities = *m.Modalities.Clone()
	clone.Capabilities = *m.Capabilities.Clone()
	clone.Deprecation = *m.Deprecation.Clone()
	if m.Size != nil {
		cloneSize := *m.Size
		clone.Size = &cloneSize
	}
	if m.Developer != nil {
		cloneDeveloper := *m.Developer
		clone.Developer = &cloneDeveloper
	}
	return &clone
}
