// Code generated by mwsapigen, DO NOT EDIT.

package support

import (
	"context"
	"fmt"

	"github.com/go-faster/jx"

	"go.mws.cloud/go-sdk/internal/conv"
	"go.mws.cloud/go-sdk/internal/decode"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	resparsers "go.mws.cloud/go-sdk/internal/resources/parsers"
	valuesctx "go.mws.cloud/go-sdk/pkg/context/values"
	resifaces "go.mws.cloud/go-sdk/pkg/resources/interfaces"
	resmodels "go.mws.cloud/go-sdk/pkg/resources/models"
)

var (
	RequestTypeRefTemplate = resparsers.Template{
		{
			Value:       "requestTypeName",
			IsConstant:  false,
			SearchAfter: false,
		},
		{
			Value:       "requestTypes",
			IsConstant:  true,
			SearchAfter: false,
		},
		{
			Value:       "support",
			IsConstant:  true,
			SearchAfter: false,
		},
	}
)

func NewRequestTypeID(requestTypeName string) (RequestTypeID, error) {
	if requestTypeName == "" {
		return RequestTypeID{}, reserrors.NewFieldIsEmptyError("requestTypeName")
	}
	m := RequestTypeID{
		requestTypeName: requestTypeName,
	}
	m.path = m.ID()
	return m, nil
}

func NewMustRequestTypeID(requestTypeName string) RequestTypeID {
	m, err := NewRequestTypeID(requestTypeName)
	if err != nil {
		panic(err)
	}
	return m
}

func ParseRequestTypeID(path string) (RequestTypeID, error) {
	m := RequestTypeID{
		path: path,
	}
	if err := m.parse(); err != nil {
		return RequestTypeID{}, err
	}
	return m, nil
}

func NewRequestTypeIDFromAnyID(resource resmodels.AnyResourceID) (RequestTypeID, error) {
	return ParseRequestTypeID(resource.ID())
}

type RequestTypeID struct {
	requestTypeName string
	path            string
}

func (m *RequestTypeID) ResourceName() resifaces.ResourceName {
	if m == nil {
		return ""
	}
	return resifaces.ResourceName(m.requestTypeName)
}

func (m *RequestTypeID) GetRequestTypeName() string {
	if m == nil {
		return ""
	}
	return m.requestTypeName
}

func (m *RequestTypeID) ServiceSlug() string {
	return "support"
}

func (m *RequestTypeID) ID() string {
	if m == nil || m.requestTypeName == "" {
		return ""
	}

	return m.ServiceSlug() + "/requestTypes/" + m.requestTypeName
}

func (m *RequestTypeID) String() string {
	return m.ID()
}

func (m *RequestTypeID) Clone() *RequestTypeID {
	if m == nil {
		return nil
	}
	clone := *m
	return &clone
}

func (m *RequestTypeID) AsRef() *RequestTypeRef {
	if m == nil {
		return nil
	}
	return &RequestTypeRef{
		id: *m,
	}
}

func (m *RequestTypeID) Equal(other *RequestTypeID) bool {
	if m == other {
		return true
	}
	if m == nil || other == nil {
		return false
	}
	return m.requestTypeName == other.requestTypeName
}

func (m RequestTypeID) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	if err := m.Encode(&e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (m *RequestTypeID) Encode(e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	result := m.ID()
	if result == "" {
		return fmt.Errorf("encode id: %w", reserrors.ErrIDIsEmpty)
	}
	e.Str(result)
	return nil
}

func (m *RequestTypeID) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *RequestTypeID) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("RequestTypeID")
	}

	v, err := decode.Str(d)
	if err != nil {
		return err
	}

	m.path = v
	return m.parse()
}

// Deprecated: Parse method is no longer required.
// Internal fields are populated automatically during decoding.
// This method will be removed in the next SDK release.
func (m *RequestTypeID) Parse(ctx context.Context) error {
	return nil
}

func (m *RequestTypeID) parse() error {
	if m == nil {
		return nil
	}

	if m.path == "" {
		return reserrors.NewParseIDError("", reserrors.ErrPathIsEmpty)
	}

	result, err := resparsers.Reference(context.Background(), m.path, RequestTypeRefTemplate.AsID())
	if err != nil {
		return reserrors.NewParseIDError(m.path, err)
	}

	m.requestTypeName = result["requestTypeName"]

	return nil
}

func NewRequestTypeRef(requestTypeName string) (RequestTypeRef, error) {
	if requestTypeName == "" {
		return RequestTypeRef{}, reserrors.NewFieldIsEmptyError("requestTypeName")
	}
	m := RequestTypeRef{
		id: RequestTypeID{
			requestTypeName: requestTypeName,
		},
	}
	m.id.path = m.absolutePath()
	return m, nil
}

func NewMustRequestTypeRef(requestTypeName string) RequestTypeRef {
	m, err := NewRequestTypeRef(requestTypeName)
	if err != nil {
		panic(err)
	}
	return m
}

func ParseRequestTypeRef(ctx context.Context, path string) (RequestTypeRef, error) {
	m := RequestTypeRef{
		id: RequestTypeID{
			path: path,
		},
	}
	if err := m.Parse(ctx); err != nil {
		return RequestTypeRef{}, err
	}
	return m, nil
}

func NewRequestTypeRefFromAnyRef(ref resmodels.AnyResourceRef) (RequestTypeRef, error) {
	ctx := valuesctx.WithValuesStore(context.Background(), ref.GetPathValues())
	return ParseRequestTypeRef(ctx, ref.Path())
}

type RequestTypeRef struct {
	id RequestTypeID
}

func (m *RequestTypeRef) ResourceName() resifaces.ResourceName {
	if m == nil {
		return ""
	}
	return m.id.ResourceName()
}

func (m *RequestTypeRef) GetRequestTypeName() string {
	if m == nil {
		return ""
	}
	return m.id.GetRequestTypeName()
}

func (m *RequestTypeRef) ServiceSlug() string {
	return "support"
}

func (m *RequestTypeRef) IDPath() string {
	if m == nil {
		return ""
	}
	return m.id.ID()
}

func (m *RequestTypeRef) Path() string {
	if m == nil {
		return ""
	}
	if m.id.path == "" {
		return m.absolutePath()
	}
	return m.id.path
}

func (m *RequestTypeRef) String() string {
	return m.IDPath()
}

func (m *RequestTypeRef) Parse(ctx context.Context) error {
	return m.parse(ctx, false)
}

func (m *RequestTypeRef) Clone() *RequestTypeRef {
	if m == nil {
		return nil
	}
	clone := *m
	return &clone
}

func (m *RequestTypeRef) Equal(other *RequestTypeRef) bool {
	if m == other {
		return true
	}
	if m == nil || other == nil {
		return false
	}
	return m.id.requestTypeName == other.id.requestTypeName
}

func (m RequestTypeRef) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	if err := m.Encode(&e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (m *RequestTypeRef) Encode(e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	result := m.Path()
	if result == "" {
		return fmt.Errorf("encode reference: %w", reserrors.ErrPathIsEmpty)
	}
	e.Str(result)
	return nil
}

func (m *RequestTypeRef) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *RequestTypeRef) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("RequestTypeRef")
	}

	v, err := decode.Str(d)
	if err != nil {
		return err
	}

	m.id.path = v
	return m.parse(context.Background(), true)
}

func (m *RequestTypeRef) parse(ctx context.Context, allowPartial bool) error {
	if m == nil || m.isParsed() {
		return nil
	}

	if m.id.path == "" {
		return reserrors.NewParseReferenceError("", reserrors.ErrPathIsEmpty)
	}

	var options []resparsers.Option
	if allowPartial {
		options = append(options, resparsers.AllowPartial())
	}

	result, err := resparsers.Reference(ctx, m.id.path, RequestTypeRefTemplate, options...)
	if err != nil {
		return reserrors.NewParseReferenceError(m.id.path, err)
	}

	m.id.requestTypeName = result["requestTypeName"]

	return nil
}

func (m *RequestTypeRef) isParsed() bool {
	return m != nil && m.id.requestTypeName != ""
}

func (m *RequestTypeRef) absolutePath() string {
	if m == nil || m.id.requestTypeName == "" {
		return ""
	}

	return "requestTypes/" + m.id.requestTypeName
}
