// Code generated by mwsapigen, DO NOT EDIT.

package mock_client

import (
	"context"
	"reflect"

	"go.uber.org/mock/gomock"

	"go.mws.cloud/go-sdk/service/auditlogs/client"
)

// MockCollector is a mock of Collector interface.
type MockCollector struct {
	ctrl     *gomock.Controller
	recorder *MockCollectorMockRecorder
}

// MockCollectorMockRecorder is the mock recorder for MockCollector.
type MockCollectorMockRecorder struct {
	mock *MockCollector
}

// NewMockCollector creates a new mock instance.
func NewMockCollector(ctrl *gomock.Controller) *MockCollector {
	mock := &MockCollector{ctrl: ctrl}
	mock.recorder = &MockCollectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCollector) EXPECT() *MockCollectorMockRecorder {
	return m.recorder
}

// CreateCollector mocks base method.
func (m *MockCollector) CreateCollector(arg0 context.Context, arg1 client.UpsertCollectorRequest) (*client.UpsertCollectorResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCollector", arg0, arg1)
	ret0, _ := ret[0].(*client.UpsertCollectorResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCollector indicates an expected call of CreateCollector.
func (mr *MockCollectorMockRecorder) CreateCollector(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCollector", reflect.TypeOf((*MockCollector)(nil).CreateCollector), arg0, arg1)
}

// DeleteCollector mocks base method.
func (m *MockCollector) DeleteCollector(arg0 context.Context, arg1 client.DeleteCollectorRequest) (*client.DeleteCollectorResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCollector", arg0, arg1)
	ret0, _ := ret[0].(*client.DeleteCollectorResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteCollector indicates an expected call of DeleteCollector.
func (mr *MockCollectorMockRecorder) DeleteCollector(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCollector", reflect.TypeOf((*MockCollector)(nil).DeleteCollector), arg0, arg1)
}

// GetCollector mocks base method.
func (m *MockCollector) GetCollector(arg0 context.Context, arg1 client.GetCollectorRequest) (*client.GetCollectorResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCollector", arg0, arg1)
	ret0, _ := ret[0].(*client.GetCollectorResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCollector indicates an expected call of GetCollector.
func (mr *MockCollectorMockRecorder) GetCollector(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCollector", reflect.TypeOf((*MockCollector)(nil).GetCollector), arg0, arg1)
}

// ListCollectors mocks base method.
func (m *MockCollector) ListCollectors(arg0 context.Context, arg1 client.ListCollectorsRequest) (*client.ListCollectorsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCollectors", arg0, arg1)
	ret0, _ := ret[0].(*client.ListCollectorsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCollectors indicates an expected call of ListCollectors.
func (mr *MockCollectorMockRecorder) ListCollectors(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCollectors", reflect.TypeOf((*MockCollector)(nil).ListCollectors), arg0, arg1)
}

// UpdateCollector mocks base method.
func (m *MockCollector) UpdateCollector(arg0 context.Context, arg1 client.UpdateCollectorRequest) (*client.UpsertCollectorResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCollector", arg0, arg1)
	ret0, _ := ret[0].(*client.UpsertCollectorResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCollector indicates an expected call of UpdateCollector.
func (mr *MockCollectorMockRecorder) UpdateCollector(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCollector", reflect.TypeOf((*MockCollector)(nil).UpdateCollector), arg0, arg1)
}

// UpsertCollector mocks base method.
func (m *MockCollector) UpsertCollector(arg0 context.Context, arg1 client.UpsertCollectorRequest) (*client.UpsertCollectorResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertCollector", arg0, arg1)
	ret0, _ := ret[0].(*client.UpsertCollectorResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertCollector indicates an expected call of UpsertCollector.
func (mr *MockCollectorMockRecorder) UpsertCollector(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertCollector", reflect.TypeOf((*MockCollector)(nil).UpsertCollector), arg0, arg1)
}
