// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"context"
	"fmt"
	"slices"

	commonclient "go.mws.cloud/go-sdk/internal/client"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	"go.mws.cloud/go-sdk/service/resources/references/vpc"
)

type UpdateEgressNatSpecInternalRequest struct {
	// Коллекция относительных ссылок на подсети, для которых будет осуществляться трансляция.
	Subnets commonclient.Optional[[]vpc.SubnetRef] `json:"subnets" yaml:"subnets"`
}

func (m *EgressNatSpecInternalRequest) AsUpdateModel() UpdateEgressNatSpecInternalRequest {
	var u UpdateEgressNatSpecInternalRequest
	u.Subnets = commonclient.NewOptional(m.GetSubnets())
	return u
}

// Diff creates an object that can be used in Update methods. This object represents changes from src to the current state
func (m *EgressNatSpecInternalRequest) Diff(src *EgressNatSpecInternalRequest) UpdateEgressNatSpecInternalRequest {
	nilDiffers := src != nil && m == nil
	upd := UpdateEgressNatSpecInternalRequest{}
	if !nilDiffers {
		upd.Subnets = m.diffSubnets(src)
	}
	return upd
}

func (m *EgressNatSpecInternalRequest) WithChanges(u UpdateEgressNatSpecInternalRequest) EgressNatSpecInternalRequest {
	var out EgressNatSpecInternalRequest
	if m != nil {
		out = *m
	}

	if u.Subnets.IsSet() {
		out.Subnets = slices.Clone(u.Subnets.Value)
	}
	return out
}

// HasChanges returns true if any field has Set == true
func (m UpdateEgressNatSpecInternalRequest) HasChanges() bool {
	return m.Subnets.Set
}

func (m *UpdateEgressNatSpecInternalRequest) Parse(ctx context.Context) error {
	if m == nil {
		return nil
	}

	if m.Subnets.IsSet() {
		for index := range m.Subnets.Value {
			if err := m.Subnets.Value[index].Parse(ctx); err != nil {
				return reserrors.NewPathAccumulatorError("Subnets"+fmt.Sprint("[", index, "]"), err)
			}
		}
	}

	return nil
}

func (m *EgressNatSpecInternalRequest) diffSubnets(src *EgressNatSpecInternalRequest) commonclient.Optional[[]vpc.SubnetRef] {
	value, hasChanges := commonclient.GetChangesArrayPrimitive(src.GetSubnets(), m.GetSubnets())
	return commonclient.NewDirectOptional[[]vpc.SubnetRef](value, hasChanges)
}
