// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	common "go.mws.cloud/go-sdk/service/common/model"
)

func EgressNatSpecExternalRequestToOptionalResponse(request *EgressNatSpecExternalRequest) (*EgressNatSpecExternalOptionalResponse, error) {
	if request == nil {
		return nil, nil
	}
	var response EgressNatSpecExternalOptionalResponse
	for _, e := range request.Addresses {
		tmp, err := common.ResourceExternalAddressSpecOrRefRequestToOptionalResponse(&e)
		if err != nil {
			return nil, err
		}
		response.Addresses = append(response.Addresses, *tmp)
	}
	return &response, nil
}
