// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"context"

	"go.mws.cloud/util-toolset/pkg/utils/ptr"

	commonclient "go.mws.cloud/go-sdk/internal/client"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
)

type UpdateEgressNatSpecRequest struct {
	// Группирующий элемент для всего, что касается внутренних ресурсов.
	Internal commonclient.Optional[UpdateEgressNatSpecInternalRequest] `json:"internal" yaml:"internal"`
	// Группирующий элемент для всего, что касается внешней части (ресурсов, доступных извне).
	External commonclient.Optional[UpdateEgressNatSpecExternalRequest] `json:"external" yaml:"external"`
	// Описывает настройки управления портами.
	PortAllocation commonclient.OptionalNil[UpdateEgressNatSpecPortAllocationRequest] `json:"portAllocation" yaml:"portAllocation"`
	// Описывает настройки управления портами (Port Block Allocation).
	Pba commonclient.OptionalNil[UpdateEgressNatSpecPbaRequest] `json:"pba" yaml:"pba"`
}

func (m *EgressNatSpecRequest) AsUpdateModel() UpdateEgressNatSpecRequest {
	var u UpdateEgressNatSpecRequest
	u.Internal = commonclient.NewOptional(m.Internal.AsUpdateModel())
	u.External = commonclient.NewOptional(m.External.AsUpdateModel())
	if m.PortAllocation != nil {
		u.PortAllocation = commonclient.NewOptionalNil(m.PortAllocation.AsUpdateModel())
	}
	if m.Pba != nil {
		u.Pba = commonclient.NewOptionalNil(m.Pba.AsUpdateModel())
	}
	return u
}

// Diff creates an object that can be used in Update methods. This object represents changes from src to the current state
func (m *EgressNatSpecRequest) Diff(src *EgressNatSpecRequest) UpdateEgressNatSpecRequest {
	nilDiffers := src != nil && m == nil
	upd := UpdateEgressNatSpecRequest{}
	if !nilDiffers {
		upd.Internal = m.diffInternal(src)
		upd.External = m.diffExternal(src)
		upd.PortAllocation = m.diffPortAllocation(src)
		upd.Pba = m.diffPba(src)
	}
	return upd
}

func (m *EgressNatSpecRequest) WithChanges(u UpdateEgressNatSpecRequest) EgressNatSpecRequest {
	var out EgressNatSpecRequest
	if m != nil {
		out = *m
	}

	if u.Internal.IsSet() {
		out.Internal = out.Internal.WithChanges(u.Internal.Value)
	}
	if u.External.IsSet() {
		out.External = out.External.WithChanges(u.External.Value)
	}
	if u.PortAllocation.IsSet() {
		out.PortAllocation = ptr.Get(out.PortAllocation.WithChanges(u.PortAllocation.Value))
	} else if u.PortAllocation.IsNull() {
		out.PortAllocation = nil
	}
	if u.Pba.IsSet() {
		out.Pba = ptr.Get(out.Pba.WithChanges(u.Pba.Value))
	} else if u.Pba.IsNull() {
		out.Pba = nil
	}
	return out
}

// HasChanges returns true if any field has Set == true
func (m UpdateEgressNatSpecRequest) HasChanges() bool {
	return m.Internal.Set ||
		m.External.Set ||
		m.PortAllocation.Set ||
		m.Pba.Set
}

func (m *UpdateEgressNatSpecRequest) Parse(ctx context.Context) error {
	if m == nil {
		return nil
	}

	if m.Internal.IsSet() {
		if err := m.Internal.Value.Parse(ctx); err != nil {
			return reserrors.NewPathAccumulatorError("Internal", err)
		}
	}

	if m.External.IsSet() {
		if err := m.External.Value.Parse(ctx); err != nil {
			return reserrors.NewPathAccumulatorError("External", err)
		}
	}

	return nil
}

func (m *EgressNatSpecRequest) diffInternal(src *EgressNatSpecRequest) commonclient.Optional[UpdateEgressNatSpecInternalRequest] {
	from := src.GetInternal()
	to := m.GetInternal()
	value := to.Diff(&from)
	return commonclient.NewDirectOptional[UpdateEgressNatSpecInternalRequest](value, value.HasChanges())
}

func (m *EgressNatSpecRequest) diffExternal(src *EgressNatSpecRequest) commonclient.Optional[UpdateEgressNatSpecExternalRequest] {
	from := src.GetExternal()
	to := m.GetExternal()
	value := to.Diff(&from)
	return commonclient.NewDirectOptional[UpdateEgressNatSpecExternalRequest](value, value.HasChanges())
}

func (m *EgressNatSpecRequest) diffPortAllocation(src *EgressNatSpecRequest) commonclient.OptionalNil[UpdateEgressNatSpecPortAllocationRequest] {
	nilDiffers := src != nil && m == nil
	value := m.GetPortAllocation().Diff(src.GetPortAllocation())
	return commonclient.NewDirectOptionalNil[UpdateEgressNatSpecPortAllocationRequest](value, nilDiffers || value.HasChanges(), nilDiffers)
}

func (m *EgressNatSpecRequest) diffPba(src *EgressNatSpecRequest) commonclient.OptionalNil[UpdateEgressNatSpecPbaRequest] {
	nilDiffers := src != nil && m == nil
	value := m.GetPba().Diff(src.GetPba())
	return commonclient.NewDirectOptionalNil[UpdateEgressNatSpecPbaRequest](value, nilDiffers || value.HasChanges(), nilDiffers)
}
