// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"go.mws.cloud/util-toolset/pkg/utils/ptr"

	commonclient "go.mws.cloud/go-sdk/internal/client"
	common "go.mws.cloud/go-sdk/service/common/model"
)

type UpdateFirewallRuleRequest struct {
	// Метаданные правила Firewall'а.
	Metadata commonclient.OptionalNil[common.UpdateCommonTypedResourceMetadataRequest] `json:"metadata" yaml:"metadata"`
	// Спецификация правила Firewall'а.
	Spec commonclient.Optional[UpdateFirewallRuleSpecRequest] `json:"spec" yaml:"spec"`
}

func (m *FirewallRuleRequest) AsUpdateModel() UpdateFirewallRuleRequest {
	var u UpdateFirewallRuleRequest
	if m.Metadata != nil {
		u.Metadata = commonclient.NewOptionalNil(m.Metadata.AsUpdateModel())
	}
	u.Spec = commonclient.NewOptional(m.Spec.AsUpdateModel())
	return u
}

// Diff creates an object that can be used in Update methods. This object represents changes from src to the current state
func (m *FirewallRuleRequest) Diff(src *FirewallRuleRequest) UpdateFirewallRuleRequest {
	nilDiffers := src != nil && m == nil
	upd := UpdateFirewallRuleRequest{}
	if !nilDiffers {
		upd.Metadata = m.diffMetadata(src)
		upd.Spec = m.diffSpec(src)
	}
	return upd
}

func (m *FirewallRuleRequest) WithChanges(u UpdateFirewallRuleRequest) FirewallRuleRequest {
	var out FirewallRuleRequest
	if m != nil {
		out = *m
	}

	if u.Metadata.IsSet() {
		out.Metadata = ptr.Get(out.Metadata.WithChanges(u.Metadata.Value))
	} else if u.Metadata.IsNull() {
		out.Metadata = nil
	}
	if u.Spec.IsSet() {
		out.Spec = out.Spec.WithChanges(u.Spec.Value)
	}
	return out
}

// HasChanges returns true if any field has Set == true
func (m UpdateFirewallRuleRequest) HasChanges() bool {
	return m.Metadata.Set ||
		m.Spec.Set
}

func (m *FirewallRuleRequest) diffMetadata(src *FirewallRuleRequest) commonclient.OptionalNil[common.UpdateCommonTypedResourceMetadataRequest] {
	nilDiffers := src != nil && m == nil
	value := m.GetMetadata().Diff(src.GetMetadata())
	return commonclient.NewDirectOptionalNil[common.UpdateCommonTypedResourceMetadataRequest](value, nilDiffers || value.HasChanges(), nilDiffers)
}

func (m *FirewallRuleRequest) diffSpec(src *FirewallRuleRequest) commonclient.Optional[UpdateFirewallRuleSpecRequest] {
	from := src.GetSpec()
	to := m.GetSpec()
	value := to.Diff(&from)
	return commonclient.NewDirectOptional[UpdateFirewallRuleSpecRequest](value, value.HasChanges())
}
