// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"context"
	"fmt"

	commonclient "go.mws.cloud/go-sdk/internal/client"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	common "go.mws.cloud/go-sdk/service/common/model"
)

// Real OAPI model name: ListRoutesResponse
type ListRoutesResponseOptionalResponse struct {
	Items []RouteOptionalResponse `json:"items" yaml:"items"`
	// Строка, которую нужно передать в следующий запрос, чтобы получить следующую страницу. Для последней страницы не задан
	NextPageToken commonclient.Optional[common.NextPageToken] `json:"nextPageToken,omitempty" yaml:"nextPageToken,omitempty"`
}

func (m *ListRoutesResponseOptionalResponse) GetItems() []RouteOptionalResponse {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ListRoutesResponseOptionalResponse) SetItems(val []RouteOptionalResponse) {
	m.Items = val
}

func (m *ListRoutesResponseOptionalResponse) GetNextPageToken() *common.NextPageToken {
	if m != nil && m.NextPageToken.IsSet() {
		return &m.NextPageToken.Value
	}
	return nil
}

func (m *ListRoutesResponseOptionalResponse) GetNextPageTokenOr(val common.NextPageToken) common.NextPageToken {
	if m != nil && m.NextPageToken.IsSet() {
		return m.NextPageToken.Value
	}
	return val
}

func (m *ListRoutesResponseOptionalResponse) Clone() *ListRoutesResponseOptionalResponse {
	if m == nil {
		return nil
	}

	clone := *m
	if m.Items != nil {
		clone.Items = make([]RouteOptionalResponse, len(m.Items))
		for i, v := range m.Items {
			clone.Items[i] = *v.Clone()
		}
	}
	return &clone
}

func (m *ListRoutesResponseOptionalResponse) Parse(ctx context.Context) error {
	if m == nil {
		return nil
	}

	for index := range m.Items {
		if err := m.Items[index].Parse(ctx); err != nil {
			return reserrors.NewPathAccumulatorError("Items"+fmt.Sprint("[", index, "]"), err)
		}
	}

	return nil
}
