// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"context"

	commonclient "go.mws.cloud/go-sdk/internal/client"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	common "go.mws.cloud/go-sdk/service/common/model"
)

// Сеть — это виртуальный аналог физической сети на базе инфраструктуры MWS
// Real OAPI model name: Network
type NetworkOptionalResponse struct {
	Kind *string `json:"kind,omitempty" yaml:"kind,omitempty"`
	// Набор общих для всех пользовательских объектов аттрибутов. Может быть расширен аттрибутами, специфичными для контейнеров.
	Metadata commonclient.OptionalNil[common.CommonTypedResourceMetadataOptionalResponse] `json:"metadata,omitempty" yaml:"metadata,omitempty"`
	Spec     VpcNetworkSpecOptionalResponse                                               `json:"spec" yaml:"spec"`
	Status   *NetworkStatusResponse                                                       `json:"status,omitempty" yaml:"status,omitempty"`
}

func (m *NetworkOptionalResponse) GetKind() *string {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (m *NetworkOptionalResponse) SetKind(val *string) {
	m.Kind = val
}

func (m *NetworkOptionalResponse) GetKindOr(val string) string {
	if m != nil && m.Kind != nil {
		return *m.Kind
	}
	return val
}

func (m *NetworkOptionalResponse) GetMetadata() *common.CommonTypedResourceMetadataOptionalResponse {
	if m != nil && m.Metadata.IsSet() {
		return &m.Metadata.Value
	}
	return nil
}

func (m *NetworkOptionalResponse) GetMetadataOr(val common.CommonTypedResourceMetadataOptionalResponse) common.CommonTypedResourceMetadataOptionalResponse {
	if m != nil && m.Metadata.IsSet() {
		return m.Metadata.Value
	}
	return val
}

func (m *NetworkOptionalResponse) GetSpec() VpcNetworkSpecOptionalResponse {
	if m != nil {
		return m.Spec
	}
	return VpcNetworkSpecOptionalResponse{}
}

func (m *NetworkOptionalResponse) SetSpec(val VpcNetworkSpecOptionalResponse) {
	m.Spec = val
}

func (m *NetworkOptionalResponse) GetStatus() *NetworkStatusResponse {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *NetworkOptionalResponse) SetStatus(val *NetworkStatusResponse) {
	m.Status = val
}

func (m *NetworkOptionalResponse) GetStatusOr(val NetworkStatusResponse) NetworkStatusResponse {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return val
}

func (m *NetworkOptionalResponse) Clone() *NetworkOptionalResponse {
	if m == nil {
		return nil
	}

	clone := *m
	if m.Kind != nil {
		cloneKind := *m.Kind
		clone.Kind = &cloneKind
	}
	if clone.Metadata.IsSet() {
		clone.Metadata.Value = *m.Metadata.Value.Clone()
	}
	clone.Spec = *m.Spec.Clone()
	clone.Status = m.Status.Clone()
	return &clone
}

func (m *NetworkOptionalResponse) Parse(ctx context.Context) error {
	if m == nil {
		return nil
	}

	if m.Metadata.IsSet() {
		if err := m.Metadata.Value.Parse(ctx); err != nil {
			return reserrors.NewPathAccumulatorError("Metadata", err)
		}
	}

	return nil
}
