// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	commonclient "go.mws.cloud/go-sdk/internal/client"
	common "go.mws.cloud/go-sdk/service/common/model"
)

func OneToOneNatRequestToOptionalResponse(request *OneToOneNatRequest) (*OneToOneNatOptionalResponse, error) {
	if request == nil {
		return nil, nil
	}
	var response OneToOneNatOptionalResponse
	if request.Metadata != nil {
		tmpMetadata, err := common.CommonTypedResourceMetadataRequestToOptionalResponse(request.Metadata)
		if err != nil {
			return nil, err
		}
		response.Metadata = commonclient.NewOptionalNil(*tmpMetadata)
	}
	tmpSpec, err := OneToOneNatSpecRequestToOptionalResponse(&request.Spec)
	if err != nil {
		return nil, err
	}
	response.Spec = *tmpSpec
	return &response, nil
}
