// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"context"

	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	commonmodel "go.mws.cloud/go-sdk/service/common/model"
)

// Группирующий элемент для всего, что касается внутренних ресурсов.
// Real OAPI model name: OneToOneNatSpecInternal
type OneToOneNatSpecInternalOptionalResponse struct {
	// Спецификация внутреннего адреса, для которого будет осуществляться трансляция.
	Address commonmodel.ResourceAddressSpecOrRefOptionalResponse `json:"address" yaml:"address"`
}

func (m *OneToOneNatSpecInternalOptionalResponse) GetAddress() commonmodel.ResourceAddressSpecOrRefOptionalResponse {
	if m != nil {
		return m.Address
	}
	return commonmodel.ResourceAddressSpecOrRefOptionalResponse{}
}

func (m *OneToOneNatSpecInternalOptionalResponse) SetAddress(val commonmodel.ResourceAddressSpecOrRefOptionalResponse) {
	m.Address = val
}

func (m *OneToOneNatSpecInternalOptionalResponse) Clone() *OneToOneNatSpecInternalOptionalResponse {
	if m == nil {
		return nil
	}

	clone := *m
	clone.Address = *m.Address.Clone()
	return &clone
}

func (m *OneToOneNatSpecInternalOptionalResponse) Parse(ctx context.Context) error {
	if m == nil {
		return nil
	}

	if err := m.Address.Parse(ctx); err != nil {
		return reserrors.NewPathAccumulatorError("Address", err)
	}

	return nil
}
