// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/go-faster/jx"

	"go.mws.cloud/go-sdk/internal/conv"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
)

func (m UpdateOneToOneNatSpecExternalRequest) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *UpdateOneToOneNatSpecExternalRequest) Encode(e *jx.Encoder) {
	if m == nil {
		e.Null()
		return
	}
	e.ObjStart()
	m.encodeFields(e)
	e.ObjEnd()
}

func (m *UpdateOneToOneNatSpecExternalRequest) encodeFields(e *jx.Encoder) {
	if m.Address.IsSet() {
		e.FieldStart("address")
		m.Address.Value.Encode(e)
	}
}

func (m *UpdateOneToOneNatSpecExternalRequest) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *UpdateOneToOneNatSpecExternalRequest) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("UpdateOneToOneNatSpecExternalRequest")
	}

	return d.ObjBytes(reserrors.PathAccumulatorErrorObjBytesFuncWrap(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "address":
			var v UpdateResourceExternalAddressSpecOrRefRequest
			if err := v.Decode(d); err != nil {
				return err
			}

			m.Address.SetTo(v)
			return nil
		default:
			return d.Skip()
		}
	}))
}
