// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"context"

	"go.mws.cloud/go-sdk/pkg/apimodels/ipaddress"

	commonclient "go.mws.cloud/go-sdk/internal/client"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	"go.mws.cloud/go-sdk/service/resources/references/vpc"
)

// Спецификация внутреннего адреса.
// Real OAPI model name: ResourceAddressSpec
type ResourceAddressSpecOptionalResponse struct {
	// Подсеть облачной сети к которой принадлежит адрес. В случае приватного адреса, он всегда принадлежит к некоторой подсети внутри облачной сети.
	Subnet vpc.SubnetRef `json:"subnet" yaml:"subnet"`
	// Значение IP адреса.
	IpAddress commonclient.Optional[ipaddress.IPAddress]                 `json:"ipAddress,omitempty" yaml:"ipAddress,omitempty"`
	Dns       commonclient.Optional[[]VpcAddressDnsSpecOptionalResponse] `json:"dns,omitempty" yaml:"dns,omitempty"`
}

func (m *ResourceAddressSpecOptionalResponse) GetSubnet() vpc.SubnetRef {
	if m != nil {
		return m.Subnet
	}
	return vpc.SubnetRef{}
}

func (m *ResourceAddressSpecOptionalResponse) SetSubnet(val vpc.SubnetRef) {
	m.Subnet = val
}

func (m *ResourceAddressSpecOptionalResponse) GetIpAddress() *ipaddress.IPAddress {
	if m != nil && m.IpAddress.IsSet() {
		return &m.IpAddress.Value
	}
	return nil
}

func (m *ResourceAddressSpecOptionalResponse) GetIpAddressOr(val ipaddress.IPAddress) ipaddress.IPAddress {
	if m != nil && m.IpAddress.IsSet() {
		return m.IpAddress.Value
	}
	return val
}

func (m *ResourceAddressSpecOptionalResponse) GetDns() []VpcAddressDnsSpecOptionalResponse {
	if m != nil && m.Dns.IsSet() {
		return m.Dns.Value
	}
	return nil
}

func (m *ResourceAddressSpecOptionalResponse) GetDnsOr(val []VpcAddressDnsSpecOptionalResponse) []VpcAddressDnsSpecOptionalResponse {
	if m != nil && m.Dns.IsSet() {
		return m.Dns.Value
	}
	return val
}

func (m *ResourceAddressSpecOptionalResponse) Clone() *ResourceAddressSpecOptionalResponse {
	if m == nil {
		return nil
	}

	clone := *m
	clone.Subnet = *m.Subnet.Clone()
	if clone.IpAddress.IsSet() {
		clone.IpAddress.Value = *m.IpAddress.Value.Clone()
	}
	if m.Dns.Value != nil {
		clone.Dns.Value = make([]VpcAddressDnsSpecOptionalResponse, len(m.Dns.Value))
		for i, v := range m.Dns.Value {
			clone.Dns.Value[i] = *v.Clone()
		}
	}
	return &clone
}

func (m *ResourceAddressSpecOptionalResponse) Parse(ctx context.Context) error {
	if m == nil {
		return nil
	}

	if err := m.Subnet.Parse(ctx); err != nil {
		return reserrors.NewPathAccumulatorError("Subnet", err)
	}

	return nil
}
