// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"context"

	"github.com/go-faster/jx"

	"go.mws.cloud/go-sdk/internal/conv"
	"go.mws.cloud/go-sdk/internal/decode"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	"go.mws.cloud/go-sdk/pkg/optional"
	commonmodel "go.mws.cloud/go-sdk/service/common/model"
)

// Подсеть - это сегмент сети, ассоциированный с диапазоном внутренних адресов
// Real OAPI model name: Subnet
type SubnetOptionalResponse struct {
	Kind *string `json:"kind,omitempty" yaml:"kind,omitempty"`
	// Набор общих для всех пользовательских объектов атрибутов. Может быть расширен атрибутами, специфичными для контейнеров.
	Metadata optional.OptionalNil[commonmodel.CommonTypedResourceMetadataOptionalResponse] `json:"metadata,omitempty" yaml:"metadata,omitempty"`
	Spec     SubnetSpecOptionalResponse                                                    `json:"spec" yaml:"spec"`
	Status   *SubnetStatusResponse                                                         `json:"status,omitempty" yaml:"status,omitempty"`
}

func (m *SubnetOptionalResponse) GetKind() *string {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (m *SubnetOptionalResponse) SetKind(val *string) {
	m.Kind = val
}

func (m *SubnetOptionalResponse) GetKindOr(val string) string {
	if m != nil && m.Kind != nil {
		return *m.Kind
	}
	return val
}

func (m *SubnetOptionalResponse) GetMetadata() *commonmodel.CommonTypedResourceMetadataOptionalResponse {
	if m != nil && m.Metadata.IsSet() && !m.Metadata.IsNull() {
		return &m.Metadata.Value
	}
	return nil
}

func (m *SubnetOptionalResponse) GetMetadataOr(val commonmodel.CommonTypedResourceMetadataOptionalResponse) commonmodel.CommonTypedResourceMetadataOptionalResponse {
	if m != nil && m.Metadata.IsSet() && !m.Metadata.IsNull() {
		return m.Metadata.Value
	}
	return val
}

func (m *SubnetOptionalResponse) GetSpec() SubnetSpecOptionalResponse {
	if m != nil {
		return m.Spec
	}
	return SubnetSpecOptionalResponse{}
}

func (m *SubnetOptionalResponse) SetSpec(val SubnetSpecOptionalResponse) {
	m.Spec = val
}

func (m *SubnetOptionalResponse) GetStatus() *SubnetStatusResponse {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *SubnetOptionalResponse) SetStatus(val *SubnetStatusResponse) {
	m.Status = val
}

func (m *SubnetOptionalResponse) GetStatusOr(val SubnetStatusResponse) SubnetStatusResponse {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return val
}

func (m *SubnetOptionalResponse) Clone() *SubnetOptionalResponse {
	if m == nil {
		return nil
	}

	clone := *m
	if m.Kind != nil {
		cloneKind := *m.Kind
		clone.Kind = &cloneKind
	}
	if clone.Metadata.IsSet() {
		clone.Metadata.Value = *m.Metadata.Value.Clone()
	}
	clone.Spec = *m.Spec.Clone()
	clone.Status = m.Status.Clone()
	return &clone
}

func (m *SubnetOptionalResponse) Parse(ctx context.Context) error {
	if m == nil {
		return nil
	}

	if err := m.Spec.Parse(ctx); err != nil {
		return reserrors.NewPathAccumulatorError("Spec", err)
	}

	return nil
}

// JSON methods

func (m SubnetOptionalResponse) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	if err := m.Encode(&e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (m *SubnetOptionalResponse) Encode(e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	if err := m.encodeFields(e); err != nil {
		return err
	}
	e.ObjEnd()
	return nil
}

func (m *SubnetOptionalResponse) encodeFields(e *jx.Encoder) error {
	if m.Kind != nil {
		e.FieldStart("kind")
		e.Str(*m.Kind)
	}

	if m.Metadata.IsSet() {
		e.FieldStart("metadata")
		if m.Metadata.IsNull() {
			e.Null()
		} else {
			if err := m.Metadata.Value.Encode(e); err != nil {
				return err
			}
		}
	}

	e.FieldStart("spec")
	if err := m.Spec.Encode(e); err != nil {
		return err
	}

	if m.Status != nil {
		e.FieldStart("status")
		if err := m.Status.Encode(e); err != nil {
			return err
		}
	}
	return nil
}

func (m *SubnetOptionalResponse) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *SubnetOptionalResponse) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("SubnetOptionalResponse")
	}

	return d.ObjBytes(reserrors.PathAccumulatorErrorObjBytesFuncWrap(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "kind":
			v, err := decode.Str(d)
			if err != nil {
				return err
			}

			m.Kind = &v
			return nil
		case "metadata":
			if d.Next() == jx.Null {
				m.Metadata.SetToNull()
				return d.Null()
			}

			var v commonmodel.CommonTypedResourceMetadataOptionalResponse
			if err := v.Decode(d); err != nil {
				return err
			}

			m.Metadata.SetTo(v)
			return nil
		case "spec":
			var v SubnetSpecOptionalResponse
			if err := v.Decode(d); err != nil {
				return err
			}

			m.Spec = v
			return nil
		case "status":
			if d.Next() == jx.Null {
				return d.Null()
			}

			var v SubnetStatusResponse
			if err := v.Decode(d); err != nil {
				return err
			}

			m.Status = &v
			return nil
		default:
			return d.Skip()
		}
	}))
}
