// Code generated by mwsapigen, DO NOT EDIT.

package model

func SubnetDhcpOptionsRequestToResponse(request *SubnetDhcpOptionsRequest) (*SubnetDhcpOptionsResponse, error) {
	if request == nil {
		return nil, nil
	}
	var response SubnetDhcpOptionsResponse
	response.DomainName = request.DomainName
	response.DomainNameServers = request.DomainNameServers
	response.NtpServers = request.NtpServers
	return &response, nil
}
