// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"context"

	"go.mws.cloud/go-sdk/pkg/apimodels/cidraddress"

	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	"go.mws.cloud/go-sdk/service/resources/references/rm"
)

// Real OAPI model name: SubnetSpec
type SubnetSpecRequest struct {
	// Регион, которому принадлежит подсеть.
	Region      *rm.RegionRef             `json:"region,omitempty" yaml:"region,omitempty"`
	Cidr        cidraddress.CIDR4Address  `json:"cidr" yaml:"cidr"`
	DhcpOptions *SubnetDhcpOptionsRequest `json:"dhcpOptions,omitempty" yaml:"dhcpOptions,omitempty"`
}

func (m *SubnetSpecRequest) GetRegion() *rm.RegionRef {
	if m != nil {
		return m.Region
	}
	return nil
}

func (m *SubnetSpecRequest) SetRegion(val *rm.RegionRef) {
	m.Region = val
}

func (m *SubnetSpecRequest) GetRegionOr(val rm.RegionRef) rm.RegionRef {
	if m != nil && m.Region != nil {
		return *m.Region
	}
	return val
}

func (m *SubnetSpecRequest) GetCidr() cidraddress.CIDR4Address {
	if m != nil {
		return m.Cidr
	}
	return cidraddress.CIDR4Address{}
}

func (m *SubnetSpecRequest) SetCidr(val cidraddress.CIDR4Address) {
	m.Cidr = val
}

func (m *SubnetSpecRequest) GetDhcpOptions() *SubnetDhcpOptionsRequest {
	if m != nil {
		return m.DhcpOptions
	}
	return nil
}

func (m *SubnetSpecRequest) SetDhcpOptions(val *SubnetDhcpOptionsRequest) {
	m.DhcpOptions = val
}

func (m *SubnetSpecRequest) GetDhcpOptionsOr(val SubnetDhcpOptionsRequest) SubnetDhcpOptionsRequest {
	if m != nil && m.DhcpOptions != nil {
		return *m.DhcpOptions
	}
	return val
}

func (m *SubnetSpecRequest) Clone() *SubnetSpecRequest {
	if m == nil {
		return nil
	}

	clone := *m
	clone.Region = m.Region.Clone()
	clone.Cidr = *m.Cidr.Clone()
	clone.DhcpOptions = m.DhcpOptions.Clone()
	return &clone
}

func (m *SubnetSpecRequest) Parse(ctx context.Context) error {
	if m == nil {
		return nil
	}

	if err := m.Region.Parse(ctx); err != nil {
		return reserrors.NewPathAccumulatorError("Region", err)
	}

	return nil
}
