// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/go-faster/jx"
	"go.mws.cloud/go-sdk/pkg/apimodels/units/duration"

	"go.mws.cloud/go-sdk/internal/conv"
	"go.mws.cloud/go-sdk/internal/decode"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
)

func (m UpdateVpcAddressDnsSpecRequest) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *UpdateVpcAddressDnsSpecRequest) Encode(e *jx.Encoder) {
	if m == nil {
		e.Null()
		return
	}
	e.ObjStart()
	m.encodeFields(e)
	e.ObjEnd()
}

func (m *UpdateVpcAddressDnsSpecRequest) encodeFields(e *jx.Encoder) {
	if m.Name.IsSet() {
		e.FieldStart("name")
		e.Str(m.Name.Value)
	}

	if m.Ttl.IsSet() {
		e.FieldStart("ttl")
		m.Ttl.Value.Encode(e)
	}

	if m.Ptr.IsSet() {
		e.FieldStart("ptr")
		e.Bool(m.Ptr.Value)
	}
}

func (m *UpdateVpcAddressDnsSpecRequest) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *UpdateVpcAddressDnsSpecRequest) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("UpdateVpcAddressDnsSpecRequest")
	}

	return d.ObjBytes(reserrors.PathAccumulatorErrorObjBytesFuncWrap(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "name":
			v, err := decode.Str(d)
			if err != nil {
				return err
			}

			m.Name.SetTo(v)
			return nil
		case "ttl":
			var v duration.Duration
			if err := v.Decode(d); err != nil {
				return err
			}

			m.Ttl.SetTo(v)
			return nil
		case "ptr":
			v, err := decode.Bool(d)
			if err != nil {
				return err
			}

			m.Ptr.SetTo(v)
			return nil
		default:
			return d.Skip()
		}
	}))
}
