// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"context"
	"fmt"

	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	common "go.mws.cloud/go-sdk/service/common/model"
	"go.mws.cloud/go-sdk/service/resources/references/rm"
	"go.mws.cloud/go-sdk/service/resources/references/vpc"
)

// Статус группы адресов.
// Real OAPI model name: VpcAddressGroupStatus
type VpcAddressGroupStatusResponse struct {
	common.ResourceStatusResponse `yaml:"-,inline"`
	// Список статусов внутренних IP-адресов.
	Addresses []ResourceAddressStatusResponse `json:"addresses,omitempty" yaml:"addresses,omitempty"`
	// Список ссылок на внутренние IP-адреса, которые были удалены, но остались в спецификации группы.
	OrphanAddresses []vpc.AddressRef `json:"orphanAddresses,omitempty" yaml:"orphanAddresses,omitempty"`
	// Регион, которому принадлежит группа IP-адресов.
	Region *rm.RegionID `json:"region,omitempty" yaml:"region,omitempty"`
}

func (m *VpcAddressGroupStatusResponse) GetReady() common.ResourceStatusReadyResponse {
	if m != nil {
		return m.ResourceStatusResponse.GetReady()
	}
	return common.ResourceStatusReadyResponse{}
}

func (m *VpcAddressGroupStatusResponse) GetAddresses() []ResourceAddressStatusResponse {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *VpcAddressGroupStatusResponse) GetAddressesOr(val []ResourceAddressStatusResponse) []ResourceAddressStatusResponse {
	if m != nil && m.Addresses != nil {
		return m.Addresses
	}
	return val
}

func (m *VpcAddressGroupStatusResponse) GetOrphanAddresses() []vpc.AddressRef {
	if m != nil {
		return m.OrphanAddresses
	}
	return nil
}

func (m *VpcAddressGroupStatusResponse) GetOrphanAddressesOr(val []vpc.AddressRef) []vpc.AddressRef {
	if m != nil && m.OrphanAddresses != nil {
		return m.OrphanAddresses
	}
	return val
}

func (m *VpcAddressGroupStatusResponse) GetRegion() *rm.RegionID {
	if m != nil {
		return m.Region
	}
	return nil
}

func (m *VpcAddressGroupStatusResponse) GetRegionOr(val rm.RegionID) rm.RegionID {
	if m != nil && m.Region != nil {
		return *m.Region
	}
	return val
}

func (m *VpcAddressGroupStatusResponse) Clone() *VpcAddressGroupStatusResponse {
	if m == nil {
		return nil
	}

	clone := *m
	clone.ResourceStatusResponse = *m.ResourceStatusResponse.Clone()
	if m.Addresses != nil {
		clone.Addresses = make([]ResourceAddressStatusResponse, len(m.Addresses))
		for i, v := range m.Addresses {
			clone.Addresses[i] = *v.Clone()
		}
	}
	if m.OrphanAddresses != nil {
		clone.OrphanAddresses = make([]vpc.AddressRef, len(m.OrphanAddresses))
		for i, v := range m.OrphanAddresses {
			clone.OrphanAddresses[i] = *v.Clone()
		}
	}
	clone.Region = m.Region.Clone()

	return &clone
}

func (m *VpcAddressGroupStatusResponse) Parse(ctx context.Context) error {
	if m == nil {
		return nil
	}

	for index := range m.Addresses {
		if err := m.Addresses[index].Parse(ctx); err != nil {
			return reserrors.NewPathAccumulatorError("Addresses"+fmt.Sprint("[", index, "]"), err)
		}
	}

	for index := range m.OrphanAddresses {
		if err := m.OrphanAddresses[index].Parse(ctx); err != nil {
			return reserrors.NewPathAccumulatorError("OrphanAddresses"+fmt.Sprint("[", index, "]"), err)
		}
	}

	return nil
}
