// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"go.mws.cloud/util-toolset/pkg/utils/ptr"
)

func (m *VpcNetworkSpecRequest) WithDefaults() VpcNetworkSpecRequest {
	var out VpcNetworkSpecRequest
	if m != nil {
		out = *m
	}

	if out.Mtu == nil {
		out.Mtu = ptr.Get(int32(1500))
	}
	if out.InternetAccess == nil {
		out.InternetAccess = ptr.Get(true)
	}
	return out
}
