// Code generated by MockGen. DO NOT EDIT.
// Source: go/pkg/sdk/endpoints/discovery.go
//
// Generated by this command:
//
//	mockgen -typed -package mocks -source=go/pkg/sdk/endpoints/discovery.go -destination go/pkg/sdk/endpoints/mocks/mockdiscovery.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	http "net/http"
	reflect "reflect"

	endpoints "go.mws.cloud/go-sdk/mws/endpoints"
	gomock "go.uber.org/mock/gomock"
)

// MockHTTPClient is a mock of HTTPClient interface.
type MockHTTPClient struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPClientMockRecorder
	isgomock struct{}
}

// MockHTTPClientMockRecorder is the mock recorder for MockHTTPClient.
type MockHTTPClientMockRecorder struct {
	mock *MockHTTPClient
}

// NewMockHTTPClient creates a new mock instance.
func NewMockHTTPClient(ctrl *gomock.Controller) *MockHTTPClient {
	mock := &MockHTTPClient{ctrl: ctrl}
	mock.recorder = &MockHTTPClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTTPClient) EXPECT() *MockHTTPClientMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockHTTPClient) Do(arg0 *http.Request) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", arg0)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockHTTPClientMockRecorder) Do(arg0 any) *MockHTTPClientDoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockHTTPClient)(nil).Do), arg0)
	return &MockHTTPClientDoCall{Call: call}
}

// MockHTTPClientDoCall wrap *gomock.Call
type MockHTTPClientDoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHTTPClientDoCall) Return(arg0 *http.Response, arg1 error) *MockHTTPClientDoCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHTTPClientDoCall) Do(f func(*http.Request) (*http.Response, error)) *MockHTTPClientDoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHTTPClientDoCall) DoAndReturn(f func(*http.Request) (*http.Response, error)) *MockHTTPClientDoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockDiscoveryClient is a mock of DiscoveryClient interface.
type MockDiscoveryClient struct {
	ctrl     *gomock.Controller
	recorder *MockDiscoveryClientMockRecorder
	isgomock struct{}
}

// MockDiscoveryClientMockRecorder is the mock recorder for MockDiscoveryClient.
type MockDiscoveryClientMockRecorder struct {
	mock *MockDiscoveryClient
}

// NewMockDiscoveryClient creates a new mock instance.
func NewMockDiscoveryClient(ctrl *gomock.Controller) *MockDiscoveryClient {
	mock := &MockDiscoveryClient{ctrl: ctrl}
	mock.recorder = &MockDiscoveryClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiscoveryClient) EXPECT() *MockDiscoveryClientMockRecorder {
	return m.recorder
}

// Endpoints mocks base method.
func (m *MockDiscoveryClient) Endpoints(arg0 context.Context) (endpoints.DiscoveryEndpoints, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Endpoints", arg0)
	ret0, _ := ret[0].(endpoints.DiscoveryEndpoints)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Endpoints indicates an expected call of Endpoints.
func (mr *MockDiscoveryClientMockRecorder) Endpoints(arg0 any) *MockDiscoveryClientEndpointsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Endpoints", reflect.TypeOf((*MockDiscoveryClient)(nil).Endpoints), arg0)
	return &MockDiscoveryClientEndpointsCall{Call: call}
}

// MockDiscoveryClientEndpointsCall wrap *gomock.Call
type MockDiscoveryClientEndpointsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDiscoveryClientEndpointsCall) Return(arg0 endpoints.DiscoveryEndpoints, arg1 error) *MockDiscoveryClientEndpointsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDiscoveryClientEndpointsCall) Do(f func(context.Context) (endpoints.DiscoveryEndpoints, error)) *MockDiscoveryClientEndpointsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDiscoveryClientEndpointsCall) DoAndReturn(f func(context.Context) (endpoints.DiscoveryEndpoints, error)) *MockDiscoveryClientEndpointsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
