// Code generated by mwsapigen, DO NOT EDIT.

package client

import (
	"net/url"

	commonclient "go.mws.cloud/go-sdk/internal/client"
	"go.mws.cloud/go-sdk/service/iam/client"
)

var _ client.Role = (*Role)(nil)

type Role struct {
	client    commonclient.MWSClient
	serverURL *url.URL
}

func NewRole(cfg commonclient.Config) *Role {
	return &Role{
		client:    cfg.GetClient(),
		serverURL: cfg.GetURL(),
	}
}

func NewRoleSugared(cfg commonclient.Config) *client.RoleSugared {
	return client.NewRoleSugared(NewRole(cfg))
}
