// Code generated by mwsapigen, DO NOT EDIT.

package client

import (
	"context"
	"errors"
	"net/http"
	"net/url"

	commonclient "go.mws.cloud/go-sdk/internal/client"
	commonattribute "go.mws.cloud/go-sdk/internal/client/interceptors/attribute"
	"go.mws.cloud/go-sdk/internal/conv"
	mwserrors "go.mws.cloud/go-sdk/mws/errors"
	valuesctx "go.mws.cloud/go-sdk/pkg/context/values"
	"go.mws.cloud/go-sdk/service/iam/client"
)

// ListGlobalRoleV2 листинг ролей v2.
// Гарантируется, что либо будет заполнено одно из полей ответа, либо вернется ошибка.
//
// Путь: GET /iam/v2/roles
func (c *Role) ListGlobalRoleV2(ctx context.Context, request client.ListGlobalRoleV2Request) (r *client.ListGlobalRoleV2Response, err error) {
	ctx = c.setListGlobalRoleV2Attributes(ctx)
	r = &client.ListGlobalRoleV2Response{}

	if err = c.client.Intercept(ctx, &request, r, c.listGlobalRoleV2Invoker); err != nil {
		return nil, err
	}

	return r, nil
}

func (c *Role) setListGlobalRoleV2Attributes(ctx context.Context) context.Context {
	a := []commonattribute.KeyValue{
		commonattribute.String(commonattribute.Method, "ListGlobalRoleV2"),
		commonattribute.String(commonattribute.PathTemplate, "/iam/v2/roles"),
		commonattribute.String(commonattribute.ProjectName, "iam"),
		commonattribute.String(commonattribute.ServiceName, "role"),
	}

	return commonattribute.WithContext(ctx, a...)
}

func (c *Role) listGlobalRoleV2Invoker(ctx context.Context, anyReq any, response commonclient.APIResp) error {
	request := anyReq.(*client.ListGlobalRoleV2Request)

	requestURL, _ := url.JoinPath(c.serverURL.String(),
		"iam",
		"v2",
		"roles")

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, http.NoBody)
	if err != nil {
		return err
	}

	httpReq.URL.RawQuery = c.queryListGlobalRoleV2(request)

	commonclient.AddOutgoingMetadataToHeader(ctx, httpReq)
	c.headerListGlobalRoleV2(httpReq, request)

	httpResp, err := c.client.Do(httpReq)
	if err != nil {
		return mwserrors.NewTransportError(err)
	}

	defer func() {
		cErr := httpResp.Body.Close()
		if cErr != nil {
			err = errors.Join(err, cErr)
		}
	}()

	decodedResp, err := decodeListGlobalRoleV2Response(httpResp)
	if err != nil {
		return err
	}

	respPtr := response.(*client.ListGlobalRoleV2Response)
	*respPtr = *decodedResp

	return nil
}

func (c *Role) queryListGlobalRoleV2(request *client.ListGlobalRoleV2Request) string {
	q := make(url.Values)
	if request.PageSize != nil {
		q.Add("pageSize", conv.IntToString(*request.PageSize))
	}
	if request.PageToken != nil {
		q.Add("pageToken", conv.StringToString(*request.PageToken))
	}
	if request.Filter != nil {
		q.Add("filter", conv.StringToString(*request.Filter))
	}
	if request.OrderBy != nil {
		q.Add("orderBy", conv.StringToString(*request.OrderBy))
	}
	if request.ShowDeleted != nil {
		q.Add("showDeleted", conv.StringToString(*request.ShowDeleted))
	}
	return q.Encode()
}

func (c *Role) headerListGlobalRoleV2(req *http.Request, request *client.ListGlobalRoleV2Request) {
	req.Header.Add("Authorization", conv.StringToString(request.Authorization))
}

// GetGlobalRoleV2 получение информации о роли.
// Гарантируется, что либо будет заполнено одно из полей ответа, либо вернется ошибка.
//
// Путь: GET /iam/v2/roles/{role}
func (c *Role) GetGlobalRoleV2(ctx context.Context, request client.GetGlobalRoleV2Request) (r *client.GetGlobalRoleV2Response, err error) {
	ctx = c.setGetGlobalRoleV2Attributes(ctx)
	r = &client.GetGlobalRoleV2Response{}

	if err = c.client.Intercept(ctx, &request, r, c.getGlobalRoleV2Invoker); err != nil {
		return nil, err
	}

	return r, nil
}

func (c *Role) setGetGlobalRoleV2Attributes(ctx context.Context) context.Context {
	a := []commonattribute.KeyValue{
		commonattribute.String(commonattribute.Method, "GetGlobalRoleV2"),
		commonattribute.String(commonattribute.PathTemplate, "/iam/v2/roles/{role}"),
		commonattribute.String(commonattribute.ProjectName, "iam"),
		commonattribute.String(commonattribute.ServiceName, "role"),
	}

	return commonattribute.WithContext(ctx, a...)
}

func (c *Role) getGlobalRoleV2Invoker(ctx context.Context, anyReq any, response commonclient.APIResp) error {
	request := anyReq.(*client.GetGlobalRoleV2Request)

	requestURL, _ := url.JoinPath(c.serverURL.String(),
		"iam",
		"v2",
		"roles",
		url.PathEscape(request.Role))

	ctx = valuesctx.With(ctx, "role", request.Role)

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, http.NoBody)
	if err != nil {
		return err
	}

	commonclient.AddOutgoingMetadataToHeader(ctx, httpReq)
	c.headerGetGlobalRoleV2(httpReq, request)

	httpResp, err := c.client.Do(httpReq)
	if err != nil {
		return mwserrors.NewTransportError(err)
	}

	defer func() {
		cErr := httpResp.Body.Close()
		if cErr != nil {
			err = errors.Join(err, cErr)
		}
	}()

	decodedResp, err := decodeGetGlobalRoleV2Response(httpResp)
	if err != nil {
		return err
	}

	respPtr := response.(*client.GetGlobalRoleV2Response)
	*respPtr = *decodedResp

	return nil
}

func (c *Role) headerGetGlobalRoleV2(req *http.Request, request *client.GetGlobalRoleV2Request) {
	req.Header.Add("Authorization", conv.StringToString(request.Authorization))
}
