// Code generated by mwsapigen, DO NOT EDIT.

package model_test

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/service/secretmanager/model"
)

func TestAddSecretVersionRequestMarshalling(t *testing.T) {
	t.Parallel()
	expected := initAddSecretVersionRequest()
	b, err := json.Marshal(expected)
	require.NoError(t, err)

	var actual model.AddSecretVersionRequest
	require.NoError(t, json.Unmarshal(b, &actual))
	require.Equal(t, expected, actual)
}

func initAddSecretVersionRequest() model.AddSecretVersionRequest {
	var v model.AddSecretVersionRequest
	return v
}
