// Code generated by mwsapigen, DO NOT EDIT.

package model_test

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/service/secretmanager/model"
)

func TestSecretSpecRequestMarshalling(t *testing.T) {
	expected := initSecretSpecRequest()
	b, err := json.Marshal(expected)
	require.NoError(t, err)

	var actual model.SecretSpecRequest
	require.NoError(t, json.Unmarshal(b, &actual))
	require.Equal(t, expected, actual)
}

func initSecretSpecRequest() model.SecretSpecRequest {
	var v model.SecretSpecRequest
	return v
}
