// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"context"

	"go.mws.cloud/util-toolset/pkg/utils/ptr"

	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	"go.mws.cloud/go-sdk/pkg/optional"
)

type UpdateClusterSpecRequest struct {
	Network        optional.Optional[UpdateClusterSpecNetworkRequest]        `json:"network" yaml:"network"`
	VersionControl optional.Optional[UpdateClusterVersionControlSpecRequest] `json:"versionControl" yaml:"versionControl"`
}

func (m *ClusterSpecRequest) AsUpdateModel() UpdateClusterSpecRequest {
	var u UpdateClusterSpecRequest
	u.Network = optional.NewOptional(m.Network.AsUpdateModel())
	u.VersionControl = optional.NewOptional(m.VersionControl.AsUpdateModel())
	return u
}

// Diff creates an object that can be used in Update methods. This object represents changes from src to the current state
func (m *ClusterSpecRequest) Diff(src *ClusterSpecRequest) UpdateClusterSpecRequest {
	nilDiffers := src != nil && m == nil
	upd := UpdateClusterSpecRequest{}
	if !nilDiffers {
		upd.Network = m.diffNetwork(src)
		upd.VersionControl = m.diffVersionControl(src)
	}
	return upd
}

func (m *ClusterSpecRequest) WithChanges(u UpdateClusterSpecRequest) ClusterSpecRequest {
	var out ClusterSpecRequest
	if m != nil {
		out = *m
	}

	if u.Network.IsSet() {
		out.Network = out.Network.WithChanges(u.Network.Value)
	}
	if u.VersionControl.IsSet() {
		out.VersionControl = out.VersionControl.WithChanges(u.VersionControl.Value)
	}
	return out
}

// HasChanges returns true if any field has Set == true
func (m UpdateClusterSpecRequest) HasChanges() bool {
	return m.Network.Set ||
		m.VersionControl.Set
}

func (m *UpdateClusterSpecRequest) Parse(ctx context.Context) error {
	if m == nil {
		return nil
	}

	if m.Network.IsSet() {
		if err := m.Network.Value.Parse(ctx); err != nil {
			return reserrors.NewPathAccumulatorError("Network", err)
		}
	}

	return nil
}

func (m *ClusterSpecRequest) diffNetwork(src *ClusterSpecRequest) optional.Optional[UpdateClusterSpecNetworkRequest] {
	from := src.GetNetwork()
	to := m.GetNetwork()
	value := to.Diff(&from)
	return optional.Optional[UpdateClusterSpecNetworkRequest]{
		Value: value,
		Set:   value.HasChanges(),
	}
}

func (m *ClusterSpecRequest) diffVersionControl(src *ClusterSpecRequest) optional.Optional[UpdateClusterVersionControlSpecRequest] {
	from := src.GetVersionControl()
	to := m.GetVersionControl()
	value := to.Diff(&from)
	return optional.Optional[UpdateClusterVersionControlSpecRequest]{
		Value: value,
		Set:   value.HasChanges(),
	}
}

type UpdateClusterSpecNetworkRequest struct {
	// внешний ip-адрес
	PublicEndpoint optional.OptionalNil[UpdateClusterPublicEndpointSpecOrRefRequest] `json:"publicEndpoint" yaml:"publicEndpoint"`
}

func (m *ClusterSpecNetworkRequest) AsUpdateModel() UpdateClusterSpecNetworkRequest {
	var u UpdateClusterSpecNetworkRequest
	if m.PublicEndpoint != nil {
		u.PublicEndpoint = optional.NewOptionalNil(m.PublicEndpoint.AsUpdateModel())
	}
	return u
}

// Diff creates an object that can be used in Update methods. This object represents changes from src to the current state
func (m *ClusterSpecNetworkRequest) Diff(src *ClusterSpecNetworkRequest) UpdateClusterSpecNetworkRequest {
	nilDiffers := src != nil && m == nil
	upd := UpdateClusterSpecNetworkRequest{}
	if !nilDiffers {
		upd.PublicEndpoint = m.diffPublicEndpoint(src)
	}
	return upd
}

func (m *ClusterSpecNetworkRequest) WithChanges(u UpdateClusterSpecNetworkRequest) ClusterSpecNetworkRequest {
	var out ClusterSpecNetworkRequest
	if m != nil {
		out = *m
	}

	if u.PublicEndpoint.IsSet() {
		out.PublicEndpoint = ptr.Get(out.PublicEndpoint.WithChanges(u.PublicEndpoint.Value))
	} else if u.PublicEndpoint.IsNull() {
		out.PublicEndpoint = nil
	}
	return out
}

// HasChanges returns true if any field has Set == true
func (m UpdateClusterSpecNetworkRequest) HasChanges() bool {
	return m.PublicEndpoint.Set
}

func (m *UpdateClusterSpecNetworkRequest) Parse(ctx context.Context) error {
	if m == nil {
		return nil
	}

	if m.PublicEndpoint.IsSet() {
		if err := m.PublicEndpoint.Value.Parse(ctx); err != nil {
			return reserrors.NewPathAccumulatorError("PublicEndpoint", err)
		}
	}

	return nil
}

func (m *ClusterSpecNetworkRequest) diffPublicEndpoint(src *ClusterSpecNetworkRequest) optional.OptionalNil[UpdateClusterPublicEndpointSpecOrRefRequest] {
	nilDiffers := src != nil && m == nil
	value := m.GetPublicEndpoint().Diff(src.GetPublicEndpoint())
	return optional.OptionalNil[UpdateClusterPublicEndpointSpecOrRefRequest]{
		Value: value,
		Set:   nilDiffers || value.HasChanges(),
		Null:  nilDiffers,
	}
}
