// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"go.mws.cloud/util-toolset/pkg/utils/ptr"

	commonclient "go.mws.cloud/go-sdk/internal/client"
)

type UpdateClusterPublicEndpointSpecRequest struct {
	// Версия IP протокола.
	Version commonclient.Optional[ClusterPublicEndpointSpecVersionRequest] `json:"version" yaml:"version"`
}

func (m *ClusterPublicEndpointSpecRequest) AsUpdateModel() UpdateClusterPublicEndpointSpecRequest {
	var u UpdateClusterPublicEndpointSpecRequest
	if m.Version != nil {
		u.Version = commonclient.NewOptional(m.GetVersionOr(""))
	}
	return u
}

// Diff creates an object that can be used in Update methods. This object represents changes from src to the current state
func (m *ClusterPublicEndpointSpecRequest) Diff(src *ClusterPublicEndpointSpecRequest) UpdateClusterPublicEndpointSpecRequest {
	nilDiffers := src != nil && m == nil
	upd := UpdateClusterPublicEndpointSpecRequest{}
	if !nilDiffers {
		upd.Version = m.diffVersion(src)
	}
	return upd
}

func (m *ClusterPublicEndpointSpecRequest) WithChanges(u UpdateClusterPublicEndpointSpecRequest) ClusterPublicEndpointSpecRequest {
	var out ClusterPublicEndpointSpecRequest
	if m != nil {
		out = *m
	}

	if u.Version.IsSet() {
		out.Version = ptr.Get(u.Version.Value)
	}
	return out
}

// HasChanges returns true if any field has Set == true
func (m UpdateClusterPublicEndpointSpecRequest) HasChanges() bool {
	return m.Version.Set
}

func (m *ClusterPublicEndpointSpecRequest) diffVersion(src *ClusterPublicEndpointSpecRequest) commonclient.Optional[ClusterPublicEndpointSpecVersionRequest] {
	nilDiffers := src != nil && m == nil
	return commonclient.DiffPrimitiveNonRequired(src.GetVersion(), m.GetVersion(), nilDiffers)
}
