// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	commonclient "go.mws.cloud/go-sdk/internal/client"
)

type UpdateNodeTaintSpecRequest struct {
	// Ключ может состоять из двух частей: необязательный префикс и ключ, разделенные "/".
	// Максимальная длина префикса 253 символа.
	// Максимальная длина ключа 63 символа.
	Key commonclient.Optional[string] `json:"key" yaml:"key"`
	// Значение taint на node. Если строка пустая, то value нет.
	Value commonclient.Optional[string] `json:"value" yaml:"value"`
	// Эффект taint на node, влияющий на pod scheduling, которые под него попадают.
	Effect commonclient.Optional[NodeTaintSpecEffectRequest] `json:"effect" yaml:"effect"`
}

func (m *NodeTaintSpecRequest) AsUpdateModel() UpdateNodeTaintSpecRequest {
	var u UpdateNodeTaintSpecRequest
	u.Key = commonclient.NewOptional(m.GetKey())
	u.Value = commonclient.NewOptional(m.GetValue())
	u.Effect = commonclient.NewOptional(m.GetEffect())
	return u
}

// Diff creates an object that can be used in Update methods. This object represents changes from src to the current state
func (m *NodeTaintSpecRequest) Diff(src *NodeTaintSpecRequest) UpdateNodeTaintSpecRequest {
	nilDiffers := src != nil && m == nil
	upd := UpdateNodeTaintSpecRequest{}
	if !nilDiffers {
		upd.Key = m.diffKey(src)
		upd.Value = m.diffValue(src)
		upd.Effect = m.diffEffect(src)
	}
	return upd
}

func (m *NodeTaintSpecRequest) WithChanges(u UpdateNodeTaintSpecRequest) NodeTaintSpecRequest {
	var out NodeTaintSpecRequest
	if m != nil {
		out = *m
	}

	if u.Key.IsSet() {
		out.Key = u.Key.Value
	}
	if u.Value.IsSet() {
		out.Value = u.Value.Value
	}
	if u.Effect.IsSet() {
		out.Effect = u.Effect.Value
	}
	return out
}

// HasChanges returns true if any field has Set == true
func (m UpdateNodeTaintSpecRequest) HasChanges() bool {
	return m.Key.Set ||
		m.Value.Set ||
		m.Effect.Set
}

func (m *NodeTaintSpecRequest) diffKey(src *NodeTaintSpecRequest) commonclient.Optional[string] {
	nilDiffers := src != nil && m == nil
	return commonclient.DiffPrimitiveRequired(src.GetKey(), m.GetKey(), nilDiffers)
}

func (m *NodeTaintSpecRequest) diffValue(src *NodeTaintSpecRequest) commonclient.Optional[string] {
	nilDiffers := src != nil && m == nil
	return commonclient.DiffPrimitiveRequired(src.GetValue(), m.GetValue(), nilDiffers)
}

func (m *NodeTaintSpecRequest) diffEffect(src *NodeTaintSpecRequest) commonclient.Optional[NodeTaintSpecEffectRequest] {
	nilDiffers := src != nil && m == nil
	return commonclient.DiffPrimitiveRequired(src.GetEffect(), m.GetEffect(), nilDiffers)
}
