// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"go.mws.cloud/go-sdk/pkg/optional"
)

func NodeGroupSpecNetworkRequestToOptionalResponse(request *NodeGroupSpecNetworkRequest) (*NodeGroupSpecNetworkOptionalResponse, error) {
	if request == nil {
		return nil, nil
	}
	var response NodeGroupSpecNetworkOptionalResponse
	if request.PrimaryInterface != nil {
		tmpPrimaryInterface, err := NodeGroupSpecNetworkPrimaryInterfaceRequestToOptionalResponse(request.PrimaryInterface)
		if err != nil {
			return nil, err
		}
		response.PrimaryInterface = optional.NewOptionalNil(*tmpPrimaryInterface)
	}
	return &response, nil
}

func NodeGroupSpecNetworkPrimaryInterfaceRequestToOptionalResponse(request *NodeGroupSpecNetworkPrimaryInterfaceRequest) (*NodeGroupSpecNetworkPrimaryInterfaceOptionalResponse, error) {
	if request == nil {
		return nil, nil
	}
	var response NodeGroupSpecNetworkPrimaryInterfaceOptionalResponse
	if request.ExternalIPv4 != nil {
		tmpExternalIPv4, err := NodeGroupSpecNetworkPrimaryInterfaceExternalIPv4RequestToOptionalResponse(request.ExternalIPv4)
		if err != nil {
			return nil, err
		}
		response.ExternalIPv4 = optional.NewOptionalNil(*tmpExternalIPv4)
	}
	return &response, nil
}

func NodeGroupSpecNetworkPrimaryInterfaceExternalIPv4RequestToOptionalResponse(request *NodeGroupSpecNetworkPrimaryInterfaceExternalIPv4Request) (*NodeGroupSpecNetworkPrimaryInterfaceExternalIPv4OptionalResponse, error) {
	if request == nil {
		return nil, nil
	}
	var response NodeGroupSpecNetworkPrimaryInterfaceExternalIPv4OptionalResponse
	if request.Enabled != nil {
		response.Enabled = optional.NewOptional(*request.Enabled)
	}
	return &response, nil
}
