// Code generated by mwsapigen, DO NOT EDIT.

package model

// Real OAPI model name: NodeTaintSpec
type NodeTaintSpecResponse struct {
	// Ключ может состоять из двух частей: необязательный префикс и ключ, разделенные "/".
	// Максимальная длина префикса 253 символа.
	// Максимальная длина ключа 63 символа.
	Key string `json:"key" yaml:"key"`
	// Значение taint на node. Если строка пустая, то value нет.
	Value string `json:"value" yaml:"value"`
	// Эффект taint на node, влияющий на pod scheduling, которые под него попадают.
	Effect NodeTaintSpecEffectResponse `json:"effect" yaml:"effect"`
}

func (m *NodeTaintSpecResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *NodeTaintSpecResponse) SetKey(val string) {
	m.Key = val
}

func (m *NodeTaintSpecResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *NodeTaintSpecResponse) SetValue(val string) {
	m.Value = val
}

func (m *NodeTaintSpecResponse) GetEffect() NodeTaintSpecEffectResponse {
	if m != nil {
		return m.Effect
	}
	return ""
}

func (m *NodeTaintSpecResponse) SetEffect(val NodeTaintSpecEffectResponse) {
	m.Effect = val
}

func (m *NodeTaintSpecResponse) Clone() *NodeTaintSpecResponse {
	if m == nil {
		return nil
	}

	clone := *m
	return &clone
}

// Представление поля Effect enum типа структуры NodeTaintSpec
// Real OAPI model name: NodeTaintSpecEffect
type NodeTaintSpecEffectResponse string

const (
	NodeTaintSpecEffectResponse_NO_SCHEDULE        NodeTaintSpecEffectResponse = "NO_SCHEDULE"
	NodeTaintSpecEffectResponse_PREFER_NO_SCHEDULE NodeTaintSpecEffectResponse = "PREFER_NO_SCHEDULE"
	NodeTaintSpecEffectResponse_NO_EXECUTE         NodeTaintSpecEffectResponse = "NO_EXECUTE"
)

func (m NodeTaintSpecEffectResponse) String() string {
	return string(m)
}
