// Code generated by mwsapigen, DO NOT EDIT.

package model

// Real OAPI model name: ReleaseChannel
type ReleaseChannelResponse struct {
	// Если release channel name не указан, то будет проставлено default значение stable
	Name        string  `json:"name" yaml:"name"`
	Description *string `json:"description,omitempty" yaml:"description,omitempty"`
	// Если false, то релизный канал не доступен для выбора
	Enabled bool `json:"enabled" yaml:"enabled"`
}

func (m *ReleaseChannelResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReleaseChannelResponse) SetName(val string) {
	m.Name = val
}

func (m *ReleaseChannelResponse) GetDescription() *string {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *ReleaseChannelResponse) SetDescription(val *string) {
	m.Description = val
}

func (m *ReleaseChannelResponse) GetDescriptionOr(val string) string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return val
}

func (m *ReleaseChannelResponse) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *ReleaseChannelResponse) SetEnabled(val bool) {
	m.Enabled = val
}

func (m *ReleaseChannelResponse) Clone() *ReleaseChannelResponse {
	if m == nil {
		return nil
	}

	clone := *m
	if m.Description != nil {
		cloneDescription := *m.Description
		clone.Description = &cloneDescription
	}
	return &clone
}
