// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"go.mws.cloud/go-sdk/pkg/apimodels/units/bytesize"

	"go.mws.cloud/go-sdk/pkg/optional"
)

// Конфигурация схемы хранилищ ClickHouse.
//
// Real OAPI model name: ClickhouseStorageConfiguration
type ClickhouseStorageConfigurationOptionalResponse struct {
	// Включить гибридное хранилище (hot SSD + cold S3).
	HybridStorageEnabled optional.Optional[bool] `json:"hybridStorageEnabled,omitempty" yaml:"hybridStorageEnabled,omitempty"`
	// Соотношение свободного дискового пространства на SSD дисках кластера (от 0.01 до 1) Когда это соотношение превышает значение параметра конфигурации, ClickHouse начинает перемещать данные в следующий том по порядку.
	MoveFactor optional.Optional[float64] `json:"moveFactor,omitempty" yaml:"moveFactor,omitempty"`
	// Включить кеширование данных с объектного хранилища на сетевых SSD дисках.
	DataCachingEnabled optional.Optional[bool] `json:"dataCachingEnabled,omitempty" yaml:"dataCachingEnabled,omitempty"`
	// Максимальный размер кеша объектного хранилища, расположенный на SSD.
	CacheMaxSize optional.Optional[bytesize.ByteSize] `json:"cacheMaxSize,omitempty" yaml:"cacheMaxSize,omitempty"`
	// Максимальный размер части данных в байтах, который может храниться на дисках тома (SSD).
	MaxDataPartSizeSsd optional.Optional[bytesize.ByteSize] `json:"maxDataPartSizeSsd,omitempty" yaml:"maxDataPartSizeSsd,omitempty"`
}

func (m *ClickhouseStorageConfigurationOptionalResponse) GetHybridStorageEnabled() *bool {
	if m != nil && m.HybridStorageEnabled.IsSet() {
		return &m.HybridStorageEnabled.Value
	}
	return nil
}

func (m *ClickhouseStorageConfigurationOptionalResponse) GetHybridStorageEnabledOr(val bool) bool {
	if m != nil && m.HybridStorageEnabled.IsSet() {
		return m.HybridStorageEnabled.Value
	}
	return val
}

func (m *ClickhouseStorageConfigurationOptionalResponse) GetMoveFactor() *float64 {
	if m != nil && m.MoveFactor.IsSet() {
		return &m.MoveFactor.Value
	}
	return nil
}

func (m *ClickhouseStorageConfigurationOptionalResponse) GetMoveFactorOr(val float64) float64 {
	if m != nil && m.MoveFactor.IsSet() {
		return m.MoveFactor.Value
	}
	return val
}

func (m *ClickhouseStorageConfigurationOptionalResponse) GetDataCachingEnabled() *bool {
	if m != nil && m.DataCachingEnabled.IsSet() {
		return &m.DataCachingEnabled.Value
	}
	return nil
}

func (m *ClickhouseStorageConfigurationOptionalResponse) GetDataCachingEnabledOr(val bool) bool {
	if m != nil && m.DataCachingEnabled.IsSet() {
		return m.DataCachingEnabled.Value
	}
	return val
}

func (m *ClickhouseStorageConfigurationOptionalResponse) GetCacheMaxSize() *bytesize.ByteSize {
	if m != nil && m.CacheMaxSize.IsSet() {
		return &m.CacheMaxSize.Value
	}
	return nil
}

func (m *ClickhouseStorageConfigurationOptionalResponse) GetCacheMaxSizeOr(val bytesize.ByteSize) bytesize.ByteSize {
	if m != nil && m.CacheMaxSize.IsSet() {
		return m.CacheMaxSize.Value
	}
	return val
}

func (m *ClickhouseStorageConfigurationOptionalResponse) GetMaxDataPartSizeSsd() *bytesize.ByteSize {
	if m != nil && m.MaxDataPartSizeSsd.IsSet() {
		return &m.MaxDataPartSizeSsd.Value
	}
	return nil
}

func (m *ClickhouseStorageConfigurationOptionalResponse) GetMaxDataPartSizeSsdOr(val bytesize.ByteSize) bytesize.ByteSize {
	if m != nil && m.MaxDataPartSizeSsd.IsSet() {
		return m.MaxDataPartSizeSsd.Value
	}
	return val
}

func (m *ClickhouseStorageConfigurationOptionalResponse) Clone() *ClickhouseStorageConfigurationOptionalResponse {
	if m == nil {
		return nil
	}

	clone := *m
	if clone.CacheMaxSize.IsSet() {
		clone.CacheMaxSize.Value = *m.CacheMaxSize.Value.Clone()
	}
	if clone.MaxDataPartSizeSsd.IsSet() {
		clone.MaxDataPartSizeSsd.Value = *m.MaxDataPartSizeSsd.Value.Clone()
	}
	return &clone
}
