// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"context"
	"time"

	"github.com/go-faster/jx"

	"go.mws.cloud/go-sdk/internal/conv"
	"go.mws.cloud/go-sdk/internal/decode"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	"go.mws.cloud/go-sdk/pkg/optional"
	commonmodel "go.mws.cloud/go-sdk/service/common/model"
	"go.mws.cloud/go-sdk/service/resources/references/mclickhouse"
)

// Кластер Managed ClickHouse — это группа узлов (виртуальных машин), объединенных для высокоскоростной обработки и хранения данных с помощью СУБД ClickHouse.
// Real OAPI model name: ClickhouseCluster
type ClickhouseClusterOptionalResponse struct {
	Kind     *string                                                         `json:"kind,omitempty" yaml:"kind,omitempty"`
	Metadata optional.OptionalNil[ClickhouseClusterMetadataOptionalResponse] `json:"metadata,omitempty" yaml:"metadata,omitempty"`
	// Параметры кластера.
	Spec   ClickhouseClusterSpecOptionalResponse `json:"spec" yaml:"spec"`
	Status *ClickhouseClusterStatusResponse      `json:"status,omitempty" yaml:"status,omitempty"`
}

func (m *ClickhouseClusterOptionalResponse) GetKind() *string {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (m *ClickhouseClusterOptionalResponse) SetKind(val *string) {
	m.Kind = val
}

func (m *ClickhouseClusterOptionalResponse) GetKindOr(val string) string {
	if m != nil && m.Kind != nil {
		return *m.Kind
	}
	return val
}

func (m *ClickhouseClusterOptionalResponse) GetMetadata() *ClickhouseClusterMetadataOptionalResponse {
	if m != nil && m.Metadata.IsSet() && !m.Metadata.IsNull() {
		return &m.Metadata.Value
	}
	return nil
}

func (m *ClickhouseClusterOptionalResponse) GetMetadataOr(val ClickhouseClusterMetadataOptionalResponse) ClickhouseClusterMetadataOptionalResponse {
	if m != nil && m.Metadata.IsSet() && !m.Metadata.IsNull() {
		return m.Metadata.Value
	}
	return val
}

func (m *ClickhouseClusterOptionalResponse) GetSpec() ClickhouseClusterSpecOptionalResponse {
	if m != nil {
		return m.Spec
	}
	return ClickhouseClusterSpecOptionalResponse{}
}

func (m *ClickhouseClusterOptionalResponse) SetSpec(val ClickhouseClusterSpecOptionalResponse) {
	m.Spec = val
}

func (m *ClickhouseClusterOptionalResponse) GetStatus() *ClickhouseClusterStatusResponse {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ClickhouseClusterOptionalResponse) SetStatus(val *ClickhouseClusterStatusResponse) {
	m.Status = val
}

func (m *ClickhouseClusterOptionalResponse) GetStatusOr(val ClickhouseClusterStatusResponse) ClickhouseClusterStatusResponse {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return val
}

func (m *ClickhouseClusterOptionalResponse) Clone() *ClickhouseClusterOptionalResponse {
	if m == nil {
		return nil
	}

	clone := *m
	if m.Kind != nil {
		cloneKind := *m.Kind
		clone.Kind = &cloneKind
	}
	if clone.Metadata.IsSet() {
		clone.Metadata.Value = *m.Metadata.Value.Clone()
	}
	clone.Spec = *m.Spec.Clone()
	clone.Status = m.Status.Clone()
	return &clone
}

func (m *ClickhouseClusterOptionalResponse) Parse(ctx context.Context) error {
	if m == nil {
		return nil
	}

	if err := m.Spec.Parse(ctx); err != nil {
		return reserrors.NewPathAccumulatorError("Spec", err)
	}

	if err := m.Status.Parse(ctx); err != nil {
		return reserrors.NewPathAccumulatorError("Status", err)
	}

	return nil
}

// Представление поля Metadata анонимного типа структуры ClickhouseCluster
// Real OAPI model name: ClickhouseClusterMetadata
type ClickhouseClusterMetadataOptionalResponse struct {
	commonmodel.TypedResourceMetadataOptionalResponse `yaml:"-,inline"`
	// Ссылка на типизированный референс.
	Id *mclickhouse.ClickhouseClusterID `json:"id,omitempty" yaml:"id,omitempty"`
}

func (m *ClickhouseClusterMetadataOptionalResponse) GetDisplayName() *string {
	if m != nil && m.DisplayName.IsSet() {
		return m.TypedResourceMetadataOptionalResponse.GetDisplayName()
	}
	return nil
}

func (m *ClickhouseClusterMetadataOptionalResponse) GetDisplayNameOr(val string) string {
	if m != nil {
		return m.TypedResourceMetadataOptionalResponse.GetDisplayNameOr(val)
	}
	return val
}

func (m *ClickhouseClusterMetadataOptionalResponse) GetCreateTime() *time.Time {
	if m != nil {
		return m.TypedResourceMetadataOptionalResponse.GetCreateTime()
	}
	return nil
}

func (m *ClickhouseClusterMetadataOptionalResponse) GetCreateTimeOr(val time.Time) time.Time {
	if m != nil {
		return m.TypedResourceMetadataOptionalResponse.GetCreateTimeOr(val)
	}
	return val
}

func (m *ClickhouseClusterMetadataOptionalResponse) GetUpdateTime() *time.Time {
	if m != nil {
		return m.TypedResourceMetadataOptionalResponse.GetUpdateTime()
	}
	return nil
}

func (m *ClickhouseClusterMetadataOptionalResponse) GetUpdateTimeOr(val time.Time) time.Time {
	if m != nil {
		return m.TypedResourceMetadataOptionalResponse.GetUpdateTimeOr(val)
	}
	return val
}

func (m *ClickhouseClusterMetadataOptionalResponse) GetDeleteTime() *time.Time {
	if m != nil {
		return m.TypedResourceMetadataOptionalResponse.GetDeleteTime()
	}
	return nil
}

func (m *ClickhouseClusterMetadataOptionalResponse) GetDeleteTimeOr(val time.Time) time.Time {
	if m != nil {
		return m.TypedResourceMetadataOptionalResponse.GetDeleteTimeOr(val)
	}
	return val
}

func (m *ClickhouseClusterMetadataOptionalResponse) GetPurgeTime() *time.Time {
	if m != nil {
		return m.TypedResourceMetadataOptionalResponse.GetPurgeTime()
	}
	return nil
}

func (m *ClickhouseClusterMetadataOptionalResponse) GetPurgeTimeOr(val time.Time) time.Time {
	if m != nil {
		return m.TypedResourceMetadataOptionalResponse.GetPurgeTimeOr(val)
	}
	return val
}

func (m *ClickhouseClusterMetadataOptionalResponse) GetUsages() []commonmodel.TypedUsageOptionalResponse {
	if m != nil && m.Usages.IsSet() {
		return m.TypedResourceMetadataOptionalResponse.GetUsages()
	}
	return nil
}

func (m *ClickhouseClusterMetadataOptionalResponse) GetUsagesOr(val []commonmodel.TypedUsageOptionalResponse) []commonmodel.TypedUsageOptionalResponse {
	if m != nil {
		return m.TypedResourceMetadataOptionalResponse.GetUsagesOr(val)
	}
	return val
}

func (m *ClickhouseClusterMetadataOptionalResponse) GetEtag() *string {
	if m != nil && m.Etag.IsSet() {
		return m.TypedResourceMetadataOptionalResponse.GetEtag()
	}
	return nil
}

func (m *ClickhouseClusterMetadataOptionalResponse) GetEtagOr(val string) string {
	if m != nil {
		return m.TypedResourceMetadataOptionalResponse.GetEtagOr(val)
	}
	return val
}

func (m *ClickhouseClusterMetadataOptionalResponse) GetDescription() *string {
	if m != nil && m.Description.IsSet() {
		return m.TypedResourceMetadataOptionalResponse.GetDescription()
	}
	return nil
}

func (m *ClickhouseClusterMetadataOptionalResponse) GetDescriptionOr(val string) string {
	if m != nil {
		return m.TypedResourceMetadataOptionalResponse.GetDescriptionOr(val)
	}
	return val
}

func (m *ClickhouseClusterMetadataOptionalResponse) GetId() *mclickhouse.ClickhouseClusterID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ClickhouseClusterMetadataOptionalResponse) GetIdOr(val mclickhouse.ClickhouseClusterID) mclickhouse.ClickhouseClusterID {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return val
}

func (m *ClickhouseClusterMetadataOptionalResponse) Clone() *ClickhouseClusterMetadataOptionalResponse {
	if m == nil {
		return nil
	}

	clone := *m
	clone.TypedResourceMetadataOptionalResponse = *m.TypedResourceMetadataOptionalResponse.Clone()
	clone.Id = m.Id.Clone()

	return &clone
}

// JSON methods

func (m ClickhouseClusterOptionalResponse) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	if err := m.Encode(&e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (m *ClickhouseClusterOptionalResponse) Encode(e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	if err := m.encodeFields(e); err != nil {
		return err
	}
	e.ObjEnd()
	return nil
}

func (m *ClickhouseClusterOptionalResponse) encodeFields(e *jx.Encoder) error {
	if m.Kind != nil {
		e.FieldStart("kind")
		e.Str(*m.Kind)
	}

	if m.Metadata.IsSet() {
		e.FieldStart("metadata")
		if m.Metadata.IsNull() {
			e.Null()
		} else {
			if err := m.Metadata.Value.Encode(e); err != nil {
				return err
			}
		}
	}

	e.FieldStart("spec")
	if err := m.Spec.Encode(e); err != nil {
		return err
	}

	if m.Status != nil {
		e.FieldStart("status")
		if err := m.Status.Encode(e); err != nil {
			return err
		}
	}
	return nil
}

func (m *ClickhouseClusterOptionalResponse) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *ClickhouseClusterOptionalResponse) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("ClickhouseClusterOptionalResponse")
	}

	return d.ObjBytes(reserrors.PathAccumulatorErrorObjBytesFuncWrap(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "kind":
			v, err := decode.Str(d)
			if err != nil {
				return err
			}

			m.Kind = &v
			return nil
		case "metadata":
			if d.Next() == jx.Null {
				m.Metadata.SetToNull()
				return d.Null()
			}

			var v ClickhouseClusterMetadataOptionalResponse
			if err := v.Decode(d); err != nil {
				return err
			}

			m.Metadata.SetTo(v)
			return nil
		case "spec":
			var v ClickhouseClusterSpecOptionalResponse
			if err := v.Decode(d); err != nil {
				return err
			}

			m.Spec = v
			return nil
		case "status":
			if d.Next() == jx.Null {
				return d.Null()
			}

			var v ClickhouseClusterStatusResponse
			if err := v.Decode(d); err != nil {
				return err
			}

			m.Status = &v
			return nil
		default:
			return d.Skip()
		}
	}))
}

func (m ClickhouseClusterMetadataOptionalResponse) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	if err := m.Encode(&e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (m *ClickhouseClusterMetadataOptionalResponse) Encode(e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	if err := m.encodeFields(e); err != nil {
		return err
	}
	e.ObjEnd()
	return nil
}

func (m *ClickhouseClusterMetadataOptionalResponse) encodeFields(e *jx.Encoder) error {
	if m.DisplayName.IsSet() {
		e.FieldStart("displayName")
		e.Str(m.DisplayName.Value)
	}

	if m.CreateTime != nil {
		e.FieldStart("createTime")
		conv.EncodeDateTimeUTC(e, *m.CreateTime)
	}

	if m.UpdateTime != nil {
		e.FieldStart("updateTime")
		conv.EncodeDateTimeUTC(e, *m.UpdateTime)
	}

	if m.DeleteTime != nil {
		e.FieldStart("deleteTime")
		conv.EncodeDateTimeUTC(e, *m.DeleteTime)
	}

	if m.PurgeTime != nil {
		e.FieldStart("purgeTime")
		conv.EncodeDateTimeUTC(e, *m.PurgeTime)
	}

	if m.Usages.IsSet() {
		e.FieldStart("usages")
		e.ArrStart()
		for _, elem := range m.Usages.Value {
			if err := elem.Encode(e); err != nil {
				return err
			}
		}
		e.ArrEnd()
	}

	if m.Etag.IsSet() {
		e.FieldStart("etag")
		e.Str(m.Etag.Value)
	}

	if m.Description.IsSet() {
		e.FieldStart("description")
		e.Str(m.Description.Value)
	}
	if m.Id != nil {
		e.FieldStart("id")
		if err := m.Id.Encode(e); err != nil {
			return err
		}
	}
	return nil
}

func (m *ClickhouseClusterMetadataOptionalResponse) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *ClickhouseClusterMetadataOptionalResponse) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("ClickhouseClusterMetadataOptionalResponse")
	}

	return d.ObjBytes(reserrors.PathAccumulatorErrorObjBytesFuncWrap(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "displayName":
			v, err := decode.Str(d)
			if err != nil {
				return err
			}

			m.DisplayName.SetTo(v)
			return nil
		case "createTime":
			v, err := decode.DateTime(d)
			if err != nil {
				return err
			}

			m.CreateTime = &v
			return nil
		case "updateTime":
			v, err := decode.DateTime(d)
			if err != nil {
				return err
			}

			m.UpdateTime = &v
			return nil
		case "deleteTime":
			v, err := decode.DateTime(d)
			if err != nil {
				return err
			}

			m.DeleteTime = &v
			return nil
		case "purgeTime":
			v, err := decode.DateTime(d)
			if err != nil {
				return err
			}

			m.PurgeTime = &v
			return nil
		case "usages":
			c := make([]commonmodel.TypedUsageOptionalResponse, 0)
			if err := d.Arr(reserrors.PathAccumulatorErrorAsIndexArrFuncWrap(func(d *jx.Decoder) error {
				var v commonmodel.TypedUsageOptionalResponse
				if err := v.Decode(d); err != nil {
					return err
				}
				c = append(c, v)
				return nil
			})); err != nil {
				return err
			}

			m.Usages.SetTo(c)
			return nil
		case "etag":
			v, err := decode.Str(d)
			if err != nil {
				return err
			}

			m.Etag.SetTo(v)
			return nil
		case "description":
			v, err := decode.Str(d)
			if err != nil {
				return err
			}

			m.Description.SetTo(v)
			return nil
		case "id":
			var v mclickhouse.ClickhouseClusterID
			if err := v.Decode(d); err != nil {
				return err
			}

			m.Id = &v
			return nil
		default:
			return d.Skip()
		}
	}))
}
