// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/go-faster/jx"
	"go.mws.cloud/go-sdk/pkg/apimodels/units/bytesize"

	"go.mws.cloud/go-sdk/internal/conv"
	"go.mws.cloud/go-sdk/internal/decode"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	"go.mws.cloud/go-sdk/pkg/optional"
)

// Конфигурация схемы хранилищ ClickHouse.
//
// Real OAPI model name: ClickhouseStorageConfiguration
type ClickhouseStorageConfigurationOptionalResponse struct {
	// Включить гибридное хранилище (hot SSD + cold S3).
	HybridStorageEnabled optional.Optional[bool] `json:"hybridStorageEnabled,omitempty" yaml:"hybridStorageEnabled,omitempty"`
	// Соотношение свободного дискового пространства на SSD дисках кластера (от 0.01 до 1) Когда это соотношение превышает значение параметра конфигурации, ClickHouse начинает перемещать данные в следующий том по порядку.
	MoveFactor optional.Optional[float64] `json:"moveFactor,omitempty" yaml:"moveFactor,omitempty"`
	// Включить кеширование данных с объектного хранилища на сетевых SSD дисках.
	DataCachingEnabled optional.Optional[bool] `json:"dataCachingEnabled,omitempty" yaml:"dataCachingEnabled,omitempty"`
	// Максимальный размер кеша объектного хранилища, расположенный на SSD.
	CacheMaxSize optional.Optional[bytesize.ByteSize] `json:"cacheMaxSize,omitempty" yaml:"cacheMaxSize,omitempty"`
	// Максимальный размер части данных в байтах, который может храниться на дисках тома (SSD).
	MaxDataPartSizeSsd optional.Optional[bytesize.ByteSize] `json:"maxDataPartSizeSsd,omitempty" yaml:"maxDataPartSizeSsd,omitempty"`
}

func (m *ClickhouseStorageConfigurationOptionalResponse) GetHybridStorageEnabled() *bool {
	if m != nil && m.HybridStorageEnabled.IsSet() {
		return &m.HybridStorageEnabled.Value
	}
	return nil
}

func (m *ClickhouseStorageConfigurationOptionalResponse) GetHybridStorageEnabledOr(val bool) bool {
	if m != nil && m.HybridStorageEnabled.IsSet() {
		return m.HybridStorageEnabled.Value
	}
	return val
}

func (m *ClickhouseStorageConfigurationOptionalResponse) GetMoveFactor() *float64 {
	if m != nil && m.MoveFactor.IsSet() {
		return &m.MoveFactor.Value
	}
	return nil
}

func (m *ClickhouseStorageConfigurationOptionalResponse) GetMoveFactorOr(val float64) float64 {
	if m != nil && m.MoveFactor.IsSet() {
		return m.MoveFactor.Value
	}
	return val
}

func (m *ClickhouseStorageConfigurationOptionalResponse) GetDataCachingEnabled() *bool {
	if m != nil && m.DataCachingEnabled.IsSet() {
		return &m.DataCachingEnabled.Value
	}
	return nil
}

func (m *ClickhouseStorageConfigurationOptionalResponse) GetDataCachingEnabledOr(val bool) bool {
	if m != nil && m.DataCachingEnabled.IsSet() {
		return m.DataCachingEnabled.Value
	}
	return val
}

func (m *ClickhouseStorageConfigurationOptionalResponse) GetCacheMaxSize() *bytesize.ByteSize {
	if m != nil && m.CacheMaxSize.IsSet() {
		return &m.CacheMaxSize.Value
	}
	return nil
}

func (m *ClickhouseStorageConfigurationOptionalResponse) GetCacheMaxSizeOr(val bytesize.ByteSize) bytesize.ByteSize {
	if m != nil && m.CacheMaxSize.IsSet() {
		return m.CacheMaxSize.Value
	}
	return val
}

func (m *ClickhouseStorageConfigurationOptionalResponse) GetMaxDataPartSizeSsd() *bytesize.ByteSize {
	if m != nil && m.MaxDataPartSizeSsd.IsSet() {
		return &m.MaxDataPartSizeSsd.Value
	}
	return nil
}

func (m *ClickhouseStorageConfigurationOptionalResponse) GetMaxDataPartSizeSsdOr(val bytesize.ByteSize) bytesize.ByteSize {
	if m != nil && m.MaxDataPartSizeSsd.IsSet() {
		return m.MaxDataPartSizeSsd.Value
	}
	return val
}

func (m *ClickhouseStorageConfigurationOptionalResponse) Clone() *ClickhouseStorageConfigurationOptionalResponse {
	if m == nil {
		return nil
	}

	clone := *m
	if clone.CacheMaxSize.IsSet() {
		clone.CacheMaxSize.Value = *m.CacheMaxSize.Value.Clone()
	}
	if clone.MaxDataPartSizeSsd.IsSet() {
		clone.MaxDataPartSizeSsd.Value = *m.MaxDataPartSizeSsd.Value.Clone()
	}
	return &clone
}

// JSON methods

func (m ClickhouseStorageConfigurationOptionalResponse) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	if err := m.Encode(&e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (m *ClickhouseStorageConfigurationOptionalResponse) Encode(e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	if err := m.encodeFields(e); err != nil {
		return err
	}
	e.ObjEnd()
	return nil
}

func (m *ClickhouseStorageConfigurationOptionalResponse) encodeFields(e *jx.Encoder) error {
	if m.HybridStorageEnabled.IsSet() {
		e.FieldStart("hybridStorageEnabled")
		e.Bool(m.HybridStorageEnabled.Value)
	}

	if m.MoveFactor.IsSet() {
		e.FieldStart("moveFactor")
		e.Float64(m.MoveFactor.Value)
	}

	if m.DataCachingEnabled.IsSet() {
		e.FieldStart("dataCachingEnabled")
		e.Bool(m.DataCachingEnabled.Value)
	}

	if m.CacheMaxSize.IsSet() {
		e.FieldStart("cacheMaxSize")
		m.CacheMaxSize.Value.Encode(e)
	}

	if m.MaxDataPartSizeSsd.IsSet() {
		e.FieldStart("maxDataPartSizeSsd")
		m.MaxDataPartSizeSsd.Value.Encode(e)
	}
	return nil
}

func (m *ClickhouseStorageConfigurationOptionalResponse) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *ClickhouseStorageConfigurationOptionalResponse) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("ClickhouseStorageConfigurationOptionalResponse")
	}

	return d.ObjBytes(reserrors.PathAccumulatorErrorObjBytesFuncWrap(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "hybridStorageEnabled":
			v, err := decode.Bool(d)
			if err != nil {
				return err
			}

			m.HybridStorageEnabled.SetTo(v)
			return nil
		case "moveFactor":
			v, err := decode.Float64(d)
			if err != nil {
				return err
			}

			m.MoveFactor.SetTo(v)
			return nil
		case "dataCachingEnabled":
			v, err := decode.Bool(d)
			if err != nil {
				return err
			}

			m.DataCachingEnabled.SetTo(v)
			return nil
		case "cacheMaxSize":
			var v bytesize.ByteSize
			if err := v.Decode(d); err != nil {
				return err
			}

			m.CacheMaxSize.SetTo(v)
			return nil
		case "maxDataPartSizeSsd":
			var v bytesize.ByteSize
			if err := v.Decode(d); err != nil {
				return err
			}

			m.MaxDataPartSizeSsd.SetTo(v)
			return nil
		default:
			return d.Skip()
		}
	}))
}
