// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"context"

	"github.com/go-faster/jx"
	"go.mws.cloud/go-sdk/pkg/apimodels/ipaddress"

	"go.mws.cloud/go-sdk/internal/conv"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	"go.mws.cloud/go-sdk/service/resources/references/vpc"
)

// Описание внешнего доступа к кластеру.
// Real OAPI model name: ClickhouseEndpointExternalAddressResource
type ClickhouseEndpointExternalAddressResourceResponse struct {
	// Идентификатор адреса в VPC.
	Ref vpc.ExternalAddressRef `json:"ref" yaml:"ref"`
	// Выделенный адрес.
	IpAddress ipaddress.IPAddress `json:"ipAddress" yaml:"ipAddress"`
}

func (m *ClickhouseEndpointExternalAddressResourceResponse) GetRef() vpc.ExternalAddressRef {
	if m != nil {
		return m.Ref
	}
	return vpc.ExternalAddressRef{}
}

func (m *ClickhouseEndpointExternalAddressResourceResponse) SetRef(val vpc.ExternalAddressRef) {
	m.Ref = val
}

func (m *ClickhouseEndpointExternalAddressResourceResponse) GetIpAddress() ipaddress.IPAddress {
	if m != nil {
		return m.IpAddress
	}
	return ipaddress.IPAddress{}
}

func (m *ClickhouseEndpointExternalAddressResourceResponse) SetIpAddress(val ipaddress.IPAddress) {
	m.IpAddress = val
}

func (m *ClickhouseEndpointExternalAddressResourceResponse) Clone() *ClickhouseEndpointExternalAddressResourceResponse {
	if m == nil {
		return nil
	}

	clone := *m
	clone.Ref = *m.Ref.Clone()
	clone.IpAddress = *m.IpAddress.Clone()
	return &clone
}

func (m *ClickhouseEndpointExternalAddressResourceResponse) Parse(ctx context.Context) error {
	if m == nil {
		return nil
	}

	if err := m.Ref.Parse(ctx); err != nil {
		return reserrors.NewPathAccumulatorError("Ref", err)
	}

	return nil
}

// JSON methods

func (m ClickhouseEndpointExternalAddressResourceResponse) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	if err := m.Encode(&e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (m *ClickhouseEndpointExternalAddressResourceResponse) Encode(e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	if err := m.encodeFields(e); err != nil {
		return err
	}
	e.ObjEnd()
	return nil
}

func (m *ClickhouseEndpointExternalAddressResourceResponse) encodeFields(e *jx.Encoder) error {
	e.FieldStart("ref")
	if err := m.Ref.Encode(e); err != nil {
		return err
	}

	e.FieldStart("ipAddress")
	m.IpAddress.Encode(e)
	return nil
}

func (m *ClickhouseEndpointExternalAddressResourceResponse) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *ClickhouseEndpointExternalAddressResourceResponse) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("ClickhouseEndpointExternalAddressResourceResponse")
	}

	return d.ObjBytes(reserrors.PathAccumulatorErrorObjBytesFuncWrap(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "ref":
			var v vpc.ExternalAddressRef
			if err := v.Decode(d); err != nil {
				return err
			}

			m.Ref = v
			return nil
		case "ipAddress":
			var v ipaddress.IPAddress
			if err := v.Decode(d); err != nil {
				return err
			}

			m.IpAddress = v
			return nil
		default:
			return d.Skip()
		}
	}))
}
