// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"encoding/json"

	"github.com/go-faster/jx"

	"go.mws.cloud/go-sdk/internal/conv"
	"go.mws.cloud/go-sdk/internal/decode"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	common "go.mws.cloud/go-sdk/service/common/model"
)

func (m ClickhouseClusterSpecRequest) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	if err := m.Encode(&e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (m *ClickhouseClusterSpecRequest) Encode(e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	if err := m.encodeFields(e); err != nil {
		return err
	}
	e.ObjEnd()
	return nil
}

func (m *ClickhouseClusterSpecRequest) encodeFields(e *jx.Encoder) error {
	if m.Active != nil {
		e.FieldStart("active")
		e.Bool(*m.Active)
	}

	e.FieldStart("version")
	e.Str(m.Version)

	if m.Endpoints != nil {
		e.FieldStart("endpoints")
		e.ArrStart()
		for _, elem := range m.Endpoints {
			elem.Encode(e)
		}
		e.ArrEnd()
	}

	if m.Coordinator != nil {
		e.FieldStart("coordinator")
		m.Coordinator.Encode(e)
	}

	e.FieldStart("shards")
	e.ArrStart()
	for _, elem := range m.Shards {
		elem.Encode(e)
	}
	e.ArrEnd()

	if m.Config != nil {
		e.FieldStart("config")
		e.ObjStart()
		for key, elem := range m.Config {
			e.FieldStart(key)
			if elem == nil {
				e.Null()
				continue
			}
			e.Raw(elem)
		}
		e.ObjEnd()
	}

	if m.Storage != nil {
		e.FieldStart("storage")
		m.Storage.Encode(e)
	}

	e.FieldStart("bootstrapAdmin")
	m.BootstrapAdmin.Encode(e)

	if m.Backup != nil {
		e.FieldStart("backup")
		m.Backup.Encode(e)
	}

	if m.MaintenanceWindow != nil {
		e.FieldStart("maintenanceWindow")
		m.MaintenanceWindow.Encode(e)
	}
	return nil
}

func (m *ClickhouseClusterSpecRequest) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *ClickhouseClusterSpecRequest) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("ClickhouseClusterSpecRequest")
	}

	requiredFilled := map[string]bool{
		"version":        false,
		"shards":         false,
		"bootstrapAdmin": false,
	}
	err := d.ObjBytes(reserrors.PathAccumulatorErrorObjBytesFuncWrap(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "active":
			v, err := decode.Bool(d)
			if err != nil {
				return err
			}

			m.Active = &v
			return nil
		case "version":
			v, err := decode.Str(d)
			if err != nil {
				return err
			}

			m.Version = v
			requiredFilled["version"] = true
			return nil
		case "endpoints":
			c := make([]ClickhouseEndpointRequest, 0)
			if err := d.Arr(reserrors.PathAccumulatorErrorAsIndexArrFuncWrap(func(d *jx.Decoder) error {
				var v ClickhouseEndpointRequest
				if err := v.Decode(d); err != nil {
					return err
				}
				c = append(c, v)
				return nil
			})); err != nil {
				return err
			}

			m.Endpoints = c
			return nil
		case "coordinator":
			if d.Next() == jx.Null {
				return d.Null()
			}

			var v ClickhouseClusterCoordinatorRequest
			if err := v.Decode(d); err != nil {
				return err
			}

			m.Coordinator = &v
			return nil
		case "shards":
			c := make([]ClickhouseClusterShardRequest, 0)
			if err := d.Arr(reserrors.PathAccumulatorErrorAsIndexArrFuncWrap(func(d *jx.Decoder) error {
				var v ClickhouseClusterShardRequest
				if err := v.Decode(d); err != nil {
					return err
				}
				c = append(c, v)
				return nil
			})); err != nil {
				return err
			}

			m.Shards = c
			requiredFilled["shards"] = true
			return nil
		case "config":
			c := make(map[string]json.RawMessage)
			if err := d.ObjBytes(reserrors.PathAccumulatorErrorAsIndexObjBytesFuncWrap(func(d *jx.Decoder, k []byte) error {
				v, err := d.Raw()
				if err != nil {
					return err
				}

				c[string(k)] = json.RawMessage(v)
				return nil
			})); err != nil {
				return err
			}

			m.Config = c
			return nil
		case "storage":
			if d.Next() == jx.Null {
				return d.Null()
			}

			var v ClickhouseStorageConfigurationRequest
			if err := v.Decode(d); err != nil {
				return err
			}

			m.Storage = &v
			return nil
		case "bootstrapAdmin":
			var v ClickhouseClusterBootstrapAdminSpecRequest
			if err := v.Decode(d); err != nil {
				return err
			}

			m.BootstrapAdmin = v
			requiredFilled["bootstrapAdmin"] = true
			return nil
		case "backup":
			if d.Next() == jx.Null {
				return d.Null()
			}

			var v ClickhouseClusterBackupRequest
			if err := v.Decode(d); err != nil {
				return err
			}

			m.Backup = &v
			return nil
		case "maintenanceWindow":
			if d.Next() == jx.Null {
				return d.Null()
			}

			var v common.MaintenanceWindowRequest
			if err := v.Decode(d); err != nil {
				return err
			}

			m.MaintenanceWindow = &v
			return nil
		default:
			return d.Skip()
		}
	}))
	if err != nil {
		return err
	}

	return conv.ValidateRequired(requiredFilled)
}
