// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"context"

	"go.mws.cloud/go-sdk/pkg/apimodels/units/bytesize"

	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	"go.mws.cloud/go-sdk/service/resources/references/compute"
)

// Параметры диска.
// Real OAPI model name: ClickhouseInstanceDiskSpec
type ClickhouseInstanceDiskSpecRequest struct {
	// Размер диска.
	Size bytesize.ByteSize `json:"size" yaml:"size"`
	// Тип диска.
	Type compute.DiskTypeRef `json:"type" yaml:"type"`
	// IOPS
	Iops *Iops `json:"iops,omitempty" yaml:"iops,omitempty"`
}

func (m *ClickhouseInstanceDiskSpecRequest) GetSize() bytesize.ByteSize {
	if m != nil {
		return m.Size
	}
	return bytesize.ByteSize{}
}

func (m *ClickhouseInstanceDiskSpecRequest) SetSize(val bytesize.ByteSize) {
	m.Size = val
}

func (m *ClickhouseInstanceDiskSpecRequest) GetType() compute.DiskTypeRef {
	if m != nil {
		return m.Type
	}
	return compute.DiskTypeRef{}
}

func (m *ClickhouseInstanceDiskSpecRequest) SetType(val compute.DiskTypeRef) {
	m.Type = val
}

func (m *ClickhouseInstanceDiskSpecRequest) GetIops() *Iops {
	if m != nil {
		return m.Iops
	}
	return nil
}

func (m *ClickhouseInstanceDiskSpecRequest) SetIops(val *Iops) {
	m.Iops = val
}

func (m *ClickhouseInstanceDiskSpecRequest) GetIopsOr(val Iops) Iops {
	if m != nil && m.Iops != nil {
		return *m.Iops
	}
	return val
}

func (m *ClickhouseInstanceDiskSpecRequest) Clone() *ClickhouseInstanceDiskSpecRequest {
	if m == nil {
		return nil
	}

	clone := *m
	clone.Size = *m.Size.Clone()
	clone.Type = *m.Type.Clone()
	if m.Iops != nil {
		cloneIops := *m.Iops
		clone.Iops = &cloneIops
	}
	return &clone
}

func (m *ClickhouseInstanceDiskSpecRequest) Parse(ctx context.Context) error {
	if m == nil {
		return nil
	}

	if err := m.Type.Parse(ctx); err != nil {
		return reserrors.NewPathAccumulatorError("Type", err)
	}

	return nil
}
