// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"go.mws.cloud/go-sdk/pkg/optional"
)

func ClickhouseClusterShardRequestToOptionalResponse(request *ClickhouseClusterShardRequest) (*ClickhouseClusterShardOptionalResponse, error) {
	if request == nil {
		return nil, nil
	}
	var response ClickhouseClusterShardOptionalResponse
	response.Name = request.Name
	if request.Count != nil {
		response.Count = optional.NewOptional(*request.Count)
	}
	tmpResources, err := ClickhouseInstanceHWResourcesRequestToOptionalResponse(&request.Resources)
	if err != nil {
		return nil, err
	}
	response.Resources = *tmpResources
	if request.Weight != nil {
		response.Weight = optional.NewOptional(*request.Weight)
	}
	for _, e := range request.Endpoints {
		tmp, err := ClickhouseEndpointRequestToOptionalResponse(&e)
		if err != nil {
			return nil, err
		}
		response.Endpoints.SetTo(append(response.Endpoints.Value, *tmp))
	}
	for _, e := range request.Instances {
		tmp, err := ClickhouseClusterInstanceRequestToOptionalResponse(&e)
		if err != nil {
			return nil, err
		}
		response.Instances = append(response.Instances, *tmp)
	}
	return &response, nil
}
