// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"context"

	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	"go.mws.cloud/go-sdk/service/resources/references/mclickhouse"
	"go.mws.cloud/go-sdk/service/resources/references/rm"
)

// Описание инстанса координатора.
// Real OAPI model name: ClickhouseClusterCoordinatorInstanceResource
type ClickhouseClusterCoordinatorInstanceResourceResponse struct {
	// Идентификатор инстанса координатора.
	Id mclickhouse.ClickhouseClusterCoordinatorInstanceID `json:"id" yaml:"id"`
	// Зона доступности.
	Zone   rm.ZoneRef                `json:"zone" yaml:"zone"`
	Health *ClickhouseInstanceHealth `json:"health,omitempty" yaml:"health,omitempty"`
}

func (m *ClickhouseClusterCoordinatorInstanceResourceResponse) GetId() mclickhouse.ClickhouseClusterCoordinatorInstanceID {
	if m != nil {
		return m.Id
	}
	return mclickhouse.ClickhouseClusterCoordinatorInstanceID{}
}

func (m *ClickhouseClusterCoordinatorInstanceResourceResponse) SetId(val mclickhouse.ClickhouseClusterCoordinatorInstanceID) {
	m.Id = val
}

func (m *ClickhouseClusterCoordinatorInstanceResourceResponse) GetZone() rm.ZoneRef {
	if m != nil {
		return m.Zone
	}
	return rm.ZoneRef{}
}

func (m *ClickhouseClusterCoordinatorInstanceResourceResponse) SetZone(val rm.ZoneRef) {
	m.Zone = val
}

func (m *ClickhouseClusterCoordinatorInstanceResourceResponse) GetHealth() *ClickhouseInstanceHealth {
	if m != nil {
		return m.Health
	}
	return nil
}

func (m *ClickhouseClusterCoordinatorInstanceResourceResponse) SetHealth(val *ClickhouseInstanceHealth) {
	m.Health = val
}

func (m *ClickhouseClusterCoordinatorInstanceResourceResponse) GetHealthOr(val ClickhouseInstanceHealth) ClickhouseInstanceHealth {
	if m != nil && m.Health != nil {
		return *m.Health
	}
	return val
}

func (m *ClickhouseClusterCoordinatorInstanceResourceResponse) Clone() *ClickhouseClusterCoordinatorInstanceResourceResponse {
	if m == nil {
		return nil
	}

	clone := *m
	clone.Id = *m.Id.Clone()
	clone.Zone = *m.Zone.Clone()
	if m.Health != nil {
		cloneHealth := *m.Health
		clone.Health = &cloneHealth
	}
	return &clone
}

func (m *ClickhouseClusterCoordinatorInstanceResourceResponse) Parse(ctx context.Context) error {
	if m == nil {
		return nil
	}

	if err := m.Id.Parse(ctx); err != nil {
		return reserrors.NewPathAccumulatorError("Id", err)
	}

	if err := m.Zone.Parse(ctx); err != nil {
		return reserrors.NewPathAccumulatorError("Zone", err)
	}

	return nil
}
