// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"context"
	"fmt"

	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	"go.mws.cloud/go-sdk/pkg/optional"
	"go.mws.cloud/go-sdk/service/resources/references/rm"
)

// Описание инстанса кластера.
// Real OAPI model name: ClickhouseClusterInstance
type ClickhouseClusterInstanceOptionalResponse struct {
	// -> Имя инстанса в шарде. В случае count>1, имя формируется как name-{replicaIndex}, где replicaIndex имеет сквозную нумерацию в шарде.
	Name optional.Optional[string] `json:"name,omitempty" yaml:"name,omitempty"`
	// Количество инстансов в зоне доступности
	Count optional.Optional[int] `json:"count,omitempty" yaml:"count,omitempty"`
	// Зона доступности
	Zone rm.ZoneRef `json:"zone" yaml:"zone"`
	// Описание эдпойнтов инстансов.
	Endpoints optional.Optional[[]ClickhouseEndpointOptionalResponse] `json:"endpoints,omitempty" yaml:"endpoints,omitempty"`
}

func (m *ClickhouseClusterInstanceOptionalResponse) GetName() *string {
	if m != nil && m.Name.IsSet() {
		return &m.Name.Value
	}
	return nil
}

func (m *ClickhouseClusterInstanceOptionalResponse) GetNameOr(val string) string {
	if m != nil && m.Name.IsSet() {
		return m.Name.Value
	}
	return val
}

func (m *ClickhouseClusterInstanceOptionalResponse) GetCount() *int {
	if m != nil && m.Count.IsSet() {
		return &m.Count.Value
	}
	return nil
}

func (m *ClickhouseClusterInstanceOptionalResponse) GetCountOr(val int) int {
	if m != nil && m.Count.IsSet() {
		return m.Count.Value
	}
	return val
}

func (m *ClickhouseClusterInstanceOptionalResponse) GetZone() rm.ZoneRef {
	if m != nil {
		return m.Zone
	}
	return rm.ZoneRef{}
}

func (m *ClickhouseClusterInstanceOptionalResponse) SetZone(val rm.ZoneRef) {
	m.Zone = val
}

func (m *ClickhouseClusterInstanceOptionalResponse) GetEndpoints() []ClickhouseEndpointOptionalResponse {
	if m != nil && m.Endpoints.IsSet() {
		return m.Endpoints.Value
	}
	return nil
}

func (m *ClickhouseClusterInstanceOptionalResponse) GetEndpointsOr(val []ClickhouseEndpointOptionalResponse) []ClickhouseEndpointOptionalResponse {
	if m != nil && m.Endpoints.IsSet() {
		return m.Endpoints.Value
	}
	return val
}

func (m *ClickhouseClusterInstanceOptionalResponse) Clone() *ClickhouseClusterInstanceOptionalResponse {
	if m == nil {
		return nil
	}

	clone := *m
	clone.Zone = *m.Zone.Clone()
	if m.Endpoints.Value != nil {
		clone.Endpoints.Value = make([]ClickhouseEndpointOptionalResponse, len(m.Endpoints.Value))
		for i, v := range m.Endpoints.Value {
			clone.Endpoints.Value[i] = *v.Clone()
		}
	}
	return &clone
}

func (m *ClickhouseClusterInstanceOptionalResponse) Parse(ctx context.Context) error {
	if m == nil {
		return nil
	}

	if err := m.Zone.Parse(ctx); err != nil {
		return reserrors.NewPathAccumulatorError("Zone", err)
	}

	if m.Endpoints.IsSet() {
		for index := range m.Endpoints.Value {
			if err := m.Endpoints.Value[index].Parse(ctx); err != nil {
				return reserrors.NewPathAccumulatorError("Endpoints"+fmt.Sprint("[", index, "]"), err)
			}
		}
	}

	return nil
}
