// Code generated by mwsapigen, DO NOT EDIT.

package model

// Добавление пользователей при создании кластера Clickhouse.
// Real OAPI model name: ClickhouseClusterBootstrapAdminSpec
type ClickhouseClusterBootstrapAdminSpecRequest struct {
	// Имя учетной записи администратора.
	Username string `json:"username" yaml:"username"`
	// Пароль учетной записи администратора.
	Password string `json:"password" yaml:"password"`
}

func (m *ClickhouseClusterBootstrapAdminSpecRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ClickhouseClusterBootstrapAdminSpecRequest) SetUsername(val string) {
	m.Username = val
}

func (m *ClickhouseClusterBootstrapAdminSpecRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ClickhouseClusterBootstrapAdminSpecRequest) SetPassword(val string) {
	m.Password = val
}

func (m *ClickhouseClusterBootstrapAdminSpecRequest) Clone() *ClickhouseClusterBootstrapAdminSpecRequest {
	if m == nil {
		return nil
	}

	clone := *m
	return &clone
}
