// Code generated by mwsapigen, DO NOT EDIT.

package client

import (
	"context"

	"go.mws.cloud/util-toolset/pkg/utils/ptr"

	mwserrors "go.mws.cloud/go-sdk/mws/errors"
	"go.mws.cloud/go-sdk/mws/wait"
	"go.mws.cloud/go-sdk/service/rm/model"
)

type RegionSugared struct {
	impl Region
}

func NewRegionSugared(impl Region) *RegionSugared {
	return &RegionSugared{
		impl: impl,
	}
}

func (x *RegionSugared) Impl() Region {
	return x.impl
}

// ListRegions список регионов.
//
// Путь: GET /rm/v1/regions
func (x *RegionSugared) ListRegions(ctx context.Context, request ListRegionsRequest) (*model.RegionListResponse, error) {
	resp, err := x.impl.ListRegions(ctx, request)
	if err != nil {
		return nil, err
	}

	return x.respHandlerListRegions(resp)
}

func (x *RegionSugared) respHandlerListRegions(resp *ListRegionsResponse) (*model.RegionListResponse, error) {
	if err := resp.GetErr(); err != nil {
		return nil, err
	}

	if resp.Response200 != nil {
		return resp.Response200, nil
	}

	return nil, mwserrors.NewAPIError(resp.Code, mwserrors.Unknown, "unexpected result")
}

// GetRegion get region.
//
// Путь: GET /rm/v1/regions/{region}
func (x *RegionSugared) GetRegion(ctx context.Context, request GetRegionRequest, opts ...Option) (*model.RegionResponse, error) {
	config := newConfig(opts...)

	resp, err := x.impl.GetRegion(ctx, request)
	if err != nil {
		return nil, err
	}

	sugaredResponse, err := x.respHandlerGetRegion(resp)
	if err != nil {
		return nil, err
	}

	if !config.wait {
		return sugaredResponse, nil
	}

	return x.waitGetRegion(ctx, request, config.waitOptions...)
}

func (x *RegionSugared) respHandlerGetRegion(resp *GetRegionResponse) (*model.RegionResponse, error) {
	if err := resp.GetErr(); err != nil {
		return nil, err
	}

	if resp.Response200 != nil {
		return resp.Response200, nil
	}

	return nil, mwserrors.NewAPIError(resp.Code, mwserrors.Unknown, "unexpected result")
}

func (x *RegionSugared) waitGetRegion(ctx context.Context, request GetRegionRequest, opts ...wait.WaiterOption) (*model.RegionResponse, error) {
	callback := func(ctx context.Context) (*model.RegionResponse, bool, error) {
		response, err := x.GetRegion(ctx, request)
		stop := string(ptr.Get(response.GetStatus().GetReady()).GetState()) != "PROCESSING"
		return response, stop, err
	}
	waiter := wait.NewWaiter(callback, opts...)
	return waiter.Wait(ctx)
}
