// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	common "go.mws.cloud/go-sdk/service/common/model"
)

// Real OAPI model name: EnabledServiceStatus
type EnabledServiceStatusResponse struct {
	common.ResourceStatusResponse `yaml:"-,inline"`
}

func (m *EnabledServiceStatusResponse) GetReady() common.ResourceStatusReadyResponse {
	if m != nil {
		return m.ResourceStatusResponse.GetReady()
	}
	return common.ResourceStatusReadyResponse{}
}

func (m *EnabledServiceStatusResponse) Clone() *EnabledServiceStatusResponse {
	if m == nil {
		return nil
	}

	clone := *m
	clone.ResourceStatusResponse = *m.ResourceStatusResponse.Clone()

	return &clone
}
