// Code generated by mwsapigen, DO NOT EDIT.

package model_test

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/service/kms/model"
)

func TestGenerateDataKeyResponseMarshalling(t *testing.T) {
	t.Parallel()
	expected := initGenerateDataKeyResponse()
	b, err := json.Marshal(expected)
	require.NoError(t, err)

	var actual model.GenerateDataKeyResponse
	require.NoError(t, json.Unmarshal(b, &actual))
	require.Equal(t, expected, actual)
}

func initGenerateDataKeyResponse() model.GenerateDataKeyResponse {
	var v model.GenerateDataKeyResponse
	v.DataKeyCiphertext = make([]byte, 0)
	return v
}
