// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"context"

	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	"go.mws.cloud/go-sdk/service/resources/references/iam"
)

type CommonRoleBindingSpec struct {
	Subject CommonRoleBindingSpecSubject `json:"subject" yaml:"subject"`
	// Роль, определяющая права субъекта на ресурс
	Role iam.RoleRef `json:"role" yaml:"role"`
}

func (m *CommonRoleBindingSpec) GetSubject() CommonRoleBindingSpecSubject {
	if m != nil {
		return m.Subject
	}
	return CommonRoleBindingSpecSubject{}
}

func (m *CommonRoleBindingSpec) SetSubject(val CommonRoleBindingSpecSubject) {
	m.Subject = val
}

func (m *CommonRoleBindingSpec) GetRole() iam.RoleRef {
	if m != nil {
		return m.Role
	}
	return iam.RoleRef{}
}

func (m *CommonRoleBindingSpec) SetRole(val iam.RoleRef) {
	m.Role = val
}

func (m *CommonRoleBindingSpec) Clone() *CommonRoleBindingSpec {
	if m == nil {
		return nil
	}

	clone := *m
	clone.Subject = *m.Subject.Clone()
	clone.Role = *m.Role.Clone()
	return &clone
}

func (m *CommonRoleBindingSpec) Parse(ctx context.Context) error {
	if m == nil {
		return nil
	}

	if err := m.Subject.Parse(ctx); err != nil {
		return reserrors.NewPathAccumulatorError("Subject", err)
	}

	if err := m.Role.Parse(ctx); err != nil {
		return reserrors.NewPathAccumulatorError("Role", err)
	}

	return nil
}
