// Code generated by mwsapigen, DO NOT EDIT.

package model

func CommonRoleBindingFederationContextRequestToResponse(request *CommonRoleBindingFederationContextRequest) (*CommonRoleBindingFederationContextResponse, error) {
	if request == nil {
		return nil, nil
	}
	var response CommonRoleBindingFederationContextResponse
	response.Subject = request.Subject
	tmpAttribute, err := CommonRoleBindingFederationContextAttributeRequestToResponse(request.Attribute)
	if err != nil {
		return nil, err
	}
	response.Attribute = tmpAttribute
	return &response, nil
}
