// Code generated by mwsapigen, DO NOT EDIT.

package model

func CommonRoleBindingWorkloadFederationRequestToResponse(request *CommonRoleBindingWorkloadFederationRequest) (*CommonRoleBindingWorkloadFederationResponse, error) {
	if request == nil {
		return nil, nil
	}
	var response CommonRoleBindingWorkloadFederationResponse
	response.Id = request.Id
	tmpContext, err := CommonRoleBindingFederationContextRequestToResponse(request.Context)
	if err != nil {
		return nil, err
	}
	response.Context = tmpContext
	return &response, nil
}
