// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"go.mws.cloud/util-toolset/pkg/utils/ptr"

	commonclient "go.mws.cloud/go-sdk/internal/client"
	"go.mws.cloud/go-sdk/internal/merge"
	"go.mws.cloud/go-sdk/pkg/optional"
)

type UpdateCommonTypedResourceMetadata struct {
	// Обязательное уникальное, глобально или в пределах проекта, имя. Используется в качестве части составного идентификатора объекта.
	//
	// Deprecated: Отказываемся в пользу metadata.id
	Name optional.Optional[string] `json:"name" yaml:"name"`
	// Отображаемое имя свойства
	DisplayName optional.Optional[string] `json:"displayName" yaml:"displayName"`
	// Связи с другими ресурсами. В зависимости от типа связи, операции над ресурсом могут быть ограничены
	Usages optional.Optional[[]UpdateUsage] `json:"usages" yaml:"usages"`
	// Идентификатор состояния ресурса, позволяет отслеживать изменение ресурса
	Etag optional.Optional[string] `json:"etag" yaml:"etag"`
	// Описание ресурса
	Description optional.Optional[string] `json:"description" yaml:"description"`
}

func (m *CommonTypedResourceMetadata) AsUpdateModel() UpdateCommonTypedResourceMetadata {
	var u UpdateCommonTypedResourceMetadata
	if m.Name != nil {
		u.Name = optional.NewOptional(m.GetNameOr(""))
	}
	if m.DisplayName != nil {
		u.DisplayName = optional.NewOptional(m.GetDisplayNameOr(""))
	}
	if m.Usages != nil {
		u.Usages = optional.NewOptional(func() []UpdateUsage {
			var tmp []UpdateUsage
			if m.GetUsages() != nil {
				tmp = make([]UpdateUsage, 0, len(m.GetUsages()))
			}
			for _, val := range m.GetUsages() {
				tmp = append(tmp, val.AsUpdateModel())
			}
			return tmp
		}())
	}
	if m.Etag != nil {
		u.Etag = optional.NewOptional(m.GetEtagOr(""))
	}
	if m.Description != nil {
		u.Description = optional.NewOptional(m.GetDescriptionOr(""))
	}
	return u
}

// Diff creates an object that can be used in Update methods. This object represents changes from src to the current state
func (m *CommonTypedResourceMetadata) Diff(src *CommonTypedResourceMetadata) UpdateCommonTypedResourceMetadata {
	nilDiffers := src != nil && m == nil
	upd := UpdateCommonTypedResourceMetadata{}
	if !nilDiffers {
		upd.Name = m.diffName(src)
		upd.DisplayName = m.diffDisplayName(src)
		upd.Usages = m.diffUsages(src)
		upd.Etag = m.diffEtag(src)
		upd.Description = m.diffDescription(src)
	}
	return upd
}

func (m *CommonTypedResourceMetadata) WithChanges(u UpdateCommonTypedResourceMetadata) CommonTypedResourceMetadata {
	var out CommonTypedResourceMetadata
	if m != nil {
		out = *m
	}

	if u.Name.IsSet() {
		out.Name = ptr.Get(u.Name.Value)
	}
	if u.DisplayName.IsSet() {
		out.DisplayName = ptr.Get(u.DisplayName.Value)
	}
	if u.Usages.IsSet() {
		out.Usages = merge.Slice(out.Usages, u.Usages.Value, (*Usage).WithChanges, (*Usage).GetName, (*UpdateUsage).GetName)
	}
	if u.Etag.IsSet() {
		out.Etag = ptr.Get(u.Etag.Value)
	}
	if u.Description.IsSet() {
		out.Description = ptr.Get(u.Description.Value)
	}
	return out
}

// HasChanges returns true if any field has Set == true
func (m UpdateCommonTypedResourceMetadata) HasChanges() bool {
	return m.Name.Set ||
		m.DisplayName.Set ||
		m.Usages.Set ||
		m.Etag.Set ||
		m.Description.Set
}

// SetName is used in the Diff function for NamedArray
func (m *UpdateCommonTypedResourceMetadata) SetName(name string) {
	m.Name = optional.NewOptional(name)
}

func (m *CommonTypedResourceMetadata) diffName(src *CommonTypedResourceMetadata) optional.Optional[string] {
	nilDiffers := src != nil && m == nil
	return commonclient.DiffPrimitiveNonRequired(src.GetName(), m.GetName(), nilDiffers)
}

func (m *CommonTypedResourceMetadata) diffDisplayName(src *CommonTypedResourceMetadata) optional.Optional[string] {
	nilDiffers := src != nil && m == nil
	return commonclient.DiffPrimitiveNonRequired(src.GetDisplayName(), m.GetDisplayName(), nilDiffers)
}

func (m *CommonTypedResourceMetadata) diffUsages(src *CommonTypedResourceMetadata) optional.Optional[[]UpdateUsage] {
	diffFunc := func(fromItem, toItem Usage, fromNil bool) UpdateUsage {
		if fromNil {
			return toItem.Diff(nil)
		}
		return toItem.Diff(&fromItem)
	}
	value, hasChanges := commonclient.GetChangesArrayObject(src.GetUsages(), m.GetUsages(), diffFunc)
	return optional.Optional[[]UpdateUsage]{
		Value: value,
		Set:   hasChanges,
	}
}

func (m *CommonTypedResourceMetadata) diffEtag(src *CommonTypedResourceMetadata) optional.Optional[string] {
	nilDiffers := src != nil && m == nil
	return commonclient.DiffPrimitiveNonRequired(src.GetEtag(), m.GetEtag(), nilDiffers)
}

func (m *CommonTypedResourceMetadata) diffDescription(src *CommonTypedResourceMetadata) optional.Optional[string] {
	nilDiffers := src != nil && m == nil
	return commonclient.DiffPrimitiveNonRequired(src.GetDescription(), m.GetDescription(), nilDiffers)
}
