// Code generated by mwsapigen, DO NOT EDIT.

package model

// Информация о статусе реконсиляции
// Real OAPI model name: ResourceStatusReady
type ResourceStatusReadyResponse struct {
	// Состояние ресурса
	State ResourceStatusState `json:"state" yaml:"state"`
	// Описание статуса
	Message *string `json:"message,omitempty" yaml:"message,omitempty"`
}

func (m *ResourceStatusReadyResponse) GetState() ResourceStatusState {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *ResourceStatusReadyResponse) SetState(val ResourceStatusState) {
	m.State = val
}

func (m *ResourceStatusReadyResponse) GetMessage() *string {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *ResourceStatusReadyResponse) SetMessage(val *string) {
	m.Message = val
}

func (m *ResourceStatusReadyResponse) GetMessageOr(val string) string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return val
}

func (m *ResourceStatusReadyResponse) Clone() *ResourceStatusReadyResponse {
	if m == nil {
		return nil
	}

	clone := *m
	if m.Message != nil {
		cloneMessage := *m.Message
		clone.Message = &cloneMessage
	}
	return &clone
}
