// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"context"

	"go.mws.cloud/go-sdk/pkg/apimodels/ipaddress"

	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	"go.mws.cloud/go-sdk/service/resources/references/vpc"
)

// Статус IP-адреса внешнего балансировщика.
// Real OAPI model name: ResourceExternalAddressStatus
type ResourceExternalAddressStatusOptionalResponse struct {
	// Относительная ссылка на статический адрес.
	Ref vpc.ExternalAddressRef `json:"ref" yaml:"ref"`
	// Значение IP адреса.
	IpAddress ipaddress.IPAddress `json:"ipAddress" yaml:"ipAddress"`
}

func (m *ResourceExternalAddressStatusOptionalResponse) GetRef() vpc.ExternalAddressRef {
	if m != nil {
		return m.Ref
	}
	return vpc.ExternalAddressRef{}
}

func (m *ResourceExternalAddressStatusOptionalResponse) SetRef(val vpc.ExternalAddressRef) {
	m.Ref = val
}

func (m *ResourceExternalAddressStatusOptionalResponse) GetIpAddress() ipaddress.IPAddress {
	if m != nil {
		return m.IpAddress
	}
	return ipaddress.IPAddress{}
}

func (m *ResourceExternalAddressStatusOptionalResponse) SetIpAddress(val ipaddress.IPAddress) {
	m.IpAddress = val
}

func (m *ResourceExternalAddressStatusOptionalResponse) Clone() *ResourceExternalAddressStatusOptionalResponse {
	if m == nil {
		return nil
	}

	clone := *m
	clone.Ref = *m.Ref.Clone()
	clone.IpAddress = *m.IpAddress.Clone()
	return &clone
}

func (m *ResourceExternalAddressStatusOptionalResponse) Parse(ctx context.Context) error {
	if m == nil {
		return nil
	}

	if err := m.Ref.Parse(ctx); err != nil {
		return reserrors.NewPathAccumulatorError("Ref", err)
	}

	return nil
}
