// Code generated by mwsapigen, DO NOT EDIT.

package model

func ResourceStatusReadyRequestToResponse(request *ResourceStatusReadyRequest) (*ResourceStatusReadyResponse, error) {
	if request == nil {
		return nil, nil
	}
	var response ResourceStatusReadyResponse
	response.State = request.State
	response.Message = request.Message
	return &response, nil
}
