// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"fmt"

	"github.com/go-faster/jx"
	"go.mws.cloud/util-toolset/pkg/utils/consterr"

	"go.mws.cloud/go-sdk/internal/conv"
	"go.mws.cloud/go-sdk/internal/decode"
)

// Шаг увеличения таймаута
type RetryTimeoutScale string

const (
	RetryTimeoutScale_FIXED       RetryTimeoutScale = "FIXED"
	RetryTimeoutScale_LINEAR      RetryTimeoutScale = "LINEAR"
	RetryTimeoutScale_PROGRESSIVE RetryTimeoutScale = "PROGRESSIVE"
	RetryTimeoutScale_EXPONENTIAL RetryTimeoutScale = "EXPONENTIAL"

	ErrUnknownRetryTimeoutScale = consterr.Error(`unknown kind, want one of "FIXED", "LINEAR", "PROGRESSIVE", "EXPONENTIAL"`)
)

func NewRetryTimeoutScale(s string) (RetryTimeoutScale, error) {
	v := RetryTimeoutScale(s)
	if !v.IsValid() {
		return "", fmt.Errorf("%w, got %q", ErrUnknownRetryTimeoutScale, s)
	}
	return v, nil
}

func (m RetryTimeoutScale) String() string {
	return string(m)
}

func (m RetryTimeoutScale) IsValid() bool {
	switch m {
	case RetryTimeoutScale_FIXED:
		return true
	case RetryTimeoutScale_LINEAR:
		return true
	case RetryTimeoutScale_PROGRESSIVE:
		return true
	case RetryTimeoutScale_EXPONENTIAL:
		return true
	}
	return false
}

// JSON methods

func (m RetryTimeoutScale) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	if err := m.Encode(&e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (m *RetryTimeoutScale) Encode(e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.Str(string(*m))
	return nil
}

func (m *RetryTimeoutScale) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *RetryTimeoutScale) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("RetryTimeoutScale")
	}

	v, err := decode.StrBytes(d)
	if err != nil {
		return err
	}

	*m = RetryTimeoutScale(v)
	return nil
}
