// Code generated by mwsapigen, DO NOT EDIT.

package model

func UsageRequestToResponse(request *UsageRequest) (*UsageResponse, error) {
	if request == nil {
		return nil, nil
	}
	var response UsageResponse
	response.UsageType = request.UsageType
	response.Name = request.Name
	response.Resource = request.Resource
	return &response, nil
}
