// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/go-faster/jx"

	"go.mws.cloud/go-sdk/internal/conv"
	"go.mws.cloud/go-sdk/internal/decode"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
)

// Связь ресурса с другим ресурсом. В зависимости от типа связи операции над ресурсом могут быть ограничены
type Usage struct {
	// Тип связи. Помимо стандартных `own` и `use` могут быть добавлены специализированные типы для конкретных сервисов.
	UsageType string `json:"usageType" yaml:"usageType"`
	// Имя связи. Требуется для модификации коллекции.
	Name string `json:"name" yaml:"name"`
	// Ссылка на ресурс
	Resource string `json:"resource" yaml:"resource"`
}

func (m *Usage) GetUsageType() string {
	if m != nil {
		return m.UsageType
	}
	return ""
}

func (m *Usage) SetUsageType(val string) {
	m.UsageType = val
}

func (m *Usage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Usage) SetName(val string) {
	m.Name = val
}

func (m *Usage) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

func (m *Usage) SetResource(val string) {
	m.Resource = val
}

func (m *Usage) Clone() *Usage {
	if m == nil {
		return nil
	}

	clone := *m
	return &clone
}

// JSON methods

func (m Usage) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	if err := m.Encode(&e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (m *Usage) Encode(e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	if err := m.encodeFields(e); err != nil {
		return err
	}
	e.ObjEnd()
	return nil
}

func (m *Usage) encodeFields(e *jx.Encoder) error {
	e.FieldStart("usageType")
	e.Str(m.UsageType)

	e.FieldStart("name")
	e.Str(m.Name)

	e.FieldStart("resource")
	e.Str(m.Resource)
	return nil
}

func (m *Usage) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *Usage) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("Usage")
	}

	requiredFilled := map[string]bool{
		"usageType": false,
		"name":      false,
		"resource":  false,
	}
	err := d.ObjBytes(reserrors.PathAccumulatorErrorObjBytesFuncWrap(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "usageType":
			v, err := decode.Str(d)
			if err != nil {
				return err
			}

			m.UsageType = v
			requiredFilled["usageType"] = true
			return nil
		case "name":
			v, err := decode.Str(d)
			if err != nil {
				return err
			}

			m.Name = v
			requiredFilled["name"] = true
			return nil
		case "resource":
			v, err := decode.Str(d)
			if err != nil {
				return err
			}

			m.Resource = v
			requiredFilled["resource"] = true
			return nil
		default:
			return d.Skip()
		}
	}))
	if err != nil {
		return err
	}

	return conv.ValidateRequired(requiredFilled)
}
