// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/go-faster/jx"
	"go.mws.cloud/go-sdk/pkg/apimodels/units/duration"

	"go.mws.cloud/go-sdk/internal/conv"
	"go.mws.cloud/go-sdk/internal/decode"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
)

func (m UpdateWeeklyMaintenanceWindowRequest) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	if err := m.Encode(&e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (m *UpdateWeeklyMaintenanceWindowRequest) Encode(e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	if err := m.encodeFields(e); err != nil {
		return err
	}
	e.ObjEnd()
	return nil
}

func (m *UpdateWeeklyMaintenanceWindowRequest) encodeFields(e *jx.Encoder) error {
	if m.Days.IsSet() {
		e.FieldStart("days")
		e.ArrStart()
		for _, elem := range m.Days.Value {
			elem.Encode(e)
		}
		e.ArrEnd()
	}

	if m.Hour.IsSet() {
		e.FieldStart("hour")
		e.Int(m.Hour.Value)
	}

	if m.Duration.IsSet() {
		e.FieldStart("duration")
		if m.Duration.IsNull() {
			e.Null()
		} else {
			m.Duration.Value.Encode(e)
		}
	}
	return nil
}

func (m *UpdateWeeklyMaintenanceWindowRequest) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *UpdateWeeklyMaintenanceWindowRequest) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("UpdateWeeklyMaintenanceWindowRequest")
	}

	return d.ObjBytes(reserrors.PathAccumulatorErrorObjBytesFuncWrap(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "days":
			c := make([]DayOfWeek, 0)
			if err := d.Arr(reserrors.PathAccumulatorErrorAsIndexArrFuncWrap(func(d *jx.Decoder) error {
				var v DayOfWeek
				if err := v.Decode(d); err != nil {
					return err
				}
				c = append(c, v)
				return nil
			})); err != nil {
				return err
			}

			m.Days.SetTo(c)
			return nil
		case "hour":
			v, err := decode.Int(d)
			if err != nil {
				return err
			}

			m.Hour.SetTo(v)
			return nil
		case "duration":
			if d.Next() == jx.Null {
				m.Duration.SetToNull()
				return d.Null()
			}

			var v duration.Duration
			if err := v.Decode(d); err != nil {
				return err
			}

			m.Duration.SetTo(v)
			return nil
		default:
			return d.Skip()
		}
	}))
}
