// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/go-faster/jx"
	"go.mws.cloud/go-sdk/pkg/apimodels/units/duration"

	"go.mws.cloud/go-sdk/internal/conv"
	"go.mws.cloud/go-sdk/internal/decode"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
)

func (m WeeklyMaintenanceWindowResponse) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *WeeklyMaintenanceWindowResponse) Encode(e *jx.Encoder) {
	if m == nil {
		e.Null()
		return
	}
	e.ObjStart()
	m.encodeFields(e)
	e.ObjEnd()
}

func (m *WeeklyMaintenanceWindowResponse) encodeFields(e *jx.Encoder) {
	e.FieldStart("days")
	e.ArrStart()
	for _, elem := range m.Days {
		elem.Encode(e)
	}
	e.ArrEnd()

	e.FieldStart("hour")
	e.Int(m.Hour)

	if m.Duration != nil {
		e.FieldStart("duration")
		m.Duration.Encode(e)
	}
}

func (m *WeeklyMaintenanceWindowResponse) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *WeeklyMaintenanceWindowResponse) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("WeeklyMaintenanceWindowResponse")
	}

	return d.ObjBytes(reserrors.PathAccumulatorErrorObjBytesFuncWrap(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "days":
			c := make([]DayOfWeek, 0)
			if err := d.Arr(reserrors.PathAccumulatorErrorAsIndexArrFuncWrap(func(d *jx.Decoder) error {
				var v DayOfWeek
				if err := v.Decode(d); err != nil {
					return err
				}
				c = append(c, v)
				return nil
			})); err != nil {
				return err
			}

			m.Days = c
			return nil
		case "hour":
			v, err := decode.Int(d)
			if err != nil {
				return err
			}

			m.Hour = v
			return nil
		case "duration":
			var v duration.Duration
			if err := v.Decode(d); err != nil {
				return err
			}

			m.Duration = &v
			return nil
		default:
			return d.Skip()
		}
	}))
}
