// Code generated by mwsapigen, DO NOT EDIT.

package model_test

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/service/queue/model"
)

func TestConsumerGroupStateMarshalling(t *testing.T) {
	t.Parallel()
	expected := initConsumerGroupState()
	b, err := json.Marshal(expected)
	require.NoError(t, err)

	var actual model.ConsumerGroupState
	require.NoError(t, json.Unmarshal(b, &actual))
	require.Equal(t, expected, actual)
}

func initConsumerGroupState() model.ConsumerGroupState {
	var v model.ConsumerGroupState
	return v
}
