// Code generated by mwsapigen, DO NOT EDIT.

package client

import (
	"context"

	"go.mws.cloud/util-toolset/pkg/utils/ptr"

	mwserrors "go.mws.cloud/go-sdk/mws/errors"
	"go.mws.cloud/go-sdk/mws/wait"
	"go.mws.cloud/go-sdk/service/mkafka/model"
)

type KafkaSugared struct {
	impl Kafka
}

func NewKafkaSugared(impl Kafka) *KafkaSugared {
	return &KafkaSugared{
		impl: impl,
	}
}

func (x *KafkaSugared) Impl() Kafka {
	return x.impl
}

// ListKafkaClusters list Kafka clusters.
//
// Путь: GET /mkafka/v1/projects/{project}/clusters
func (x *KafkaSugared) ListKafkaClusters(ctx context.Context, request ListKafkaClustersRequest) (*model.KafkaClusterPageResponse, error) {
	resp, err := x.impl.ListKafkaClusters(ctx, request)
	if err != nil {
		return nil, err
	}

	return x.respHandlerListKafkaClusters(resp)
}

func (x *KafkaSugared) respHandlerListKafkaClusters(resp *ListKafkaClustersResponse) (*model.KafkaClusterPageResponse, error) {
	if err := resp.GetErr(); err != nil {
		return nil, err
	}

	if resp.Response200 != nil {
		return resp.Response200, nil
	}

	return nil, mwserrors.NewAPIError(resp.Code, mwserrors.Unknown, "unexpected result")
}

// StopCluster request stopping Kafka cluster.
//
// Путь: POST /mkafka/v1/projects/{project}/clusters/{cluster}:stop
func (x *KafkaSugared) StopCluster(ctx context.Context, request StopClusterRequest) (*model.KafkaClusterResponse, error) {
	resp, err := x.impl.StopCluster(ctx, request)
	if err != nil {
		return nil, err
	}

	return x.respHandlerStopCluster(resp)
}

func (x *KafkaSugared) respHandlerStopCluster(resp *StopClusterResponse) (*model.KafkaClusterResponse, error) {
	if err := resp.GetErr(); err != nil {
		return nil, err
	}

	if resp.Response200 != nil {
		return resp.Response200, nil
	}

	return nil, mwserrors.NewAPIError(resp.Code, mwserrors.Unknown, "unexpected result")
}

// StartCluster request starting Kafka cluster.
//
// Путь: POST /mkafka/v1/projects/{project}/clusters/{cluster}:start
func (x *KafkaSugared) StartCluster(ctx context.Context, request StartClusterRequest) (*model.KafkaClusterResponse, error) {
	resp, err := x.impl.StartCluster(ctx, request)
	if err != nil {
		return nil, err
	}

	return x.respHandlerStartCluster(resp)
}

func (x *KafkaSugared) respHandlerStartCluster(resp *StartClusterResponse) (*model.KafkaClusterResponse, error) {
	if err := resp.GetErr(); err != nil {
		return nil, err
	}

	if resp.Response200 != nil {
		return resp.Response200, nil
	}

	return nil, mwserrors.NewAPIError(resp.Code, mwserrors.Unknown, "unexpected result")
}

// DeleteKafkaCluster delete Kafka cluster.
//
// Путь: DELETE /mkafka/v1/projects/{project}/clusters/{cluster}
func (x *KafkaSugared) DeleteKafkaCluster(ctx context.Context, request DeleteKafkaClusterRequest, opts ...Option) error {
	config := newConfig(opts...)

	resp, err := x.impl.DeleteKafkaCluster(ctx, request)
	if err != nil {
		return err
	}

	err = x.respHandlerDeleteKafkaCluster(resp)
	if err != nil {
		return err
	}

	if !config.wait {
		return nil
	}

	return x.waitDeleteKafkaCluster(ctx, request.getKafkaClusterRequest(), config.waitOptions...)
}

func (x *KafkaSugared) respHandlerDeleteKafkaCluster(resp *DeleteKafkaClusterResponse) error {
	if err := resp.GetErr(); err != nil {
		return err
	}

	if resp.Response204 {
		return nil
	}

	return mwserrors.NewAPIError(resp.Code, mwserrors.Unknown, "unexpected result")
}

func (x *KafkaSugared) waitDeleteKafkaCluster(ctx context.Context, request GetKafkaClusterRequest, opts ...wait.WaiterOption) error {
	callback := func(ctx context.Context) (*model.KafkaClusterResponse, bool, error) {
		_, err := x.GetKafkaCluster(ctx, request)
		if mwserrors.IsAPIErrorNotFoundStatus(err) {
			return nil, true, nil
		}
		return nil, false, err
	}
	waiter := wait.NewWaiter(callback, opts...)
	_, err := waiter.Wait(ctx)
	return err
}

// GetKafkaCluster returns info about the specified cluster.
//
// Путь: GET /mkafka/v1/projects/{project}/clusters/{cluster}
func (x *KafkaSugared) GetKafkaCluster(ctx context.Context, request GetKafkaClusterRequest, opts ...Option) (*model.KafkaClusterResponse, error) {
	config := newConfig(opts...)

	resp, err := x.impl.GetKafkaCluster(ctx, request)
	if err != nil {
		return nil, err
	}

	sugaredResponse, err := x.respHandlerGetKafkaCluster(resp)
	if err != nil {
		return nil, err
	}

	if !config.wait {
		return sugaredResponse, nil
	}

	return x.waitGetKafkaCluster(ctx, request, config.waitOptions...)
}

func (x *KafkaSugared) respHandlerGetKafkaCluster(resp *GetKafkaClusterResponse) (*model.KafkaClusterResponse, error) {
	if err := resp.GetErr(); err != nil {
		return nil, err
	}

	if resp.Response200 != nil {
		return resp.Response200, nil
	}

	return nil, mwserrors.NewAPIError(resp.Code, mwserrors.Unknown, "unexpected result")
}

func (x *KafkaSugared) waitGetKafkaCluster(ctx context.Context, request GetKafkaClusterRequest, opts ...wait.WaiterOption) (*model.KafkaClusterResponse, error) {
	callback := func(ctx context.Context) (*model.KafkaClusterResponse, bool, error) {
		response, err := x.GetKafkaCluster(ctx, request)
		stop := string(ptr.Get(response.GetStatus().GetReady()).GetState()) != "PROCESSING"
		return response, stop, err
	}
	waiter := wait.NewWaiter(callback, opts...)
	return waiter.Wait(ctx)
}

// UpsertKafkaCluster upsert Kafka cluster.
//
// Путь: POST /mkafka/v1/projects/{project}/clusters/{cluster}
func (x *KafkaSugared) UpsertKafkaCluster(ctx context.Context, request UpsertKafkaClusterRequest, opts ...Option) (*model.KafkaClusterResponse, error) {
	config := newConfig(opts...)

	resp, err := x.impl.UpsertKafkaCluster(ctx, request)
	if err != nil {
		return nil, err
	}

	sugaredResponse, err := x.respHandlerUpsertKafkaCluster(resp)
	if err != nil {
		return nil, err
	}

	if !config.wait {
		return sugaredResponse, nil
	}

	return x.waitUpsertKafkaCluster(ctx, request.getKafkaClusterRequest(), config.waitOptions...)
}

func (x *KafkaSugared) respHandlerUpsertKafkaCluster(resp *UpsertKafkaClusterResponse) (*model.KafkaClusterResponse, error) {
	if err := resp.GetErr(); err != nil {
		return nil, err
	}

	if resp.Response200 != nil {
		return resp.Response200, nil
	}

	return nil, mwserrors.NewAPIError(resp.Code, mwserrors.Unknown, "unexpected result")
}

func (x *KafkaSugared) waitUpsertKafkaCluster(ctx context.Context, request GetKafkaClusterRequest, opts ...wait.WaiterOption) (*model.KafkaClusterResponse, error) {
	callback := func(ctx context.Context) (*model.KafkaClusterResponse, bool, error) {
		response, err := x.GetKafkaCluster(ctx, request)
		stop := string(ptr.Get(response.GetStatus().GetReady()).GetState()) != "PROCESSING"
		return response, stop, err
	}
	waiter := wait.NewWaiter(callback, opts...)
	return waiter.Wait(ctx)
}

// CreateKafkaCluster upsert Kafka cluster.
// Данный метод не описан в OpenAPI-спецификации, он был сгенерирован на основе операции upsert, для удобства.
//
// Путь: POST /mkafka/v1/projects/{project}/clusters/{cluster}?createOnly=true
func (x *KafkaSugared) CreateKafkaCluster(ctx context.Context, request UpsertKafkaClusterRequest, opts ...Option) (*model.KafkaClusterResponse, error) {
	config := newConfig(opts...)

	resp, err := x.impl.CreateKafkaCluster(ctx, request)
	if err != nil {
		return nil, err
	}

	sugaredResponse, err := x.respHandlerUpsertKafkaCluster(resp)
	if err != nil {
		return nil, err
	}

	if !config.wait {
		return sugaredResponse, nil
	}

	return x.waitUpsertKafkaCluster(ctx, request.getKafkaClusterRequest(), config.waitOptions...)
}

// UpdateKafkaCluster upsert Kafka cluster.
// Данный метод не описан в OpenAPI-спецификации, он был сгенерирован на основе операции upsert, для удобства.
//
// Путь: POST /mkafka/v1/projects/{project}/clusters/{cluster}?updateOnly=true
func (x *KafkaSugared) UpdateKafkaCluster(ctx context.Context, request UpdateKafkaClusterRequest, opts ...Option) (*model.KafkaClusterResponse, error) {
	config := newConfig(opts...)

	resp, err := x.impl.UpdateKafkaCluster(ctx, request)
	if err != nil {
		return nil, err
	}

	sugaredResponse, err := x.respHandlerUpsertKafkaCluster(resp)
	if err != nil {
		return nil, err
	}

	if !config.wait {
		return sugaredResponse, nil
	}

	return x.waitUpsertKafkaCluster(ctx, request.getKafkaClusterRequest(), config.waitOptions...)
}
