// Code generated by mwsapigen, DO NOT EDIT.

package model_test

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/service/certmanager/model"
)

func TestHttp01ChallengeResponseMarshalling(t *testing.T) {
	expected := initHttp01ChallengeResponse()
	b, err := json.Marshal(expected)
	require.NoError(t, err)

	var actual model.Http01ChallengeResponse
	require.NoError(t, json.Unmarshal(b, &actual))
	require.Equal(t, expected, actual)
}

func initHttp01ChallengeResponse() model.Http01ChallengeResponse {
	var v model.Http01ChallengeResponse
	return v
}
