// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/go-faster/jx"

	"go.mws.cloud/go-sdk/internal/conv"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
)

func (m UpdateCertificateSpecRequest) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	if err := m.Encode(&e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (m *UpdateCertificateSpecRequest) Encode(e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	if err := m.encodeFields(e); err != nil {
		return err
	}
	e.ObjEnd()
	return nil
}

func (m *UpdateCertificateSpecRequest) encodeFields(e *jx.Encoder) error {
	if m.SelfManaged.IsSet() {
		e.FieldStart("selfManaged")
		if m.SelfManaged.IsNull() {
			e.Null()
		} else {
			m.SelfManaged.Value.Encode(e)
		}
	}
	return nil
}

func (m *UpdateCertificateSpecRequest) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *UpdateCertificateSpecRequest) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("UpdateCertificateSpecRequest")
	}

	return d.ObjBytes(reserrors.PathAccumulatorErrorObjBytesFuncWrap(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "selfManaged":
			if d.Next() == jx.Null {
				m.SelfManaged.SetToNull()
				return d.Null()
			}

			var v UpdateSelfManagedSpecRequest
			if err := v.Decode(d); err != nil {
				return err
			}

			m.SelfManaged.SetTo(v)
			return nil
		default:
			return d.Skip()
		}
	}))
}
