// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"context"

	commonclient "go.mws.cloud/go-sdk/internal/client"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	common "go.mws.cloud/go-sdk/service/common/model"
)

// Real OAPI model name: CertificateRoleBinding
type CertificateRoleBindingOptionalResponse struct {
	Kind string `json:"kind" yaml:"kind"`
	// Набор общих для всех пользовательских объектов атрибутов. Может быть расширен атрибутами, специфичными для контейнеров.
	Metadata commonclient.OptionalNil[common.CommonTypedResourceMetadataOptionalResponse] `json:"metadata,omitempty" yaml:"metadata,omitempty"`
	Spec     common.CommonRoleBindingSpecOptionalResponse                                 `json:"spec" yaml:"spec"`
	Status   *common.CommonRoleBindingStatusResponse                                      `json:"status,omitempty" yaml:"status,omitempty"`
}

func (m *CertificateRoleBindingOptionalResponse) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *CertificateRoleBindingOptionalResponse) SetKind(val string) {
	m.Kind = val
}

func (m *CertificateRoleBindingOptionalResponse) GetMetadata() *common.CommonTypedResourceMetadataOptionalResponse {
	if m != nil && m.Metadata.IsSet() {
		return &m.Metadata.Value
	}
	return nil
}

func (m *CertificateRoleBindingOptionalResponse) GetMetadataOr(val common.CommonTypedResourceMetadataOptionalResponse) common.CommonTypedResourceMetadataOptionalResponse {
	if m != nil && m.Metadata.IsSet() {
		return m.Metadata.Value
	}
	return val
}

func (m *CertificateRoleBindingOptionalResponse) GetSpec() common.CommonRoleBindingSpecOptionalResponse {
	if m != nil {
		return m.Spec
	}
	return common.CommonRoleBindingSpecOptionalResponse{}
}

func (m *CertificateRoleBindingOptionalResponse) SetSpec(val common.CommonRoleBindingSpecOptionalResponse) {
	m.Spec = val
}

func (m *CertificateRoleBindingOptionalResponse) GetStatus() *common.CommonRoleBindingStatusResponse {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *CertificateRoleBindingOptionalResponse) SetStatus(val *common.CommonRoleBindingStatusResponse) {
	m.Status = val
}

func (m *CertificateRoleBindingOptionalResponse) GetStatusOr(val common.CommonRoleBindingStatusResponse) common.CommonRoleBindingStatusResponse {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return val
}

func (m *CertificateRoleBindingOptionalResponse) Clone() *CertificateRoleBindingOptionalResponse {
	if m == nil {
		return nil
	}

	clone := *m
	if clone.Metadata.IsSet() {
		clone.Metadata.Value = *m.Metadata.Value.Clone()
	}
	clone.Spec = *m.Spec.Clone()
	clone.Status = m.Status.Clone()
	return &clone
}

func (m *CertificateRoleBindingOptionalResponse) Parse(ctx context.Context) error {
	if m == nil {
		return nil
	}

	if m.Metadata.IsSet() {
		if err := m.Metadata.Value.Parse(ctx); err != nil {
			return reserrors.NewPathAccumulatorError("Metadata", err)
		}
	}

	if err := m.Spec.Parse(ctx); err != nil {
		return reserrors.NewPathAccumulatorError("Spec", err)
	}

	return nil
}
