// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/go-faster/jx"

	"go.mws.cloud/go-sdk/internal/conv"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
)

func (m CertificateSpecRequest) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *CertificateSpecRequest) Encode(e *jx.Encoder) {
	if m == nil {
		e.Null()
		return
	}
	e.ObjStart()
	m.encodeFields(e)
	e.ObjEnd()
}

func (m *CertificateSpecRequest) encodeFields(e *jx.Encoder) {
	if m.SelfManaged != nil {
		e.FieldStart("selfManaged")
		m.SelfManaged.Encode(e)
	}

	if m.Managed != nil {
		e.FieldStart("managed")
		m.Managed.Encode(e)
	}
}

func (m *CertificateSpecRequest) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *CertificateSpecRequest) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("CertificateSpecRequest")
	}

	return d.ObjBytes(reserrors.PathAccumulatorErrorObjBytesFuncWrap(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "selfManaged":
			if d.Next() == jx.Null {
				return d.Null()
			}

			var v SelfManagedSpecRequest
			if err := v.Decode(d); err != nil {
				return err
			}

			m.SelfManaged = &v
			return nil
		case "managed":
			if d.Next() == jx.Null {
				return d.Null()
			}

			var v CertificateManagedSpecRequest
			if err := v.Decode(d); err != nil {
				return err
			}

			m.Managed = &v
			return nil
		default:
			return d.Skip()
		}
	}))
}
