// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/go-faster/jx"

	"go.mws.cloud/go-sdk/internal/conv"
	"go.mws.cloud/go-sdk/internal/decode"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	commonmodel "go.mws.cloud/go-sdk/service/common/model"
)

// TLS/SSL-сертификат — это цифровой объект, с помощью которого веб-системы идентифицируют пользователя и устанавливают зашифрованное сетевое соединение с ним, используя протокол SSL/TLS (Secure Sockets Layer/Transport Layer Security)
// Real OAPI model name: Certificate
type CertificateOptionalResponse struct {
	Kind string `json:"kind" yaml:"kind"`
	// Набор общих для всех пользовательских объектов атрибутов. Может быть расширен атрибутами, специфичными для контейнеров.
	Metadata commonmodel.CommonTypedResourceMetadataOptionalResponse `json:"metadata" yaml:"metadata"`
	Spec     CertificateSpecOptionalResponse                         `json:"spec" yaml:"spec"`
	Status   CertificateStatusResponse                               `json:"status" yaml:"status"`
}

func (m *CertificateOptionalResponse) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *CertificateOptionalResponse) SetKind(val string) {
	m.Kind = val
}

func (m *CertificateOptionalResponse) GetMetadata() commonmodel.CommonTypedResourceMetadataOptionalResponse {
	if m != nil {
		return m.Metadata
	}
	return commonmodel.CommonTypedResourceMetadataOptionalResponse{}
}

func (m *CertificateOptionalResponse) SetMetadata(val commonmodel.CommonTypedResourceMetadataOptionalResponse) {
	m.Metadata = val
}

func (m *CertificateOptionalResponse) GetSpec() CertificateSpecOptionalResponse {
	if m != nil {
		return m.Spec
	}
	return CertificateSpecOptionalResponse{}
}

func (m *CertificateOptionalResponse) SetSpec(val CertificateSpecOptionalResponse) {
	m.Spec = val
}

func (m *CertificateOptionalResponse) GetStatus() CertificateStatusResponse {
	if m != nil {
		return m.Status
	}
	return CertificateStatusResponse{}
}

func (m *CertificateOptionalResponse) SetStatus(val CertificateStatusResponse) {
	m.Status = val
}

func (m *CertificateOptionalResponse) Clone() *CertificateOptionalResponse {
	if m == nil {
		return nil
	}

	clone := *m
	clone.Metadata = *m.Metadata.Clone()
	clone.Spec = *m.Spec.Clone()
	clone.Status = *m.Status.Clone()
	return &clone
}

// JSON methods

func (m CertificateOptionalResponse) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	if err := m.Encode(&e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (m *CertificateOptionalResponse) Encode(e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	if err := m.encodeFields(e); err != nil {
		return err
	}
	e.ObjEnd()
	return nil
}

func (m *CertificateOptionalResponse) encodeFields(e *jx.Encoder) error {
	e.FieldStart("kind")
	e.Str(m.Kind)

	e.FieldStart("metadata")
	if err := m.Metadata.Encode(e); err != nil {
		return err
	}

	e.FieldStart("spec")
	if err := m.Spec.Encode(e); err != nil {
		return err
	}

	e.FieldStart("status")
	if err := m.Status.Encode(e); err != nil {
		return err
	}
	return nil
}

func (m *CertificateOptionalResponse) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *CertificateOptionalResponse) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("CertificateOptionalResponse")
	}

	return d.ObjBytes(reserrors.PathAccumulatorErrorObjBytesFuncWrap(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "kind":
			v, err := decode.Str(d)
			if err != nil {
				return err
			}

			m.Kind = v
			return nil
		case "metadata":
			var v commonmodel.CommonTypedResourceMetadataOptionalResponse
			if err := v.Decode(d); err != nil {
				return err
			}

			m.Metadata = v
			return nil
		case "spec":
			var v CertificateSpecOptionalResponse
			if err := v.Decode(d); err != nil {
				return err
			}

			m.Spec = v
			return nil
		case "status":
			var v CertificateStatusResponse
			if err := v.Decode(d); err != nil {
				return err
			}

			m.Status = v
			return nil
		default:
			return d.Skip()
		}
	}))
}
