// Code generated by mwsapigen, DO NOT EDIT.

package client

import (
	"context"

	"go.mws.cloud/util-toolset/pkg/utils/ptr"

	mwserrors "go.mws.cloud/go-sdk/mws/errors"
	"go.mws.cloud/go-sdk/mws/wait"
	"go.mws.cloud/go-sdk/service/mclickhouse/model"
)

type ClickhouseClusterBackupSugared struct {
	impl ClickhouseClusterBackup
}

func NewClickhouseClusterBackupSugared(impl ClickhouseClusterBackup) *ClickhouseClusterBackupSugared {
	return &ClickhouseClusterBackupSugared{
		impl: impl,
	}
}

func (x *ClickhouseClusterBackupSugared) Impl() ClickhouseClusterBackup {
	return x.impl
}

// ListClickhouseClusterBackups list Clickhouse cluster backups.
//
// Путь: GET /mclickhouse/v1/projects/{project}/clusters/{cluster}/backups
func (x *ClickhouseClusterBackupSugared) ListClickhouseClusterBackups(ctx context.Context, request ListClickhouseClusterBackupsRequest) (*model.ClickhouseBackupPageOptionalResponse, error) {
	resp, err := x.impl.ListClickhouseClusterBackups(ctx, request)
	if err != nil {
		return nil, err
	}

	return x.respHandlerListClickhouseClusterBackups(resp)
}

func (x *ClickhouseClusterBackupSugared) respHandlerListClickhouseClusterBackups(resp *ListClickhouseClusterBackupsResponse) (*model.ClickhouseBackupPageOptionalResponse, error) {
	if err := resp.GetErr(); err != nil {
		return nil, err
	}

	if resp.Response200 != nil {
		return resp.Response200, nil
	}

	return nil, mwserrors.NewAPIError(resp.Code, mwserrors.Unknown, "unexpected result")
}

// DeleteClickhouseClusterBackup delete Clickhouse cluster backup.
//
// Путь: DELETE /mclickhouse/v1/projects/{project}/clusters/{cluster}/backups/{backup}
func (x *ClickhouseClusterBackupSugared) DeleteClickhouseClusterBackup(ctx context.Context, request DeleteClickhouseClusterBackupRequest, opts ...Option) error {
	config := newConfig(opts...)

	resp, err := x.impl.DeleteClickhouseClusterBackup(ctx, request)
	if err != nil {
		return err
	}

	err = x.respHandlerDeleteClickhouseClusterBackup(resp)
	if err != nil {
		return err
	}

	if !config.wait {
		return nil
	}

	return x.waitDeleteClickhouseClusterBackup(ctx, request.getClickhouseClusterBackupRequest(), config.waitOptions...)
}

func (x *ClickhouseClusterBackupSugared) respHandlerDeleteClickhouseClusterBackup(resp *DeleteClickhouseClusterBackupResponse) error {
	if err := resp.GetErr(); err != nil {
		return err
	}

	if resp.Response204 {
		return nil
	}

	return mwserrors.NewAPIError(resp.Code, mwserrors.Unknown, "unexpected result")
}

func (x *ClickhouseClusterBackupSugared) waitDeleteClickhouseClusterBackup(ctx context.Context, request GetClickhouseClusterBackupRequest, opts ...wait.WaiterOption) error {
	callback := func(ctx context.Context) (*model.ClickhouseBackupOptionalResponse, bool, error) {
		_, err := x.GetClickhouseClusterBackup(ctx, request)
		if mwserrors.IsAPIErrorNotFoundStatus(err) {
			return nil, true, nil
		}
		return nil, false, err
	}
	waiter := wait.NewWaiter(callback, opts...)
	_, err := waiter.Wait(ctx)
	return err
}

// GetClickhouseClusterBackup returns info about the specified cluster backup.
//
// Путь: GET /mclickhouse/v1/projects/{project}/clusters/{cluster}/backups/{backup}
func (x *ClickhouseClusterBackupSugared) GetClickhouseClusterBackup(ctx context.Context, request GetClickhouseClusterBackupRequest, opts ...Option) (*model.ClickhouseBackupOptionalResponse, error) {
	config := newConfig(opts...)

	resp, err := x.impl.GetClickhouseClusterBackup(ctx, request)
	if err != nil {
		return nil, err
	}

	sugaredResponse, err := x.respHandlerGetClickhouseClusterBackup(resp)
	if err != nil {
		return nil, err
	}

	if !config.wait {
		return sugaredResponse, nil
	}

	return x.waitGetClickhouseClusterBackup(ctx, request, config.waitOptions...)
}

func (x *ClickhouseClusterBackupSugared) respHandlerGetClickhouseClusterBackup(resp *GetClickhouseClusterBackupResponse) (*model.ClickhouseBackupOptionalResponse, error) {
	if err := resp.GetErr(); err != nil {
		return nil, err
	}

	if resp.Response200 != nil {
		return resp.Response200, nil
	}

	return nil, mwserrors.NewAPIError(resp.Code, mwserrors.Unknown, "unexpected result")
}

func (x *ClickhouseClusterBackupSugared) waitGetClickhouseClusterBackup(ctx context.Context, request GetClickhouseClusterBackupRequest, opts ...wait.WaiterOption) (*model.ClickhouseBackupOptionalResponse, error) {
	callback := func(ctx context.Context) (*model.ClickhouseBackupOptionalResponse, bool, error) {
		response, err := x.GetClickhouseClusterBackup(ctx, request)
		stop := string(ptr.Get(response.GetStatus().GetReady()).GetState()) != "PROCESSING"
		return response, stop, err
	}
	waiter := wait.NewWaiter(callback, opts...)
	return waiter.Wait(ctx)
}

// UpsertClickhouseClusterBackup upsert Clickhouse cluster backup.
//
// Путь: POST /mclickhouse/v1/projects/{project}/clusters/{cluster}/backups/{backup}
func (x *ClickhouseClusterBackupSugared) UpsertClickhouseClusterBackup(ctx context.Context, request UpsertClickhouseClusterBackupRequest, opts ...Option) (*model.ClickhouseBackupOptionalResponse, error) {
	config := newConfig(opts...)

	resp, err := x.impl.UpsertClickhouseClusterBackup(ctx, request)
	if err != nil {
		return nil, err
	}

	sugaredResponse, err := x.respHandlerUpsertClickhouseClusterBackup(resp)
	if err != nil {
		return nil, err
	}

	if !config.wait {
		return sugaredResponse, nil
	}

	return x.waitUpsertClickhouseClusterBackup(ctx, request.getClickhouseClusterBackupRequest(), config.waitOptions...)
}

func (x *ClickhouseClusterBackupSugared) respHandlerUpsertClickhouseClusterBackup(resp *UpsertClickhouseClusterBackupResponse) (*model.ClickhouseBackupOptionalResponse, error) {
	if err := resp.GetErr(); err != nil {
		return nil, err
	}

	if resp.Response200 != nil {
		return resp.Response200, nil
	}

	return nil, mwserrors.NewAPIError(resp.Code, mwserrors.Unknown, "unexpected result")
}

func (x *ClickhouseClusterBackupSugared) waitUpsertClickhouseClusterBackup(ctx context.Context, request GetClickhouseClusterBackupRequest, opts ...wait.WaiterOption) (*model.ClickhouseBackupOptionalResponse, error) {
	callback := func(ctx context.Context) (*model.ClickhouseBackupOptionalResponse, bool, error) {
		response, err := x.GetClickhouseClusterBackup(ctx, request)
		stop := string(ptr.Get(response.GetStatus().GetReady()).GetState()) != "PROCESSING"
		return response, stop, err
	}
	waiter := wait.NewWaiter(callback, opts...)
	return waiter.Wait(ctx)
}

// CreateClickhouseClusterBackup upsert Clickhouse cluster backup.
// Данный метод не описан в OpenAPI-спецификации, он был сгенерирован на основе операции upsert, для удобства.
//
// Путь: POST /mclickhouse/v1/projects/{project}/clusters/{cluster}/backups/{backup}?createOnly=true
func (x *ClickhouseClusterBackupSugared) CreateClickhouseClusterBackup(ctx context.Context, request UpsertClickhouseClusterBackupRequest, opts ...Option) (*model.ClickhouseBackupOptionalResponse, error) {
	config := newConfig(opts...)

	resp, err := x.impl.CreateClickhouseClusterBackup(ctx, request)
	if err != nil {
		return nil, err
	}

	sugaredResponse, err := x.respHandlerUpsertClickhouseClusterBackup(resp)
	if err != nil {
		return nil, err
	}

	if !config.wait {
		return sugaredResponse, nil
	}

	return x.waitUpsertClickhouseClusterBackup(ctx, request.getClickhouseClusterBackupRequest(), config.waitOptions...)
}

// UpdateClickhouseClusterBackup upsert Clickhouse cluster backup.
// Данный метод не описан в OpenAPI-спецификации, он был сгенерирован на основе операции upsert, для удобства.
//
// Путь: POST /mclickhouse/v1/projects/{project}/clusters/{cluster}/backups/{backup}?updateOnly=true
func (x *ClickhouseClusterBackupSugared) UpdateClickhouseClusterBackup(ctx context.Context, request UpdateClickhouseClusterBackupRequest, opts ...Option) (*model.ClickhouseBackupOptionalResponse, error) {
	config := newConfig(opts...)

	resp, err := x.impl.UpdateClickhouseClusterBackup(ctx, request)
	if err != nil {
		return nil, err
	}

	sugaredResponse, err := x.respHandlerUpsertClickhouseClusterBackup(resp)
	if err != nil {
		return nil, err
	}

	if !config.wait {
		return sugaredResponse, nil
	}

	return x.waitUpsertClickhouseClusterBackup(ctx, request.getClickhouseClusterBackupRequest(), config.waitOptions...)
}
