// Code generated by mwsapigen, DO NOT EDIT.

package mock_client

import (
	"context"
	"reflect"

	"go.uber.org/mock/gomock"

	"go.mws.cloud/go-sdk/service/vpc/client"
)

// MockSubnet is a mock of Subnet interface.
type MockSubnet struct {
	ctrl     *gomock.Controller
	recorder *MockSubnetMockRecorder
}

// MockSubnetMockRecorder is the mock recorder for MockSubnet.
type MockSubnetMockRecorder struct {
	mock *MockSubnet
}

// NewMockSubnet creates a new mock instance.
func NewMockSubnet(ctrl *gomock.Controller) *MockSubnet {
	mock := &MockSubnet{ctrl: ctrl}
	mock.recorder = &MockSubnetMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubnet) EXPECT() *MockSubnetMockRecorder {
	return m.recorder
}

// CreateSubnet mocks base method.
func (m *MockSubnet) CreateSubnet(arg0 context.Context, arg1 client.UpsertSubnetRequest) (*client.UpsertSubnetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubnet", arg0, arg1)
	ret0, _ := ret[0].(*client.UpsertSubnetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSubnet indicates an expected call of CreateSubnet.
func (mr *MockSubnetMockRecorder) CreateSubnet(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubnet", reflect.TypeOf((*MockSubnet)(nil).CreateSubnet), arg0, arg1)
}

// DeleteSubnet mocks base method.
func (m *MockSubnet) DeleteSubnet(arg0 context.Context, arg1 client.DeleteSubnetRequest) (*client.DeleteSubnetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSubnet", arg0, arg1)
	ret0, _ := ret[0].(*client.DeleteSubnetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteSubnet indicates an expected call of DeleteSubnet.
func (mr *MockSubnetMockRecorder) DeleteSubnet(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSubnet", reflect.TypeOf((*MockSubnet)(nil).DeleteSubnet), arg0, arg1)
}

// GetSubnet mocks base method.
func (m *MockSubnet) GetSubnet(arg0 context.Context, arg1 client.GetSubnetRequest) (*client.GetSubnetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubnet", arg0, arg1)
	ret0, _ := ret[0].(*client.GetSubnetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubnet indicates an expected call of GetSubnet.
func (mr *MockSubnetMockRecorder) GetSubnet(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubnet", reflect.TypeOf((*MockSubnet)(nil).GetSubnet), arg0, arg1)
}

// ListSubnets mocks base method.
func (m *MockSubnet) ListSubnets(arg0 context.Context, arg1 client.ListSubnetsRequest) (*client.ListSubnetsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSubnets", arg0, arg1)
	ret0, _ := ret[0].(*client.ListSubnetsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSubnets indicates an expected call of ListSubnets.
func (mr *MockSubnetMockRecorder) ListSubnets(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSubnets", reflect.TypeOf((*MockSubnet)(nil).ListSubnets), arg0, arg1)
}

// UpdateSubnet mocks base method.
func (m *MockSubnet) UpdateSubnet(arg0 context.Context, arg1 client.UpdateSubnetRequest) (*client.UpsertSubnetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubnet", arg0, arg1)
	ret0, _ := ret[0].(*client.UpsertSubnetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSubnet indicates an expected call of UpdateSubnet.
func (mr *MockSubnetMockRecorder) UpdateSubnet(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubnet", reflect.TypeOf((*MockSubnet)(nil).UpdateSubnet), arg0, arg1)
}

// UpsertSubnet mocks base method.
func (m *MockSubnet) UpsertSubnet(arg0 context.Context, arg1 client.UpsertSubnetRequest) (*client.UpsertSubnetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertSubnet", arg0, arg1)
	ret0, _ := ret[0].(*client.UpsertSubnetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertSubnet indicates an expected call of UpsertSubnet.
func (mr *MockSubnetMockRecorder) UpsertSubnet(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertSubnet", reflect.TypeOf((*MockSubnet)(nil).UpsertSubnet), arg0, arg1)
}
