// Code generated by mwsapigen, DO NOT EDIT.

package model_test

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/require"

	common "go.mws.cloud/go-sdk/service/common/model"
	"go.mws.cloud/go-sdk/service/compute/model"
)

func TestDiskStatusResponseMarshalling(t *testing.T) {
	expected := initDiskStatusResponse()
	b, err := json.Marshal(expected)
	require.NoError(t, err)

	var actual model.DiskStatusResponse
	require.NoError(t, json.Unmarshal(b, &actual))
	require.Equal(t, expected, actual)
}

func initDiskStatusResponse() model.DiskStatusResponse {
	var v model.DiskStatusResponse
	v.LinkedVms = make([]common.LinkedVmInfoResponse, 0)
	return v
}
