// Code generated by mwsapigen, DO NOT EDIT.

package model_test

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/service/compute/model"
)

func TestOsTypeMarshalling(t *testing.T) {
	t.Parallel()
	expected := initOsType()
	b, err := json.Marshal(expected)
	require.NoError(t, err)

	var actual model.OsType
	require.NoError(t, json.Unmarshal(b, &actual))
	require.Equal(t, expected, actual)
}

func initOsType() model.OsType {
	var v model.OsType
	return v
}
