// Code generated by mwsapigen, DO NOT EDIT.

package model_test

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/service/vpc/model"
)

func TestListRoutesResponseOptionalResponseMarshalling(t *testing.T) {
	t.Parallel()
	expected := initListRoutesResponseOptionalResponse()
	b, err := json.Marshal(expected)
	require.NoError(t, err)

	var actual model.ListRoutesResponseOptionalResponse
	require.NoError(t, json.Unmarshal(b, &actual))
	require.Equal(t, expected, actual)
}

func initListRoutesResponseOptionalResponse() model.ListRoutesResponseOptionalResponse {
	var v model.ListRoutesResponseOptionalResponse
	v.Items = make([]model.RouteOptionalResponse, 0)
	return v
}
