// Code generated by mwsapigen, DO NOT EDIT.

package model_test

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/service/vpc/model"
)

func TestNetworkRequestMarshalling(t *testing.T) {
	t.Parallel()
	expected := initNetworkRequest()
	b, err := json.Marshal(expected)
	require.NoError(t, err)

	var actual model.NetworkRequest
	require.NoError(t, json.Unmarshal(b, &actual))
	require.Equal(t, expected, actual)
}

func initNetworkRequest() model.NetworkRequest {
	var v model.NetworkRequest
	return v
}
