// Code generated by mwsapigen, DO NOT EDIT.

package model_test

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/service/vpc/model"
)

func TestNlbRuleOptionalResponseMarshalling(t *testing.T) {
	t.Parallel()
	expected := initNlbRuleOptionalResponse()
	b, err := json.Marshal(expected)
	require.NoError(t, err)

	var actual model.NlbRuleOptionalResponse
	require.NoError(t, json.Unmarshal(b, &actual))
	require.Equal(t, expected, actual)
}

func initNlbRuleOptionalResponse() model.NlbRuleOptionalResponse {
	var v model.NlbRuleOptionalResponse
	v.TargetAddressGroups = make([]model.VpcAddressGroupSpecOrRefOptionalResponse, 0)
	return v
}
