// Code generated by mwsapigen, DO NOT EDIT.

package model_test

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/require"
	"go.mws.cloud/go-sdk/pkg/apimodels/ipaddress"

	"go.mws.cloud/go-sdk/service/vpc/model"
)

func TestResourceExternalAddressStatusResponseMarshalling(t *testing.T) {
	t.Parallel()
	expected := initResourceExternalAddressStatusResponse()
	b, err := json.Marshal(expected)
	require.NoError(t, err)

	var actual model.ResourceExternalAddressStatusResponse
	require.NoError(t, json.Unmarshal(b, &actual))
	require.Equal(t, expected, actual)
}

func initResourceExternalAddressStatusResponse() model.ResourceExternalAddressStatusResponse {
	var v model.ResourceExternalAddressStatusResponse
	v.IpAddress = ipaddress.MustParseIPAddressString("192.168.1.1")
	return v
}
