// Code generated by mwsapigen, DO NOT EDIT.

package model

// Работоспособность кластера
//   - `ALIVE`    - Полностью работоспособен
//   - `DEGRADED` - Деградирует (некоторые, но не все, экземпляры неработоспособны)
//   - `FAILED`   - Неработоспособен
//   - `UNKNOWN`  - Не удаётся определить состояние (на этапе создания)
type ClusterHealth string

const (
	ClusterHealth_ALIVE    ClusterHealth = "ALIVE"
	ClusterHealth_DEGRADED ClusterHealth = "DEGRADED"
	ClusterHealth_FAILED   ClusterHealth = "FAILED"
	ClusterHealth_UNKNOWN  ClusterHealth = "UNKNOWN"
)

func (m ClusterHealth) String() string {
	return string(m)
}
