// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"context"

	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	"go.mws.cloud/go-sdk/service/resources/references/compute"
)

// Параметры виртуальной машины, где будет работать KRaft контроллер Кафки.
// Real OAPI model name: KafkaControllerInstanceSpec
type KafkaControllerInstanceSpecResponse struct {
	// Размещать контроллеры на тех же виртуальных машинах, что и брокеры
	CombinedWithBroker *bool `json:"combinedWithBroker,omitempty" yaml:"combinedWithBroker,omitempty"`
	// Тип виртуальной машины, описывающий ресурсы (vCPU, memory).
	VmType *compute.VmTypeRef `json:"vmType,omitempty" yaml:"vmType,omitempty"`
	// Параметры диска с данными на узле кластера.
	Disk *KafkaDataDiskSpecResponse `json:"disk,omitempty" yaml:"disk,omitempty"`
	// Параметры размещения контроллеров по зонам.
	Allocation []KafkaAllocationResponse `json:"allocation,omitempty" yaml:"allocation,omitempty"`
}

func (m *KafkaControllerInstanceSpecResponse) GetCombinedWithBroker() *bool {
	if m != nil {
		return m.CombinedWithBroker
	}
	return nil
}

func (m *KafkaControllerInstanceSpecResponse) SetCombinedWithBroker(val *bool) {
	m.CombinedWithBroker = val
}

func (m *KafkaControllerInstanceSpecResponse) GetCombinedWithBrokerOr(val bool) bool {
	if m != nil && m.CombinedWithBroker != nil {
		return *m.CombinedWithBroker
	}
	return val
}

func (m *KafkaControllerInstanceSpecResponse) GetVmType() *compute.VmTypeRef {
	if m != nil {
		return m.VmType
	}
	return nil
}

func (m *KafkaControllerInstanceSpecResponse) SetVmType(val *compute.VmTypeRef) {
	m.VmType = val
}

func (m *KafkaControllerInstanceSpecResponse) GetVmTypeOr(val compute.VmTypeRef) compute.VmTypeRef {
	if m != nil && m.VmType != nil {
		return *m.VmType
	}
	return val
}

func (m *KafkaControllerInstanceSpecResponse) GetDisk() *KafkaDataDiskSpecResponse {
	if m != nil {
		return m.Disk
	}
	return nil
}

func (m *KafkaControllerInstanceSpecResponse) SetDisk(val *KafkaDataDiskSpecResponse) {
	m.Disk = val
}

func (m *KafkaControllerInstanceSpecResponse) GetDiskOr(val KafkaDataDiskSpecResponse) KafkaDataDiskSpecResponse {
	if m != nil && m.Disk != nil {
		return *m.Disk
	}
	return val
}

func (m *KafkaControllerInstanceSpecResponse) GetAllocation() []KafkaAllocationResponse {
	if m != nil {
		return m.Allocation
	}
	return nil
}

func (m *KafkaControllerInstanceSpecResponse) SetAllocation(val []KafkaAllocationResponse) {
	m.Allocation = val
}

func (m *KafkaControllerInstanceSpecResponse) GetAllocationOr(val []KafkaAllocationResponse) []KafkaAllocationResponse {
	if m != nil && m.Allocation != nil {
		return m.Allocation
	}
	return val
}

func (m *KafkaControllerInstanceSpecResponse) Clone() *KafkaControllerInstanceSpecResponse {
	if m == nil {
		return nil
	}

	clone := *m
	if m.CombinedWithBroker != nil {
		cloneCombinedWithBroker := *m.CombinedWithBroker
		clone.CombinedWithBroker = &cloneCombinedWithBroker
	}
	clone.VmType = m.VmType.Clone()
	clone.Disk = m.Disk.Clone()
	if m.Allocation != nil {
		clone.Allocation = make([]KafkaAllocationResponse, len(m.Allocation))
		for i, v := range m.Allocation {
			clone.Allocation[i] = *v.Clone()
		}
	}
	return &clone
}

func (m *KafkaControllerInstanceSpecResponse) Parse(ctx context.Context) error {
	if m == nil {
		return nil
	}

	if err := m.VmType.Parse(ctx); err != nil {
		return reserrors.NewPathAccumulatorError("VmType", err)
	}

	return nil
}
