// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/go-faster/jx"

	"go.mws.cloud/go-sdk/internal/conv"
	"go.mws.cloud/go-sdk/internal/decode"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	commonmodel "go.mws.cloud/go-sdk/service/common/model"
)

// Real OAPI model name: KafkaConnector
type KafkaConnectorRequest struct {
	Metadata *KafkaConnectorMetadataRequest `json:"metadata,omitempty" yaml:"metadata,omitempty"`
	// Параметры коннектора.
	Spec KafkaConnectorSpecRequest `json:"spec" yaml:"spec"`
}

func (m *KafkaConnectorRequest) GetMetadata() *KafkaConnectorMetadataRequest {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *KafkaConnectorRequest) SetMetadata(val *KafkaConnectorMetadataRequest) {
	m.Metadata = val
}

func (m *KafkaConnectorRequest) GetMetadataOr(val KafkaConnectorMetadataRequest) KafkaConnectorMetadataRequest {
	if m != nil && m.Metadata != nil {
		return *m.Metadata
	}
	return val
}

func (m *KafkaConnectorRequest) GetSpec() KafkaConnectorSpecRequest {
	if m != nil {
		return m.Spec
	}
	return KafkaConnectorSpecRequest{}
}

func (m *KafkaConnectorRequest) SetSpec(val KafkaConnectorSpecRequest) {
	m.Spec = val
}

func (m *KafkaConnectorRequest) Clone() *KafkaConnectorRequest {
	if m == nil {
		return nil
	}

	clone := *m
	clone.Metadata = m.Metadata.Clone()
	clone.Spec = *m.Spec.Clone()
	return &clone
}

// Представление поля Metadata анонимного типа структуры KafkaConnector
// Real OAPI model name: KafkaConnectorMetadata
type KafkaConnectorMetadataRequest struct {
	commonmodel.TypedResourceMetadataRequest `yaml:"-,inline"`
}

func (m *KafkaConnectorMetadataRequest) GetDisplayName() *string {
	if m != nil {
		return m.TypedResourceMetadataRequest.GetDisplayName()
	}
	return nil
}

func (m *KafkaConnectorMetadataRequest) GetDisplayNameOr(val string) string {
	if m != nil {
		return m.TypedResourceMetadataRequest.GetDisplayNameOr(val)
	}
	return val
}

func (m *KafkaConnectorMetadataRequest) GetUsages() []commonmodel.TypedUsageRequest {
	if m != nil {
		return m.TypedResourceMetadataRequest.GetUsages()
	}
	return nil
}

func (m *KafkaConnectorMetadataRequest) GetUsagesOr(val []commonmodel.TypedUsageRequest) []commonmodel.TypedUsageRequest {
	if m != nil {
		return m.TypedResourceMetadataRequest.GetUsagesOr(val)
	}
	return val
}

func (m *KafkaConnectorMetadataRequest) GetEtag() *string {
	if m != nil {
		return m.TypedResourceMetadataRequest.GetEtag()
	}
	return nil
}

func (m *KafkaConnectorMetadataRequest) GetEtagOr(val string) string {
	if m != nil {
		return m.TypedResourceMetadataRequest.GetEtagOr(val)
	}
	return val
}

func (m *KafkaConnectorMetadataRequest) GetDescription() *string {
	if m != nil {
		return m.TypedResourceMetadataRequest.GetDescription()
	}
	return nil
}

func (m *KafkaConnectorMetadataRequest) GetDescriptionOr(val string) string {
	if m != nil {
		return m.TypedResourceMetadataRequest.GetDescriptionOr(val)
	}
	return val
}

func (m *KafkaConnectorMetadataRequest) Clone() *KafkaConnectorMetadataRequest {
	if m == nil {
		return nil
	}

	clone := *m
	clone.TypedResourceMetadataRequest = *m.TypedResourceMetadataRequest.Clone()

	return &clone
}

// JSON methods

func (m KafkaConnectorRequest) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	if err := m.Encode(&e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (m *KafkaConnectorRequest) Encode(e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	if err := m.encodeFields(e); err != nil {
		return err
	}
	e.ObjEnd()
	return nil
}

func (m *KafkaConnectorRequest) encodeFields(e *jx.Encoder) error {
	if m.Metadata != nil {
		e.FieldStart("metadata")
		if err := m.Metadata.Encode(e); err != nil {
			return err
		}
	}

	e.FieldStart("spec")
	if err := m.Spec.Encode(e); err != nil {
		return err
	}
	return nil
}

func (m *KafkaConnectorRequest) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *KafkaConnectorRequest) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("KafkaConnectorRequest")
	}

	requiredFilled := map[string]bool{
		"spec": false,
	}
	err := d.ObjBytes(reserrors.PathAccumulatorErrorObjBytesFuncWrap(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "metadata":
			if d.Next() == jx.Null {
				return d.Null()
			}

			var v KafkaConnectorMetadataRequest
			if err := v.Decode(d); err != nil {
				return err
			}

			m.Metadata = &v
			return nil
		case "spec":
			var v KafkaConnectorSpecRequest
			if err := v.Decode(d); err != nil {
				return err
			}

			m.Spec = v
			requiredFilled["spec"] = true
			return nil
		default:
			return d.Skip()
		}
	}))
	if err != nil {
		return err
	}

	return conv.ValidateRequired(requiredFilled)
}

func (m KafkaConnectorMetadataRequest) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	if err := m.Encode(&e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (m *KafkaConnectorMetadataRequest) Encode(e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	if err := m.encodeFields(e); err != nil {
		return err
	}
	e.ObjEnd()
	return nil
}

func (m *KafkaConnectorMetadataRequest) encodeFields(e *jx.Encoder) error {
	if m.DisplayName != nil {
		e.FieldStart("displayName")
		e.Str(*m.DisplayName)
	}

	if m.Usages != nil {
		e.FieldStart("usages")
		e.ArrStart()
		for _, elem := range m.Usages {
			if err := elem.Encode(e); err != nil {
				return err
			}
		}
		e.ArrEnd()
	}

	if m.Etag != nil {
		e.FieldStart("etag")
		e.Str(*m.Etag)
	}

	if m.Description != nil {
		e.FieldStart("description")
		e.Str(*m.Description)
	}
	return nil
}

func (m *KafkaConnectorMetadataRequest) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *KafkaConnectorMetadataRequest) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("KafkaConnectorMetadataRequest")
	}

	return d.ObjBytes(reserrors.PathAccumulatorErrorObjBytesFuncWrap(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "displayName":
			v, err := decode.Str(d)
			if err != nil {
				return err
			}

			m.DisplayName = &v
			return nil
		case "usages":
			c := make([]commonmodel.TypedUsageRequest, 0)
			if err := d.Arr(reserrors.PathAccumulatorErrorAsIndexArrFuncWrap(func(d *jx.Decoder) error {
				var v commonmodel.TypedUsageRequest
				if err := v.Decode(d); err != nil {
					return err
				}
				c = append(c, v)
				return nil
			})); err != nil {
				return err
			}

			m.Usages = c
			return nil
		case "etag":
			v, err := decode.Str(d)
			if err != nil {
				return err
			}

			m.Etag = &v
			return nil
		case "description":
			v, err := decode.Str(d)
			if err != nil {
				return err
			}

			m.Description = &v
			return nil
		default:
			return d.Skip()
		}
	}))
}

// Defaults

func (m *KafkaConnectorRequest) WithDefaults() KafkaConnectorRequest {
	var out KafkaConnectorRequest
	if m != nil {
		out = *m
	}

	out.Spec = out.Spec.WithDefaults()
	return out
}
