// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"context"

	"go.mws.cloud/go-sdk/pkg/apimodels/ipaddress"

	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	"go.mws.cloud/go-sdk/service/resources/references/vpc"
)

// Описание адреса пользовательской сети, назначенного брокеру.
// Real OAPI model name: KafkaEndpointBrokerAddressStatus
type KafkaEndpointBrokerAddressStatusResponse struct {
	// Идентификатор адреса.
	Ref *vpc.AddressRef `json:"ref,omitempty" yaml:"ref,omitempty"`
	// Подсеть, в которой выделен адрес.
	Subnet *vpc.SubnetRef `json:"subnet,omitempty" yaml:"subnet,omitempty"`
	// Выделенный адрес.
	IpAddress *ipaddress.IPAddress `json:"ipAddress,omitempty" yaml:"ipAddress,omitempty"`
	// Доменные имена.
	Dns []KafkaEndpointBrokerAddressDnsStatusResponse `json:"dns,omitempty" yaml:"dns,omitempty"`
}

func (m *KafkaEndpointBrokerAddressStatusResponse) GetRef() *vpc.AddressRef {
	if m != nil {
		return m.Ref
	}
	return nil
}

func (m *KafkaEndpointBrokerAddressStatusResponse) SetRef(val *vpc.AddressRef) {
	m.Ref = val
}

func (m *KafkaEndpointBrokerAddressStatusResponse) GetRefOr(val vpc.AddressRef) vpc.AddressRef {
	if m != nil && m.Ref != nil {
		return *m.Ref
	}
	return val
}

func (m *KafkaEndpointBrokerAddressStatusResponse) GetSubnet() *vpc.SubnetRef {
	if m != nil {
		return m.Subnet
	}
	return nil
}

func (m *KafkaEndpointBrokerAddressStatusResponse) SetSubnet(val *vpc.SubnetRef) {
	m.Subnet = val
}

func (m *KafkaEndpointBrokerAddressStatusResponse) GetSubnetOr(val vpc.SubnetRef) vpc.SubnetRef {
	if m != nil && m.Subnet != nil {
		return *m.Subnet
	}
	return val
}

func (m *KafkaEndpointBrokerAddressStatusResponse) GetIpAddress() *ipaddress.IPAddress {
	if m != nil {
		return m.IpAddress
	}
	return nil
}

func (m *KafkaEndpointBrokerAddressStatusResponse) SetIpAddress(val *ipaddress.IPAddress) {
	m.IpAddress = val
}

func (m *KafkaEndpointBrokerAddressStatusResponse) GetIpAddressOr(val ipaddress.IPAddress) ipaddress.IPAddress {
	if m != nil && m.IpAddress != nil {
		return *m.IpAddress
	}
	return val
}

func (m *KafkaEndpointBrokerAddressStatusResponse) GetDns() []KafkaEndpointBrokerAddressDnsStatusResponse {
	if m != nil {
		return m.Dns
	}
	return nil
}

func (m *KafkaEndpointBrokerAddressStatusResponse) SetDns(val []KafkaEndpointBrokerAddressDnsStatusResponse) {
	m.Dns = val
}

func (m *KafkaEndpointBrokerAddressStatusResponse) GetDnsOr(val []KafkaEndpointBrokerAddressDnsStatusResponse) []KafkaEndpointBrokerAddressDnsStatusResponse {
	if m != nil && m.Dns != nil {
		return m.Dns
	}
	return val
}

func (m *KafkaEndpointBrokerAddressStatusResponse) Clone() *KafkaEndpointBrokerAddressStatusResponse {
	if m == nil {
		return nil
	}

	clone := *m
	clone.Ref = m.Ref.Clone()
	clone.Subnet = m.Subnet.Clone()
	clone.IpAddress = m.IpAddress.Clone()
	if m.Dns != nil {
		clone.Dns = make([]KafkaEndpointBrokerAddressDnsStatusResponse, len(m.Dns))
		for i, v := range m.Dns {
			clone.Dns[i] = *v.Clone()
		}
	}
	return &clone
}

func (m *KafkaEndpointBrokerAddressStatusResponse) Parse(ctx context.Context) error {
	if m == nil {
		return nil
	}

	if err := m.Ref.Parse(ctx); err != nil {
		return reserrors.NewPathAccumulatorError("Ref", err)
	}

	if err := m.Subnet.Parse(ctx); err != nil {
		return reserrors.NewPathAccumulatorError("Subnet", err)
	}

	return nil
}
