// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/go-faster/jx"

	"go.mws.cloud/go-sdk/internal/conv"
	"go.mws.cloud/go-sdk/internal/decode"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
)

func (m KafkaEndpointExternalAccessesResponse) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	if err := m.Encode(&e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (m *KafkaEndpointExternalAccessesResponse) Encode(e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	if err := m.encodeFields(e); err != nil {
		return err
	}
	e.ObjEnd()
	return nil
}

func (m *KafkaEndpointExternalAccessesResponse) encodeFields(e *jx.Encoder) error {
	e.FieldStart("allowed")
	e.Bool(m.Allowed)

	if m.BrokerAddresses != nil {
		e.FieldStart("brokerAddresses")
		e.ArrStart()
		for _, elem := range m.BrokerAddresses {
			elem.Encode(e)
		}
		e.ArrEnd()
	}
	return nil
}

func (m *KafkaEndpointExternalAccessesResponse) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *KafkaEndpointExternalAccessesResponse) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("KafkaEndpointExternalAccessesResponse")
	}

	return d.ObjBytes(reserrors.PathAccumulatorErrorObjBytesFuncWrap(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "allowed":
			v, err := decode.Bool(d)
			if err != nil {
				return err
			}

			m.Allowed = v
			return nil
		case "brokerAddresses":
			c := make([]KafkaEndpointExternalAddressSpecOrRefResponse, 0)
			if err := d.Arr(reserrors.PathAccumulatorErrorAsIndexArrFuncWrap(func(d *jx.Decoder) error {
				var v KafkaEndpointExternalAddressSpecOrRefResponse
				if err := v.Decode(d); err != nil {
					return err
				}
				c = append(c, v)
				return nil
			})); err != nil {
				return err
			}

			m.BrokerAddresses = c
			return nil
		default:
			return d.Skip()
		}
	}))
}
