// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"fmt"

	"github.com/go-faster/jx"
	"go.mws.cloud/util-toolset/pkg/utils/consterr"

	"go.mws.cloud/go-sdk/internal/conv"
	"go.mws.cloud/go-sdk/internal/decode"
)

// Тип узла кластера Kafka, для которого доступен тип ВМ.
type KafkaVmTypeInstance string

const (
	KafkaVmTypeInstance_BROKER     KafkaVmTypeInstance = "BROKER"
	KafkaVmTypeInstance_CONTROLLER KafkaVmTypeInstance = "CONTROLLER"

	ErrUnknownKafkaVmTypeInstance = consterr.Error(`unknown kind, want one of "BROKER", "CONTROLLER"`)
)

func NewKafkaVmTypeInstance(s string) (KafkaVmTypeInstance, error) {
	v := KafkaVmTypeInstance(s)
	if !v.IsValid() {
		return "", fmt.Errorf("%w, got %q", ErrUnknownKafkaVmTypeInstance, s)
	}
	return v, nil
}

func (m KafkaVmTypeInstance) String() string {
	return string(m)
}

func (m KafkaVmTypeInstance) IsValid() bool {
	switch m {
	case KafkaVmTypeInstance_BROKER:
		return true
	case KafkaVmTypeInstance_CONTROLLER:
		return true
	}
	return false
}

// JSON methods

func (m KafkaVmTypeInstance) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	if err := m.Encode(&e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (m *KafkaVmTypeInstance) Encode(e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.Str(string(*m))
	return nil
}

func (m *KafkaVmTypeInstance) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *KafkaVmTypeInstance) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("KafkaVmTypeInstance")
	}

	v, err := decode.StrBytes(d)
	if err != nil {
		return err
	}

	*m = KafkaVmTypeInstance(v)
	return nil
}
