// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/go-faster/jx"

	"go.mws.cloud/go-sdk/internal/conv"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
)

func (m KafkaInstanceStatusResponse) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	if err := m.Encode(&e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (m *KafkaInstanceStatusResponse) Encode(e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	if err := m.encodeFields(e); err != nil {
		return err
	}
	e.ObjEnd()
	return nil
}

func (m *KafkaInstanceStatusResponse) encodeFields(e *jx.Encoder) error {
	if m.Disk != nil {
		e.FieldStart("disk")
		m.Disk.Encode(e)
	}
	return nil
}

func (m *KafkaInstanceStatusResponse) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *KafkaInstanceStatusResponse) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("KafkaInstanceStatusResponse")
	}

	return d.ObjBytes(reserrors.PathAccumulatorErrorObjBytesFuncWrap(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "disk":
			if d.Next() == jx.Null {
				return d.Null()
			}

			var v KafkaDataDiskStatusResponse
			if err := v.Decode(d); err != nil {
				return err
			}

			m.Disk = &v
			return nil
		default:
			return d.Skip()
		}
	}))
}
