// Code generated by mwsapigen, DO NOT EDIT.

package model

func KafkaDataDiskSpecRequestToResponse(request *KafkaDataDiskSpecRequest) (*KafkaDataDiskSpecResponse, error) {
	if request == nil {
		return nil, nil
	}
	var response KafkaDataDiskSpecResponse
	response.Size = request.Size
	response.Type = request.Type
	response.Iops = request.Iops
	return &response, nil
}
