// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/go-faster/jx"

	"go.mws.cloud/go-sdk/internal/conv"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
)

func (m UpdateKafkaInstanceRequest) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	if err := m.Encode(&e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (m *UpdateKafkaInstanceRequest) Encode(e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	if err := m.encodeFields(e); err != nil {
		return err
	}
	e.ObjEnd()
	return nil
}

func (m *UpdateKafkaInstanceRequest) encodeFields(e *jx.Encoder) error {
	if m.Broker.IsSet() {
		e.FieldStart("broker")
		m.Broker.Value.Encode(e)
	}

	if m.Controller.IsSet() {
		e.FieldStart("controller")
		m.Controller.Value.Encode(e)
	}
	return nil
}

func (m *UpdateKafkaInstanceRequest) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *UpdateKafkaInstanceRequest) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("UpdateKafkaInstanceRequest")
	}

	return d.ObjBytes(reserrors.PathAccumulatorErrorObjBytesFuncWrap(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "broker":
			var v UpdateKafkaInstanceSpecRequest
			if err := v.Decode(d); err != nil {
				return err
			}

			m.Broker.SetTo(v)
			return nil
		case "controller":
			var v UpdateKafkaControllerInstanceSpecRequest
			if err := v.Decode(d); err != nil {
				return err
			}

			m.Controller.SetTo(v)
			return nil
		default:
			return d.Skip()
		}
	}))
}
