// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"go.mws.cloud/go-sdk/pkg/apimodels/units/bytesize"
)

// Параметры диска с данными на узле кластера.
// Real OAPI model name: KafkaDataDiskSpec
type KafkaDataDiskSpecResponse struct {
	// Размер диска.
	Size bytesize.ByteSize `json:"size" yaml:"size"`
	// Тип используемого диска:
	// * `NETWORK_STANDARD_SSD` — сетевой SSD
	Type *KafkaDataDiskType `json:"type,omitempty" yaml:"type,omitempty"`
	// Количество дисковых операций в секунду.
	Iops *KafkaDataDiskIops `json:"iops,omitempty" yaml:"iops,omitempty"`
}

func (m *KafkaDataDiskSpecResponse) GetSize() bytesize.ByteSize {
	if m != nil {
		return m.Size
	}
	return bytesize.ByteSize{}
}

func (m *KafkaDataDiskSpecResponse) SetSize(val bytesize.ByteSize) {
	m.Size = val
}

func (m *KafkaDataDiskSpecResponse) GetType() *KafkaDataDiskType {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *KafkaDataDiskSpecResponse) SetType(val *KafkaDataDiskType) {
	m.Type = val
}

func (m *KafkaDataDiskSpecResponse) GetTypeOr(val KafkaDataDiskType) KafkaDataDiskType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return val
}

func (m *KafkaDataDiskSpecResponse) GetIops() *KafkaDataDiskIops {
	if m != nil {
		return m.Iops
	}
	return nil
}

func (m *KafkaDataDiskSpecResponse) SetIops(val *KafkaDataDiskIops) {
	m.Iops = val
}

func (m *KafkaDataDiskSpecResponse) GetIopsOr(val KafkaDataDiskIops) KafkaDataDiskIops {
	if m != nil && m.Iops != nil {
		return *m.Iops
	}
	return val
}

func (m *KafkaDataDiskSpecResponse) Clone() *KafkaDataDiskSpecResponse {
	if m == nil {
		return nil
	}

	clone := *m
	clone.Size = *m.Size.Clone()
	if m.Type != nil {
		cloneType := *m.Type
		clone.Type = &cloneType
	}
	if m.Iops != nil {
		cloneIops := *m.Iops
		clone.Iops = &cloneIops
	}
	return &clone
}
