// Code generated by mwsapigen, DO NOT EDIT.

package model

func (m *KafkaClusterRequest) WithDefaults() KafkaClusterRequest {
	var out KafkaClusterRequest
	if m != nil {
		out = *m
	}

	out.Spec = out.Spec.WithDefaults()
	return out
}
