// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/go-faster/jx"

	"go.mws.cloud/go-sdk/internal/conv"
	"go.mws.cloud/go-sdk/internal/decode"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
)

func (m KafkaEndpointExternalAccessesRequest) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	if err := m.Encode(&e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (m *KafkaEndpointExternalAccessesRequest) Encode(e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	if err := m.encodeFields(e); err != nil {
		return err
	}
	e.ObjEnd()
	return nil
}

func (m *KafkaEndpointExternalAccessesRequest) encodeFields(e *jx.Encoder) error {
	e.FieldStart("allowed")
	e.Bool(m.Allowed)

	if m.BrokerAddresses != nil {
		e.FieldStart("brokerAddresses")
		e.ArrStart()
		for _, elem := range m.BrokerAddresses {
			elem.Encode(e)
		}
		e.ArrEnd()
	}
	return nil
}

func (m *KafkaEndpointExternalAccessesRequest) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *KafkaEndpointExternalAccessesRequest) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("KafkaEndpointExternalAccessesRequest")
	}

	requiredFilled := map[string]bool{
		"allowed": false,
	}
	err := d.ObjBytes(reserrors.PathAccumulatorErrorObjBytesFuncWrap(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "allowed":
			v, err := decode.Bool(d)
			if err != nil {
				return err
			}

			m.Allowed = v
			requiredFilled["allowed"] = true
			return nil
		case "brokerAddresses":
			c := make([]KafkaEndpointExternalAddressSpecOrRefRequest, 0)
			if err := d.Arr(reserrors.PathAccumulatorErrorAsIndexArrFuncWrap(func(d *jx.Decoder) error {
				var v KafkaEndpointExternalAddressSpecOrRefRequest
				if err := v.Decode(d); err != nil {
					return err
				}
				c = append(c, v)
				return nil
			})); err != nil {
				return err
			}

			m.BrokerAddresses = c
			return nil
		default:
			return d.Skip()
		}
	}))
	if err != nil {
		return err
	}

	return conv.ValidateRequired(requiredFilled)
}
