// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/go-faster/jx"

	"go.mws.cloud/go-sdk/internal/conv"
	"go.mws.cloud/go-sdk/internal/decode"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
)

func (m KafkaTopicSpecResponse) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	if err := m.Encode(&e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (m *KafkaTopicSpecResponse) Encode(e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	if err := m.encodeFields(e); err != nil {
		return err
	}
	e.ObjEnd()
	return nil
}

func (m *KafkaTopicSpecResponse) encodeFields(e *jx.Encoder) error {
	if m.Partitions != nil {
		e.FieldStart("partitions")
		e.Int32(*m.Partitions)
	}

	if m.ReplicationFactor != nil {
		e.FieldStart("replicationFactor")
		e.Int32(*m.ReplicationFactor)
	}

	if m.Config != nil {
		e.FieldStart("config")
		e.Str(*m.Config)
	}
	return nil
}

func (m *KafkaTopicSpecResponse) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *KafkaTopicSpecResponse) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("KafkaTopicSpecResponse")
	}

	return d.ObjBytes(reserrors.PathAccumulatorErrorObjBytesFuncWrap(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "partitions":
			v, err := decode.Int32(d)
			if err != nil {
				return err
			}

			m.Partitions = &v
			return nil
		case "replicationFactor":
			v, err := decode.Int32(d)
			if err != nil {
				return err
			}

			m.ReplicationFactor = &v
			return nil
		case "config":
			v, err := decode.Str(d)
			if err != nil {
				return err
			}

			m.Config = &v
			return nil
		default:
			return d.Skip()
		}
	}))
}
