// Code generated by mwsapigen, DO NOT EDIT.

package mclickhouse

import (
	"context"
	"fmt"

	"github.com/go-faster/jx"

	"go.mws.cloud/go-sdk/internal/conv"
	"go.mws.cloud/go-sdk/internal/decode"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	resparsers "go.mws.cloud/go-sdk/internal/resources/parsers"
	valuesctx "go.mws.cloud/go-sdk/pkg/context/values"
	resifaces "go.mws.cloud/go-sdk/pkg/resources/interfaces"
	resmodels "go.mws.cloud/go-sdk/pkg/resources/models"
)

var (
	ClickhouseClusterShardInstanceRefTemplate = resparsers.Template{
		{
			Value:       "instance",
			IsConstant:  false,
			SearchAfter: false,
		},
		{
			Value:       "instances",
			IsConstant:  true,
			SearchAfter: false,
		},
		{
			Value:       "shard",
			IsConstant:  false,
			SearchAfter: true,
		},
		{
			Value:       "shards",
			IsConstant:  true,
			SearchAfter: false,
		},
		{
			Value:       "cluster",
			IsConstant:  false,
			SearchAfter: true,
		},
		{
			Value:       "clusters",
			IsConstant:  true,
			SearchAfter: false,
		},
		{
			Value:       "project",
			IsConstant:  false,
			SearchAfter: true,
		},
		{
			Value:       "projects",
			IsConstant:  true,
			SearchAfter: false,
		},
		{
			Value:       "mclickhouse",
			IsConstant:  true,
			SearchAfter: false,
		},
	}
)

func NewClickhouseClusterShardInstanceID(project, cluster, shard, instance string) (ClickhouseClusterShardInstanceID, error) {
	if instance == "" {
		return ClickhouseClusterShardInstanceID{}, reserrors.NewFieldIsEmptyError("instance")
	}
	if shard == "" {
		return ClickhouseClusterShardInstanceID{}, reserrors.NewFieldIsEmptyError("shard")
	}
	if cluster == "" {
		return ClickhouseClusterShardInstanceID{}, reserrors.NewFieldIsEmptyError("cluster")
	}
	if project == "" {
		return ClickhouseClusterShardInstanceID{}, reserrors.NewFieldIsEmptyError("project")
	}
	m := ClickhouseClusterShardInstanceID{
		instance: instance,
		shard:    shard,
		cluster:  cluster,
		project:  project,
	}
	m.path = m.ID()
	return m, nil
}

func NewMustClickhouseClusterShardInstanceID(project, cluster, shard, instance string) ClickhouseClusterShardInstanceID {
	m, err := NewClickhouseClusterShardInstanceID(project, cluster, shard, instance)
	if err != nil {
		panic(err)
	}
	return m
}

func ParseClickhouseClusterShardInstanceID(path string) (ClickhouseClusterShardInstanceID, error) {
	m := ClickhouseClusterShardInstanceID{
		path: path,
	}
	if err := m.parse(); err != nil {
		return ClickhouseClusterShardInstanceID{}, err
	}
	return m, nil
}

func NewClickhouseClusterShardInstanceIDFromAnyID(resource resmodels.AnyResourceID) (ClickhouseClusterShardInstanceID, error) {
	return ParseClickhouseClusterShardInstanceID(resource.ID())
}

type ClickhouseClusterShardInstanceID struct {
	instance string
	shard    string
	cluster  string
	project  string
	path     string
}

func (m *ClickhouseClusterShardInstanceID) ResourceName() resifaces.ResourceName {
	if m == nil {
		return ""
	}
	return resifaces.ResourceName(m.instance)
}

func (m *ClickhouseClusterShardInstanceID) GetInstance() string {
	if m == nil {
		return ""
	}
	return m.instance
}

func (m *ClickhouseClusterShardInstanceID) GetShard() string {
	if m == nil {
		return ""
	}
	return m.shard
}

func (m *ClickhouseClusterShardInstanceID) GetCluster() string {
	if m == nil {
		return ""
	}
	return m.cluster
}

func (m *ClickhouseClusterShardInstanceID) GetProject() string {
	if m == nil {
		return ""
	}
	return m.project
}

func (m *ClickhouseClusterShardInstanceID) ServiceSlug() string {
	return "mclickhouse"
}

func (m *ClickhouseClusterShardInstanceID) ID() string {
	if m == nil || m.instance == "" || m.shard == "" || m.cluster == "" || m.project == "" {
		return ""
	}

	return m.ServiceSlug() + "/projects/" + m.project + "/clusters/" + m.cluster + "/shards/" + m.shard + "/instances/" + m.instance
}

func (m *ClickhouseClusterShardInstanceID) String() string {
	return m.ID()
}

func (m *ClickhouseClusterShardInstanceID) Clone() *ClickhouseClusterShardInstanceID {
	if m == nil {
		return nil
	}
	clone := *m
	return &clone
}

func (m ClickhouseClusterShardInstanceID) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	if err := m.Encode(&e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (m *ClickhouseClusterShardInstanceID) Encode(e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	result := m.ID()
	if result == "" {
		return fmt.Errorf("encode id: %w", reserrors.ErrIDIsEmpty)
	}
	e.Str(result)
	return nil
}

func (m *ClickhouseClusterShardInstanceID) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *ClickhouseClusterShardInstanceID) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("ClickhouseClusterShardInstanceID")
	}

	v, err := decode.Str(d)
	if err != nil {
		return err
	}

	m.path = v
	return m.parse()
}

// Deprecated: Parse method is no longer required.
// Internal fields are populated automatically during decoding.
// This method will be removed in the next SDK release.
func (m *ClickhouseClusterShardInstanceID) Parse(ctx context.Context) error {
	return nil
}

func (m *ClickhouseClusterShardInstanceID) parse() error {
	if m == nil {
		return nil
	}

	if m.path == "" {
		return reserrors.NewParseIDError("", reserrors.ErrPathIsEmpty)
	}

	result, err := resparsers.Reference(context.Background(), m.path, ClickhouseClusterShardInstanceRefTemplate.AsID())
	if err != nil {
		return reserrors.NewParseIDError(m.path, err)
	}

	m.instance = result["instance"]
	m.shard = result["shard"]
	m.cluster = result["cluster"]
	m.project = result["project"]

	return nil
}

func NewClickhouseClusterShardInstanceRef(project, cluster, shard, instance string) (ClickhouseClusterShardInstanceRef, error) {
	if instance == "" {
		return ClickhouseClusterShardInstanceRef{}, reserrors.NewFieldIsEmptyError("instance")
	}
	if shard == "" {
		return ClickhouseClusterShardInstanceRef{}, reserrors.NewFieldIsEmptyError("shard")
	}
	if cluster == "" {
		return ClickhouseClusterShardInstanceRef{}, reserrors.NewFieldIsEmptyError("cluster")
	}
	if project == "" {
		return ClickhouseClusterShardInstanceRef{}, reserrors.NewFieldIsEmptyError("project")
	}
	m := ClickhouseClusterShardInstanceRef{
		id: ClickhouseClusterShardInstanceID{
			instance: instance,
			shard:    shard,
			cluster:  cluster,
			project:  project,
		},
	}
	m.id.path = m.absolutePath()
	return m, nil
}

func NewMustClickhouseClusterShardInstanceRef(project, cluster, shard, instance string) ClickhouseClusterShardInstanceRef {
	m, err := NewClickhouseClusterShardInstanceRef(project, cluster, shard, instance)
	if err != nil {
		panic(err)
	}
	return m
}

func ParseClickhouseClusterShardInstanceRef(ctx context.Context, path string) (ClickhouseClusterShardInstanceRef, error) {
	m := ClickhouseClusterShardInstanceRef{
		id: ClickhouseClusterShardInstanceID{
			path: path,
		},
	}
	if err := m.Parse(ctx); err != nil {
		return ClickhouseClusterShardInstanceRef{}, err
	}
	return m, nil
}

func NewClickhouseClusterShardInstanceRefFromAnyRef(ref resmodels.AnyResourceRef) (ClickhouseClusterShardInstanceRef, error) {
	ctx := valuesctx.WithValuesStore(context.Background(), ref.GetPathValues())
	return ParseClickhouseClusterShardInstanceRef(ctx, ref.Path())
}

type ClickhouseClusterShardInstanceRef struct {
	id ClickhouseClusterShardInstanceID
}

func (m *ClickhouseClusterShardInstanceRef) ResourceName() resifaces.ResourceName {
	if m == nil {
		return ""
	}
	return m.id.ResourceName()
}

func (m *ClickhouseClusterShardInstanceRef) GetInstance() string {
	if m == nil {
		return ""
	}
	return m.id.GetInstance()
}

func (m *ClickhouseClusterShardInstanceRef) GetShard() string {
	if m == nil {
		return ""
	}
	return m.id.GetShard()
}

func (m *ClickhouseClusterShardInstanceRef) GetCluster() string {
	if m == nil {
		return ""
	}
	return m.id.GetCluster()
}

func (m *ClickhouseClusterShardInstanceRef) GetProject() string {
	if m == nil {
		return ""
	}
	return m.id.GetProject()
}

func (m *ClickhouseClusterShardInstanceRef) ServiceSlug() string {
	return "mclickhouse"
}

func (m *ClickhouseClusterShardInstanceRef) IDPath() string {
	if m == nil {
		return ""
	}
	return m.id.ID()
}

func (m *ClickhouseClusterShardInstanceRef) Path() string {
	if m == nil {
		return ""
	}
	if m.id.path == "" {
		return m.absolutePath()
	}
	return m.id.path
}

func (m *ClickhouseClusterShardInstanceRef) String() string {
	return m.IDPath()
}

func (m *ClickhouseClusterShardInstanceRef) Parse(ctx context.Context) error {
	return m.parse(ctx, false)
}

func (m *ClickhouseClusterShardInstanceRef) Clone() *ClickhouseClusterShardInstanceRef {
	if m == nil {
		return nil
	}
	clone := *m
	return &clone
}

func (m ClickhouseClusterShardInstanceRef) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	if err := m.Encode(&e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (m *ClickhouseClusterShardInstanceRef) Encode(e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	result := m.Path()
	if result == "" {
		return fmt.Errorf("encode reference: %w", reserrors.ErrPathIsEmpty)
	}
	e.Str(result)
	return nil
}

func (m *ClickhouseClusterShardInstanceRef) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *ClickhouseClusterShardInstanceRef) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("ClickhouseClusterShardInstanceRef")
	}

	v, err := decode.Str(d)
	if err != nil {
		return err
	}

	m.id.path = v
	return m.parse(context.Background(), true)
}

func (m *ClickhouseClusterShardInstanceRef) parse(ctx context.Context, allowPartial bool) error {
	if m == nil || m.isParsed() {
		return nil
	}

	if m.id.path == "" {
		return reserrors.NewParseReferenceError("", reserrors.ErrPathIsEmpty)
	}

	var options []resparsers.Option
	if allowPartial {
		options = append(options, resparsers.AllowPartial())
	}

	result, err := resparsers.Reference(ctx, m.id.path, ClickhouseClusterShardInstanceRefTemplate, options...)
	if err != nil {
		return reserrors.NewParseReferenceError(m.id.path, err)
	}

	m.id.instance = result["instance"]
	m.id.shard = result["shard"]
	m.id.cluster = result["cluster"]
	m.id.project = result["project"]

	return nil
}

func (m *ClickhouseClusterShardInstanceRef) isParsed() bool {
	return m != nil && m.id.instance != "" && m.id.shard != "" && m.id.cluster != "" && m.id.project != ""
}

func (m *ClickhouseClusterShardInstanceRef) absolutePath() string {
	if m == nil || m.id.instance == "" || m.id.shard == "" || m.id.cluster == "" || m.id.project == "" {
		return ""
	}

	return "projects/" + m.id.project + "/clusters/" + m.id.cluster + "/shards/" + m.id.shard + "/instances/" + m.id.instance
}
