// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/go-faster/jx"
	"go.mws.cloud/go-sdk/pkg/apimodels/units/bytesize"
	"go.mws.cloud/go-sdk/pkg/apimodels/units/duration"

	"go.mws.cloud/go-sdk/internal/conv"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
)

func (m AuditLogsStorageSpecRequest) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	if err := m.Encode(&e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (m *AuditLogsStorageSpecRequest) Encode(e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	if err := m.encodeFields(e); err != nil {
		return err
	}
	e.ObjEnd()
	return nil
}

func (m *AuditLogsStorageSpecRequest) encodeFields(e *jx.Encoder) error {
	e.FieldStart("retention")
	if err := m.Retention.Encode(e); err != nil {
		return err
	}
	return nil
}

func (m *AuditLogsStorageSpecRequest) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *AuditLogsStorageSpecRequest) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("AuditLogsStorageSpecRequest")
	}

	requiredFilled := map[string]bool{
		"retention": false,
	}
	err := d.ObjBytes(reserrors.PathAccumulatorErrorObjBytesFuncWrap(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "retention":
			var v AuditLogsStorageSpecRetentionRequest
			if err := v.Decode(d); err != nil {
				return err
			}

			m.Retention = v
			requiredFilled["retention"] = true
			return nil
		default:
			return d.Skip()
		}
	}))
	if err != nil {
		return err
	}

	return conv.ValidateRequired(requiredFilled)
}

func (m AuditLogsStorageSpecRetentionRequest) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	if err := m.Encode(&e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (m *AuditLogsStorageSpecRetentionRequest) Encode(e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	if err := m.encodeFields(e); err != nil {
		return err
	}
	e.ObjEnd()
	return nil
}

func (m *AuditLogsStorageSpecRetentionRequest) encodeFields(e *jx.Encoder) error {
	if m.Size != nil {
		e.FieldStart("size")
		m.Size.Encode(e)
	}

	e.FieldStart("period")
	m.Period.Encode(e)
	return nil
}

func (m *AuditLogsStorageSpecRetentionRequest) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *AuditLogsStorageSpecRetentionRequest) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("AuditLogsStorageSpecRetentionRequest")
	}

	requiredFilled := map[string]bool{
		"period": false,
	}
	err := d.ObjBytes(reserrors.PathAccumulatorErrorObjBytesFuncWrap(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "size":
			var v bytesize.ByteSize
			if err := v.Decode(d); err != nil {
				return err
			}

			m.Size = &v
			return nil
		case "period":
			var v duration.Duration
			if err := v.Decode(d); err != nil {
				return err
			}

			m.Period = v
			requiredFilled["period"] = true
			return nil
		default:
			return d.Skip()
		}
	}))
	if err != nil {
		return err
	}

	return conv.ValidateRequired(requiredFilled)
}
