// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	commonclient "go.mws.cloud/go-sdk/internal/client"
	"go.mws.cloud/go-sdk/pkg/optional"
)

type UpdateCollectorServiceRequest struct {
	Service optional.Optional[string]                          `json:"service" yaml:"service"`
	Filter  optional.Optional[UpdateServiceEventFilterRequest] `json:"filter" yaml:"filter"`
}

func (m *CollectorServiceRequest) AsUpdateModel() UpdateCollectorServiceRequest {
	var u UpdateCollectorServiceRequest
	u.Service = optional.NewOptional(m.GetService())
	u.Filter = optional.NewOptional(m.Filter.AsUpdateModel())
	return u
}

// Diff creates an object that can be used in Update methods. This object represents changes from src to the current state
func (m *CollectorServiceRequest) Diff(src *CollectorServiceRequest) UpdateCollectorServiceRequest {
	nilDiffers := src != nil && m == nil
	upd := UpdateCollectorServiceRequest{}
	if !nilDiffers {
		upd.Service = m.diffService(src)
		upd.Filter = m.diffFilter(src)
	}
	return upd
}

func (m *CollectorServiceRequest) WithChanges(u UpdateCollectorServiceRequest) CollectorServiceRequest {
	var out CollectorServiceRequest
	if m != nil {
		out = *m
	}

	if u.Service.IsSet() {
		out.Service = u.Service.Value
	}
	if u.Filter.IsSet() {
		out.Filter = out.Filter.WithChanges(u.Filter.Value)
	}
	return out
}

// HasChanges returns true if any field has Set == true
func (m UpdateCollectorServiceRequest) HasChanges() bool {
	return m.Service.Set ||
		m.Filter.Set
}

func (m *CollectorServiceRequest) diffService(src *CollectorServiceRequest) optional.Optional[string] {
	nilDiffers := src != nil && m == nil
	return commonclient.DiffPrimitiveRequired(src.GetService(), m.GetService(), nilDiffers)
}

func (m *CollectorServiceRequest) diffFilter(src *CollectorServiceRequest) optional.Optional[UpdateServiceEventFilterRequest] {
	from := src.GetFilter()
	to := m.GetFilter()
	value := to.Diff(&from)
	return optional.Optional[UpdateServiceEventFilterRequest]{
		Value: value,
		Set:   value.HasChanges(),
	}
}
