// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"time"

	commonmodel "go.mws.cloud/go-sdk/service/common/model"
	"go.mws.cloud/go-sdk/service/resources/references/auditlogs"
)

// Real OAPI model name: CollectorTypedResourceMetadata
type CollectorTypedResourceMetadataResponse struct {
	commonmodel.TypedResourceMetadataResponse `yaml:"-,inline"`
	// ссылка на типизированный референс коллектора
	Id *auditlogs.CollectorID `json:"id,omitempty" yaml:"id,omitempty"`
}

func (m *CollectorTypedResourceMetadataResponse) GetDisplayName() *string {
	if m != nil {
		return m.TypedResourceMetadataResponse.GetDisplayName()
	}
	return nil
}

func (m *CollectorTypedResourceMetadataResponse) GetDisplayNameOr(val string) string {
	if m != nil {
		return m.TypedResourceMetadataResponse.GetDisplayNameOr(val)
	}
	return val
}

func (m *CollectorTypedResourceMetadataResponse) GetCreateTime() *time.Time {
	if m != nil {
		return m.TypedResourceMetadataResponse.GetCreateTime()
	}
	return nil
}

func (m *CollectorTypedResourceMetadataResponse) GetCreateTimeOr(val time.Time) time.Time {
	if m != nil {
		return m.TypedResourceMetadataResponse.GetCreateTimeOr(val)
	}
	return val
}

func (m *CollectorTypedResourceMetadataResponse) GetUpdateTime() *time.Time {
	if m != nil {
		return m.TypedResourceMetadataResponse.GetUpdateTime()
	}
	return nil
}

func (m *CollectorTypedResourceMetadataResponse) GetUpdateTimeOr(val time.Time) time.Time {
	if m != nil {
		return m.TypedResourceMetadataResponse.GetUpdateTimeOr(val)
	}
	return val
}

func (m *CollectorTypedResourceMetadataResponse) GetDeleteTime() *time.Time {
	if m != nil {
		return m.TypedResourceMetadataResponse.GetDeleteTime()
	}
	return nil
}

func (m *CollectorTypedResourceMetadataResponse) GetDeleteTimeOr(val time.Time) time.Time {
	if m != nil {
		return m.TypedResourceMetadataResponse.GetDeleteTimeOr(val)
	}
	return val
}

func (m *CollectorTypedResourceMetadataResponse) GetPurgeTime() *time.Time {
	if m != nil {
		return m.TypedResourceMetadataResponse.GetPurgeTime()
	}
	return nil
}

func (m *CollectorTypedResourceMetadataResponse) GetPurgeTimeOr(val time.Time) time.Time {
	if m != nil {
		return m.TypedResourceMetadataResponse.GetPurgeTimeOr(val)
	}
	return val
}

func (m *CollectorTypedResourceMetadataResponse) GetUsages() []commonmodel.TypedUsageResponse {
	if m != nil {
		return m.TypedResourceMetadataResponse.GetUsages()
	}
	return nil
}

func (m *CollectorTypedResourceMetadataResponse) GetUsagesOr(val []commonmodel.TypedUsageResponse) []commonmodel.TypedUsageResponse {
	if m != nil {
		return m.TypedResourceMetadataResponse.GetUsagesOr(val)
	}
	return val
}

func (m *CollectorTypedResourceMetadataResponse) GetEtag() *string {
	if m != nil {
		return m.TypedResourceMetadataResponse.GetEtag()
	}
	return nil
}

func (m *CollectorTypedResourceMetadataResponse) GetEtagOr(val string) string {
	if m != nil {
		return m.TypedResourceMetadataResponse.GetEtagOr(val)
	}
	return val
}

func (m *CollectorTypedResourceMetadataResponse) GetDescription() *string {
	if m != nil {
		return m.TypedResourceMetadataResponse.GetDescription()
	}
	return nil
}

func (m *CollectorTypedResourceMetadataResponse) GetDescriptionOr(val string) string {
	if m != nil {
		return m.TypedResourceMetadataResponse.GetDescriptionOr(val)
	}
	return val
}

func (m *CollectorTypedResourceMetadataResponse) GetId() *auditlogs.CollectorID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *CollectorTypedResourceMetadataResponse) GetIdOr(val auditlogs.CollectorID) auditlogs.CollectorID {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return val
}

func (m *CollectorTypedResourceMetadataResponse) Clone() *CollectorTypedResourceMetadataResponse {
	if m == nil {
		return nil
	}

	clone := *m
	clone.TypedResourceMetadataResponse = *m.TypedResourceMetadataResponse.Clone()
	clone.Id = m.Id.Clone()

	return &clone
}
