// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"context"

	"go.mws.cloud/util-toolset/pkg/utils/ptr"

	commonclient "go.mws.cloud/go-sdk/internal/client"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	"go.mws.cloud/go-sdk/pkg/optional"
	"go.mws.cloud/go-sdk/service/resources/references/org"
	"go.mws.cloud/go-sdk/service/resources/references/rm"
)

type UpdateEventSourceSpecRequest struct {
	Project      optional.Optional[rm.ProjectRef]       `json:"project" yaml:"project"`
	Organization optional.Optional[org.OrganizationRef] `json:"organization" yaml:"organization"`
}

func (m *EventSourceSpecRequest) AsUpdateModel() UpdateEventSourceSpecRequest {
	var u UpdateEventSourceSpecRequest
	if m.Project != nil {
		u.Project = optional.NewOptional(m.GetProjectOr(rm.ProjectRef{}))
	}
	if m.Organization != nil {
		u.Organization = optional.NewOptional(m.GetOrganizationOr(org.OrganizationRef{}))
	}
	return u
}

// Diff creates an object that can be used in Update methods. This object represents changes from src to the current state
func (m *EventSourceSpecRequest) Diff(src *EventSourceSpecRequest) UpdateEventSourceSpecRequest {
	nilDiffers := src != nil && m == nil
	upd := UpdateEventSourceSpecRequest{}
	if !nilDiffers {
		upd.Project = m.diffProject(src)
		upd.Organization = m.diffOrganization(src)
	}
	return upd
}

func (m *EventSourceSpecRequest) WithChanges(u UpdateEventSourceSpecRequest) EventSourceSpecRequest {
	var out EventSourceSpecRequest
	if m != nil {
		out = *m
	}

	if u.Project.IsSet() {
		out.Project = ptr.Get(u.Project.Value)
	}
	if u.Organization.IsSet() {
		out.Organization = ptr.Get(u.Organization.Value)
	}
	return out
}

// HasChanges returns true if any field has Set == true
func (m UpdateEventSourceSpecRequest) HasChanges() bool {
	return m.Project.Set ||
		m.Organization.Set
}

func (m *UpdateEventSourceSpecRequest) Parse(ctx context.Context) error {
	if m == nil {
		return nil
	}

	if m.Project.IsSet() {
		if err := m.Project.Value.Parse(ctx); err != nil {
			return reserrors.NewPathAccumulatorError("Project", err)
		}
	}

	if m.Organization.IsSet() {
		if err := m.Organization.Value.Parse(ctx); err != nil {
			return reserrors.NewPathAccumulatorError("Organization", err)
		}
	}

	return nil
}

func (m *EventSourceSpecRequest) diffProject(src *EventSourceSpecRequest) optional.Optional[rm.ProjectRef] {
	nilDiffers := src != nil && m == nil
	return commonclient.DiffPrimitiveNonRequired(src.GetProject(), m.GetProject(), nilDiffers)
}

func (m *EventSourceSpecRequest) diffOrganization(src *EventSourceSpecRequest) optional.Optional[org.OrganizationRef] {
	nilDiffers := src != nil && m == nil
	return commonclient.DiffPrimitiveNonRequired(src.GetOrganization(), m.GetOrganization(), nilDiffers)
}
