// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/go-faster/jx"

	"go.mws.cloud/go-sdk/internal/conv"
	"go.mws.cloud/go-sdk/internal/decode"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	"go.mws.cloud/go-sdk/pkg/optional"
)

// Real OAPI model name: Storage
type StorageOptionalResponse struct {
	Kind     *string                                                            `json:"kind,omitempty" yaml:"kind,omitempty"`
	Metadata optional.OptionalNil[StorageTypedResourceMetadataOptionalResponse] `json:"metadata,omitempty" yaml:"metadata,omitempty"`
	Spec     AuditLogsStorageSpecOptionalResponse                               `json:"spec" yaml:"spec"`
	Status   *StorageStatusResponse                                             `json:"status,omitempty" yaml:"status,omitempty"`
}

func (m *StorageOptionalResponse) GetKind() *string {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (m *StorageOptionalResponse) SetKind(val *string) {
	m.Kind = val
}

func (m *StorageOptionalResponse) GetKindOr(val string) string {
	if m != nil && m.Kind != nil {
		return *m.Kind
	}
	return val
}

func (m *StorageOptionalResponse) GetMetadata() *StorageTypedResourceMetadataOptionalResponse {
	if m != nil && m.Metadata.IsSet() && !m.Metadata.IsNull() {
		return &m.Metadata.Value
	}
	return nil
}

func (m *StorageOptionalResponse) GetMetadataOr(val StorageTypedResourceMetadataOptionalResponse) StorageTypedResourceMetadataOptionalResponse {
	if m != nil && m.Metadata.IsSet() && !m.Metadata.IsNull() {
		return m.Metadata.Value
	}
	return val
}

func (m *StorageOptionalResponse) GetSpec() AuditLogsStorageSpecOptionalResponse {
	if m != nil {
		return m.Spec
	}
	return AuditLogsStorageSpecOptionalResponse{}
}

func (m *StorageOptionalResponse) SetSpec(val AuditLogsStorageSpecOptionalResponse) {
	m.Spec = val
}

func (m *StorageOptionalResponse) GetStatus() *StorageStatusResponse {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *StorageOptionalResponse) SetStatus(val *StorageStatusResponse) {
	m.Status = val
}

func (m *StorageOptionalResponse) GetStatusOr(val StorageStatusResponse) StorageStatusResponse {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return val
}

func (m *StorageOptionalResponse) Clone() *StorageOptionalResponse {
	if m == nil {
		return nil
	}

	clone := *m
	if m.Kind != nil {
		cloneKind := *m.Kind
		clone.Kind = &cloneKind
	}
	if clone.Metadata.IsSet() {
		clone.Metadata.Value = *m.Metadata.Value.Clone()
	}
	clone.Spec = *m.Spec.Clone()
	clone.Status = m.Status.Clone()
	return &clone
}

// JSON methods

func (m StorageOptionalResponse) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	if err := m.Encode(&e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (m *StorageOptionalResponse) Encode(e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	if err := m.encodeFields(e); err != nil {
		return err
	}
	e.ObjEnd()
	return nil
}

func (m *StorageOptionalResponse) encodeFields(e *jx.Encoder) error {
	if m.Kind != nil {
		e.FieldStart("kind")
		e.Str(*m.Kind)
	}

	if m.Metadata.IsSet() {
		e.FieldStart("metadata")
		if m.Metadata.IsNull() {
			e.Null()
		} else {
			if err := m.Metadata.Value.Encode(e); err != nil {
				return err
			}
		}
	}

	e.FieldStart("spec")
	if err := m.Spec.Encode(e); err != nil {
		return err
	}

	if m.Status != nil {
		e.FieldStart("status")
		if err := m.Status.Encode(e); err != nil {
			return err
		}
	}
	return nil
}

func (m *StorageOptionalResponse) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *StorageOptionalResponse) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("StorageOptionalResponse")
	}

	return d.ObjBytes(reserrors.PathAccumulatorErrorObjBytesFuncWrap(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "kind":
			v, err := decode.Str(d)
			if err != nil {
				return err
			}

			m.Kind = &v
			return nil
		case "metadata":
			if d.Next() == jx.Null {
				m.Metadata.SetToNull()
				return d.Null()
			}

			var v StorageTypedResourceMetadataOptionalResponse
			if err := v.Decode(d); err != nil {
				return err
			}

			m.Metadata.SetTo(v)
			return nil
		case "spec":
			var v AuditLogsStorageSpecOptionalResponse
			if err := v.Decode(d); err != nil {
				return err
			}

			m.Spec = v
			return nil
		case "status":
			if d.Next() == jx.Null {
				return d.Null()
			}

			var v StorageStatusResponse
			if err := v.Decode(d); err != nil {
				return err
			}

			m.Status = &v
			return nil
		default:
			return d.Skip()
		}
	}))
}
