// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"go.mws.cloud/util-toolset/pkg/utils/ptr"

	"go.mws.cloud/go-sdk/pkg/optional"
)

type UpdateStorageRequest struct {
	Metadata optional.OptionalNil[UpdateStorageTypedResourceMetadataRequest] `json:"metadata" yaml:"metadata"`
	Spec     optional.Optional[UpdateAuditLogsStorageSpecRequest]            `json:"spec" yaml:"spec"`
}

func (m *StorageRequest) AsUpdateModel() UpdateStorageRequest {
	var u UpdateStorageRequest
	if m.Metadata != nil {
		u.Metadata = optional.NewOptionalNil(m.Metadata.AsUpdateModel())
	}
	u.Spec = optional.NewOptional(m.Spec.AsUpdateModel())
	return u
}

// Diff creates an object that can be used in Update methods. This object represents changes from src to the current state
func (m *StorageRequest) Diff(src *StorageRequest) UpdateStorageRequest {
	nilDiffers := src != nil && m == nil
	upd := UpdateStorageRequest{}
	if !nilDiffers {
		upd.Metadata = m.diffMetadata(src)
		upd.Spec = m.diffSpec(src)
	}
	return upd
}

func (m *StorageRequest) WithChanges(u UpdateStorageRequest) StorageRequest {
	var out StorageRequest
	if m != nil {
		out = *m
	}

	if u.Metadata.IsSet() {
		out.Metadata = ptr.Get(out.Metadata.WithChanges(u.Metadata.Value))
	} else if u.Metadata.IsNull() {
		out.Metadata = nil
	}
	if u.Spec.IsSet() {
		out.Spec = out.Spec.WithChanges(u.Spec.Value)
	}
	return out
}

// HasChanges returns true if any field has Set == true
func (m UpdateStorageRequest) HasChanges() bool {
	return m.Metadata.Set ||
		m.Spec.Set
}

func (m *StorageRequest) diffMetadata(src *StorageRequest) optional.OptionalNil[UpdateStorageTypedResourceMetadataRequest] {
	nilDiffers := src != nil && m == nil
	value := m.GetMetadata().Diff(src.GetMetadata())
	return optional.OptionalNil[UpdateStorageTypedResourceMetadataRequest]{
		Value: value,
		Set:   nilDiffers || value.HasChanges(),
		Null:  nilDiffers,
	}
}

func (m *StorageRequest) diffSpec(src *StorageRequest) optional.Optional[UpdateAuditLogsStorageSpecRequest] {
	from := src.GetSpec()
	to := m.GetSpec()
	value := to.Diff(&from)
	return optional.Optional[UpdateAuditLogsStorageSpecRequest]{
		Value: value,
		Set:   value.HasChanges(),
	}
}
