// Code generated by mwsapigen, DO NOT EDIT.

package model_test

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/service/mclickhouse/model"
)

func TestClickhouseClusterUserRoleMarshalling(t *testing.T) {
	t.Parallel()
	expected := initClickhouseClusterUserRole()
	b, err := json.Marshal(expected)
	require.NoError(t, err)

	var actual model.ClickhouseClusterUserRole
	require.NoError(t, json.Unmarshal(b, &actual))
	require.Equal(t, expected, actual)
}

func initClickhouseClusterUserRole() model.ClickhouseClusterUserRole {
	var v model.ClickhouseClusterUserRole
	return v
}
