// Code generated by mwsapigen, DO NOT EDIT.

package model_test

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/service/mk8s/model"
)

func TestLocalDiskStatusResponseMarshalling(t *testing.T) {
	t.Parallel()
	expected := initLocalDiskStatusResponse()
	b, err := json.Marshal(expected)
	require.NoError(t, err)

	var actual model.LocalDiskStatusResponse
	require.NoError(t, json.Unmarshal(b, &actual))
	require.Equal(t, expected, actual)
}

func initLocalDiskStatusResponse() model.LocalDiskStatusResponse {
	var v model.LocalDiskStatusResponse
	return v
}
