// Code generated by mwsapigen, DO NOT EDIT.

package model_test

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/require"

	common "go.mws.cloud/go-sdk/service/common/model"
	"go.mws.cloud/go-sdk/service/resources/references/iam"
)

func TestCommonRoleBindingWorkloadFederationRequestMarshalling(t *testing.T) {
	t.Parallel()
	expected := initCommonRoleBindingWorkloadFederationRequest()
	b, err := json.Marshal(expected)
	require.NoError(t, err)

	var actual common.CommonRoleBindingWorkloadFederationRequest
	require.NoError(t, json.Unmarshal(b, &actual))
	require.Equal(t, expected, actual)
}

func initCommonRoleBindingWorkloadFederationRequest() common.CommonRoleBindingWorkloadFederationRequest {
	var v common.CommonRoleBindingWorkloadFederationRequest
	v.Id = iam.NewMustWorkloadFederationRef("projectID", "workloadFederationID")
	return v
}
