// Code generated by mwsapigen, DO NOT EDIT.

package model_test

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/require"

	common "go.mws.cloud/go-sdk/service/common/model"
)

func TestCommonRoleBindingSpecRequestMarshalling(t *testing.T) {
	t.Parallel()
	expected := initCommonRoleBindingSpecRequest()
	b, err := json.Marshal(expected)
	require.NoError(t, err)

	var actual common.CommonRoleBindingSpecRequest
	require.NoError(t, json.Unmarshal(b, &actual))
	require.Equal(t, expected, actual)
}

func initCommonRoleBindingSpecRequest() common.CommonRoleBindingSpecRequest {
	var v common.CommonRoleBindingSpecRequest
	return v
}
