// Code generated by mwsapigen, DO NOT EDIT.

package model_test

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/require"

	commonmodel "go.mws.cloud/go-sdk/service/common/model"
)

func TestResourceExternalAddressSpecOrRefRequestMarshalling(t *testing.T) {
	t.Parallel()
	expected := initResourceExternalAddressSpecOrRefRequest()
	b, err := json.Marshal(expected)
	require.NoError(t, err)

	var actual commonmodel.ResourceExternalAddressSpecOrRefRequest
	require.NoError(t, json.Unmarshal(b, &actual))
	require.Equal(t, expected, actual)
}

func initResourceExternalAddressSpecOrRefRequest() commonmodel.ResourceExternalAddressSpecOrRefRequest {
	var v commonmodel.ResourceExternalAddressSpecOrRefRequest
	return v
}
