// Code generated by mwsapigen, DO NOT EDIT.

package model_test

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/require"

	common "go.mws.cloud/go-sdk/service/common/model"
)

func TestTypedUsageOptionalResponseMarshalling(t *testing.T) {
	t.Parallel()
	expected := initTypedUsageOptionalResponse()
	b, err := json.Marshal(expected)
	require.NoError(t, err)

	var actual common.TypedUsageOptionalResponse
	require.NoError(t, json.Unmarshal(b, &actual))
	require.Equal(t, expected, actual)
}

func initTypedUsageOptionalResponse() common.TypedUsageOptionalResponse {
	var v common.TypedUsageOptionalResponse
	return v
}
