// Code generated by mwsapigen, DO NOT EDIT.

package model_test

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/require"
	"go.mws.cloud/util-toolset/pkg/utils/ptr"

	common "go.mws.cloud/go-sdk/service/common/model"
)

func TestUpdateTypedResourceMetadataMarshalling(t *testing.T) {
	expected := ptr.Get(initTypedResourceMetadata()).AsUpdateModel()
	b, err := json.Marshal(expected)
	require.NoError(t, err)

	var actual common.UpdateTypedResourceMetadata
	require.NoError(t, json.Unmarshal(b, &actual))
	require.Equal(t, expected, actual)
}
