// Code generated by mwsapigen, DO NOT EDIT.

package model_test

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/require"

	commonmodel "go.mws.cloud/go-sdk/service/common/model"
)

func TestVpcAddressGroupSpecOrRefOptionalResponseMarshalling(t *testing.T) {
	t.Parallel()
	expected := initVpcAddressGroupSpecOrRefOptionalResponse()
	b, err := json.Marshal(expected)
	require.NoError(t, err)

	var actual commonmodel.VpcAddressGroupSpecOrRefOptionalResponse
	require.NoError(t, json.Unmarshal(b, &actual))
	require.Equal(t, expected, actual)
}

func initVpcAddressGroupSpecOrRefOptionalResponse() commonmodel.VpcAddressGroupSpecOrRefOptionalResponse {
	var v commonmodel.VpcAddressGroupSpecOrRefOptionalResponse
	return v
}
