// Code generated by mwsapigen, DO NOT EDIT.

package model_test

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/require"
	"go.mws.cloud/go-sdk/pkg/apimodels/units/duration"

	common "go.mws.cloud/go-sdk/service/common/model"
)

func TestVpcAddressDnsSpecResponseMarshalling(t *testing.T) {
	t.Parallel()
	expected := initVpcAddressDnsSpecResponse()
	b, err := json.Marshal(expected)
	require.NoError(t, err)

	var actual common.VpcAddressDnsSpecResponse
	require.NoError(t, json.Unmarshal(b, &actual))
	require.Equal(t, expected, actual)
}

func initVpcAddressDnsSpecResponse() common.VpcAddressDnsSpecResponse {
	var v common.VpcAddressDnsSpecResponse
	v.Ttl = duration.MustParseString("PT0S")
	return v
}
