// Code generated by mwsapigen, DO NOT EDIT.

package model_test

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/require"

	commonmodel "go.mws.cloud/go-sdk/service/common/model"
)

func TestVpcAddressGroupSpecResponseMarshalling(t *testing.T) {
	t.Parallel()
	expected := initVpcAddressGroupSpecResponse()
	b, err := json.Marshal(expected)
	require.NoError(t, err)

	var actual commonmodel.VpcAddressGroupSpecResponse
	require.NoError(t, json.Unmarshal(b, &actual))
	require.Equal(t, expected, actual)
}

func initVpcAddressGroupSpecResponse() commonmodel.VpcAddressGroupSpecResponse {
	var v commonmodel.VpcAddressGroupSpecResponse
	v.Addresses = make([]commonmodel.ResourceAddressSpecOrRefResponse, 0)
	return v
}
