// Code generated by mwsapigen, DO NOT EDIT.

package model_test

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/require"

	commonmodel "go.mws.cloud/go-sdk/service/common/model"
)

func TestWeeklyMaintenanceWindowMarshalling(t *testing.T) {
	t.Parallel()
	expected := initWeeklyMaintenanceWindow()
	b, err := json.Marshal(expected)
	require.NoError(t, err)

	var actual commonmodel.WeeklyMaintenanceWindow
	require.NoError(t, json.Unmarshal(b, &actual))
	require.Equal(t, expected, actual)
}

func initWeeklyMaintenanceWindow() commonmodel.WeeklyMaintenanceWindow {
	var v commonmodel.WeeklyMaintenanceWindow
	v.Days = make([]commonmodel.DayOfWeek, 0)
	return v
}
