// Code generated by mwsapigen, DO NOT EDIT.

package client

import (
	"context"
	"errors"
	"net/http"
	"net/url"

	commonclient "go.mws.cloud/go-sdk/internal/client"
	commonattribute "go.mws.cloud/go-sdk/internal/client/interceptors/attribute"
	"go.mws.cloud/go-sdk/internal/conv"
	mwserrors "go.mws.cloud/go-sdk/mws/errors"
	"go.mws.cloud/go-sdk/service/rm/client"
)

// ListProjectsV3 листинг проектов. Авторизация управляется флагом onlyAvailableProjects. onlyAvailableProjects=false (по умолчанию) — требуется rm.project.list на организации (одна проверка прав на весь список). onlyAvailableProjects=true — per-project фильтрация через access-service :availableResources с правом rm.project.get; rm.project.list не нужен; возвращаются только проекты, на которые у subject есть rm.project.get; запрос медленнее на больших коллекциях.
// Гарантируется, что либо будет заполнено одно из полей ответа, либо вернется ошибка.
//
// Путь: GET /rm/v3/projects
func (c *Project) ListProjectsV3(ctx context.Context, request client.ListProjectsV3Request) (r *client.ListProjectsV3Response, err error) {
	ctx = c.setListProjectsV3Attributes(ctx)
	r = &client.ListProjectsV3Response{}

	if err = c.client.Intercept(ctx, &request, r, c.listProjectsV3Invoker); err != nil {
		return nil, err
	}

	return r, nil
}

func (c *Project) setListProjectsV3Attributes(ctx context.Context) context.Context {
	a := []commonattribute.KeyValue{
		commonattribute.String(commonattribute.Method, "ListProjectsV3"),
		commonattribute.String(commonattribute.PathTemplate, "/rm/v3/projects"),
		commonattribute.String(commonattribute.ProjectName, "rm"),
		commonattribute.String(commonattribute.ServiceName, "project"),
	}

	return commonattribute.WithContext(ctx, a...)
}

func (c *Project) listProjectsV3Invoker(ctx context.Context, anyReq any, response commonclient.APIResp) error {
	request := anyReq.(*client.ListProjectsV3Request)

	requestURL, _ := url.JoinPath(c.serverURL.String(),
		"rm",
		"v3",
		"projects")

	httpReq, err := http.NewRequestWithContext(ctx, "GET", requestURL, http.NoBody)
	if err != nil {
		return err
	}

	httpReq.URL.RawQuery = c.queryListProjectsV3(request)

	commonclient.AddOutgoingMetadataToHeader(ctx, httpReq)
	c.headerListProjectsV3(httpReq, request)

	httpResp, err := c.client.Do(httpReq)
	if err != nil {
		return mwserrors.NewTransportError(err)
	}

	defer func() {
		cErr := httpResp.Body.Close()
		if cErr != nil {
			err = errors.Join(err, cErr)
		}
	}()

	decodedResp, err := decodeListProjectsV3Response(httpResp)
	if err != nil {
		return err
	}

	respPtr := response.(*client.ListProjectsV3Response)
	*respPtr = *decodedResp

	return nil
}

func (c *Project) queryListProjectsV3(request *client.ListProjectsV3Request) string {
	q := make(url.Values)
	if request.Organization != nil {
		q.Add("organization", conv.StringToString(*request.Organization))
	}
	if request.PageSize != nil {
		q.Add("pageSize", conv.IntToString(*request.PageSize))
	}
	if request.PageToken != nil {
		q.Add("pageToken", conv.StringToString(*request.PageToken))
	}
	if request.Filter != nil {
		q.Add("filter", conv.StringToString(*request.Filter))
	}
	if request.OrderBy != nil {
		q.Add("orderBy", conv.StringToString(*request.OrderBy))
	}
	if request.ShowDeleted != nil {
		q.Add("showDeleted", conv.StringToString(*request.ShowDeleted))
	}
	if request.OnlyAvailableProjects != nil {
		q.Add("onlyAvailableProjects", conv.BoolToString(*request.OnlyAvailableProjects))
	}
	return q.Encode()
}

func (c *Project) headerListProjectsV3(req *http.Request, request *client.ListProjectsV3Request) {
	req.Header.Add("Authorization", conv.StringToString(request.Authorization))
}
