// Code generated by mwsapigen, DO NOT EDIT.

package client

import (
	"context"

	mwsinternalerrors "go.mws.cloud/go-sdk/internal/errors"
	"go.mws.cloud/go-sdk/pkg/apimodels/sensitive"
	commonmodel "go.mws.cloud/go-sdk/service/common/model"
	"go.mws.cloud/go-sdk/service/vpc/model"
)

type ServiceEndpoint interface {
	// ListServiceEndpoints list service endpoints.
	//
	// Путь: GET /vpc/v1/projects/{project}/networks/{network}/serviceEndpoints
	ListServiceEndpoints(context.Context, ListServiceEndpointsRequest) (*ListServiceEndpointsResponse, error)
	// DeleteServiceEndpoint позволяет удалить точку доступа Private Link.
	//
	// Путь: DELETE /vpc/v1/projects/{project}/networks/{network}/serviceEndpoints/{serviceEndpoint}
	DeleteServiceEndpoint(context.Context, DeleteServiceEndpointRequest) (*DeleteServiceEndpointResponse, error)
	// GetServiceEndpoint позволяет получить информацию о точке доступа Private Link.
	//
	// Путь: GET /vpc/v1/projects/{project}/networks/{network}/serviceEndpoints/{serviceEndpoint}
	GetServiceEndpoint(context.Context, GetServiceEndpointRequest) (*GetServiceEndpointResponse, error)
	// UpsertServiceEndpoint позволяет создать или изменить точку доступа Private Link.
	//
	// Путь: POST /vpc/v1/projects/{project}/networks/{network}/serviceEndpoints/{serviceEndpoint}
	UpsertServiceEndpoint(context.Context, UpsertServiceEndpointRequest) (*UpsertServiceEndpointResponse, error)
	// CreateServiceEndpoint позволяет создать или изменить точку доступа Private Link.
	// Данный метод не описан в OpenAPI-спецификации, он был сгенерирован на основе операции upsert, для удобства.
	//
	// Путь: POST /vpc/v1/projects/{project}/networks/{network}/serviceEndpoints/{serviceEndpoint}?createOnly=true
	CreateServiceEndpoint(context.Context, UpsertServiceEndpointRequest) (*UpsertServiceEndpointResponse, error)
	// UpdateServiceEndpoint позволяет создать или изменить точку доступа Private Link.
	// Данный метод не описан в OpenAPI-спецификации, он был сгенерирован на основе операции upsert, для удобства.
	//
	// Путь: POST /vpc/v1/projects/{project}/networks/{network}/serviceEndpoints/{serviceEndpoint}?updateOnly=true
	UpdateServiceEndpoint(context.Context, UpdateServiceEndpointRequest) (*UpsertServiceEndpointResponse, error)
}

type ListServiceEndpointsRequest struct {
	// Токен авторизации IAM
	Authorization sensitive.Sensitive[string] // header: "Authorization"
	// Путь к проекту.
	Project string // path: "project"
	// Имя сети
	Network string // path: "network"
	// Максимальное количество объектов, которые клиент готов принять. Сервис определяет значение по умолчанию и верхнюю границу
	PageSize *int // query: "pageSize"
	// Строка, из предыдущего ответа на аналогичный запрос, для получения следующей страницы с объектами. Не задано для получения первой страницы
	PageToken *string // query: "pageToken"
	// Строка фильтра.
	// Для фильтрации используется ограниченная реализация AIP-160 (https://google.aip.dev/160).
	// Она включает в себя операции =, !=, OR, AND и (), фильтрацию свойств вложенных объектов и wildcard-поиск подстрок
	Filter *string // query: "filter"
	// Строка сортировки.
	// Для сортировки используется реализация AIP-132 (https://google.aip.dev/132#ordering).
	// Указывается перечислением полей с направлением сортировки (asc, desc) через запятую.
	// По умолчанию используется сортировка по возрастанию (asc)
	OrderBy *string // query: "orderBy"
}

func (m *ListServiceEndpointsRequest) SetAuthorization(authorization sensitive.Sensitive[string]) {
	m.Authorization = authorization
}

func (m ListServiceEndpointsRequest) GetProject() string {
	return m.Project
}

func (m *ListServiceEndpointsRequest) SetProject(project string) {
	m.Project = project
}

func (m ListServiceEndpointsRequest) WithPageToken(token *string) ListServiceEndpointsRequest {
	m.PageToken = token
	return m
}

type ListServiceEndpointsResponse struct {
	Code        int
	Response200 *model.ListServiceEndpointsResponseOptionalResponse
	Response400 *commonmodel.ApiError
	Response403 *commonmodel.ApiError
	Response404 *commonmodel.ApiError
	Response408 *commonmodel.ApiError
	Response412 *commonmodel.ApiError
	Response499 *commonmodel.ApiError
	Response500 *commonmodel.ApiError

	errorWrapper func(err error) error
}

func (m *ListServiceEndpointsResponse) GetCode() int {
	return m.Code
}

func (m *ListServiceEndpointsResponse) GetErr() (err error) {
	defer func() {
		if err != nil && m.errorWrapper != nil {
			err = m.errorWrapper(err)
		}
	}()
	if m.Response400 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response400)
	}
	if m.Response403 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response403)
	}
	if m.Response404 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response404)
	}
	if m.Response408 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response408)
	}
	if m.Response412 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response412)
	}
	if m.Response499 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response499)
	}
	if m.Response500 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response500)
	}
	return nil
}

func (m *ListServiceEndpointsResponse) SetErrorWrapper(f func(err error) error) {
	if m != nil {
		m.errorWrapper = f
	}
}

type DeleteServiceEndpointRequest struct {
	// Токен авторизации IAM
	Authorization sensitive.Sensitive[string] // header: "Authorization"
	// Ключ идемпотентности
	IdempotencyKey *string // header: "Idempotency-Key"
	// Путь к проекту.
	Project string // path: "project"
	// Имя сети
	Network string // path: "network"
	// Имя точки доступа Private Link
	ServiceEndpoint string // path: "serviceEndpoint"
}

func (m *DeleteServiceEndpointRequest) SetAuthorization(authorization sensitive.Sensitive[string]) {
	m.Authorization = authorization
}

func (m DeleteServiceEndpointRequest) GetProject() string {
	return m.Project
}

func (m *DeleteServiceEndpointRequest) SetProject(project string) {
	m.Project = project
}

func (m *DeleteServiceEndpointRequest) getServiceEndpointRequest() GetServiceEndpointRequest {
	return GetServiceEndpointRequest{
		Authorization:   m.Authorization,
		Project:         m.Project,
		Network:         m.Network,
		ServiceEndpoint: m.ServiceEndpoint,
	}
}

type DeleteServiceEndpointResponse struct {
	Code        int
	Response204 bool // empty response
	Response400 *commonmodel.ApiError
	Response403 *commonmodel.ApiError
	Response404 *commonmodel.ApiError
	Response408 *commonmodel.ApiError
	Response412 *commonmodel.ApiError
	Response499 *commonmodel.ApiError
	Response500 *commonmodel.ApiError

	errorWrapper func(err error) error
}

func (m *DeleteServiceEndpointResponse) GetCode() int {
	return m.Code
}

func (m *DeleteServiceEndpointResponse) GetErr() (err error) {
	defer func() {
		if err != nil && m.errorWrapper != nil {
			err = m.errorWrapper(err)
		}
	}()
	if m.Response400 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response400)
	}
	if m.Response403 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response403)
	}
	if m.Response404 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response404)
	}
	if m.Response408 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response408)
	}
	if m.Response412 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response412)
	}
	if m.Response499 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response499)
	}
	if m.Response500 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response500)
	}
	return nil
}

func (m *DeleteServiceEndpointResponse) SetErrorWrapper(f func(err error) error) {
	if m != nil {
		m.errorWrapper = f
	}
}

type GetServiceEndpointRequest struct {
	// Токен авторизации IAM
	Authorization sensitive.Sensitive[string] // header: "Authorization"
	// Путь к проекту.
	Project string // path: "project"
	// Имя сети
	Network string // path: "network"
	// Имя точки доступа Private Link
	ServiceEndpoint string // path: "serviceEndpoint"
}

func (m *GetServiceEndpointRequest) SetAuthorization(authorization sensitive.Sensitive[string]) {
	m.Authorization = authorization
}

func (m GetServiceEndpointRequest) GetProject() string {
	return m.Project
}

func (m *GetServiceEndpointRequest) SetProject(project string) {
	m.Project = project
}

type GetServiceEndpointResponse struct {
	Code        int
	Response200 *model.ServiceEndpointOptionalResponse
	Response400 *commonmodel.ApiError
	Response403 *commonmodel.ApiError
	Response404 *commonmodel.ApiError
	Response408 *commonmodel.ApiError
	Response412 *commonmodel.ApiError
	Response499 *commonmodel.ApiError
	Response500 *commonmodel.ApiError

	errorWrapper func(err error) error
}

func (m *GetServiceEndpointResponse) GetCode() int {
	return m.Code
}

func (m *GetServiceEndpointResponse) GetErr() (err error) {
	defer func() {
		if err != nil && m.errorWrapper != nil {
			err = m.errorWrapper(err)
		}
	}()
	if m.Response400 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response400)
	}
	if m.Response403 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response403)
	}
	if m.Response404 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response404)
	}
	if m.Response408 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response408)
	}
	if m.Response412 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response412)
	}
	if m.Response499 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response499)
	}
	if m.Response500 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response500)
	}
	return nil
}

func (m *GetServiceEndpointResponse) SetErrorWrapper(f func(err error) error) {
	if m != nil {
		m.errorWrapper = f
	}
}

type UpsertServiceEndpointRequest struct {
	// Токен авторизации IAM
	Authorization sensitive.Sensitive[string] // header: "Authorization"
	// Ключ идемпотентности
	IdempotencyKey *string // header: "Idempotency-Key"
	// Путь к проекту.
	Project string // path: "project"
	// Имя сети
	Network string // path: "network"
	// Имя точки доступа Private Link
	ServiceEndpoint string // path: "serviceEndpoint"
	// Данные для создания или изменения точки доступа Private Link
	Body model.ServiceEndpointRequest // body
}

func (m *UpsertServiceEndpointRequest) SetAuthorization(authorization sensitive.Sensitive[string]) {
	m.Authorization = authorization
}

func (m UpsertServiceEndpointRequest) GetProject() string {
	return m.Project
}

func (m *UpsertServiceEndpointRequest) SetProject(project string) {
	m.Project = project
}

func (m *UpsertServiceEndpointRequest) getServiceEndpointRequest() GetServiceEndpointRequest {
	return GetServiceEndpointRequest{
		Authorization:   m.Authorization,
		Project:         m.Project,
		Network:         m.Network,
		ServiceEndpoint: m.ServiceEndpoint,
	}
}

type UpdateServiceEndpointRequest struct {
	// Токен авторизации IAM
	Authorization sensitive.Sensitive[string] // header: "Authorization"
	// Ключ идемпотентности
	IdempotencyKey *string // header: "Idempotency-Key"
	// Путь к проекту.
	Project string // path: "project"
	// Имя сети
	Network string // path: "network"
	// Имя точки доступа Private Link
	ServiceEndpoint string // path: "serviceEndpoint"
	// Данные для создания или изменения точки доступа Private Link
	Body model.UpdateServiceEndpointRequest // body
}

func (m *UpdateServiceEndpointRequest) SetAuthorization(authorization sensitive.Sensitive[string]) {
	m.Authorization = authorization
}

func (m UpdateServiceEndpointRequest) GetProject() string {
	return m.Project
}

func (m *UpdateServiceEndpointRequest) SetProject(project string) {
	m.Project = project
}

func (m *UpdateServiceEndpointRequest) getServiceEndpointRequest() GetServiceEndpointRequest {
	return GetServiceEndpointRequest{
		Authorization:   m.Authorization,
		Project:         m.Project,
		Network:         m.Network,
		ServiceEndpoint: m.ServiceEndpoint,
	}
}

type UpsertServiceEndpointResponse struct {
	Code        int
	Response200 *model.ServiceEndpointOptionalResponse
	Response400 *commonmodel.ApiError
	Response403 *commonmodel.ApiError
	Response404 *commonmodel.ApiError
	Response408 *commonmodel.ApiError
	Response409 *commonmodel.ApiError
	Response412 *commonmodel.ApiError
	Response422 *commonmodel.ApiError
	Response499 *commonmodel.ApiError
	Response500 *commonmodel.ApiError

	errorWrapper func(err error) error
}

func (m *UpsertServiceEndpointResponse) GetCode() int {
	return m.Code
}

func (m *UpsertServiceEndpointResponse) GetErr() (err error) {
	defer func() {
		if err != nil && m.errorWrapper != nil {
			err = m.errorWrapper(err)
		}
	}()
	if m.Response400 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response400)
	}
	if m.Response403 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response403)
	}
	if m.Response404 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response404)
	}
	if m.Response408 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response408)
	}
	if m.Response409 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response409)
	}
	if m.Response412 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response412)
	}
	if m.Response422 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response422)
	}
	if m.Response499 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response499)
	}
	if m.Response500 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response500)
	}
	return nil
}

func (m *UpsertServiceEndpointResponse) SetErrorWrapper(f func(err error) error) {
	if m != nil {
		m.errorWrapper = f
	}
}
