// Code generated by mwsapigen, DO NOT EDIT.

package model_test

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/service/mkafka/model"
)

func TestKafkaConnectorStateMarshalling(t *testing.T) {
	t.Parallel()
	expected := initKafkaConnectorState()
	b, err := json.Marshal(expected)
	require.NoError(t, err)

	var actual model.KafkaConnectorState
	require.NoError(t, json.Unmarshal(b, &actual))
	require.Equal(t, expected, actual)
}

func initKafkaConnectorState() model.KafkaConnectorState {
	var v model.KafkaConnectorState
	return v
}
