// Code generated by mwsapigen, DO NOT EDIT.

package model_test

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/service/mkafka/model"
)

func TestKafkaEndpointResponseMarshalling(t *testing.T) {
	t.Parallel()
	expected := initKafkaEndpointResponse()
	b, err := json.Marshal(expected)
	require.NoError(t, err)

	var actual model.KafkaEndpointResponse
	require.NoError(t, json.Unmarshal(b, &actual))
	require.Equal(t, expected, actual)
}

func initKafkaEndpointResponse() model.KafkaEndpointResponse {
	var v model.KafkaEndpointResponse
	v.BrokerAddresses = make([]model.KafkaEndpointBrokerAddressResponse, 0)
	return v
}
