// Code generated by mwsapigen, DO NOT EDIT.

package model_test

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/require"
	"go.mws.cloud/go-sdk/pkg/apimodels/units/bytesize"

	"go.mws.cloud/go-sdk/service/mkafka/model"
)

func TestKafkaInstanceSpecResponseMarshalling(t *testing.T) {
	t.Parallel()
	expected := initKafkaInstanceSpecResponse()
	b, err := json.Marshal(expected)
	require.NoError(t, err)

	var actual model.KafkaInstanceSpecResponse
	require.NoError(t, json.Unmarshal(b, &actual))
	require.Equal(t, expected, actual)
}

func initKafkaInstanceSpecResponse() model.KafkaInstanceSpecResponse {
	var v model.KafkaInstanceSpecResponse
	v.Disk.Size = bytesize.MustParseString("0 B")
	return v
}
