// Code generated by mwsapigen, DO NOT EDIT.

package model_test

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/service/mkafka/model"
)

func TestKafkaInstanceStatusResponseMarshalling(t *testing.T) {
	t.Parallel()
	expected := initKafkaInstanceStatusResponse()
	b, err := json.Marshal(expected)
	require.NoError(t, err)

	var actual model.KafkaInstanceStatusResponse
	require.NoError(t, json.Unmarshal(b, &actual))
	require.Equal(t, expected, actual)
}

func initKafkaInstanceStatusResponse() model.KafkaInstanceStatusResponse {
	var v model.KafkaInstanceStatusResponse
	return v
}
