// Code generated by mwsapigen, DO NOT EDIT.

package model_test

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/require"
	"go.mws.cloud/go-sdk/pkg/apimodels/units/bytesize"

	"go.mws.cloud/go-sdk/service/mkafka/model"
)

func TestKafkaDataDiskSpecRequestMarshalling(t *testing.T) {
	t.Parallel()
	expected := initKafkaDataDiskSpecRequest()
	b, err := json.Marshal(expected)
	require.NoError(t, err)

	var actual model.KafkaDataDiskSpecRequest
	require.NoError(t, json.Unmarshal(b, &actual))
	require.Equal(t, expected, actual)
}

func initKafkaDataDiskSpecRequest() model.KafkaDataDiskSpecRequest {
	var v model.KafkaDataDiskSpecRequest
	v.Size = bytesize.MustParseString("0 B")
	return v
}
