// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/go-faster/jx"

	"go.mws.cloud/go-sdk/internal/conv"
	"go.mws.cloud/go-sdk/internal/decode"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
)

func (m UpdateNlbHealthCheckHttpRequest) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	if err := m.Encode(&e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (m *UpdateNlbHealthCheckHttpRequest) Encode(e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	if err := m.encodeFields(e); err != nil {
		return err
	}
	e.ObjEnd()
	return nil
}

func (m *UpdateNlbHealthCheckHttpRequest) encodeFields(e *jx.Encoder) error {
	if m.Port.IsSet() {
		e.FieldStart("port")
		e.Int(m.Port.Value)
	}

	if m.Path.IsSet() {
		e.FieldStart("path")
		e.Str(m.Path.Value)
	}

	if m.ExpectedCode.IsSet() {
		e.FieldStart("expectedCode")
		e.Int(m.ExpectedCode.Value)
	}
	return nil
}

func (m *UpdateNlbHealthCheckHttpRequest) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *UpdateNlbHealthCheckHttpRequest) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("UpdateNlbHealthCheckHttpRequest")
	}

	return d.ObjBytes(reserrors.PathAccumulatorErrorObjBytesFuncWrap(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "port":
			v, err := decode.Int(d)
			if err != nil {
				return err
			}

			m.Port.SetTo(v)
			return nil
		case "path":
			v, err := decode.Str(d)
			if err != nil {
				return err
			}

			m.Path.SetTo(v)
			return nil
		case "expectedCode":
			v, err := decode.Int(d)
			if err != nil {
				return err
			}

			m.ExpectedCode.SetTo(v)
			return nil
		default:
			return d.Skip()
		}
	}))
}
