// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	commonmodel "go.mws.cloud/go-sdk/service/common/model"
)

func NlbListenerInternalRequestToOptionalResponse(request *NlbListenerInternalRequest) (*NlbListenerInternalOptionalResponse, error) {
	if request == nil {
		return nil, nil
	}
	var response NlbListenerInternalOptionalResponse
	tmpAddress, err := commonmodel.ResourceAddressSpecOrRefRequestToOptionalResponse(&request.Address)
	if err != nil {
		return nil, err
	}
	response.Address = *tmpAddress
	return &response, nil
}
