// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"context"

	"github.com/go-faster/jx"

	"go.mws.cloud/go-sdk/internal/conv"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	"go.mws.cloud/go-sdk/pkg/optional"
)

// Конфигурация IP-адреса, на котором балансировщик будет принимать запросы.
// Real OAPI model name: NlbListener
type NlbListenerOptionalResponse struct {
	// Конфигурация IP-адреса внутреннего балансировщика.
	Internal optional.OptionalNil[NlbListenerInternalOptionalResponse] `json:"internal,omitempty" yaml:"internal,omitempty"`
	// Конфигурация IP-адреса внутреннего балансировщика.
	External optional.OptionalNil[NlbListenerExternalOptionalResponse] `json:"external,omitempty" yaml:"external,omitempty"`
}

func (m *NlbListenerOptionalResponse) GetInternal() *NlbListenerInternalOptionalResponse {
	if m != nil && m.Internal.IsSet() && !m.Internal.IsNull() {
		return &m.Internal.Value
	}
	return nil
}

func (m *NlbListenerOptionalResponse) GetInternalOr(val NlbListenerInternalOptionalResponse) NlbListenerInternalOptionalResponse {
	if m != nil && m.Internal.IsSet() && !m.Internal.IsNull() {
		return m.Internal.Value
	}
	return val
}

func (m *NlbListenerOptionalResponse) GetExternal() *NlbListenerExternalOptionalResponse {
	if m != nil && m.External.IsSet() && !m.External.IsNull() {
		return &m.External.Value
	}
	return nil
}

func (m *NlbListenerOptionalResponse) GetExternalOr(val NlbListenerExternalOptionalResponse) NlbListenerExternalOptionalResponse {
	if m != nil && m.External.IsSet() && !m.External.IsNull() {
		return m.External.Value
	}
	return val
}

func (m *NlbListenerOptionalResponse) Clone() *NlbListenerOptionalResponse {
	if m == nil {
		return nil
	}

	clone := *m
	if clone.Internal.IsSet() {
		clone.Internal.Value = *m.Internal.Value.Clone()
	}
	if clone.External.IsSet() {
		clone.External.Value = *m.External.Value.Clone()
	}
	return &clone
}

func (m *NlbListenerOptionalResponse) Parse(ctx context.Context) error {
	if m == nil {
		return nil
	}

	if m.Internal.IsSet() && !m.Internal.IsNull() {
		if err := m.Internal.Value.Parse(ctx); err != nil {
			return reserrors.NewPathAccumulatorError("Internal", err)
		}
	}

	if m.External.IsSet() && !m.External.IsNull() {
		if err := m.External.Value.Parse(ctx); err != nil {
			return reserrors.NewPathAccumulatorError("External", err)
		}
	}

	return nil
}

// JSON methods

func (m NlbListenerOptionalResponse) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	if err := m.Encode(&e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (m *NlbListenerOptionalResponse) Encode(e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	if err := m.encodeFields(e); err != nil {
		return err
	}
	e.ObjEnd()
	return nil
}

func (m *NlbListenerOptionalResponse) encodeFields(e *jx.Encoder) error {
	if m.Internal.IsSet() {
		e.FieldStart("internal")
		if m.Internal.IsNull() {
			e.Null()
		} else {
			if err := m.Internal.Value.Encode(e); err != nil {
				return err
			}
		}
	}

	if m.External.IsSet() {
		e.FieldStart("external")
		if m.External.IsNull() {
			e.Null()
		} else {
			if err := m.External.Value.Encode(e); err != nil {
				return err
			}
		}
	}
	return nil
}

func (m *NlbListenerOptionalResponse) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *NlbListenerOptionalResponse) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("NlbListenerOptionalResponse")
	}

	return d.ObjBytes(reserrors.PathAccumulatorErrorObjBytesFuncWrap(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "internal":
			if d.Next() == jx.Null {
				m.Internal.SetToNull()
				return d.Null()
			}

			var v NlbListenerInternalOptionalResponse
			if err := v.Decode(d); err != nil {
				return err
			}

			m.Internal.SetTo(v)
			return nil
		case "external":
			if d.Next() == jx.Null {
				m.External.SetToNull()
				return d.Null()
			}

			var v NlbListenerExternalOptionalResponse
			if err := v.Decode(d); err != nil {
				return err
			}

			m.External.SetTo(v)
			return nil
		default:
			return d.Skip()
		}
	}))
}
