// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"context"

	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	commonmodel "go.mws.cloud/go-sdk/service/common/model"
)

// Конфигурация адреса внешнего балансировщика
// Real OAPI model name: NlbListenerExternal
type NlbListenerExternalRequest struct {
	// Описывает ссылку на внешний адрес или спецификацию внешнего адреса как дополнительный ресурс.
	Address commonmodel.ResourceExternalAddressSpecOrRefRequest `json:"address" yaml:"address"`
}

func (m *NlbListenerExternalRequest) GetAddress() commonmodel.ResourceExternalAddressSpecOrRefRequest {
	if m != nil {
		return m.Address
	}
	return commonmodel.ResourceExternalAddressSpecOrRefRequest{}
}

func (m *NlbListenerExternalRequest) SetAddress(val commonmodel.ResourceExternalAddressSpecOrRefRequest) {
	m.Address = val
}

func (m *NlbListenerExternalRequest) Clone() *NlbListenerExternalRequest {
	if m == nil {
		return nil
	}

	clone := *m
	clone.Address = *m.Address.Clone()
	return &clone
}

func (m *NlbListenerExternalRequest) Parse(ctx context.Context) error {
	if m == nil {
		return nil
	}

	if err := m.Address.Parse(ctx); err != nil {
		return reserrors.NewPathAccumulatorError("Address", err)
	}

	return nil
}
