// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"fmt"

	"github.com/go-faster/jx"
	"go.mws.cloud/util-toolset/pkg/utils/consterr"

	"go.mws.cloud/go-sdk/internal/conv"
	"go.mws.cloud/go-sdk/internal/decode"
)

type CryptoKeyAlgorithm string

const (
	CryptoKeyAlgorithm_AES_128_GCM CryptoKeyAlgorithm = "AES_128_GCM"
	CryptoKeyAlgorithm_AES_192_GCM CryptoKeyAlgorithm = "AES_192_GCM"
	CryptoKeyAlgorithm_AES_256_GCM CryptoKeyAlgorithm = "AES_256_GCM"

	ErrUnknownCryptoKeyAlgorithm = consterr.Error(`unknown kind, want one of "AES_128_GCM", "AES_192_GCM", "AES_256_GCM"`)
)

func NewCryptoKeyAlgorithm(s string) (CryptoKeyAlgorithm, error) {
	v := CryptoKeyAlgorithm(s)
	if !v.IsValid() {
		return "", fmt.Errorf("%w, got %q", ErrUnknownCryptoKeyAlgorithm, s)
	}
	return v, nil
}

func (m CryptoKeyAlgorithm) String() string {
	return string(m)
}

func (m CryptoKeyAlgorithm) IsValid() bool {
	switch m {
	case CryptoKeyAlgorithm_AES_128_GCM:
		return true
	case CryptoKeyAlgorithm_AES_192_GCM:
		return true
	case CryptoKeyAlgorithm_AES_256_GCM:
		return true
	}
	return false
}

// JSON methods

func (m CryptoKeyAlgorithm) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	if err := m.Encode(&e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (m *CryptoKeyAlgorithm) Encode(e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.Str(string(*m))
	return nil
}

func (m *CryptoKeyAlgorithm) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *CryptoKeyAlgorithm) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("CryptoKeyAlgorithm")
	}

	v, err := decode.StrBytes(d)
	if err != nil {
		return err
	}

	*m = CryptoKeyAlgorithm(v)
	return nil
}
