// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/go-faster/jx"

	"go.mws.cloud/go-sdk/internal/conv"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	commonmodel "go.mws.cloud/go-sdk/service/common/model"
)

// Real OAPI model name: CryptoKeyVersion
type CryptoKeyVersionRequest struct {
	// Набор общих для всех пользовательских объектов атрибутов. Может быть расширен атрибутами, специфичными для контейнеров.
	Metadata *commonmodel.CommonTypedResourceMetadataRequest `json:"metadata,omitempty" yaml:"metadata,omitempty"`
	Spec     CryptoKeyVersionSpecRequest                     `json:"spec" yaml:"spec"`
}

func (m *CryptoKeyVersionRequest) GetMetadata() *commonmodel.CommonTypedResourceMetadataRequest {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *CryptoKeyVersionRequest) SetMetadata(val *commonmodel.CommonTypedResourceMetadataRequest) {
	m.Metadata = val
}

func (m *CryptoKeyVersionRequest) GetMetadataOr(val commonmodel.CommonTypedResourceMetadataRequest) commonmodel.CommonTypedResourceMetadataRequest {
	if m != nil && m.Metadata != nil {
		return *m.Metadata
	}
	return val
}

func (m *CryptoKeyVersionRequest) GetSpec() CryptoKeyVersionSpecRequest {
	if m != nil {
		return m.Spec
	}
	return CryptoKeyVersionSpecRequest{}
}

func (m *CryptoKeyVersionRequest) SetSpec(val CryptoKeyVersionSpecRequest) {
	m.Spec = val
}

func (m *CryptoKeyVersionRequest) Clone() *CryptoKeyVersionRequest {
	if m == nil {
		return nil
	}

	clone := *m
	clone.Metadata = m.Metadata.Clone()
	clone.Spec = *m.Spec.Clone()
	return &clone
}

// JSON methods

func (m CryptoKeyVersionRequest) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	if err := m.Encode(&e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (m *CryptoKeyVersionRequest) Encode(e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	if err := m.encodeFields(e); err != nil {
		return err
	}
	e.ObjEnd()
	return nil
}

func (m *CryptoKeyVersionRequest) encodeFields(e *jx.Encoder) error {
	if m.Metadata != nil {
		e.FieldStart("metadata")
		if err := m.Metadata.Encode(e); err != nil {
			return err
		}
	}

	e.FieldStart("spec")
	if err := m.Spec.Encode(e); err != nil {
		return err
	}
	return nil
}

func (m *CryptoKeyVersionRequest) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *CryptoKeyVersionRequest) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("CryptoKeyVersionRequest")
	}

	requiredFilled := map[string]bool{
		"spec": false,
	}
	err := d.ObjBytes(reserrors.PathAccumulatorErrorObjBytesFuncWrap(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "metadata":
			if d.Next() == jx.Null {
				return d.Null()
			}

			var v commonmodel.CommonTypedResourceMetadataRequest
			if err := v.Decode(d); err != nil {
				return err
			}

			m.Metadata = &v
			return nil
		case "spec":
			var v CryptoKeyVersionSpecRequest
			if err := v.Decode(d); err != nil {
				return err
			}

			m.Spec = v
			requiredFilled["spec"] = true
			return nil
		default:
			return d.Skip()
		}
	}))
	if err != nil {
		return err
	}

	return conv.ValidateRequired(requiredFilled)
}
