// Code generated by mwsapigen, DO NOT EDIT.

package model_test

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/service/mpostgres/model"
)

func TestPostgresNetworkDirectAddressRequestMarshalling(t *testing.T) {
	t.Parallel()
	expected := initPostgresNetworkDirectAddressRequest()
	b, err := json.Marshal(expected)
	require.NoError(t, err)

	var actual model.PostgresNetworkDirectAddressRequest
	require.NoError(t, json.Unmarshal(b, &actual))
	require.Equal(t, expected, actual)
}

func initPostgresNetworkDirectAddressRequest() model.PostgresNetworkDirectAddressRequest {
	var v model.PostgresNetworkDirectAddressRequest
	return v
}
