// Code generated by mwsapigen, DO NOT EDIT.

package model_test

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/service/mpostgres/model"
)

func TestPostgresNetworkAddressSpecRequestMarshalling(t *testing.T) {
	t.Parallel()
	expected := initPostgresNetworkAddressSpecRequest()
	b, err := json.Marshal(expected)
	require.NoError(t, err)

	var actual model.PostgresNetworkAddressSpecRequest
	require.NoError(t, json.Unmarshal(b, &actual))
	require.Equal(t, expected, actual)
}

func initPostgresNetworkAddressSpecRequest() model.PostgresNetworkAddressSpecRequest {
	var v model.PostgresNetworkAddressSpecRequest
	return v
}
