// Code generated by mwsapigen, DO NOT EDIT.

package compute

import (
	"context"

	"github.com/go-faster/jx"

	"go.mws.cloud/go-sdk/internal/conv"
	"go.mws.cloud/go-sdk/internal/decode"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	resparsers "go.mws.cloud/go-sdk/internal/resources/parsers"
	valuesctx "go.mws.cloud/go-sdk/pkg/context/values"
	resifaces "go.mws.cloud/go-sdk/pkg/resources/interfaces"
	resmodels "go.mws.cloud/go-sdk/pkg/resources/models"
)

var (
	SnapshotRefTemplate = resparsers.Template{
		{
			Value:       "snapshot",
			IsConstant:  false,
			SearchAfter: false,
		},
		{
			Value:       "snapshots",
			IsConstant:  true,
			SearchAfter: false,
		},
		{
			Value:       "project",
			IsConstant:  false,
			SearchAfter: true,
		},
		{
			Value:       "projects",
			IsConstant:  true,
			SearchAfter: false,
		},
		{
			Value:       "compute",
			IsConstant:  true,
			SearchAfter: false,
		},
	}
)

func NewSnapshotID(project, snapshot string) SnapshotID {
	m := SnapshotID{
		snapshot: snapshot,
		project:  project,
	}
	m.path = m.ID()
	return m
}

func ParseSnapshotID(path string) (SnapshotID, error) {
	m := SnapshotID{
		path: path,
	}
	if err := m.Parse(context.Background()); err != nil {
		return SnapshotID{}, err
	}
	return m, nil
}

func NewSnapshotIDFromAnyID(resource resmodels.AnyResourceID) (SnapshotID, error) {
	return ParseSnapshotID(resource.ID())
}

type SnapshotID struct {
	snapshot string
	project  string
	path     string
}

func (m *SnapshotID) ResourceName() resifaces.ResourceName {
	if m == nil {
		return ""
	}
	return resifaces.ResourceName(m.snapshot)
}

func (m *SnapshotID) GetSnapshot() string {
	if m == nil {
		return ""
	}
	return m.snapshot
}

func (m *SnapshotID) GetProject() string {
	if m == nil {
		return ""
	}
	return m.project
}

func (m *SnapshotID) ServiceSlug() string {
	return "compute"
}

func (m *SnapshotID) ID() string {
	if m == nil || m.snapshot == "" || m.project == "" {
		return ""
	}

	return m.ServiceSlug() + "/projects/" + m.project + "/snapshots/" + m.snapshot
}

func (m *SnapshotID) String() string {
	return m.ID()
}

func (m *SnapshotID) Parse(ctx context.Context) error {
	if m == nil {
		return nil
	}

	result, err := resparsers.Reference(ctx, m.path, SnapshotRefTemplate.AsID())
	if err != nil {
		return reserrors.NewParseIDError(m.path, err)
	}

	m.snapshot = result["snapshot"]
	m.project = result["project"]

	return nil
}

func (m *SnapshotID) Clone() *SnapshotID {
	if m == nil {
		return nil
	}
	clone := *m
	return &clone
}

func (m SnapshotID) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	if err := m.Encode(&e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (m *SnapshotID) Encode(e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	result := m.ID()
	if result == "" {
		result = m.path
	}
	e.Str(result)
	return nil
}

func (m *SnapshotID) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *SnapshotID) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("SnapshotRef")
	}

	v, err := decode.Str(d)
	if err != nil {
		return err
	}

	m.path = v
	return nil
}

func NewSnapshotRef(project, snapshot string) SnapshotRef {
	m := SnapshotRef{
		id: SnapshotID{
			snapshot: snapshot,
			project:  project,
		},
	}
	m.id.path = m.absolutePath()
	return m
}

func ParseSnapshotRef(ctx context.Context, path string) (SnapshotRef, error) {
	m := SnapshotRef{
		id: SnapshotID{
			path: path,
		},
	}
	if err := m.Parse(ctx); err != nil {
		return SnapshotRef{}, err
	}
	return m, nil
}

func NewSnapshotRefFromAnyRef(ref resmodels.AnyResourceRef) (SnapshotRef, error) {
	ctx := valuesctx.WithValuesStore(context.Background(), ref.GetPathValues())
	return ParseSnapshotRef(ctx, ref.Path())
}

type SnapshotRef struct {
	id SnapshotID
}

func (m *SnapshotRef) ResourceName() resifaces.ResourceName {
	if m == nil {
		return ""
	}
	return m.id.ResourceName()
}

func (m *SnapshotRef) GetSnapshot() string {
	if m == nil {
		return ""
	}
	return m.id.GetSnapshot()
}

func (m *SnapshotRef) GetProject() string {
	if m == nil {
		return ""
	}
	return m.id.GetProject()
}

func (m *SnapshotRef) ServiceSlug() string {
	return "compute"
}

func (m *SnapshotRef) IDPath() string {
	if m == nil {
		return ""
	}
	return m.id.ID()
}

func (m *SnapshotRef) Path() string {
	if m == nil {
		return ""
	}
	if m.id.path == "" {
		return m.absolutePath()
	}
	return m.id.path
}

func (m *SnapshotRef) String() string {
	return m.IDPath()
}

func (m *SnapshotRef) Parse(ctx context.Context) error {
	if m == nil {
		return nil
	}

	result, err := resparsers.Reference(ctx, m.id.path, SnapshotRefTemplate)
	if err != nil {
		return reserrors.NewParseReferenceError(m.id.path, err)
	}

	m.id.snapshot = result["snapshot"]
	m.id.project = result["project"]

	return nil
}

func (m *SnapshotRef) Clone() *SnapshotRef {
	if m == nil {
		return nil
	}
	clone := *m
	return &clone
}

func (m SnapshotRef) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	if err := m.Encode(&e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (m *SnapshotRef) Encode(e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.Str(m.Path())
	return nil
}

func (m *SnapshotRef) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *SnapshotRef) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("SnapshotRef")
	}

	v, err := decode.Str(d)
	if err != nil {
		return err
	}

	m.id.path = v
	return nil
}

func (m *SnapshotRef) absolutePath() string {
	if m == nil || m.id.snapshot == "" || m.id.project == "" {
		return ""
	}

	return "projects/" + m.id.project + "/snapshots/" + m.id.snapshot
}
