// Code generated by mwsapigen, DO NOT EDIT.

package compute

import (
	"context"

	"github.com/go-faster/jx"

	"go.mws.cloud/go-sdk/internal/conv"
	"go.mws.cloud/go-sdk/internal/decode"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	resparsers "go.mws.cloud/go-sdk/internal/resources/parsers"
	valuesctx "go.mws.cloud/go-sdk/pkg/context/values"
	resifaces "go.mws.cloud/go-sdk/pkg/resources/interfaces"
	resmodels "go.mws.cloud/go-sdk/pkg/resources/models"
)

var (
	ZonalPlacementGroupRefTemplate = resparsers.Template{
		{
			Value:       "zonalPlacementGroup",
			IsConstant:  false,
			SearchAfter: false,
		},
		{
			Value:       "zonalPlacementGroups",
			IsConstant:  true,
			SearchAfter: false,
		},
		{
			Value:       "project",
			IsConstant:  false,
			SearchAfter: true,
		},
		{
			Value:       "projects",
			IsConstant:  true,
			SearchAfter: false,
		},
		{
			Value:       "zone",
			IsConstant:  false,
			SearchAfter: true,
		},
		{
			Value:       "zones",
			IsConstant:  true,
			SearchAfter: false,
		},
		{
			Value:       "compute",
			IsConstant:  true,
			SearchAfter: false,
		},
	}
)

func NewZonalPlacementGroupID(zone, project, zonalPlacementGroup string) ZonalPlacementGroupID {
	m := ZonalPlacementGroupID{
		zonalPlacementGroup: zonalPlacementGroup,
		project:             project,
		zone:                zone,
	}
	m.path = m.ID()
	return m
}

func ParseZonalPlacementGroupID(path string) (ZonalPlacementGroupID, error) {
	m := ZonalPlacementGroupID{
		path: path,
	}
	if err := m.Parse(context.Background()); err != nil {
		return ZonalPlacementGroupID{}, err
	}
	return m, nil
}

func NewZonalPlacementGroupIDFromAnyID(resource resmodels.AnyResourceID) (ZonalPlacementGroupID, error) {
	return ParseZonalPlacementGroupID(resource.ID())
}

type ZonalPlacementGroupID struct {
	zonalPlacementGroup string
	project             string
	zone                string
	path                string
}

func (m *ZonalPlacementGroupID) ResourceName() resifaces.ResourceName {
	if m == nil {
		return ""
	}
	return resifaces.ResourceName(m.zonalPlacementGroup)
}

func (m *ZonalPlacementGroupID) GetZonalPlacementGroup() string {
	if m == nil {
		return ""
	}
	return m.zonalPlacementGroup
}

func (m *ZonalPlacementGroupID) GetProject() string {
	if m == nil {
		return ""
	}
	return m.project
}

func (m *ZonalPlacementGroupID) GetZone() string {
	if m == nil {
		return ""
	}
	return m.zone
}

func (m *ZonalPlacementGroupID) ServiceSlug() string {
	return "compute"
}

func (m *ZonalPlacementGroupID) ID() string {
	if m == nil || m.zonalPlacementGroup == "" || m.project == "" || m.zone == "" {
		return ""
	}

	return m.ServiceSlug() + "/zones/" + m.zone + "/projects/" + m.project + "/zonalPlacementGroups/" + m.zonalPlacementGroup
}

func (m *ZonalPlacementGroupID) String() string {
	return m.ID()
}

func (m *ZonalPlacementGroupID) Parse(ctx context.Context) error {
	if m == nil {
		return nil
	}

	result, err := resparsers.Reference(ctx, m.path, ZonalPlacementGroupRefTemplate.AsID())
	if err != nil {
		return reserrors.NewParseIDError(m.path, err)
	}

	m.zonalPlacementGroup = result["zonalPlacementGroup"]
	m.project = result["project"]
	m.zone = result["zone"]

	return nil
}

func (m *ZonalPlacementGroupID) Clone() *ZonalPlacementGroupID {
	if m == nil {
		return nil
	}
	clone := *m
	return &clone
}

func (m ZonalPlacementGroupID) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	if err := m.Encode(&e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (m *ZonalPlacementGroupID) Encode(e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	result := m.ID()
	if result == "" {
		result = m.path
	}
	e.Str(result)
	return nil
}

func (m *ZonalPlacementGroupID) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *ZonalPlacementGroupID) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("ZonalPlacementGroupRef")
	}

	v, err := decode.Str(d)
	if err != nil {
		return err
	}

	m.path = v
	return nil
}

func NewZonalPlacementGroupRef(zone, project, zonalPlacementGroup string) ZonalPlacementGroupRef {
	m := ZonalPlacementGroupRef{
		id: ZonalPlacementGroupID{
			zonalPlacementGroup: zonalPlacementGroup,
			project:             project,
			zone:                zone,
		},
	}
	m.id.path = m.absolutePath()
	return m
}

func ParseZonalPlacementGroupRef(ctx context.Context, path string) (ZonalPlacementGroupRef, error) {
	m := ZonalPlacementGroupRef{
		id: ZonalPlacementGroupID{
			path: path,
		},
	}
	if err := m.Parse(ctx); err != nil {
		return ZonalPlacementGroupRef{}, err
	}
	return m, nil
}

func NewZonalPlacementGroupRefFromAnyRef(ref resmodels.AnyResourceRef) (ZonalPlacementGroupRef, error) {
	ctx := valuesctx.WithValuesStore(context.Background(), ref.GetPathValues())
	return ParseZonalPlacementGroupRef(ctx, ref.Path())
}

type ZonalPlacementGroupRef struct {
	id ZonalPlacementGroupID
}

func (m *ZonalPlacementGroupRef) ResourceName() resifaces.ResourceName {
	if m == nil {
		return ""
	}
	return m.id.ResourceName()
}

func (m *ZonalPlacementGroupRef) GetZonalPlacementGroup() string {
	if m == nil {
		return ""
	}
	return m.id.GetZonalPlacementGroup()
}

func (m *ZonalPlacementGroupRef) GetProject() string {
	if m == nil {
		return ""
	}
	return m.id.GetProject()
}

func (m *ZonalPlacementGroupRef) GetZone() string {
	if m == nil {
		return ""
	}
	return m.id.GetZone()
}

func (m *ZonalPlacementGroupRef) ServiceSlug() string {
	return "compute"
}

func (m *ZonalPlacementGroupRef) IDPath() string {
	if m == nil {
		return ""
	}
	return m.id.ID()
}

func (m *ZonalPlacementGroupRef) Path() string {
	if m == nil {
		return ""
	}
	if m.id.path == "" {
		return m.absolutePath()
	}
	return m.id.path
}

func (m *ZonalPlacementGroupRef) String() string {
	return m.IDPath()
}

func (m *ZonalPlacementGroupRef) Parse(ctx context.Context) error {
	if m == nil {
		return nil
	}

	result, err := resparsers.Reference(ctx, m.id.path, ZonalPlacementGroupRefTemplate)
	if err != nil {
		return reserrors.NewParseReferenceError(m.id.path, err)
	}

	m.id.zonalPlacementGroup = result["zonalPlacementGroup"]
	m.id.project = result["project"]
	m.id.zone = result["zone"]

	return nil
}

func (m *ZonalPlacementGroupRef) Clone() *ZonalPlacementGroupRef {
	if m == nil {
		return nil
	}
	clone := *m
	return &clone
}

func (m ZonalPlacementGroupRef) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	if err := m.Encode(&e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (m *ZonalPlacementGroupRef) Encode(e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.Str(m.Path())
	return nil
}

func (m *ZonalPlacementGroupRef) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *ZonalPlacementGroupRef) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("ZonalPlacementGroupRef")
	}

	v, err := decode.Str(d)
	if err != nil {
		return err
	}

	m.id.path = v
	return nil
}

func (m *ZonalPlacementGroupRef) absolutePath() string {
	if m == nil || m.id.zonalPlacementGroup == "" || m.id.project == "" || m.id.zone == "" {
		return ""
	}

	return "zones/" + m.id.zone + "/projects/" + m.id.project + "/zonalPlacementGroups/" + m.id.zonalPlacementGroup
}
