// Code generated by mwsapigen, DO NOT EDIT.

package client

import (
	"context"

	mwsinternalerrors "go.mws.cloud/go-sdk/internal/errors"
	common "go.mws.cloud/go-sdk/service/common/model"
	"go.mws.cloud/go-sdk/service/mpostgres/model"
)

type PostgresRoleBinding interface {
	// ListPostgresRoleBindings list postgres roleBindings.
	//
	// Путь: GET /mpostgres/v1/projects/{project}/clusters/{cluster}/roleBindings
	ListPostgresRoleBindings(context.Context, ListPostgresRoleBindingsRequest) (*ListPostgresRoleBindingsResponse, error)
	// DeletePostgresRoleBinding delete Postgres roleBinding.
	//
	// Путь: DELETE /mpostgres/v1/projects/{project}/clusters/{cluster}/roleBindings/{roleBinding}
	DeletePostgresRoleBinding(context.Context, DeletePostgresRoleBindingRequest) (*DeletePostgresRoleBindingResponse, error)
	// GetPostgresRoleBinding returns info about the specified roleBinding.
	//
	// Путь: GET /mpostgres/v1/projects/{project}/clusters/{cluster}/roleBindings/{roleBinding}
	GetPostgresRoleBinding(context.Context, GetPostgresRoleBindingRequest) (*GetPostgresRoleBindingResponse, error)
	// UpsertPostgresRoleBinding upsert Postgres roleBinding.
	//
	// Путь: POST /mpostgres/v1/projects/{project}/clusters/{cluster}/roleBindings/{roleBinding}
	UpsertPostgresRoleBinding(context.Context, UpsertPostgresRoleBindingRequest) (*UpsertPostgresRoleBindingResponse, error)
	// CreatePostgresRoleBinding upsert Postgres roleBinding.
	// Данный метод не описан в OpenAPI-спецификации, он был сгенерирован на основе операции upsert, для удобства.
	//
	// Путь: POST /mpostgres/v1/projects/{project}/clusters/{cluster}/roleBindings/{roleBinding}?createOnly=true
	CreatePostgresRoleBinding(context.Context, UpsertPostgresRoleBindingRequest) (*UpsertPostgresRoleBindingResponse, error)
	// UpdatePostgresRoleBinding upsert Postgres roleBinding.
	// Данный метод не описан в OpenAPI-спецификации, он был сгенерирован на основе операции upsert, для удобства.
	//
	// Путь: POST /mpostgres/v1/projects/{project}/clusters/{cluster}/roleBindings/{roleBinding}?updateOnly=true
	UpdatePostgresRoleBinding(context.Context, UpdatePostgresRoleBindingRequest) (*UpsertPostgresRoleBindingResponse, error)
}

type ListPostgresRoleBindingsRequest struct {
	// Токен авторизации IAM
	Authorization string // header: "Authorization"
	// Путь к проекту.
	Project string // path: "project"
	// Название или идентификатор кластера.
	Cluster string // path: "cluster"
	// Максимальное количество объектов, которые клиент готов принять. Сервис определяет значение по умолчанию и верхнюю границу
	PageSize *int // query: "pageSize"
	// Строка, из предыдущего ответа на аналогичный запрос, для получения следующей страницы с объектами. Не задано для получения первой страницы
	PageToken *string // query: "pageToken"
	// Строка фильтра.
	// Для фильтрации используется ограниченная реализация AIP-160 (https://google.aip.dev/160).
	// Она включает в себя операции =, !=, OR, AND и (), фильтрацию свойств вложенных объектов и wildcard-поиск подстрок
	Filter *string // query: "filter"
	// Строка сортировки.
	// Для сортировки используется реализация AIP-132 (https://google.aip.dev/132#ordering).
	// Указывается перечислением полей с направлением сортировки (asc, desc) через запятую.
	// По умолчанию используется сортировка по возрастанию (asc)
	OrderBy *string // query: "orderBy"
	// Вывод удаленных объектов для ресурсов, поддерживающих soft delete
	ShowDeleted *string // query: "showDeleted"
}

func (m *ListPostgresRoleBindingsRequest) SetAuthorization(authorization string) {
	m.Authorization = authorization
}

func (m ListPostgresRoleBindingsRequest) GetProject() string {
	return m.Project
}

func (m *ListPostgresRoleBindingsRequest) SetProject(project string) {
	m.Project = project
}

func (m ListPostgresRoleBindingsRequest) WithPageToken(token *string) ListPostgresRoleBindingsRequest {
	m.PageToken = token
	return m
}

type ListPostgresRoleBindingsResponse struct {
	Code        int
	Response200 *model.PostgresRoleBindingPageResponse
	Response400 *common.ApiError
	Response403 *common.ApiError
	Response500 *common.ApiError

	errorWrapper func(err error) error
}

func (m *ListPostgresRoleBindingsResponse) GetCode() int {
	return m.Code
}

func (m *ListPostgresRoleBindingsResponse) GetErr() (err error) {
	defer func() {
		if err != nil && m.errorWrapper != nil {
			err = m.errorWrapper(err)
		}
	}()
	if m.Response400 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response400)
	}
	if m.Response403 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response403)
	}
	if m.Response500 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response500)
	}
	return nil
}

func (m *ListPostgresRoleBindingsResponse) SetErrorWrapper(f func(err error) error) {
	if m != nil {
		m.errorWrapper = f
	}
}

type DeletePostgresRoleBindingRequest struct {
	// Токен авторизации IAM
	Authorization string // header: "Authorization"
	// Ключ идемпотентности
	IdempotencyKey *string // header: "Idempotency-Key"
	// Путь к проекту.
	Project string // path: "project"
	// Название или идентификатор кластера.
	Cluster string // path: "cluster"
	// Идентификатор привязки роли, определяющей права доступа пользователя к базе данных.
	RoleBinding string // path: "roleBinding"
}

func (m *DeletePostgresRoleBindingRequest) SetAuthorization(authorization string) {
	m.Authorization = authorization
}

func (m DeletePostgresRoleBindingRequest) GetProject() string {
	return m.Project
}

func (m *DeletePostgresRoleBindingRequest) SetProject(project string) {
	m.Project = project
}

func (m *DeletePostgresRoleBindingRequest) getPostgresRoleBindingRequest() GetPostgresRoleBindingRequest {
	return GetPostgresRoleBindingRequest{
		Authorization: m.Authorization,
		Project:       m.Project,
		Cluster:       m.Cluster,
		RoleBinding:   m.RoleBinding,
	}
}

type DeletePostgresRoleBindingResponse struct {
	Code        int
	Response204 bool // empty response
	Response400 *common.ApiError
	Response403 *common.ApiError
	Response404 *common.ApiError
	Response412 *common.ApiError
	Response500 *common.ApiError

	errorWrapper func(err error) error
}

func (m *DeletePostgresRoleBindingResponse) GetCode() int {
	return m.Code
}

func (m *DeletePostgresRoleBindingResponse) GetErr() (err error) {
	defer func() {
		if err != nil && m.errorWrapper != nil {
			err = m.errorWrapper(err)
		}
	}()
	if m.Response400 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response400)
	}
	if m.Response403 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response403)
	}
	if m.Response404 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response404)
	}
	if m.Response412 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response412)
	}
	if m.Response500 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response500)
	}
	return nil
}

func (m *DeletePostgresRoleBindingResponse) SetErrorWrapper(f func(err error) error) {
	if m != nil {
		m.errorWrapper = f
	}
}

type GetPostgresRoleBindingRequest struct {
	// Токен авторизации IAM
	Authorization string // header: "Authorization"
	// Путь к проекту.
	Project string // path: "project"
	// Название или идентификатор кластера.
	Cluster string // path: "cluster"
	// Идентификатор привязки роли, определяющей права доступа пользователя к базе данных.
	RoleBinding string // path: "roleBinding"
}

func (m *GetPostgresRoleBindingRequest) SetAuthorization(authorization string) {
	m.Authorization = authorization
}

func (m GetPostgresRoleBindingRequest) GetProject() string {
	return m.Project
}

func (m *GetPostgresRoleBindingRequest) SetProject(project string) {
	m.Project = project
}

type GetPostgresRoleBindingResponse struct {
	Code        int
	Response200 *model.PostgresRoleBindingResponse
	Response400 *common.ApiError
	Response403 *common.ApiError
	Response404 *common.ApiError
	Response500 *common.ApiError

	errorWrapper func(err error) error
}

func (m *GetPostgresRoleBindingResponse) GetCode() int {
	return m.Code
}

func (m *GetPostgresRoleBindingResponse) GetErr() (err error) {
	defer func() {
		if err != nil && m.errorWrapper != nil {
			err = m.errorWrapper(err)
		}
	}()
	if m.Response400 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response400)
	}
	if m.Response403 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response403)
	}
	if m.Response404 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response404)
	}
	if m.Response500 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response500)
	}
	return nil
}

func (m *GetPostgresRoleBindingResponse) SetErrorWrapper(f func(err error) error) {
	if m != nil {
		m.errorWrapper = f
	}
}

type UpsertPostgresRoleBindingRequest struct {
	// Токен авторизации IAM
	Authorization string // header: "Authorization"
	// Ключ идемпотентности
	IdempotencyKey *string // header: "Idempotency-Key"
	// Путь к проекту.
	Project string // path: "project"
	// Название или идентификатор кластера.
	Cluster string // path: "cluster"
	// Идентификатор привязки роли, определяющей права доступа пользователя к базе данных.
	RoleBinding string // path: "roleBinding"
	// Upsert Postgres roleBinding
	Body model.PostgresRoleBindingRequest // body
}

func (m *UpsertPostgresRoleBindingRequest) SetAuthorization(authorization string) {
	m.Authorization = authorization
}

func (m UpsertPostgresRoleBindingRequest) GetProject() string {
	return m.Project
}

func (m *UpsertPostgresRoleBindingRequest) SetProject(project string) {
	m.Project = project
}

func (m *UpsertPostgresRoleBindingRequest) getPostgresRoleBindingRequest() GetPostgresRoleBindingRequest {
	return GetPostgresRoleBindingRequest{
		Authorization: m.Authorization,
		Project:       m.Project,
		Cluster:       m.Cluster,
		RoleBinding:   m.RoleBinding,
	}
}

type UpdatePostgresRoleBindingRequest struct {
	// Токен авторизации IAM
	Authorization string // header: "Authorization"
	// Ключ идемпотентности
	IdempotencyKey *string // header: "Idempotency-Key"
	// Путь к проекту.
	Project string // path: "project"
	// Название или идентификатор кластера.
	Cluster string // path: "cluster"
	// Идентификатор привязки роли, определяющей права доступа пользователя к базе данных.
	RoleBinding string // path: "roleBinding"
	// Upsert Postgres roleBinding
	Body model.UpdatePostgresRoleBindingRequest // body
}

func (m *UpdatePostgresRoleBindingRequest) SetAuthorization(authorization string) {
	m.Authorization = authorization
}

func (m UpdatePostgresRoleBindingRequest) GetProject() string {
	return m.Project
}

func (m *UpdatePostgresRoleBindingRequest) SetProject(project string) {
	m.Project = project
}

func (m *UpdatePostgresRoleBindingRequest) getPostgresRoleBindingRequest() GetPostgresRoleBindingRequest {
	return GetPostgresRoleBindingRequest{
		Authorization: m.Authorization,
		Project:       m.Project,
		Cluster:       m.Cluster,
		RoleBinding:   m.RoleBinding,
	}
}

type UpsertPostgresRoleBindingResponse struct {
	Code        int
	Response200 *model.PostgresRoleBindingResponse
	Response400 *common.ApiError
	Response403 *common.ApiError
	Response404 *common.ApiError
	Response409 *common.ApiError
	Response412 *common.ApiError
	Response500 *common.ApiError

	errorWrapper func(err error) error
}

func (m *UpsertPostgresRoleBindingResponse) GetCode() int {
	return m.Code
}

func (m *UpsertPostgresRoleBindingResponse) GetErr() (err error) {
	defer func() {
		if err != nil && m.errorWrapper != nil {
			err = m.errorWrapper(err)
		}
	}()
	if m.Response400 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response400)
	}
	if m.Response403 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response403)
	}
	if m.Response404 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response404)
	}
	if m.Response409 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response409)
	}
	if m.Response412 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response412)
	}
	if m.Response500 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response500)
	}
	return nil
}

func (m *UpsertPostgresRoleBindingResponse) SetErrorWrapper(f func(err error) error) {
	if m != nil {
		m.errorWrapper = f
	}
}
