// Code generated by mwsapigen, DO NOT EDIT.

package client_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"
	"go.uber.org/mock/gomock"

	mwserrors "go.mws.cloud/go-sdk/mws/errors"
	"go.mws.cloud/go-sdk/service/kms/client"
	clientmocks "go.mws.cloud/go-sdk/service/kms/client/mocks"
)

func TestCryptoKeyRoleBindingSugared_ListCryptoKeyRoleBindings(t *testing.T) {
	t.Parallel()
	ctrl := gomock.NewController(t)
	defer ctrl.Finish()

	mockClient := clientmocks.NewMockCryptoKeyRoleBinding(ctrl)
	mockClient.EXPECT().ListCryptoKeyRoleBindings(gomock.Any(), gomock.Any()).Times(1).Return(nil, mwserrors.NewDecodeBodyError("", nil))

	sugared := client.NewCryptoKeyRoleBindingSugared(mockClient)

	_, err := sugared.ListCryptoKeyRoleBindings(context.Background(), client.ListCryptoKeyRoleBindingsRequest{})
	require.True(t, mwserrors.IsDecodeBodyError(err))
}

func TestCryptoKeyRoleBindingSugared_DeleteCryptoKeyRoleBinding(t *testing.T) {
	t.Parallel()
	ctrl := gomock.NewController(t)
	defer ctrl.Finish()

	mockClient := clientmocks.NewMockCryptoKeyRoleBinding(ctrl)
	mockClient.EXPECT().DeleteCryptoKeyRoleBinding(gomock.Any(), gomock.Any()).Times(1).Return(nil, mwserrors.NewDecodeBodyError("", nil))

	sugared := client.NewCryptoKeyRoleBindingSugared(mockClient)

	err := sugared.DeleteCryptoKeyRoleBinding(context.Background(), client.DeleteCryptoKeyRoleBindingRequest{})
	require.True(t, mwserrors.IsDecodeBodyError(err))
}

func TestCryptoKeyRoleBindingSugared_GetCryptoKeyRoleBinding(t *testing.T) {
	t.Parallel()
	ctrl := gomock.NewController(t)
	defer ctrl.Finish()

	mockClient := clientmocks.NewMockCryptoKeyRoleBinding(ctrl)
	mockClient.EXPECT().GetCryptoKeyRoleBinding(gomock.Any(), gomock.Any()).Times(1).Return(nil, mwserrors.NewDecodeBodyError("", nil))

	sugared := client.NewCryptoKeyRoleBindingSugared(mockClient)

	_, err := sugared.GetCryptoKeyRoleBinding(context.Background(), client.GetCryptoKeyRoleBindingRequest{})
	require.True(t, mwserrors.IsDecodeBodyError(err))
}

func TestCryptoKeyRoleBindingSugared_UpsertCryptoKeyRoleBinding(t *testing.T) {
	t.Parallel()
	ctrl := gomock.NewController(t)
	defer ctrl.Finish()

	mockClient := clientmocks.NewMockCryptoKeyRoleBinding(ctrl)
	mockClient.EXPECT().UpsertCryptoKeyRoleBinding(gomock.Any(), gomock.Any()).Times(1).Return(nil, mwserrors.NewDecodeBodyError("", nil))

	sugared := client.NewCryptoKeyRoleBindingSugared(mockClient)

	_, err := sugared.UpsertCryptoKeyRoleBinding(context.Background(), client.UpsertCryptoKeyRoleBindingRequest{})
	require.True(t, mwserrors.IsDecodeBodyError(err))
}

func TestCryptoKeyRoleBindingSugared_CreateCryptoKeyRoleBinding(t *testing.T) {
	t.Parallel()
	ctrl := gomock.NewController(t)
	defer ctrl.Finish()

	mockClient := clientmocks.NewMockCryptoKeyRoleBinding(ctrl)
	mockClient.EXPECT().CreateCryptoKeyRoleBinding(gomock.Any(), gomock.Any()).Times(1).Return(nil, mwserrors.NewDecodeBodyError("", nil))

	sugared := client.NewCryptoKeyRoleBindingSugared(mockClient)

	_, err := sugared.CreateCryptoKeyRoleBinding(context.Background(), client.UpsertCryptoKeyRoleBindingRequest{})
	require.True(t, mwserrors.IsDecodeBodyError(err))
}

func TestCryptoKeyRoleBindingSugared_UpdateCryptoKeyRoleBinding(t *testing.T) {
	t.Parallel()
	ctrl := gomock.NewController(t)
	defer ctrl.Finish()

	mockClient := clientmocks.NewMockCryptoKeyRoleBinding(ctrl)
	mockClient.EXPECT().UpdateCryptoKeyRoleBinding(gomock.Any(), gomock.Any()).Times(1).Return(nil, mwserrors.NewDecodeBodyError("", nil))

	sugared := client.NewCryptoKeyRoleBindingSugared(mockClient)

	_, err := sugared.UpdateCryptoKeyRoleBinding(context.Background(), client.UpdateCryptoKeyRoleBindingRequest{})
	require.True(t, mwserrors.IsDecodeBodyError(err))
}
