// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/go-faster/jx"

	"go.mws.cloud/go-sdk/internal/conv"
)

func (m UpdateApiKeySpecRequest) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *UpdateApiKeySpecRequest) Encode(e *jx.Encoder) {
	if m == nil {
		e.Null()
		return
	}
	e.ObjStart()
	m.encodeFields(e)
	e.ObjEnd()
}

func (m *UpdateApiKeySpecRequest) encodeFields(e *jx.Encoder) {
}

func (m *UpdateApiKeySpecRequest) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *UpdateApiKeySpecRequest) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("UpdateApiKeySpecRequest")
	}

	return d.Skip()
}
