// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/go-faster/jx"

	"go.mws.cloud/go-sdk/internal/conv"
	"go.mws.cloud/go-sdk/internal/decode"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
)

func (m AuthorizedKeySpecResponse) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *AuthorizedKeySpecResponse) Encode(e *jx.Encoder) {
	if m == nil {
		e.Null()
		return
	}
	e.ObjStart()
	m.encodeFields(e)
	e.ObjEnd()
}

func (m *AuthorizedKeySpecResponse) encodeFields(e *jx.Encoder) {
	if m.PublicKey != nil {
		e.FieldStart("publicKey")
		e.Str(*m.PublicKey)
	}

	e.FieldStart("keyAlgorithm")
	e.Str(m.KeyAlgorithm)

	if m.ExpirationTime != nil {
		e.FieldStart("expirationTime")
		conv.EncodeDateTimeUTC(e, *m.ExpirationTime)
	}
}

func (m *AuthorizedKeySpecResponse) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *AuthorizedKeySpecResponse) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("AuthorizedKeySpecResponse")
	}

	return d.ObjBytes(reserrors.PathAccumulatorErrorObjBytesFuncWrap(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "publicKey":
			v, err := decode.Str(d)
			if err != nil {
				return err
			}

			m.PublicKey = &v
			return nil
		case "keyAlgorithm":
			v, err := decode.Str(d)
			if err != nil {
				return err
			}

			m.KeyAlgorithm = v
			return nil
		case "expirationTime":
			v, err := decode.DateTime(d)
			if err != nil {
				return err
			}

			m.ExpirationTime = &v
			return nil
		default:
			return d.Skip()
		}
	}))
}
