// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"context"
	"fmt"

	"go.mws.cloud/util-toolset/pkg/utils/ptr"

	commonclient "go.mws.cloud/go-sdk/internal/client"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	"go.mws.cloud/go-sdk/service/resources/references/vpc"
)

type UpdateAddressSpecOrRefRequest struct {
	Ref commonclient.Optional[vpc.AddressRef] `json:"ref" yaml:"ref"`
	// Возможно 2 варианта:
	// - запросить резервирование случайного адреса (заданы параметры "version")
	// - запросить резервирование конкретного адреса (заданы параметры "version", "ipAddress", остальные пусты)
	// Если необходимо привязать внешний адрес, заполняется параметр "oneToOneNat"
	Spec commonclient.OptionalNil[UpdateAddressSpecRequest] `json:"spec" yaml:"spec"`
}

func (m *AddressSpecOrRefRequest) AsUpdateModel() UpdateAddressSpecOrRefRequest {
	var u UpdateAddressSpecOrRefRequest
	if m.Ref != nil {
		u.Ref = commonclient.NewOptional(m.GetRefOr(vpc.AddressRef{}))
	}
	if m.Spec != nil {
		u.Spec = commonclient.NewOptionalNil(m.Spec.AsUpdateModel())
	}
	return u
}

// Diff creates an object that can be used in Update methods. This object represents changes from src to the current state
func (m *AddressSpecOrRefRequest) Diff(src *AddressSpecOrRefRequest) (UpdateAddressSpecOrRefRequest, error) {
	var err error
	nilDiffers := src != nil && m == nil
	upd := UpdateAddressSpecOrRefRequest{}
	if !nilDiffers {
		upd.Ref = m.diffRef(src)
		upd.Spec, err = m.diffSpec(src)
		if err != nil {
			return UpdateAddressSpecOrRefRequest{}, fmt.Errorf("Spec: %w", err)
		}
	}
	return upd, nil
}

func (m *AddressSpecOrRefRequest) WithChanges(u UpdateAddressSpecOrRefRequest) AddressSpecOrRefRequest {
	var out AddressSpecOrRefRequest
	if m != nil {
		out = *m
	}

	if u.Ref.IsSet() {
		out.Ref = ptr.Get(u.Ref.Value)
	}
	if u.Spec.IsSet() {
		out.Spec = ptr.Get(out.Spec.WithChanges(u.Spec.Value))
	} else if u.Spec.IsNull() {
		out.Spec = nil
	}
	return out
}

// HasChanges returns true if any field has Set == true
func (m UpdateAddressSpecOrRefRequest) HasChanges() bool {
	return m.Ref.Set ||
		m.Spec.Set
}

func (m *UpdateAddressSpecOrRefRequest) Parse(ctx context.Context) error {
	if m == nil {
		return nil
	}

	if m.Ref.IsSet() {
		if err := m.Ref.Value.Parse(ctx); err != nil {
			return reserrors.NewPathAccumulatorError("Ref", err)
		}
	}

	if m.Spec.IsSet() {
		if err := m.Spec.Value.Parse(ctx); err != nil {
			return reserrors.NewPathAccumulatorError("Spec", err)
		}
	}

	return nil
}

func (m *AddressSpecOrRefRequest) diffRef(src *AddressSpecOrRefRequest) commonclient.Optional[vpc.AddressRef] {
	nilDiffers := src != nil && m == nil
	return commonclient.DiffPrimitiveNonRequired(src.GetRef(), m.GetRef(), nilDiffers)
}

func (m *AddressSpecOrRefRequest) diffSpec(src *AddressSpecOrRefRequest) (commonclient.OptionalNil[UpdateAddressSpecRequest], error) {
	nilDiffers := src != nil && m == nil
	value, err := m.GetSpec().Diff(src.GetSpec())
	if err != nil {
		return commonclient.OptionalNil[UpdateAddressSpecRequest]{}, err
	}
	return commonclient.NewDirectOptionalNil[UpdateAddressSpecRequest](value, nilDiffers || value.HasChanges(), nilDiffers), nil
}
