// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"go.mws.cloud/go-sdk/pkg/apimodels/units/duration"

	commonclient "go.mws.cloud/go-sdk/internal/client"
	"go.mws.cloud/go-sdk/pkg/optional"
)

type UpdateAddressDnsSpecRequest struct {
	// DNS-имя виртуальной машины в MWS Cloud Platform
	Name optional.Optional[string] `json:"name" yaml:"name"`
	// Продолжительность хранения DNS записи в кеше
	Ttl optional.Optional[duration.Duration] `json:"ttl" yaml:"ttl"`
	// Создать обратную DNS-запись
	Ptr optional.Optional[bool] `json:"ptr" yaml:"ptr"`
}

func (m *AddressDnsSpecRequest) AsUpdateModel() UpdateAddressDnsSpecRequest {
	var u UpdateAddressDnsSpecRequest
	u.Name = optional.NewOptional(m.GetName())
	u.Ttl = optional.NewOptional(m.GetTtl())
	u.Ptr = optional.NewOptional(m.GetPtr())
	return u
}

// Diff creates an object that can be used in Update methods. This object represents changes from src to the current state
func (m *AddressDnsSpecRequest) Diff(src *AddressDnsSpecRequest) UpdateAddressDnsSpecRequest {
	nilDiffers := src != nil && m == nil
	upd := UpdateAddressDnsSpecRequest{}
	if !nilDiffers {
		upd.Name = m.diffName(src)
		upd.Ttl = m.diffTtl(src)
		upd.Ptr = m.diffPtr(src)
	}
	return upd
}

func (m *AddressDnsSpecRequest) WithChanges(u UpdateAddressDnsSpecRequest) AddressDnsSpecRequest {
	var out AddressDnsSpecRequest
	if m != nil {
		out = *m
	}

	if u.Name.IsSet() {
		out.Name = u.Name.Value
	}
	if u.Ttl.IsSet() {
		out.Ttl = u.Ttl.Value
	}
	if u.Ptr.IsSet() {
		out.Ptr = u.Ptr.Value
	}
	return out
}

// HasChanges returns true if any field has Set == true
func (m UpdateAddressDnsSpecRequest) HasChanges() bool {
	return m.Name.Set ||
		m.Ttl.Set ||
		m.Ptr.Set
}

// GetName is used in the merge functions
func (m *UpdateAddressDnsSpecRequest) GetName() string {
	if m.Name.IsSet() {
		return m.Name.Value
	}
	return ""
}

// SetName is used in the Diff function for NamedArray
func (m *UpdateAddressDnsSpecRequest) SetName(name string) {
	m.Name = optional.NewOptional(name)
}

func (m *AddressDnsSpecRequest) diffName(src *AddressDnsSpecRequest) optional.Optional[string] {
	nilDiffers := src != nil && m == nil
	return commonclient.DiffPrimitiveRequired(src.GetName(), m.GetName(), nilDiffers)
}

func (m *AddressDnsSpecRequest) diffTtl(src *AddressDnsSpecRequest) optional.Optional[duration.Duration] {
	nilDiffers := src != nil && m == nil
	return commonclient.DiffEquatableIfaceRequired(src.GetTtl(), m.GetTtl(), nilDiffers)
}

func (m *AddressDnsSpecRequest) diffPtr(src *AddressDnsSpecRequest) optional.Optional[bool] {
	nilDiffers := src != nil && m == nil
	return commonclient.DiffPrimitiveRequired(src.GetPtr(), m.GetPtr(), nilDiffers)
}
