// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"context"

	"go.mws.cloud/go-sdk/pkg/apimodels/units/bytesize"

	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	"go.mws.cloud/go-sdk/pkg/optional"
	"go.mws.cloud/go-sdk/service/resources/references/compute"
)

// Спецификация глобального диска
// Real OAPI model name: DiskSpec
type DiskSpecOptionalResponse struct {
	// Зона доступности (ЦОД)
	Zone string `json:"zone" yaml:"zone"`
	// Размер диска
	Size optional.Optional[bytesize.ByteSize] `json:"size,omitempty" yaml:"size,omitempty"`
	// Источник для создания диска
	Source optional.OptionalNil[DiskSpecSourceOptionalResponse] `json:"source,omitempty" yaml:"source,omitempty"`
	// ID типа диска
	DiskType optional.Optional[compute.DiskTypeRef] `json:"diskType,omitempty" yaml:"diskType,omitempty"`
	// Запрашиваемое пользователем количество операций ввода-вывода в секунду (IOPS)
	Iops optional.Optional[Iops] `json:"iops,omitempty" yaml:"iops,omitempty"`
	// Размер блока диска
	BlockSize optional.Optional[bytesize.ByteSize] `json:"blockSize,omitempty" yaml:"blockSize,omitempty"`
	// Тип операционной системы
	OsType optional.Optional[OsType] `json:"osType,omitempty" yaml:"osType,omitempty"`
}

func (m *DiskSpecOptionalResponse) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func (m *DiskSpecOptionalResponse) SetZone(val string) {
	m.Zone = val
}

func (m *DiskSpecOptionalResponse) GetSize() *bytesize.ByteSize {
	if m != nil && m.Size.IsSet() {
		return &m.Size.Value
	}
	return nil
}

func (m *DiskSpecOptionalResponse) GetSizeOr(val bytesize.ByteSize) bytesize.ByteSize {
	if m != nil && m.Size.IsSet() {
		return m.Size.Value
	}
	return val
}

func (m *DiskSpecOptionalResponse) GetSource() *DiskSpecSourceOptionalResponse {
	if m != nil && m.Source.IsSet() && !m.Source.IsNull() {
		return &m.Source.Value
	}
	return nil
}

func (m *DiskSpecOptionalResponse) GetSourceOr(val DiskSpecSourceOptionalResponse) DiskSpecSourceOptionalResponse {
	if m != nil && m.Source.IsSet() && !m.Source.IsNull() {
		return m.Source.Value
	}
	return val
}

func (m *DiskSpecOptionalResponse) GetDiskType() *compute.DiskTypeRef {
	if m != nil && m.DiskType.IsSet() {
		return &m.DiskType.Value
	}
	return nil
}

func (m *DiskSpecOptionalResponse) GetDiskTypeOr(val compute.DiskTypeRef) compute.DiskTypeRef {
	if m != nil && m.DiskType.IsSet() {
		return m.DiskType.Value
	}
	return val
}

func (m *DiskSpecOptionalResponse) GetIops() *Iops {
	if m != nil && m.Iops.IsSet() {
		return &m.Iops.Value
	}
	return nil
}

func (m *DiskSpecOptionalResponse) GetIopsOr(val Iops) Iops {
	if m != nil && m.Iops.IsSet() {
		return m.Iops.Value
	}
	return val
}

func (m *DiskSpecOptionalResponse) GetBlockSize() *bytesize.ByteSize {
	if m != nil && m.BlockSize.IsSet() {
		return &m.BlockSize.Value
	}
	return nil
}

func (m *DiskSpecOptionalResponse) GetBlockSizeOr(val bytesize.ByteSize) bytesize.ByteSize {
	if m != nil && m.BlockSize.IsSet() {
		return m.BlockSize.Value
	}
	return val
}

func (m *DiskSpecOptionalResponse) GetOsType() *OsType {
	if m != nil && m.OsType.IsSet() {
		return &m.OsType.Value
	}
	return nil
}

func (m *DiskSpecOptionalResponse) GetOsTypeOr(val OsType) OsType {
	if m != nil && m.OsType.IsSet() {
		return m.OsType.Value
	}
	return val
}

func (m *DiskSpecOptionalResponse) Clone() *DiskSpecOptionalResponse {
	if m == nil {
		return nil
	}

	clone := *m
	if clone.Size.IsSet() {
		clone.Size.Value = *m.Size.Value.Clone()
	}
	if clone.Source.IsSet() {
		clone.Source.Value = *m.Source.Value.Clone()
	}
	if clone.DiskType.IsSet() {
		clone.DiskType.Value = *m.DiskType.Value.Clone()
	}
	if clone.BlockSize.IsSet() {
		clone.BlockSize.Value = *m.BlockSize.Value.Clone()
	}
	return &clone
}

func (m *DiskSpecOptionalResponse) Parse(ctx context.Context) error {
	if m == nil {
		return nil
	}

	if m.Source.IsSet() {
		if err := m.Source.Value.Parse(ctx); err != nil {
			return reserrors.NewPathAccumulatorError("Source", err)
		}
	}

	if m.DiskType.IsSet() {
		if err := m.DiskType.Value.Parse(ctx); err != nil {
			return reserrors.NewPathAccumulatorError("DiskType", err)
		}
	}

	return nil
}

// Представление поля Source анонимного типа структуры DiskSpec
// Real OAPI model name: DiskSpecSource
type DiskSpecSourceOptionalResponse struct {
	// ID образа
	Image optional.Optional[compute.ImageRef] `json:"image,omitempty" yaml:"image,omitempty"`
	// ID снимка
	//
	// Deprecated: Отказываемся в пользу diskBackup
	Snapshot optional.Optional[compute.SnapshotRef] `json:"snapshot,omitempty" yaml:"snapshot,omitempty"`
	// ID резервной копии диска
	DiskBackup optional.Optional[compute.DiskBackupRef] `json:"diskBackup,omitempty" yaml:"diskBackup,omitempty"`
}

func (m *DiskSpecSourceOptionalResponse) GetImage() *compute.ImageRef {
	if m != nil && m.Image.IsSet() {
		return &m.Image.Value
	}
	return nil
}

func (m *DiskSpecSourceOptionalResponse) GetImageOr(val compute.ImageRef) compute.ImageRef {
	if m != nil && m.Image.IsSet() {
		return m.Image.Value
	}
	return val
}

// Deprecated: Отказываемся в пользу diskBackup
func (m *DiskSpecSourceOptionalResponse) GetSnapshot() *compute.SnapshotRef {
	if m != nil && m.Snapshot.IsSet() {
		return &m.Snapshot.Value
	}
	return nil
}

// Deprecated: Отказываемся в пользу diskBackup
func (m *DiskSpecSourceOptionalResponse) GetSnapshotOr(val compute.SnapshotRef) compute.SnapshotRef {
	if m != nil && m.Snapshot.IsSet() {
		return m.Snapshot.Value
	}
	return val
}

func (m *DiskSpecSourceOptionalResponse) GetDiskBackup() *compute.DiskBackupRef {
	if m != nil && m.DiskBackup.IsSet() {
		return &m.DiskBackup.Value
	}
	return nil
}

func (m *DiskSpecSourceOptionalResponse) GetDiskBackupOr(val compute.DiskBackupRef) compute.DiskBackupRef {
	if m != nil && m.DiskBackup.IsSet() {
		return m.DiskBackup.Value
	}
	return val
}

func (m *DiskSpecSourceOptionalResponse) Clone() *DiskSpecSourceOptionalResponse {
	if m == nil {
		return nil
	}

	clone := *m
	if clone.Image.IsSet() {
		clone.Image.Value = *m.Image.Value.Clone()
	}
	if clone.Snapshot.IsSet() {
		clone.Snapshot.Value = *m.Snapshot.Value.Clone()
	}
	if clone.DiskBackup.IsSet() {
		clone.DiskBackup.Value = *m.DiskBackup.Value.Clone()
	}
	return &clone
}

func (m *DiskSpecSourceOptionalResponse) Parse(ctx context.Context) error {
	if m == nil {
		return nil
	}

	if m.Image.IsSet() {
		if err := m.Image.Value.Parse(ctx); err != nil {
			return reserrors.NewPathAccumulatorError("Image", err)
		}
	}

	if m.Snapshot.IsSet() {
		if err := m.Snapshot.Value.Parse(ctx); err != nil {
			return reserrors.NewPathAccumulatorError("Snapshot", err)
		}
	}

	if m.DiskBackup.IsSet() {
		if err := m.DiskBackup.Value.Parse(ctx); err != nil {
			return reserrors.NewPathAccumulatorError("DiskBackup", err)
		}
	}

	return nil
}
