// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"context"

	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	common "go.mws.cloud/go-sdk/service/common/model"
)

// Тип диска
// Real OAPI model name: DiskType
type DiskTypeResponse struct {
	// Тип объекта (diskType)
	Kind *string `json:"kind,omitempty" yaml:"kind,omitempty"`
	// Дополнительная информация об объекте
	Metadata *common.CommonTypedResourceMetadataResponse `json:"metadata,omitempty" yaml:"metadata,omitempty"`
	// Спецификация типа глобального диска
	Spec DiskTypeSpecResponse `json:"spec" yaml:"spec"`
}

func (m *DiskTypeResponse) GetKind() *string {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (m *DiskTypeResponse) SetKind(val *string) {
	m.Kind = val
}

func (m *DiskTypeResponse) GetKindOr(val string) string {
	if m != nil && m.Kind != nil {
		return *m.Kind
	}
	return val
}

func (m *DiskTypeResponse) GetMetadata() *common.CommonTypedResourceMetadataResponse {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *DiskTypeResponse) SetMetadata(val *common.CommonTypedResourceMetadataResponse) {
	m.Metadata = val
}

func (m *DiskTypeResponse) GetMetadataOr(val common.CommonTypedResourceMetadataResponse) common.CommonTypedResourceMetadataResponse {
	if m != nil && m.Metadata != nil {
		return *m.Metadata
	}
	return val
}

func (m *DiskTypeResponse) GetSpec() DiskTypeSpecResponse {
	if m != nil {
		return m.Spec
	}
	return DiskTypeSpecResponse{}
}

func (m *DiskTypeResponse) SetSpec(val DiskTypeSpecResponse) {
	m.Spec = val
}

func (m *DiskTypeResponse) Clone() *DiskTypeResponse {
	if m == nil {
		return nil
	}

	clone := *m
	if m.Kind != nil {
		cloneKind := *m.Kind
		clone.Kind = &cloneKind
	}
	clone.Metadata = m.Metadata.Clone()
	clone.Spec = *m.Spec.Clone()
	return &clone
}

func (m *DiskTypeResponse) Parse(ctx context.Context) error {
	if m == nil {
		return nil
	}

	if err := m.Metadata.Parse(ctx); err != nil {
		return reserrors.NewPathAccumulatorError("Metadata", err)
	}

	if err := m.Spec.Parse(ctx); err != nil {
		return reserrors.NewPathAccumulatorError("Spec", err)
	}

	return nil
}
