// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"go.mws.cloud/util-toolset/pkg/utils/ptr"

	commonclient "go.mws.cloud/go-sdk/internal/client"
)

type UpdateImageSpecRequest struct {
	// Семейство образа
	Family commonclient.Optional[string] `json:"family" yaml:"family"`
	// Актуальность образа
	Activity commonclient.Optional[ImageActivity] `json:"activity" yaml:"activity"`
	// Тип операционной системы
	OsType commonclient.Optional[OsType] `json:"osType" yaml:"osType"`
}

func (m *ImageSpecRequest) AsUpdateModel() UpdateImageSpecRequest {
	var u UpdateImageSpecRequest
	if m.Family != nil {
		u.Family = commonclient.NewOptional(m.GetFamilyOr(""))
	}
	if m.Activity != nil {
		u.Activity = commonclient.NewOptional(m.GetActivityOr(""))
	}
	if m.OsType != nil {
		u.OsType = commonclient.NewOptional(m.GetOsTypeOr(""))
	}
	return u
}

// Diff creates an object that can be used in Update methods. This object represents changes from src to the current state
func (m *ImageSpecRequest) Diff(src *ImageSpecRequest) UpdateImageSpecRequest {
	nilDiffers := src != nil && m == nil
	upd := UpdateImageSpecRequest{}
	if !nilDiffers {
		upd.Family = m.diffFamily(src)
		upd.Activity = m.diffActivity(src)
		upd.OsType = m.diffOsType(src)
	}
	return upd
}

func (m *ImageSpecRequest) WithChanges(u UpdateImageSpecRequest) ImageSpecRequest {
	var out ImageSpecRequest
	if m != nil {
		out = *m
	}

	if u.Family.IsSet() {
		out.Family = ptr.Get(u.Family.Value)
	}
	if u.Activity.IsSet() {
		out.Activity = ptr.Get(u.Activity.Value)
	}
	if u.OsType.IsSet() {
		out.OsType = ptr.Get(u.OsType.Value)
	}
	return out
}

// HasChanges returns true if any field has Set == true
func (m UpdateImageSpecRequest) HasChanges() bool {
	return m.Family.Set ||
		m.Activity.Set ||
		m.OsType.Set
}

func (m *ImageSpecRequest) diffFamily(src *ImageSpecRequest) commonclient.Optional[string] {
	nilDiffers := src != nil && m == nil
	return commonclient.DiffPrimitiveNonRequired(src.GetFamily(), m.GetFamily(), nilDiffers)
}

func (m *ImageSpecRequest) diffActivity(src *ImageSpecRequest) commonclient.Optional[ImageActivity] {
	nilDiffers := src != nil && m == nil
	return commonclient.DiffPrimitiveNonRequired(src.GetActivity(), m.GetActivity(), nilDiffers)
}

func (m *ImageSpecRequest) diffOsType(src *ImageSpecRequest) commonclient.Optional[OsType] {
	nilDiffers := src != nil && m == nil
	return commonclient.DiffPrimitiveNonRequired(src.GetOsType(), m.GetOsType(), nilDiffers)
}
