// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/go-faster/jx"

	"go.mws.cloud/go-sdk/internal/conv"
	"go.mws.cloud/go-sdk/internal/decode"
)

func (m PossiblyZeroIops) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *PossiblyZeroIops) Encode(e *jx.Encoder) {
	if m == nil {
		e.Null()
		return
	}
	e.Int64(int64(*m))
}

func (m *PossiblyZeroIops) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *PossiblyZeroIops) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("PossiblyZeroIops")
	}

	v, err := decode.Int64(d)
	if err != nil {
		return err
	}

	*m = PossiblyZeroIops(v)
	return nil
}
