// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"go.mws.cloud/util-toolset/pkg/utils/ptr"

	commonclient "go.mws.cloud/go-sdk/internal/client"
)

type UpdateSnapshotSpecRequest struct {
	// Тип операционной системы
	OsType commonclient.Optional[OsType] `json:"osType" yaml:"osType"`
}

func (m *SnapshotSpecRequest) AsUpdateModel() UpdateSnapshotSpecRequest {
	var u UpdateSnapshotSpecRequest
	if m.OsType != nil {
		u.OsType = commonclient.NewOptional(m.GetOsTypeOr(""))
	}
	return u
}

// Diff creates an object that can be used in Update methods. This object represents changes from src to the current state
func (m *SnapshotSpecRequest) Diff(src *SnapshotSpecRequest) UpdateSnapshotSpecRequest {
	nilDiffers := src != nil && m == nil
	upd := UpdateSnapshotSpecRequest{}
	if !nilDiffers {
		upd.OsType = m.diffOsType(src)
	}
	return upd
}

func (m *SnapshotSpecRequest) WithChanges(u UpdateSnapshotSpecRequest) SnapshotSpecRequest {
	var out SnapshotSpecRequest
	if m != nil {
		out = *m
	}

	if u.OsType.IsSet() {
		out.OsType = ptr.Get(u.OsType.Value)
	}
	return out
}

// HasChanges returns true if any field has Set == true
func (m UpdateSnapshotSpecRequest) HasChanges() bool {
	return m.OsType.Set
}

func (m *SnapshotSpecRequest) diffOsType(src *SnapshotSpecRequest) commonclient.Optional[OsType] {
	nilDiffers := src != nil && m == nil
	return commonclient.DiffPrimitiveNonRequired(src.GetOsType(), m.GetOsType(), nilDiffers)
}
