// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/go-faster/jx"
	"go.mws.cloud/go-sdk/pkg/apimodels/units/bytesize"

	"go.mws.cloud/go-sdk/internal/conv"
	"go.mws.cloud/go-sdk/internal/decode"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	common "go.mws.cloud/go-sdk/service/common/model"
)

func (m SnapshotStatusResponse) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *SnapshotStatusResponse) Encode(e *jx.Encoder) {
	if m == nil {
		e.Null()
		return
	}
	e.ObjStart()
	m.encodeFields(e)
	e.ObjEnd()
}

func (m *SnapshotStatusResponse) encodeFields(e *jx.Encoder) {
	e.FieldStart("ready")
	m.Ready.Encode(e)
	if m.StorageSize != nil {
		e.FieldStart("storageSize")
		m.StorageSize.Encode(e)
	}

	if m.Progress != nil {
		e.FieldStart("progress")
		e.Str(*m.Progress)
	}

	if m.SourceExists != nil {
		e.FieldStart("sourceExists")
		e.Bool(*m.SourceExists)
	}

	if m.MinDiskSize != nil {
		e.FieldStart("minDiskSize")
		m.MinDiskSize.Encode(e)
	}
}

func (m *SnapshotStatusResponse) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *SnapshotStatusResponse) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("SnapshotStatusResponse")
	}

	return d.ObjBytes(reserrors.PathAccumulatorErrorObjBytesFuncWrap(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "ready":
			var v common.ResourceStatusReadyResponse
			if err := v.Decode(d); err != nil {
				return err
			}

			m.Ready = v
			return nil
		case "storageSize":
			var v bytesize.ByteSize
			if err := v.Decode(d); err != nil {
				return err
			}

			m.StorageSize = &v
			return nil
		case "progress":
			v, err := decode.Str(d)
			if err != nil {
				return err
			}

			m.Progress = &v
			return nil
		case "sourceExists":
			v, err := decode.Bool(d)
			if err != nil {
				return err
			}

			m.SourceExists = &v
			return nil
		case "minDiskSize":
			var v bytesize.ByteSize
			if err := v.Decode(d); err != nil {
				return err
			}

			m.MinDiskSize = &v
			return nil
		default:
			return d.Skip()
		}
	}))
}
