// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/go-faster/jx"

	"go.mws.cloud/go-sdk/internal/conv"
	"go.mws.cloud/go-sdk/internal/decode"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	"go.mws.cloud/go-sdk/service/resources/references/compute"
	"go.mws.cloud/go-sdk/service/resources/references/iam"
)

func (m VirtualMachineSpecOptionalResponse) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	if err := m.Encode(&e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (m *VirtualMachineSpecOptionalResponse) Encode(e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	if err := m.encodeFields(e); err != nil {
		return err
	}
	e.ObjEnd()
	return nil
}

func (m *VirtualMachineSpecOptionalResponse) encodeFields(e *jx.Encoder) error {
	e.FieldStart("zone")
	e.Str(m.Zone)

	e.FieldStart("vmType")
	m.VmType.Encode(e)

	if m.Hardware.IsSet() {
		e.FieldStart("hardware")
		if m.Hardware.IsNull() {
			e.Null()
		} else {
			m.Hardware.Value.Encode(e)
		}
	}

	if m.Os.IsSet() {
		e.FieldStart("os")
		if m.Os.IsNull() {
			e.Null()
		} else {
			m.Os.Value.Encode(e)
		}
	}

	e.FieldStart("storage")
	m.Storage.Encode(e)

	e.FieldStart("network")
	m.Network.Encode(e)

	if m.ServiceAccount.IsSet() {
		e.FieldStart("serviceAccount")
		if m.ServiceAccount.IsNull() {
			e.Null()
		} else {
			m.ServiceAccount.Value.Encode(e)
		}
	}
	return nil
}

func (m *VirtualMachineSpecOptionalResponse) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *VirtualMachineSpecOptionalResponse) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("VirtualMachineSpecOptionalResponse")
	}

	return d.ObjBytes(reserrors.PathAccumulatorErrorObjBytesFuncWrap(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "zone":
			v, err := decode.Str(d)
			if err != nil {
				return err
			}

			m.Zone = v
			return nil
		case "vmType":
			var v compute.VmTypeRef
			if err := v.Decode(d); err != nil {
				return err
			}

			m.VmType = v
			return nil
		case "hardware":
			if d.Next() == jx.Null {
				m.Hardware.SetToNull()
				return d.Null()
			}

			var v HardwareSpecOptionalResponse
			if err := v.Decode(d); err != nil {
				return err
			}

			m.Hardware.SetTo(v)
			return nil
		case "os":
			if d.Next() == jx.Null {
				m.Os.SetToNull()
				return d.Null()
			}

			var v OsSpecOptionalResponse
			if err := v.Decode(d); err != nil {
				return err
			}

			m.Os.SetTo(v)
			return nil
		case "storage":
			var v StorageSpecOptionalResponse
			if err := v.Decode(d); err != nil {
				return err
			}

			m.Storage = v
			return nil
		case "network":
			var v NetworkSpecOptionalResponse
			if err := v.Decode(d); err != nil {
				return err
			}

			m.Network = v
			return nil
		case "serviceAccount":
			if d.Next() == jx.Null {
				m.ServiceAccount.SetToNull()
				return d.Null()
			}

			var v iam.ServiceAccountRef
			if err := v.Decode(d); err != nil {
				return err
			}

			m.ServiceAccount.SetTo(v)
			return nil
		default:
			return d.Skip()
		}
	}))
}
