// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	commonmodel "go.mws.cloud/go-sdk/service/common/model"
)

// Статус типа ВМ.
// Real OAPI model name: VmTypeStatus
type VmTypeStatusResponse struct {
	commonmodel.ResourceStatusResponse `yaml:"-,inline"`
}

func (m *VmTypeStatusResponse) GetReady() commonmodel.ResourceStatusReadyResponse {
	if m != nil {
		return m.ResourceStatusResponse.GetReady()
	}
	return commonmodel.ResourceStatusReadyResponse{}
}

func (m *VmTypeStatusResponse) Clone() *VmTypeStatusResponse {
	if m == nil {
		return nil
	}

	clone := *m
	clone.ResourceStatusResponse = *m.ResourceStatusResponse.Clone()

	return &clone
}
