// Code generated by mwsapigen, DO NOT EDIT.

package client

import (
	"context"

	"go.mws.cloud/util-toolset/pkg/utils/ptr"

	mwserrors "go.mws.cloud/go-sdk/mws/errors"
	"go.mws.cloud/go-sdk/mws/wait"
	"go.mws.cloud/go-sdk/service/auditlogs/model"
)

type CollectorSugared struct {
	impl Collector
}

func NewCollectorSugared(impl Collector) *CollectorSugared {
	return &CollectorSugared{
		impl: impl,
	}
}

func (x *CollectorSugared) Impl() Collector {
	return x.impl
}

// DeleteCollector позволяет удалить коллектор.
//
// Путь: DELETE /auditlogs/v1/projects/{project}/collectors/{collectorName}
func (x *CollectorSugared) DeleteCollector(ctx context.Context, request DeleteCollectorRequest, opts ...Option) error {
	config := newConfig(opts...)

	resp, err := x.impl.DeleteCollector(ctx, request)
	if err != nil {
		return err
	}

	err = x.respHandlerDeleteCollector(resp)
	if err != nil {
		return err
	}

	if !config.wait {
		return nil
	}

	return x.waitDeleteCollector(ctx, request.getCollectorRequest(), config.waitOptions...)
}

func (x *CollectorSugared) respHandlerDeleteCollector(resp *DeleteCollectorResponse) error {
	if err := resp.GetErr(); err != nil {
		return err
	}

	if resp.Response204 {
		return nil
	}

	return mwserrors.NewAPIError(resp.Code, mwserrors.Unknown, "unexpected result")
}

func (x *CollectorSugared) waitDeleteCollector(ctx context.Context, request GetCollectorRequest, opts ...wait.WaiterOption) error {
	callback := func(ctx context.Context) (*model.CollectorOptionalResponse, bool, error) {
		_, err := x.GetCollector(ctx, request)
		if mwserrors.IsAPIErrorNotFoundStatus(err) {
			return nil, true, nil
		}
		return nil, false, err
	}
	waiter := wait.NewWaiter(callback, opts...)
	_, err := waiter.Wait(ctx)
	return err
}

// GetCollector позволяет получить информацию о коллекторе.
//
// Путь: GET /auditlogs/v1/projects/{project}/collectors/{collectorName}
func (x *CollectorSugared) GetCollector(ctx context.Context, request GetCollectorRequest, opts ...Option) (*model.CollectorOptionalResponse, error) {
	config := newConfig(opts...)

	resp, err := x.impl.GetCollector(ctx, request)
	if err != nil {
		return nil, err
	}

	sugaredResponse, err := x.respHandlerGetCollector(resp)
	if err != nil {
		return nil, err
	}

	if !config.wait {
		return sugaredResponse, nil
	}

	return x.waitGetCollector(ctx, request, config.waitOptions...)
}

func (x *CollectorSugared) respHandlerGetCollector(resp *GetCollectorResponse) (*model.CollectorOptionalResponse, error) {
	if err := resp.GetErr(); err != nil {
		return nil, err
	}

	if resp.Response200 != nil {
		return resp.Response200, nil
	}

	return nil, mwserrors.NewAPIError(resp.Code, mwserrors.Unknown, "unexpected result")
}

func (x *CollectorSugared) waitGetCollector(ctx context.Context, request GetCollectorRequest, opts ...wait.WaiterOption) (*model.CollectorOptionalResponse, error) {
	callback := func(ctx context.Context) (*model.CollectorOptionalResponse, bool, error) {
		response, err := x.GetCollector(ctx, request)
		stop := string(ptr.Get(response.GetStatus().GetReady()).GetState()) != "PROCESSING"
		return response, stop, err
	}
	waiter := wait.NewWaiter(callback, opts...)
	return waiter.Wait(ctx)
}

// UpsertCollector создание и изменение коллектора.
//
// Путь: POST /auditlogs/v1/projects/{project}/collectors/{collectorName}
func (x *CollectorSugared) UpsertCollector(ctx context.Context, request UpsertCollectorRequest, opts ...Option) (*model.CollectorOptionalResponse, error) {
	config := newConfig(opts...)

	resp, err := x.impl.UpsertCollector(ctx, request)
	if err != nil {
		return nil, err
	}

	sugaredResponse, err := x.respHandlerUpsertCollector(resp)
	if err != nil {
		return nil, err
	}

	if !config.wait {
		return sugaredResponse, nil
	}

	return x.waitUpsertCollector(ctx, request.getCollectorRequest(), config.waitOptions...)
}

func (x *CollectorSugared) respHandlerUpsertCollector(resp *UpsertCollectorResponse) (*model.CollectorOptionalResponse, error) {
	if err := resp.GetErr(); err != nil {
		return nil, err
	}

	if resp.Response200 != nil {
		return resp.Response200, nil
	}

	return nil, mwserrors.NewAPIError(resp.Code, mwserrors.Unknown, "unexpected result")
}

func (x *CollectorSugared) waitUpsertCollector(ctx context.Context, request GetCollectorRequest, opts ...wait.WaiterOption) (*model.CollectorOptionalResponse, error) {
	callback := func(ctx context.Context) (*model.CollectorOptionalResponse, bool, error) {
		response, err := x.GetCollector(ctx, request)
		stop := string(ptr.Get(response.GetStatus().GetReady()).GetState()) != "PROCESSING"
		return response, stop, err
	}
	waiter := wait.NewWaiter(callback, opts...)
	return waiter.Wait(ctx)
}

// CreateCollector создание и изменение коллектора.
// Данный метод не описан в OpenAPI-спецификации, он был сгенерирован на основе операции upsert, для удобства.
//
// Путь: POST /auditlogs/v1/projects/{project}/collectors/{collectorName}?createOnly=true
func (x *CollectorSugared) CreateCollector(ctx context.Context, request UpsertCollectorRequest, opts ...Option) (*model.CollectorOptionalResponse, error) {
	config := newConfig(opts...)

	resp, err := x.impl.CreateCollector(ctx, request)
	if err != nil {
		return nil, err
	}

	sugaredResponse, err := x.respHandlerUpsertCollector(resp)
	if err != nil {
		return nil, err
	}

	if !config.wait {
		return sugaredResponse, nil
	}

	return x.waitUpsertCollector(ctx, request.getCollectorRequest(), config.waitOptions...)
}

// UpdateCollector создание и изменение коллектора.
// Данный метод не описан в OpenAPI-спецификации, он был сгенерирован на основе операции upsert, для удобства.
//
// Путь: POST /auditlogs/v1/projects/{project}/collectors/{collectorName}?updateOnly=true
func (x *CollectorSugared) UpdateCollector(ctx context.Context, request UpdateCollectorRequest, opts ...Option) (*model.CollectorOptionalResponse, error) {
	config := newConfig(opts...)

	resp, err := x.impl.UpdateCollector(ctx, request)
	if err != nil {
		return nil, err
	}

	sugaredResponse, err := x.respHandlerUpsertCollector(resp)
	if err != nil {
		return nil, err
	}

	if !config.wait {
		return sugaredResponse, nil
	}

	return x.waitUpsertCollector(ctx, request.getCollectorRequest(), config.waitOptions...)
}

// ListCollectors позволяет получить список коллекторов.
//
// Путь: GET /auditlogs/v1/projects/{project}/collectors
func (x *CollectorSugared) ListCollectors(ctx context.Context, request ListCollectorsRequest) (*ListCollectorsResponse200, error) {
	resp, err := x.impl.ListCollectors(ctx, request)
	if err != nil {
		return nil, err
	}

	return x.respHandlerListCollectors(resp)
}

func (x *CollectorSugared) respHandlerListCollectors(resp *ListCollectorsResponse) (*ListCollectorsResponse200, error) {
	if err := resp.GetErr(); err != nil {
		return nil, err
	}

	if resp.Response200 != nil {
		return resp.Response200, nil
	}

	return nil, mwserrors.NewAPIError(resp.Code, mwserrors.Unknown, "unexpected result")
}
