// Code generated by mwsapigen, DO NOT EDIT.

package client

import (
	"context"
	"fmt"

	"github.com/go-faster/jx"

	commonclient "go.mws.cloud/go-sdk/internal/client"
	"go.mws.cloud/go-sdk/internal/conv"
	mwsinternalerrors "go.mws.cloud/go-sdk/internal/errors"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	common "go.mws.cloud/go-sdk/service/common/model"
	"go.mws.cloud/go-sdk/service/compute/model"
)

type Image interface {
	// LatestImage позволяет получить latest образ.
	//
	// Путь: GET /compute/v1/projects/{project}/images:latest
	LatestImage(context.Context, LatestImageRequest) (*LatestImageResponse, error)
	// ListImages позволяет получить список образов.
	//
	// Путь: GET /compute/v1/projects/{project}/images
	ListImages(context.Context, ListImagesRequest) (*ListImagesResponse, error)
	// DeleteImage позволяет удалить образ.
	//
	// Путь: DELETE /compute/v1/projects/{project}/images/{image}
	DeleteImage(context.Context, DeleteImageRequest) (*DeleteImageResponse, error)
	// GetImage позволяет получить информацию об образе.
	//
	// Путь: GET /compute/v1/projects/{project}/images/{image}
	GetImage(context.Context, GetImageRequest) (*GetImageResponse, error)
	// UpsertImage позволяет создать или изменить образ.
	//
	// Путь: POST /compute/v1/projects/{project}/images/{image}
	UpsertImage(context.Context, UpsertImageRequest) (*UpsertImageResponse, error)
	// CreateImage позволяет создать или изменить образ.
	// Данный метод не описан в OpenAPI-спецификации, он был сгенерирован на основе операции upsert, для удобства.
	//
	// Путь: POST /compute/v1/projects/{project}/images/{image}?createOnly=true
	CreateImage(context.Context, UpsertImageRequest) (*UpsertImageResponse, error)
	// UpdateImage позволяет создать или изменить образ.
	// Данный метод не описан в OpenAPI-спецификации, он был сгенерирован на основе операции upsert, для удобства.
	//
	// Путь: POST /compute/v1/projects/{project}/images/{image}?updateOnly=true
	UpdateImage(context.Context, UpdateImageRequest) (*UpsertImageResponse, error)
}

type LatestImageRequest struct {
	// Токен авторизации IAM
	Authorization string // header: "Authorization"
	// Путь к проекту
	Project string // path: "project"
	// Название образа family
	Family string // query: "family"
}

func (m *LatestImageRequest) SetAuthorization(authorization string) {
	m.Authorization = authorization
}

func (m LatestImageRequest) GetProject() string {
	return m.Project
}

func (m *LatestImageRequest) SetProject(project string) {
	m.Project = project
}

type LatestImageResponse struct {
	Code        int
	Response200 *model.ImageOptionalResponse
	Response400 *common.ApiError
	Response403 *common.ApiError
	Response404 *common.ApiError
	Response500 *common.ApiError

	errorWrapper func(err error) error
}

func (m *LatestImageResponse) GetCode() int {
	return m.Code
}

func (m *LatestImageResponse) GetErr() (err error) {
	defer func() {
		if err != nil && m.errorWrapper != nil {
			err = m.errorWrapper(err)
		}
	}()
	if m.Response400 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response400)
	}
	if m.Response403 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response403)
	}
	if m.Response404 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response404)
	}
	if m.Response500 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response500)
	}
	return nil
}

func (m *LatestImageResponse) SetErrorWrapper(f func(err error) error) {
	if m != nil {
		m.errorWrapper = f
	}
}

type ListImagesRequest struct {
	// Токен авторизации IAM
	Authorization string // header: "Authorization"
	// Путь к проекту
	Project string // path: "project"
	// Максимальное количество объектов, которые клиент готов принять. Сервис определяет значение по умолчание и верхнюю границу
	PageSize *int // query: "pageSize"
	// Строка, из предыдущего ответа на аналогичный запрос, для получения следующей страницы с объектами. Не задано для получения первой страницы
	PageToken *string // query: "pageToken"
	// Строка фильтра.
	// Для фильтрации используется ограниченная реализация AIP-160 (https://google.aip.dev/160).
	// Она включает в себя операции =, !=, OR, AND и (), фильтрацию свойств вложенных объектов и wildcard-поиск подстрок
	Filter *string // query: "filter"
	// Строка сортировки.
	// Для сортировки используется реализация AIP-132 (https://google.aip.dev/132#ordering).
	// Указывается перечислением полей с направлением сортировки (asc, desc) через запятую.
	// По умолчанию используется сортировка по возрастанию (asc)
	OrderBy *string // query: "orderBy"
}

func (m *ListImagesRequest) SetAuthorization(authorization string) {
	m.Authorization = authorization
}

func (m ListImagesRequest) GetProject() string {
	return m.Project
}

func (m *ListImagesRequest) SetProject(project string) {
	m.Project = project
}

func (m ListImagesRequest) WithPageToken(token *string) ListImagesRequest {
	m.PageToken = token
	return m
}

type ListImagesResponse struct {
	Code        int
	Response200 *ListImagesResponse200
	Response403 *common.ApiError
	Response500 *common.ApiError

	errorWrapper func(err error) error
}

func (m *ListImagesResponse) GetCode() int {
	return m.Code
}

func (m *ListImagesResponse) GetErr() (err error) {
	defer func() {
		if err != nil && m.errorWrapper != nil {
			err = m.errorWrapper(err)
		}
	}()
	if m.Response403 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response403)
	}
	if m.Response500 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response500)
	}
	return nil
}

func (m *ListImagesResponse) SetErrorWrapper(f func(err error) error) {
	if m != nil {
		m.errorWrapper = f
	}
}

// ListImagesResponse200 is a nested type
type ListImagesResponse200 struct {
	Items []model.ImageOptionalResponse `json:"items" yaml:"items"`
	// Строка, которую нужно передать в следующий запрос, чтобы получить следующую страницу. Для последней страницы не задан
	NextPageToken commonclient.Optional[common.NextPageToken] `json:"nextPageToken,omitempty" yaml:"nextPageToken,omitempty"`
}

func (m *ListImagesResponse200) GetItems() []model.ImageOptionalResponse {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ListImagesResponse200) SetItems(val []model.ImageOptionalResponse) {
	m.Items = val
}

func (m *ListImagesResponse200) GetNextPageToken() *common.NextPageToken {
	if m != nil && m.NextPageToken.IsSet() {
		return &m.NextPageToken.Value
	}
	return nil
}

func (m *ListImagesResponse200) GetNextPageTokenOr(val common.NextPageToken) common.NextPageToken {
	if m != nil && m.NextPageToken.IsSet() {
		return m.NextPageToken.Value
	}
	return val
}

func (m *ListImagesResponse200) Clone() *ListImagesResponse200 {
	if m == nil {
		return nil
	}

	clone := *m
	if m.Items != nil {
		clone.Items = make([]model.ImageOptionalResponse, len(m.Items))
		for i, v := range m.Items {
			clone.Items[i] = *v.Clone()
		}
	}
	return &clone
}

func (m *ListImagesResponse200) Parse(ctx context.Context) error {
	if m == nil {
		return nil
	}

	for index := range m.Items {
		if err := m.Items[index].Parse(ctx); err != nil {
			return reserrors.NewPathAccumulatorError("Items"+fmt.Sprint("[", index, "]"), err)
		}
	}

	return nil
}

func (m ListImagesResponse200) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *ListImagesResponse200) Encode(e *jx.Encoder) {
	if m == nil {
		e.Null()
		return
	}
	e.ObjStart()
	m.encodeFields(e)
	e.ObjEnd()
}

func (m *ListImagesResponse200) encodeFields(e *jx.Encoder) {
	e.FieldStart("items")
	e.ArrStart()
	for _, elem := range m.Items {
		elem.Encode(e)
	}
	e.ArrEnd()

	if m.NextPageToken.IsSet() {
		e.FieldStart("nextPageToken")
		m.NextPageToken.Value.Encode(e)
	}
}

func (m *ListImagesResponse200) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *ListImagesResponse200) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("ListImagesResponse200")
	}

	return d.ObjBytes(reserrors.PathAccumulatorErrorObjBytesFuncWrap(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "items":
			c := make([]model.ImageOptionalResponse, 0)
			if err := d.Arr(reserrors.PathAccumulatorErrorAsIndexArrFuncWrap(func(d *jx.Decoder) error {
				var v model.ImageOptionalResponse
				if err := v.Decode(d); err != nil {
					return err
				}
				c = append(c, v)
				return nil
			})); err != nil {
				return err
			}

			m.Items = c
			return nil
		case "nextPageToken":
			var v common.NextPageToken
			if err := v.Decode(d); err != nil {
				return err
			}

			m.NextPageToken.SetTo(v)
			return nil
		default:
			return d.Skip()
		}
	}))
}

type DeleteImageRequest struct {
	// Токен авторизации IAM
	Authorization string // header: "Authorization"
	// Путь к проекту
	Project string // path: "project"
	// Путь к образу
	Image string // path: "image"
	// Удалить ресурс без возможности восстановления
	Purge *bool // query: "purge"
	// Ключ идемпотентности
	IdempotencyKey *string // header: "Idempotency-Key"
}

func (m *DeleteImageRequest) SetAuthorization(authorization string) {
	m.Authorization = authorization
}

func (m DeleteImageRequest) GetProject() string {
	return m.Project
}

func (m *DeleteImageRequest) SetProject(project string) {
	m.Project = project
}

func (m *DeleteImageRequest) getImageRequest() GetImageRequest {
	return GetImageRequest{
		Authorization: m.Authorization,
		Project:       m.Project,
		Image:         m.Image,
	}
}

type DeleteImageResponse struct {
	Code        int
	Response204 bool // empty response
	Response400 *common.ApiError
	Response403 *common.ApiError
	Response404 *common.ApiError
	Response500 *common.ApiError

	errorWrapper func(err error) error
}

func (m *DeleteImageResponse) GetCode() int {
	return m.Code
}

func (m *DeleteImageResponse) GetErr() (err error) {
	defer func() {
		if err != nil && m.errorWrapper != nil {
			err = m.errorWrapper(err)
		}
	}()
	if m.Response400 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response400)
	}
	if m.Response403 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response403)
	}
	if m.Response404 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response404)
	}
	if m.Response500 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response500)
	}
	return nil
}

func (m *DeleteImageResponse) SetErrorWrapper(f func(err error) error) {
	if m != nil {
		m.errorWrapper = f
	}
}

type GetImageRequest struct {
	// Токен авторизации IAM
	Authorization string // header: "Authorization"
	// Путь к проекту
	Project string // path: "project"
	// Путь к образу
	Image string // path: "image"
	// Текущий etag объекта, при передаче сервис будет дожидаться изменений в ресурсе (смены etag)
	WaitNew *string // query: "waitNew"
}

func (m *GetImageRequest) SetAuthorization(authorization string) {
	m.Authorization = authorization
}

func (m GetImageRequest) GetProject() string {
	return m.Project
}

func (m *GetImageRequest) SetProject(project string) {
	m.Project = project
}

type GetImageResponse struct {
	Code        int
	Response200 *model.ImageOptionalResponse
	Response400 *common.ApiError
	Response403 *common.ApiError
	Response404 *common.ApiError
	Response500 *common.ApiError

	errorWrapper func(err error) error
}

func (m *GetImageResponse) GetCode() int {
	return m.Code
}

func (m *GetImageResponse) GetErr() (err error) {
	defer func() {
		if err != nil && m.errorWrapper != nil {
			err = m.errorWrapper(err)
		}
	}()
	if m.Response400 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response400)
	}
	if m.Response403 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response403)
	}
	if m.Response404 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response404)
	}
	if m.Response500 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response500)
	}
	return nil
}

func (m *GetImageResponse) SetErrorWrapper(f func(err error) error) {
	if m != nil {
		m.errorWrapper = f
	}
}

type UpsertImageRequest struct {
	// Токен авторизации IAM
	Authorization string // header: "Authorization"
	// Путь к проекту
	Project string // path: "project"
	// Путь к образу
	Image string // path: "image"
	// Ключ идемпотентности
	IdempotencyKey *string // header: "Idempotency-Key"
	// Новые параметры для образа
	Body model.ImageRequest // body
}

func (m *UpsertImageRequest) SetAuthorization(authorization string) {
	m.Authorization = authorization
}

func (m UpsertImageRequest) GetProject() string {
	return m.Project
}

func (m *UpsertImageRequest) SetProject(project string) {
	m.Project = project
}

func (m *UpsertImageRequest) getImageRequest() GetImageRequest {
	return GetImageRequest{
		Authorization: m.Authorization,
		Project:       m.Project,
		Image:         m.Image,
	}
}

type UpdateImageRequest struct {
	// Токен авторизации IAM
	Authorization string // header: "Authorization"
	// Путь к проекту
	Project string // path: "project"
	// Путь к образу
	Image string // path: "image"
	// Ключ идемпотентности
	IdempotencyKey *string // header: "Idempotency-Key"
	// Новые параметры для образа
	Body model.UpdateImageRequest // body
}

func (m *UpdateImageRequest) SetAuthorization(authorization string) {
	m.Authorization = authorization
}

func (m UpdateImageRequest) GetProject() string {
	return m.Project
}

func (m *UpdateImageRequest) SetProject(project string) {
	m.Project = project
}

func (m *UpdateImageRequest) getImageRequest() GetImageRequest {
	return GetImageRequest{
		Authorization: m.Authorization,
		Project:       m.Project,
		Image:         m.Image,
	}
}

type UpsertImageResponse struct {
	Code        int
	Response200 *model.ImageOptionalResponse
	Response400 *common.ApiError
	Response403 *common.ApiError
	Response409 *common.ApiError
	Response500 *common.ApiError

	errorWrapper func(err error) error
}

func (m *UpsertImageResponse) GetCode() int {
	return m.Code
}

func (m *UpsertImageResponse) GetErr() (err error) {
	defer func() {
		if err != nil && m.errorWrapper != nil {
			err = m.errorWrapper(err)
		}
	}()
	if m.Response400 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response400)
	}
	if m.Response403 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response403)
	}
	if m.Response409 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response409)
	}
	if m.Response500 != nil {
		return mwsinternalerrors.WrapAPIGenError(m.Code, m.Response500)
	}
	return nil
}

func (m *UpsertImageResponse) SetErrorWrapper(f func(err error) error) {
	if m != nil {
		m.errorWrapper = f
	}
}
