// Code generated by mwsapigen, DO NOT EDIT.

package model

// Тело запроса для выполнения switchover в кластере managed postgres
// Real OAPI model name: PostgresClusterSwitchover
type PostgresClusterSwitchoverRequest struct {
	// Имя экземпляра postgres, являющегося кандидатом на роль нового primary
	Candidate string `json:"candidate" yaml:"candidate"`
}

func (m *PostgresClusterSwitchoverRequest) GetCandidate() string {
	if m != nil {
		return m.Candidate
	}
	return ""
}

func (m *PostgresClusterSwitchoverRequest) SetCandidate(val string) {
	m.Candidate = val
}

func (m *PostgresClusterSwitchoverRequest) Clone() *PostgresClusterSwitchoverRequest {
	if m == nil {
		return nil
	}

	clone := *m
	return &clone
}
