// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/go-faster/jx"

	"go.mws.cloud/go-sdk/internal/conv"
	"go.mws.cloud/go-sdk/internal/decode"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
)

// Real OAPI model name: PostgresInstance
type PostgresInstanceRequest struct {
	// Количество экземпляров в зоне доступности.
	Count int `json:"count" yaml:"count"`
	// Зона доступности.
	Zone *string `json:"zone,omitempty" yaml:"zone,omitempty"`
}

func (m *PostgresInstanceRequest) GetCount() int {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *PostgresInstanceRequest) SetCount(val int) {
	m.Count = val
}

func (m *PostgresInstanceRequest) GetZone() *string {
	if m != nil {
		return m.Zone
	}
	return nil
}

func (m *PostgresInstanceRequest) SetZone(val *string) {
	m.Zone = val
}

func (m *PostgresInstanceRequest) GetZoneOr(val string) string {
	if m != nil && m.Zone != nil {
		return *m.Zone
	}
	return val
}

func (m *PostgresInstanceRequest) Clone() *PostgresInstanceRequest {
	if m == nil {
		return nil
	}

	clone := *m
	if m.Zone != nil {
		cloneZone := *m.Zone
		clone.Zone = &cloneZone
	}
	return &clone
}

// JSON methods

func (m PostgresInstanceRequest) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	if err := m.Encode(&e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (m *PostgresInstanceRequest) Encode(e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	if err := m.encodeFields(e); err != nil {
		return err
	}
	e.ObjEnd()
	return nil
}

func (m *PostgresInstanceRequest) encodeFields(e *jx.Encoder) error {
	e.FieldStart("count")
	e.Int(m.Count)

	if m.Zone != nil {
		e.FieldStart("zone")
		e.Str(*m.Zone)
	}
	return nil
}

func (m *PostgresInstanceRequest) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *PostgresInstanceRequest) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("PostgresInstanceRequest")
	}

	requiredFilled := map[string]bool{
		"count": false,
	}
	err := d.ObjBytes(reserrors.PathAccumulatorErrorObjBytesFuncWrap(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "count":
			v, err := decode.Int(d)
			if err != nil {
				return err
			}

			m.Count = v
			requiredFilled["count"] = true
			return nil
		case "zone":
			v, err := decode.Str(d)
			if err != nil {
				return err
			}

			m.Zone = &v
			return nil
		default:
			return d.Skip()
		}
	}))
	if err != nil {
		return err
	}

	return conv.ValidateRequired(requiredFilled)
}
