// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"context"

	"go.mws.cloud/util-toolset/pkg/utils/ptr"

	commonclient "go.mws.cloud/go-sdk/internal/client"
	"go.mws.cloud/go-sdk/internal/merge"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	common "go.mws.cloud/go-sdk/service/common/model"
)

type UpdatePostgresBackupRequest struct {
	Metadata commonclient.OptionalNil[UpdatePostgresBackupMetadataRequest] `json:"metadata" yaml:"metadata"`
	Spec     commonclient.OptionalNil[UpdatePostgresBackupSpecRequest]     `json:"spec" yaml:"spec"`
}

func (m *PostgresBackupRequest) AsUpdateModel() UpdatePostgresBackupRequest {
	var u UpdatePostgresBackupRequest
	if m.Metadata != nil {
		u.Metadata = commonclient.NewOptionalNil(m.Metadata.AsUpdateModel())
	}
	if m.Spec != nil {
		u.Spec = commonclient.NewOptionalNil(m.Spec.AsUpdateModel())
	}
	return u
}

// Diff creates an object that can be used in Update methods. This object represents changes from src to the current state
func (m *PostgresBackupRequest) Diff(src *PostgresBackupRequest) UpdatePostgresBackupRequest {
	nilDiffers := src != nil && m == nil
	upd := UpdatePostgresBackupRequest{}
	if !nilDiffers {
		upd.Metadata = m.diffMetadata(src)
		upd.Spec = m.diffSpec(src)
	}
	return upd
}

func (m *PostgresBackupRequest) WithChanges(u UpdatePostgresBackupRequest) PostgresBackupRequest {
	var out PostgresBackupRequest
	if m != nil {
		out = *m
	}

	if u.Metadata.IsSet() {
		out.Metadata = ptr.Get(out.Metadata.WithChanges(u.Metadata.Value))
	} else if u.Metadata.IsNull() {
		out.Metadata = nil
	}
	if u.Spec.IsSet() {
		out.Spec = ptr.Get(PostgresBackupSpecRequest(u.Spec.Value))
	} else if u.Spec.IsNull() {
		out.Spec = nil
	}
	return out
}

// HasChanges returns true if any field has Set == true
func (m UpdatePostgresBackupRequest) HasChanges() bool {
	return m.Metadata.Set ||
		m.Spec.Set
}

func (m *UpdatePostgresBackupRequest) Parse(ctx context.Context) error {
	if m == nil {
		return nil
	}

	if m.Metadata.IsSet() {
		if err := m.Metadata.Value.Parse(ctx); err != nil {
			return reserrors.NewPathAccumulatorError("Metadata", err)
		}
	}

	return nil
}

func (m *PostgresBackupRequest) diffMetadata(src *PostgresBackupRequest) commonclient.OptionalNil[UpdatePostgresBackupMetadataRequest] {
	nilDiffers := src != nil && m == nil
	value := m.GetMetadata().Diff(src.GetMetadata())
	return commonclient.NewDirectOptionalNil[UpdatePostgresBackupMetadataRequest](value, nilDiffers || value.HasChanges(), nilDiffers)
}

func (m *PostgresBackupRequest) diffSpec(src *PostgresBackupRequest) commonclient.OptionalNil[UpdatePostgresBackupSpecRequest] {
	nilDiffers := src != nil && m == nil
	value := m.GetSpec().Diff(src.GetSpec())
	return commonclient.NewDirectOptionalNil[UpdatePostgresBackupSpecRequest](value, nilDiffers || value.HasChanges(), nilDiffers)
}

type UpdatePostgresBackupMetadataRequest struct {
	common.UpdateTypedResourceMetadataRequest
}

func (m *PostgresBackupMetadataRequest) AsUpdateModel() UpdatePostgresBackupMetadataRequest {
	var u UpdatePostgresBackupMetadataRequest
	if m.DisplayName != nil {
		u.DisplayName = commonclient.NewOptional(m.GetDisplayNameOr(""))
	}
	if m.Usages != nil {
		u.Usages = commonclient.NewOptional(func() []common.UpdateTypedUsageRequest {
			var tmp []common.UpdateTypedUsageRequest
			if m.GetUsages() != nil {
				tmp = make([]common.UpdateTypedUsageRequest, 0, len(m.GetUsages()))
			}
			for _, val := range m.GetUsages() {
				tmp = append(tmp, val.AsUpdateModel())
			}
			return tmp
		}())
	}
	if m.Etag != nil {
		u.Etag = commonclient.NewOptional(m.GetEtagOr(""))
	}
	if m.Description != nil {
		u.Description = commonclient.NewOptional(m.GetDescriptionOr(""))
	}
	return u
}

// Diff creates an object that can be used in Update methods. This object represents changes from src to the current state
func (m *PostgresBackupMetadataRequest) Diff(src *PostgresBackupMetadataRequest) UpdatePostgresBackupMetadataRequest {
	nilDiffers := src != nil && m == nil
	upd := UpdatePostgresBackupMetadataRequest{}
	if !nilDiffers {
		upd.DisplayName = m.diffDisplayName(src)
		upd.Usages = m.diffUsages(src)
		upd.Etag = m.diffEtag(src)
		upd.Description = m.diffDescription(src)
	}
	return upd
}

func (m *PostgresBackupMetadataRequest) WithChanges(u UpdatePostgresBackupMetadataRequest) PostgresBackupMetadataRequest {
	var out PostgresBackupMetadataRequest
	if m != nil {
		out = *m
	}

	if u.DisplayName.IsSet() {
		out.DisplayName = ptr.Get(u.DisplayName.Value)
	}
	if u.Usages.IsSet() {
		out.Usages = merge.Slice(out.Usages, u.Usages.Value, (*common.TypedUsageRequest).WithChanges, (*common.TypedUsageRequest).GetName, (*common.UpdateTypedUsageRequest).GetName)
	}
	if u.Etag.IsSet() {
		out.Etag = ptr.Get(u.Etag.Value)
	}
	if u.Description.IsSet() {
		out.Description = ptr.Get(u.Description.Value)
	}
	return out
}

// HasChanges returns true if any field has Set == true
func (m UpdatePostgresBackupMetadataRequest) HasChanges() bool {
	return m.DisplayName.Set ||
		m.Usages.Set ||
		m.Etag.Set ||
		m.Description.Set
}

func (m *UpdatePostgresBackupMetadataRequest) Parse(ctx context.Context) error {
	if m == nil {
		return nil
	}

	if err := m.UpdateTypedResourceMetadataRequest.Parse(ctx); err != nil {
		return reserrors.NewPathAccumulatorError("UpdateTypedResourceMetadataRequest", err)
	}
	return nil
}

func (m *PostgresBackupMetadataRequest) diffDisplayName(src *PostgresBackupMetadataRequest) commonclient.Optional[string] {
	nilDiffers := src != nil && m == nil
	return commonclient.DiffPrimitiveNonRequired(src.GetDisplayName(), m.GetDisplayName(), nilDiffers)
}

func (m *PostgresBackupMetadataRequest) diffUsages(src *PostgresBackupMetadataRequest) commonclient.Optional[[]common.UpdateTypedUsageRequest] {
	diffFunc := func(fromItem, toItem common.TypedUsageRequest, fromNil bool) common.UpdateTypedUsageRequest {
		if fromNil {
			return toItem.Diff(nil)
		}
		return toItem.Diff(&fromItem)
	}
	value, hasChanges := commonclient.GetChangesArrayObject(src.GetUsages(), m.GetUsages(), diffFunc)
	return commonclient.NewDirectOptional[[]common.UpdateTypedUsageRequest](value, hasChanges)
}

func (m *PostgresBackupMetadataRequest) diffEtag(src *PostgresBackupMetadataRequest) commonclient.Optional[string] {
	nilDiffers := src != nil && m == nil
	return commonclient.DiffPrimitiveNonRequired(src.GetEtag(), m.GetEtag(), nilDiffers)
}

func (m *PostgresBackupMetadataRequest) diffDescription(src *PostgresBackupMetadataRequest) commonclient.Optional[string] {
	nilDiffers := src != nil && m == nil
	return commonclient.DiffPrimitiveNonRequired(src.GetDescription(), m.GetDescription(), nilDiffers)
}

type UpdatePostgresBackupSpecRequest struct {
}

func (m *PostgresBackupSpecRequest) AsUpdateModel() UpdatePostgresBackupSpecRequest {
	var u UpdatePostgresBackupSpecRequest
	return u
}

// Diff creates an object that can be used in Update methods. This object represents changes from src to the current state
func (m *PostgresBackupSpecRequest) Diff(src *PostgresBackupSpecRequest) UpdatePostgresBackupSpecRequest {
	nilDiffers := src != nil && m == nil
	upd := UpdatePostgresBackupSpecRequest{}
	if !nilDiffers {
	}
	return upd
}

func (m *PostgresBackupSpecRequest) WithChanges(u UpdatePostgresBackupSpecRequest) PostgresBackupSpecRequest {
	var out PostgresBackupSpecRequest
	if m != nil {
		out = *m
	}

	return out
}

// HasChanges returns true if any field has Set == true
func (m UpdatePostgresBackupSpecRequest) HasChanges() bool {
	return false
}
