// Code generated by mwsapigen, DO NOT EDIT.

package model

// Real OAPI model name: PostgresBackupSpec
type PostgresBackupSpecResponse struct {
}

func (m *PostgresBackupSpecResponse) Clone() *PostgresBackupSpecResponse {
	if m == nil {
		return nil
	}

	clone := *m
	return &clone
}
