// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/go-faster/jx"

	"go.mws.cloud/go-sdk/internal/conv"
	"go.mws.cloud/go-sdk/internal/decode"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
)

// Спецификация расширения
// Real OAPI model name: PostgresExtensionSpec
type PostgresExtensionSpecResponse struct {
	// Имя расширения
	Name string `json:"name" yaml:"name"`
}

func (m *PostgresExtensionSpecResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PostgresExtensionSpecResponse) SetName(val string) {
	m.Name = val
}

func (m *PostgresExtensionSpecResponse) Clone() *PostgresExtensionSpecResponse {
	if m == nil {
		return nil
	}

	clone := *m
	return &clone
}

// JSON methods

func (m PostgresExtensionSpecResponse) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	if err := m.Encode(&e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (m *PostgresExtensionSpecResponse) Encode(e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	if err := m.encodeFields(e); err != nil {
		return err
	}
	e.ObjEnd()
	return nil
}

func (m *PostgresExtensionSpecResponse) encodeFields(e *jx.Encoder) error {
	e.FieldStart("name")
	e.Str(m.Name)
	return nil
}

func (m *PostgresExtensionSpecResponse) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *PostgresExtensionSpecResponse) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("PostgresExtensionSpecResponse")
	}

	return d.ObjBytes(reserrors.PathAccumulatorErrorObjBytesFuncWrap(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "name":
			v, err := decode.Str(d)
			if err != nil {
				return err
			}

			m.Name = v
			return nil
		default:
			return d.Skip()
		}
	}))
}
