// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"context"

	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	"go.mws.cloud/go-sdk/service/resources/references/vpc"
)

// Описание subnet пользователя, в который будет трансляция из service-vpc.
// Real OAPI model name: PostgresNetworkAddressSpec
type PostgresNetworkAddressSpecRequest struct {
	Subnet vpc.SubnetRef `json:"subnet" yaml:"subnet"`
}

func (m *PostgresNetworkAddressSpecRequest) GetSubnet() vpc.SubnetRef {
	if m != nil {
		return m.Subnet
	}
	return vpc.SubnetRef{}
}

func (m *PostgresNetworkAddressSpecRequest) SetSubnet(val vpc.SubnetRef) {
	m.Subnet = val
}

func (m *PostgresNetworkAddressSpecRequest) Clone() *PostgresNetworkAddressSpecRequest {
	if m == nil {
		return nil
	}

	clone := *m
	clone.Subnet = *m.Subnet.Clone()
	return &clone
}

func (m *PostgresNetworkAddressSpecRequest) Parse(ctx context.Context) error {
	if m == nil {
		return nil
	}

	if err := m.Subnet.Parse(ctx); err != nil {
		return reserrors.NewPathAccumulatorError("Subnet", err)
	}

	return nil
}
