// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	common "go.mws.cloud/go-sdk/service/common/model"
)

func PostgresClusterDatabaseRequestToResponse(request *PostgresClusterDatabaseRequest) (*PostgresClusterDatabaseResponse, error) {
	if request == nil {
		return nil, nil
	}
	var response PostgresClusterDatabaseResponse
	tmpMetadata, err := PostgresClusterDatabaseMetadataRequestToResponse(request.Metadata)
	if err != nil {
		return nil, err
	}
	response.Metadata = tmpMetadata
	tmpSpec, err := PostgresClusterDatabaseSpecRequestToResponse(&request.Spec)
	if err != nil {
		return nil, err
	}
	response.Spec = *tmpSpec
	return &response, nil
}

func PostgresClusterDatabaseMetadataRequestToResponse(request *PostgresClusterDatabaseMetadataRequest) (*PostgresClusterDatabaseMetadataResponse, error) {
	if request == nil {
		return nil, nil
	}
	var response PostgresClusterDatabaseMetadataResponse
	response.DisplayName = request.DisplayName
	for _, e := range request.Usages {
		tmp, err := common.TypedUsageRequestToResponse(&e)
		if err != nil {
			return nil, err
		}
		response.Usages = append(response.Usages, *tmp)
	}
	response.Etag = request.Etag
	response.Description = request.Description
	return &response, nil
}
