// Code generated by mwsapigen, DO NOT EDIT.

package model

func PostgresBackupSpecRequestToResponse(request *PostgresBackupSpecRequest) (*PostgresBackupSpecResponse, error) {
	if request == nil {
		return nil, nil
	}
	var response PostgresBackupSpecResponse
	return &response, nil
}
