// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"context"

	"github.com/go-faster/jx"

	"go.mws.cloud/go-sdk/internal/conv"
	"go.mws.cloud/go-sdk/internal/decode"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	"go.mws.cloud/go-sdk/service/resources/references/mpostgres"
)

// Real OAPI model name: PostgresClusterDatabaseSpec
type PostgresClusterDatabaseSpecResponse struct {
	// Имя владельца
	Owner mpostgres.PostgresClusterUserRef `json:"owner" yaml:"owner"`
	// Порядок сортировки строк
	LcCollate *string `json:"lcCollate,omitempty" yaml:"lcCollate,omitempty"`
	// Классификация символов
	LcCtype *string `json:"lcCtype,omitempty" yaml:"lcCtype,omitempty"`
	// Шаблон для создания базы данных
	Template *mpostgres.PostgresClusterDatabaseRef `json:"template,omitempty" yaml:"template,omitempty"`
	// Защита от удаления
	DeletionProtection *bool `json:"deletionProtection,omitempty" yaml:"deletionProtection,omitempty"`
	// Список расширений
	Extensions []PostgresExtensionSpecResponse `json:"extensions,omitempty" yaml:"extensions,omitempty"`
}

func (m *PostgresClusterDatabaseSpecResponse) GetOwner() mpostgres.PostgresClusterUserRef {
	if m != nil {
		return m.Owner
	}
	return mpostgres.PostgresClusterUserRef{}
}

func (m *PostgresClusterDatabaseSpecResponse) SetOwner(val mpostgres.PostgresClusterUserRef) {
	m.Owner = val
}

func (m *PostgresClusterDatabaseSpecResponse) GetLcCollate() *string {
	if m != nil {
		return m.LcCollate
	}
	return nil
}

func (m *PostgresClusterDatabaseSpecResponse) SetLcCollate(val *string) {
	m.LcCollate = val
}

func (m *PostgresClusterDatabaseSpecResponse) GetLcCollateOr(val string) string {
	if m != nil && m.LcCollate != nil {
		return *m.LcCollate
	}
	return val
}

func (m *PostgresClusterDatabaseSpecResponse) GetLcCtype() *string {
	if m != nil {
		return m.LcCtype
	}
	return nil
}

func (m *PostgresClusterDatabaseSpecResponse) SetLcCtype(val *string) {
	m.LcCtype = val
}

func (m *PostgresClusterDatabaseSpecResponse) GetLcCtypeOr(val string) string {
	if m != nil && m.LcCtype != nil {
		return *m.LcCtype
	}
	return val
}

func (m *PostgresClusterDatabaseSpecResponse) GetTemplate() *mpostgres.PostgresClusterDatabaseRef {
	if m != nil {
		return m.Template
	}
	return nil
}

func (m *PostgresClusterDatabaseSpecResponse) SetTemplate(val *mpostgres.PostgresClusterDatabaseRef) {
	m.Template = val
}

func (m *PostgresClusterDatabaseSpecResponse) GetTemplateOr(val mpostgres.PostgresClusterDatabaseRef) mpostgres.PostgresClusterDatabaseRef {
	if m != nil && m.Template != nil {
		return *m.Template
	}
	return val
}

func (m *PostgresClusterDatabaseSpecResponse) GetDeletionProtection() *bool {
	if m != nil {
		return m.DeletionProtection
	}
	return nil
}

func (m *PostgresClusterDatabaseSpecResponse) SetDeletionProtection(val *bool) {
	m.DeletionProtection = val
}

func (m *PostgresClusterDatabaseSpecResponse) GetDeletionProtectionOr(val bool) bool {
	if m != nil && m.DeletionProtection != nil {
		return *m.DeletionProtection
	}
	return val
}

func (m *PostgresClusterDatabaseSpecResponse) GetExtensions() []PostgresExtensionSpecResponse {
	if m != nil {
		return m.Extensions
	}
	return nil
}

func (m *PostgresClusterDatabaseSpecResponse) SetExtensions(val []PostgresExtensionSpecResponse) {
	m.Extensions = val
}

func (m *PostgresClusterDatabaseSpecResponse) GetExtensionsOr(val []PostgresExtensionSpecResponse) []PostgresExtensionSpecResponse {
	if m != nil && m.Extensions != nil {
		return m.Extensions
	}
	return val
}

func (m *PostgresClusterDatabaseSpecResponse) Clone() *PostgresClusterDatabaseSpecResponse {
	if m == nil {
		return nil
	}

	clone := *m
	clone.Owner = *m.Owner.Clone()
	if m.LcCollate != nil {
		cloneLcCollate := *m.LcCollate
		clone.LcCollate = &cloneLcCollate
	}
	if m.LcCtype != nil {
		cloneLcCtype := *m.LcCtype
		clone.LcCtype = &cloneLcCtype
	}
	clone.Template = m.Template.Clone()
	if m.DeletionProtection != nil {
		cloneDeletionProtection := *m.DeletionProtection
		clone.DeletionProtection = &cloneDeletionProtection
	}
	if m.Extensions != nil {
		clone.Extensions = make([]PostgresExtensionSpecResponse, len(m.Extensions))
		for i, v := range m.Extensions {
			clone.Extensions[i] = *v.Clone()
		}
	}
	return &clone
}

func (m *PostgresClusterDatabaseSpecResponse) Parse(ctx context.Context) error {
	if m == nil {
		return nil
	}

	if err := m.Owner.Parse(ctx); err != nil {
		return reserrors.NewPathAccumulatorError("Owner", err)
	}

	if err := m.Template.Parse(ctx); err != nil {
		return reserrors.NewPathAccumulatorError("Template", err)
	}

	return nil
}

// JSON methods

func (m PostgresClusterDatabaseSpecResponse) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	if err := m.Encode(&e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (m *PostgresClusterDatabaseSpecResponse) Encode(e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	if err := m.encodeFields(e); err != nil {
		return err
	}
	e.ObjEnd()
	return nil
}

func (m *PostgresClusterDatabaseSpecResponse) encodeFields(e *jx.Encoder) error {
	e.FieldStart("owner")
	if err := m.Owner.Encode(e); err != nil {
		return err
	}

	if m.LcCollate != nil {
		e.FieldStart("lcCollate")
		e.Str(*m.LcCollate)
	}

	if m.LcCtype != nil {
		e.FieldStart("lcCtype")
		e.Str(*m.LcCtype)
	}

	if m.Template != nil {
		e.FieldStart("template")
		if err := m.Template.Encode(e); err != nil {
			return err
		}
	}

	if m.DeletionProtection != nil {
		e.FieldStart("deletionProtection")
		e.Bool(*m.DeletionProtection)
	}

	if m.Extensions != nil {
		e.FieldStart("extensions")
		e.ArrStart()
		for _, elem := range m.Extensions {
			if err := elem.Encode(e); err != nil {
				return err
			}
		}
		e.ArrEnd()
	}
	return nil
}

func (m *PostgresClusterDatabaseSpecResponse) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *PostgresClusterDatabaseSpecResponse) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("PostgresClusterDatabaseSpecResponse")
	}

	return d.ObjBytes(reserrors.PathAccumulatorErrorObjBytesFuncWrap(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "owner":
			var v mpostgres.PostgresClusterUserRef
			if err := v.Decode(d); err != nil {
				return err
			}

			m.Owner = v
			return nil
		case "lcCollate":
			v, err := decode.Str(d)
			if err != nil {
				return err
			}

			m.LcCollate = &v
			return nil
		case "lcCtype":
			v, err := decode.Str(d)
			if err != nil {
				return err
			}

			m.LcCtype = &v
			return nil
		case "template":
			var v mpostgres.PostgresClusterDatabaseRef
			if err := v.Decode(d); err != nil {
				return err
			}

			m.Template = &v
			return nil
		case "deletionProtection":
			v, err := decode.Bool(d)
			if err != nil {
				return err
			}

			m.DeletionProtection = &v
			return nil
		case "extensions":
			c := make([]PostgresExtensionSpecResponse, 0)
			if err := d.Arr(reserrors.PathAccumulatorErrorAsIndexArrFuncWrap(func(d *jx.Decoder) error {
				var v PostgresExtensionSpecResponse
				if err := v.Decode(d); err != nil {
					return err
				}
				c = append(c, v)
				return nil
			})); err != nil {
				return err
			}

			m.Extensions = c
			return nil
		default:
			return d.Skip()
		}
	}))
}
