// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	commonclient "go.mws.cloud/go-sdk/internal/client"
)

func SecretSpecRequestToOptionalResponse(request *SecretSpecRequest) (*SecretSpecOptionalResponse, error) {
	if request == nil {
		return nil, nil
	}
	var response SecretSpecOptionalResponse
	if request.Active != nil {
		response.Active = commonclient.NewOptional(*request.Active)
	}
	if request.CurrentSecretVersion != nil {
		response.CurrentSecretVersion = commonclient.NewOptional(*request.CurrentSecretVersion)
	}
	if request.Encryption != nil {
		tmpEncryption, err := EncryptionSpecRequestToOptionalResponse(request.Encryption)
		if err != nil {
			return nil, err
		}
		response.Encryption = commonclient.NewOptionalNil(*tmpEncryption)
	}
	return &response, nil
}
