// Code generated by mwsapigen, DO NOT EDIT.

package model

func SecretSpecRequestToResponse(request *SecretSpecRequest) (*SecretSpecResponse, error) {
	if request == nil {
		return nil, nil
	}
	var response SecretSpecResponse
	response.Active = request.Active
	response.CurrentSecretVersion = request.CurrentSecretVersion
	return &response, nil
}
