// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"github.com/go-faster/jx"

	"go.mws.cloud/go-sdk/internal/conv"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	commonmodel "go.mws.cloud/go-sdk/service/common/model"
)

// Real OAPI model name: SecretVersion
type SecretVersionRequest struct {
	// Набор общих для всех пользовательских объектов атрибутов. Может быть расширен атрибутами, специфичными для контейнеров.
	Metadata *commonmodel.CommonTypedResourceMetadataRequest `json:"metadata,omitempty" yaml:"metadata,omitempty"`
	Spec     SecretVersionSpecRequest                        `json:"spec" yaml:"spec"`
}

func (m *SecretVersionRequest) GetMetadata() *commonmodel.CommonTypedResourceMetadataRequest {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *SecretVersionRequest) SetMetadata(val *commonmodel.CommonTypedResourceMetadataRequest) {
	m.Metadata = val
}

func (m *SecretVersionRequest) GetMetadataOr(val commonmodel.CommonTypedResourceMetadataRequest) commonmodel.CommonTypedResourceMetadataRequest {
	if m != nil && m.Metadata != nil {
		return *m.Metadata
	}
	return val
}

func (m *SecretVersionRequest) GetSpec() SecretVersionSpecRequest {
	if m != nil {
		return m.Spec
	}
	return SecretVersionSpecRequest{}
}

func (m *SecretVersionRequest) SetSpec(val SecretVersionSpecRequest) {
	m.Spec = val
}

func (m *SecretVersionRequest) Clone() *SecretVersionRequest {
	if m == nil {
		return nil
	}

	clone := *m
	clone.Metadata = m.Metadata.Clone()
	clone.Spec = *m.Spec.Clone()
	return &clone
}

// JSON methods

func (m SecretVersionRequest) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	if err := m.Encode(&e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (m *SecretVersionRequest) Encode(e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	e.ObjStart()
	if err := m.encodeFields(e); err != nil {
		return err
	}
	e.ObjEnd()
	return nil
}

func (m *SecretVersionRequest) encodeFields(e *jx.Encoder) error {
	if m.Metadata != nil {
		e.FieldStart("metadata")
		if err := m.Metadata.Encode(e); err != nil {
			return err
		}
	}

	e.FieldStart("spec")
	if err := m.Spec.Encode(e); err != nil {
		return err
	}
	return nil
}

func (m *SecretVersionRequest) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *SecretVersionRequest) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("SecretVersionRequest")
	}

	requiredFilled := map[string]bool{
		"spec": false,
	}
	err := d.ObjBytes(reserrors.PathAccumulatorErrorObjBytesFuncWrap(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "metadata":
			if d.Next() == jx.Null {
				return d.Null()
			}

			var v commonmodel.CommonTypedResourceMetadataRequest
			if err := v.Decode(d); err != nil {
				return err
			}

			m.Metadata = &v
			return nil
		case "spec":
			var v SecretVersionSpecRequest
			if err := v.Decode(d); err != nil {
				return err
			}

			m.Spec = v
			requiredFilled["spec"] = true
			return nil
		default:
			return d.Skip()
		}
	}))
	if err != nil {
		return err
	}

	return conv.ValidateRequired(requiredFilled)
}

// Defaults

func (m *SecretVersionRequest) WithDefaults() SecretVersionRequest {
	var out SecretVersionRequest
	if m != nil {
		out = *m
	}

	out.Spec = out.Spec.WithDefaults()
	return out
}
