// Code generated by mwsapigen, DO NOT EDIT.

package model

import (
	"go.mws.cloud/go-sdk/pkg/apimodels/sensitive"
)

// Содержимое секрета
type SecretVersionDataSpec map[string]sensitive.Sensitive[string]

func (m SecretVersionDataSpec) Clone() SecretVersionDataSpec {
	if m == nil {
		return nil
	}

	clone := make(map[string]sensitive.Sensitive[string], len(m))
	for k, v := range m {
		clone[k] = v
	}

	return clone
}
