// Code generated by mwsapigen, DO NOT EDIT.

package model

// Real OAPI model name: SecretVersionSpec
type SecretVersionSpecResponse struct {
	// Версия секрета активна/неактивна
	Active *bool `json:"active,omitempty" yaml:"active,omitempty"`
}

func (m *SecretVersionSpecResponse) GetActive() *bool {
	if m != nil {
		return m.Active
	}
	return nil
}

func (m *SecretVersionSpecResponse) SetActive(val *bool) {
	m.Active = val
}

func (m *SecretVersionSpecResponse) GetActiveOr(val bool) bool {
	if m != nil && m.Active != nil {
		return *m.Active
	}
	return val
}

func (m *SecretVersionSpecResponse) Clone() *SecretVersionSpecResponse {
	if m == nil {
		return nil
	}

	clone := *m
	if m.Active != nil {
		cloneActive := *m.Active
		clone.Active = &cloneActive
	}
	return &clone
}
