// Code generated by mwsapigen, DO NOT EDIT.

package model_test

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/service/iam/model"
)

func TestHmacKeyListResponseMarshalling(t *testing.T) {
	t.Parallel()
	expected := initHmacKeyListResponse()
	b, err := json.Marshal(expected)
	require.NoError(t, err)

	var actual model.HmacKeyListResponse
	require.NoError(t, json.Unmarshal(b, &actual))
	require.Equal(t, expected, actual)
}

func initHmacKeyListResponse() model.HmacKeyListResponse {
	var v model.HmacKeyListResponse
	v.Items = make([]model.HmacKeyResponse, 0)
	return v
}
