// Code generated by mwsapigen, DO NOT EDIT.

package model_test

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/require"

	"go.mws.cloud/go-sdk/service/iam/model"
)

func TestRoleStageResponseMarshalling(t *testing.T) {
	t.Parallel()
	expected := initRoleStageResponse()
	b, err := json.Marshal(expected)
	require.NoError(t, err)

	var actual model.RoleStageResponse
	require.NoError(t, json.Unmarshal(b, &actual))
	require.Equal(t, expected, actual)
}

func initRoleStageResponse() model.RoleStageResponse {
	var v model.RoleStageResponse
	return v
}
