// Code generated by mwsapigen, DO NOT EDIT.

package iam

import (
	"context"
	"fmt"

	"github.com/go-faster/jx"

	"go.mws.cloud/go-sdk/internal/conv"
	"go.mws.cloud/go-sdk/internal/decode"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	resparsers "go.mws.cloud/go-sdk/internal/resources/parsers"
	valuesctx "go.mws.cloud/go-sdk/pkg/context/values"
	resifaces "go.mws.cloud/go-sdk/pkg/resources/interfaces"
	resmodels "go.mws.cloud/go-sdk/pkg/resources/models"
)

var (
	FederationProviderCountRefTemplate = resparsers.Template{
		{
			Value:       "providerCount",
			IsConstant:  true,
			SearchAfter: true,
		},
		{
			Value:       "quotas",
			IsConstant:  true,
			SearchAfter: true,
		},
		{
			Value:       "iam",
			IsConstant:  true,
			SearchAfter: true,
		},
		{
			Value:       "services",
			IsConstant:  true,
			SearchAfter: false,
		},
		{
			Value:       "userFederation",
			IsConstant:  false,
			SearchAfter: true,
		},
		{
			Value:       "userFederations",
			IsConstant:  true,
			SearchAfter: false,
		},
		{
			Value:       "organization",
			IsConstant:  false,
			SearchAfter: true,
		},
		{
			Value:       "organizations",
			IsConstant:  true,
			SearchAfter: false,
		},
		{
			Value:       "iam",
			IsConstant:  true,
			SearchAfter: false,
		},
	}
)

func NewFederationProviderCountID(organization, userFederation string) (FederationProviderCountID, error) {
	if userFederation == "" {
		return FederationProviderCountID{}, reserrors.NewFieldIsEmptyError("userFederation")
	}
	if organization == "" {
		return FederationProviderCountID{}, reserrors.NewFieldIsEmptyError("organization")
	}
	m := FederationProviderCountID{
		userFederation: userFederation,
		organization:   organization,
	}
	m.path = m.ID()
	return m, nil
}

func NewMustFederationProviderCountID(organization, userFederation string) FederationProviderCountID {
	m, err := NewFederationProviderCountID(organization, userFederation)
	if err != nil {
		panic(err)
	}
	return m
}

func ParseFederationProviderCountID(path string) (FederationProviderCountID, error) {
	m := FederationProviderCountID{
		path: path,
	}
	if err := m.parse(); err != nil {
		return FederationProviderCountID{}, err
	}
	return m, nil
}

func NewFederationProviderCountIDFromAnyID(resource resmodels.AnyResourceID) (FederationProviderCountID, error) {
	return ParseFederationProviderCountID(resource.ID())
}

type FederationProviderCountID struct {
	userFederation string
	organization   string
	path           string
}

func (m *FederationProviderCountID) ResourceName() resifaces.ResourceName {
	if m == nil {
		return ""
	}
	return "federationProviderCount"
}

func (m *FederationProviderCountID) GetUserFederation() string {
	if m == nil {
		return ""
	}
	return m.userFederation
}

func (m *FederationProviderCountID) GetOrganization() string {
	if m == nil {
		return ""
	}
	return m.organization
}

func (m *FederationProviderCountID) ServiceSlug() string {
	return "iam"
}

func (m *FederationProviderCountID) ID() string {
	if m == nil || m.userFederation == "" || m.organization == "" {
		return ""
	}

	return m.ServiceSlug() + "/organizations/" + m.organization + "/userFederations/" + m.userFederation + "/services/iam/quotas/providerCount"
}

func (m *FederationProviderCountID) String() string {
	return m.ID()
}

func (m *FederationProviderCountID) Clone() *FederationProviderCountID {
	if m == nil {
		return nil
	}
	clone := *m
	return &clone
}

func (m FederationProviderCountID) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	if err := m.Encode(&e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (m *FederationProviderCountID) Encode(e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	result := m.ID()
	if result == "" {
		return fmt.Errorf("encode id: %w", reserrors.ErrIDIsEmpty)
	}
	e.Str(result)
	return nil
}

func (m *FederationProviderCountID) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *FederationProviderCountID) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("FederationProviderCountID")
	}

	v, err := decode.Str(d)
	if err != nil {
		return err
	}

	m.path = v
	return m.parse()
}

// Deprecated: Parse method is no longer required.
// Internal fields are populated automatically during decoding.
// This method will be removed in the next SDK release.
func (m *FederationProviderCountID) Parse(ctx context.Context) error {
	return nil
}

func (m *FederationProviderCountID) parse() error {
	if m == nil {
		return nil
	}

	if m.path == "" {
		return reserrors.NewParseIDError("", reserrors.ErrPathIsEmpty)
	}

	result, err := resparsers.Reference(context.Background(), m.path, FederationProviderCountRefTemplate.AsID())
	if err != nil {
		return reserrors.NewParseIDError(m.path, err)
	}

	m.userFederation = result["userFederation"]
	m.organization = result["organization"]

	return nil
}

func NewFederationProviderCountRef(organization, userFederation string) (FederationProviderCountRef, error) {
	if userFederation == "" {
		return FederationProviderCountRef{}, reserrors.NewFieldIsEmptyError("userFederation")
	}
	if organization == "" {
		return FederationProviderCountRef{}, reserrors.NewFieldIsEmptyError("organization")
	}
	m := FederationProviderCountRef{
		id: FederationProviderCountID{
			userFederation: userFederation,
			organization:   organization,
		},
	}
	m.id.path = m.absolutePath()
	return m, nil
}

func NewMustFederationProviderCountRef(organization, userFederation string) FederationProviderCountRef {
	m, err := NewFederationProviderCountRef(organization, userFederation)
	if err != nil {
		panic(err)
	}
	return m
}

func ParseFederationProviderCountRef(ctx context.Context, path string) (FederationProviderCountRef, error) {
	m := FederationProviderCountRef{
		id: FederationProviderCountID{
			path: path,
		},
	}
	if err := m.Parse(ctx); err != nil {
		return FederationProviderCountRef{}, err
	}
	return m, nil
}

func NewFederationProviderCountRefFromAnyRef(ref resmodels.AnyResourceRef) (FederationProviderCountRef, error) {
	ctx := valuesctx.WithValuesStore(context.Background(), ref.GetPathValues())
	return ParseFederationProviderCountRef(ctx, ref.Path())
}

type FederationProviderCountRef struct {
	id FederationProviderCountID
}

func (m *FederationProviderCountRef) ResourceName() resifaces.ResourceName {
	if m == nil {
		return ""
	}
	return m.id.ResourceName()
}

func (m *FederationProviderCountRef) GetUserFederation() string {
	if m == nil {
		return ""
	}
	return m.id.GetUserFederation()
}

func (m *FederationProviderCountRef) GetOrganization() string {
	if m == nil {
		return ""
	}
	return m.id.GetOrganization()
}

func (m *FederationProviderCountRef) ServiceSlug() string {
	return "iam"
}

func (m *FederationProviderCountRef) IDPath() string {
	if m == nil {
		return ""
	}
	return m.id.ID()
}

func (m *FederationProviderCountRef) Path() string {
	if m == nil {
		return ""
	}
	if m.id.path == "" {
		return m.absolutePath()
	}
	return m.id.path
}

func (m *FederationProviderCountRef) String() string {
	return m.IDPath()
}

func (m *FederationProviderCountRef) Parse(ctx context.Context) error {
	return m.parse(ctx, false)
}

func (m *FederationProviderCountRef) Clone() *FederationProviderCountRef {
	if m == nil {
		return nil
	}
	clone := *m
	return &clone
}

func (m FederationProviderCountRef) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	if err := m.Encode(&e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (m *FederationProviderCountRef) Encode(e *jx.Encoder) error {
	if m == nil {
		e.Null()
		return nil
	}
	result := m.Path()
	if result == "" {
		return fmt.Errorf("encode reference: %w", reserrors.ErrPathIsEmpty)
	}
	e.Str(result)
	return nil
}

func (m *FederationProviderCountRef) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *FederationProviderCountRef) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("FederationProviderCountRef")
	}

	v, err := decode.Str(d)
	if err != nil {
		return err
	}

	m.id.path = v
	return m.parse(context.Background(), true)
}

func (m *FederationProviderCountRef) parse(ctx context.Context, allowPartial bool) error {
	if m == nil || m.isParsed() {
		return nil
	}

	if m.id.path == "" {
		return reserrors.NewParseReferenceError("", reserrors.ErrPathIsEmpty)
	}

	var options []resparsers.Option
	if allowPartial {
		options = append(options, resparsers.AllowPartial())
	}

	result, err := resparsers.Reference(ctx, m.id.path, FederationProviderCountRefTemplate, options...)
	if err != nil {
		return reserrors.NewParseReferenceError(m.id.path, err)
	}

	m.id.userFederation = result["userFederation"]
	m.id.organization = result["organization"]

	return nil
}

func (m *FederationProviderCountRef) isParsed() bool {
	return m != nil && m.id.userFederation != "" && m.id.organization != ""
}

func (m *FederationProviderCountRef) absolutePath() string {
	if m == nil || m.id.userFederation == "" || m.id.organization == "" {
		return ""
	}

	return "organizations/" + m.id.organization + "/userFederations/" + m.id.userFederation + "/services/iam/quotas/providerCount"
}
