// Code generated by mwsapigen, DO NOT EDIT.

package iam

import (
	"context"

	"github.com/go-faster/jx"

	"go.mws.cloud/go-sdk/internal/conv"
	"go.mws.cloud/go-sdk/internal/decode"
	reserrors "go.mws.cloud/go-sdk/internal/resources/errors"
	resparsers "go.mws.cloud/go-sdk/internal/resources/parsers"
	valuesctx "go.mws.cloud/go-sdk/pkg/context/values"
	resifaces "go.mws.cloud/go-sdk/pkg/resources/interfaces"
	resmodels "go.mws.cloud/go-sdk/pkg/resources/models"
)

var (
	TotalApiKeyCountRefTemplate = resparsers.Template{
		{
			Value:       "totalApiKeyCount",
			IsConstant:  true,
			SearchAfter: true,
		},
		{
			Value:       "quotas",
			IsConstant:  true,
			SearchAfter: true,
		},
		{
			Value:       "iam",
			IsConstant:  true,
			SearchAfter: true,
		},
		{
			Value:       "services",
			IsConstant:  true,
			SearchAfter: false,
		},
		{
			Value:       "project",
			IsConstant:  false,
			SearchAfter: true,
		},
		{
			Value:       "projects",
			IsConstant:  true,
			SearchAfter: false,
		},
		{
			Value:       "iam",
			IsConstant:  true,
			SearchAfter: false,
		},
	}
)

func NewTotalApiKeyCountID(project string) TotalApiKeyCountID {
	m := TotalApiKeyCountID{
		project: project,
	}
	m.path = m.ID()
	return m
}

func ParseTotalApiKeyCountID(path string) (TotalApiKeyCountID, error) {
	m := TotalApiKeyCountID{
		path: path,
	}
	if err := m.Parse(context.Background()); err != nil {
		return TotalApiKeyCountID{}, err
	}
	return m, nil
}

func NewTotalApiKeyCountIDFromAnyID(resource resmodels.AnyResourceID) (TotalApiKeyCountID, error) {
	return ParseTotalApiKeyCountID(resource.ID())
}

type TotalApiKeyCountID struct {
	project string
	path    string
}

func (m *TotalApiKeyCountID) ResourceName() resifaces.ResourceName {
	if m == nil {
		return ""
	}
	return "totalApiKeyCount"
}

func (m *TotalApiKeyCountID) GetProject() string {
	if m == nil {
		return ""
	}
	return m.project
}

func (m *TotalApiKeyCountID) ServiceSlug() string {
	return "iam"
}

func (m *TotalApiKeyCountID) ID() string {
	if m == nil || m.project == "" {
		return ""
	}

	return m.ServiceSlug() + "/projects/" + m.project + "/services/iam/quotas/totalApiKeyCount"
}

func (m *TotalApiKeyCountID) Parse(ctx context.Context) error {
	if m == nil {
		return nil
	}

	result, err := resparsers.Reference(ctx, m.path, TotalApiKeyCountRefTemplate.AsID())
	if err != nil {
		return reserrors.NewParseIDError(m.path, err)
	}

	m.project = result["project"]

	return nil
}

func (m *TotalApiKeyCountID) Clone() *TotalApiKeyCountID {
	if m == nil {
		return nil
	}
	clone := *m
	return &clone
}

func (m TotalApiKeyCountID) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *TotalApiKeyCountID) Encode(e *jx.Encoder) {
	if m == nil {
		e.Null()
		return
	}
	result := m.ID()
	if result == "" {
		result = m.path
	}
	e.Str(result)
}

func (m *TotalApiKeyCountID) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *TotalApiKeyCountID) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("TotalApiKeyCountRef")
	}

	v, err := decode.Str(d)
	if err != nil {
		return err
	}

	m.path = v
	return nil
}

func NewTotalApiKeyCountRef(project string) TotalApiKeyCountRef {
	m := TotalApiKeyCountRef{
		id: TotalApiKeyCountID{
			project: project,
		},
	}
	m.id.path = m.absolutePath()
	return m
}

func ParseTotalApiKeyCountRef(ctx context.Context, path string) (TotalApiKeyCountRef, error) {
	m := TotalApiKeyCountRef{
		id: TotalApiKeyCountID{
			path: path,
		},
	}
	if err := m.Parse(ctx); err != nil {
		return TotalApiKeyCountRef{}, err
	}
	return m, nil
}

func NewTotalApiKeyCountRefFromAnyRef(ref resmodels.AnyResourceRef) (TotalApiKeyCountRef, error) {
	ctx := valuesctx.WithValuesStore(context.Background(), ref.GetPathValues())
	return ParseTotalApiKeyCountRef(ctx, ref.Path())
}

type TotalApiKeyCountRef struct {
	id TotalApiKeyCountID
}

func (m *TotalApiKeyCountRef) ResourceName() resifaces.ResourceName {
	if m == nil {
		return ""
	}
	return m.id.ResourceName()
}

func (m *TotalApiKeyCountRef) GetProject() string {
	if m == nil {
		return ""
	}
	return m.id.GetProject()
}

func (m *TotalApiKeyCountRef) ServiceSlug() string {
	return "iam"
}

func (m *TotalApiKeyCountRef) IDPath() string {
	if m == nil {
		return ""
	}
	return m.id.ID()
}

func (m *TotalApiKeyCountRef) Path() string {
	if m == nil {
		return ""
	}
	if m.id.path == "" {
		return m.absolutePath()
	}
	return m.id.path
}

func (m *TotalApiKeyCountRef) Parse(ctx context.Context) error {
	if m == nil {
		return nil
	}

	result, err := resparsers.Reference(ctx, m.id.path, TotalApiKeyCountRefTemplate)
	if err != nil {
		return reserrors.NewParseReferenceError(m.id.path, err)
	}

	m.id.project = result["project"]

	return nil
}

func (m *TotalApiKeyCountRef) Clone() *TotalApiKeyCountRef {
	if m == nil {
		return nil
	}
	clone := *m
	return &clone
}

func (m TotalApiKeyCountRef) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	m.Encode(&e)
	return e.Bytes(), nil
}

func (m *TotalApiKeyCountRef) Encode(e *jx.Encoder) {
	if m == nil {
		e.Null()
		return
	}
	e.Str(m.Path())
}

func (m *TotalApiKeyCountRef) UnmarshalJSON(b []byte) error {
	return m.Decode(jx.DecodeBytes(b))
}

func (m *TotalApiKeyCountRef) Decode(d *jx.Decoder) error {
	if m == nil {
		return conv.NewDecodeToNilError("TotalApiKeyCountRef")
	}

	v, err := decode.Str(d)
	if err != nil {
		return err
	}

	m.id.path = v
	return nil
}

func (m *TotalApiKeyCountRef) absolutePath() string {
	if m == nil || m.id.project == "" {
		return ""
	}

	return "projects/" + m.id.project + "/services/iam/quotas/totalApiKeyCount"
}
