// Code generated by mwsapigen, DO NOT EDIT.

package mock_client

import (
	"context"
	"reflect"

	"go.uber.org/mock/gomock"

	"go.mws.cloud/go-sdk/service/compute/client"
)

// MockVirtualMachine is a mock of VirtualMachine interface.
type MockVirtualMachine struct {
	ctrl     *gomock.Controller
	recorder *MockVirtualMachineMockRecorder
}

// MockVirtualMachineMockRecorder is the mock recorder for MockVirtualMachine.
type MockVirtualMachineMockRecorder struct {
	mock *MockVirtualMachine
}

// NewMockVirtualMachine creates a new mock instance.
func NewMockVirtualMachine(ctrl *gomock.Controller) *MockVirtualMachine {
	mock := &MockVirtualMachine{ctrl: ctrl}
	mock.recorder = &MockVirtualMachineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVirtualMachine) EXPECT() *MockVirtualMachineMockRecorder {
	return m.recorder
}

// CreateVirtualMachine mocks base method.
func (m *MockVirtualMachine) CreateVirtualMachine(arg0 context.Context, arg1 client.UpsertVirtualMachineRequest) (*client.UpsertVirtualMachineResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVirtualMachine", arg0, arg1)
	ret0, _ := ret[0].(*client.UpsertVirtualMachineResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVirtualMachine indicates an expected call of CreateVirtualMachine.
func (mr *MockVirtualMachineMockRecorder) CreateVirtualMachine(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVirtualMachine", reflect.TypeOf((*MockVirtualMachine)(nil).CreateVirtualMachine), arg0, arg1)
}

// DeleteVirtualMachine mocks base method.
func (m *MockVirtualMachine) DeleteVirtualMachine(arg0 context.Context, arg1 client.DeleteVirtualMachineRequest) (*client.DeleteVirtualMachineResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVirtualMachine", arg0, arg1)
	ret0, _ := ret[0].(*client.DeleteVirtualMachineResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteVirtualMachine indicates an expected call of DeleteVirtualMachine.
func (mr *MockVirtualMachineMockRecorder) DeleteVirtualMachine(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVirtualMachine", reflect.TypeOf((*MockVirtualMachine)(nil).DeleteVirtualMachine), arg0, arg1)
}

// GetVirtualMachine mocks base method.
func (m *MockVirtualMachine) GetVirtualMachine(arg0 context.Context, arg1 client.GetVirtualMachineRequest) (*client.GetVirtualMachineResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVirtualMachine", arg0, arg1)
	ret0, _ := ret[0].(*client.GetVirtualMachineResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVirtualMachine indicates an expected call of GetVirtualMachine.
func (mr *MockVirtualMachineMockRecorder) GetVirtualMachine(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVirtualMachine", reflect.TypeOf((*MockVirtualMachine)(nil).GetVirtualMachine), arg0, arg1)
}

// ListVirtualMachines mocks base method.
func (m *MockVirtualMachine) ListVirtualMachines(arg0 context.Context, arg1 client.ListVirtualMachinesRequest) (*client.ListVirtualMachinesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVirtualMachines", arg0, arg1)
	ret0, _ := ret[0].(*client.ListVirtualMachinesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVirtualMachines indicates an expected call of ListVirtualMachines.
func (mr *MockVirtualMachineMockRecorder) ListVirtualMachines(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVirtualMachines", reflect.TypeOf((*MockVirtualMachine)(nil).ListVirtualMachines), arg0, arg1)
}

// UpdateVirtualMachine mocks base method.
func (m *MockVirtualMachine) UpdateVirtualMachine(arg0 context.Context, arg1 client.UpdateVirtualMachineRequest) (*client.UpsertVirtualMachineResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVirtualMachine", arg0, arg1)
	ret0, _ := ret[0].(*client.UpsertVirtualMachineResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateVirtualMachine indicates an expected call of UpdateVirtualMachine.
func (mr *MockVirtualMachineMockRecorder) UpdateVirtualMachine(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVirtualMachine", reflect.TypeOf((*MockVirtualMachine)(nil).UpdateVirtualMachine), arg0, arg1)
}

// UpsertVirtualMachine mocks base method.
func (m *MockVirtualMachine) UpsertVirtualMachine(arg0 context.Context, arg1 client.UpsertVirtualMachineRequest) (*client.UpsertVirtualMachineResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertVirtualMachine", arg0, arg1)
	ret0, _ := ret[0].(*client.UpsertVirtualMachineResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertVirtualMachine indicates an expected call of UpsertVirtualMachine.
func (mr *MockVirtualMachineMockRecorder) UpsertVirtualMachine(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertVirtualMachine", reflect.TypeOf((*MockVirtualMachine)(nil).UpsertVirtualMachine), arg0, arg1)
}
