// Code generated by mwsapigen, DO NOT EDIT.

package client

import (
	"net/url"

	commonclient "go.mws.cloud/go-sdk/internal/client"
	"go.mws.cloud/go-sdk/service/mclickhouse/client"
)

var _ client.ClickhouseClusterBackup = (*ClickhouseClusterBackup)(nil)

type ClickhouseClusterBackup struct {
	client    commonclient.MWSClient
	serverURL *url.URL
}

func NewClickhouseClusterBackup(cfg commonclient.Config) *ClickhouseClusterBackup {
	return &ClickhouseClusterBackup{
		client:    cfg.GetClient(),
		serverURL: cfg.GetURL(),
	}
}

func NewClickhouseClusterBackupSugared(cfg commonclient.Config) *client.ClickhouseClusterBackupSugared {
	return client.NewClickhouseClusterBackupSugared(NewClickhouseClusterBackup(cfg))
}
